create or replace secure view SEC_VW_CDM_VISIBILITY_APP_CFACTS(
	SYSTEM_ID,
	HWAM_VISIBLE,
	SWAM_VISIBLE,
	VUL_VISIBLE,
	HARDWARE_DATACENTERS,
	HARDWARE_HOST_STATUS,
	AWS_SECHUB_ENABLED,
	LASTSEEN_HWAM,
	LASTSEEN_SWAM,
	LASTSEEN_VUL
) as
WITH LAST_SEEN AS (
    SELECT 
        S.SYSTEM_ID,
        MAX(VS.LASTSEEN_HWAM)::DATE AS LASTSEEN_HWAM,
        MAX(VS.LASTSEEN_SWAM)::DATE AS LASTSEEN_SWAM,
        MAX(VS.LASTSEEN_VUL)::DATE AS LASTSEEN_VUL,
        ARRAY_AGG(DISTINCT VS.DATACENTER_ACRONYM) 
            WITHIN GROUP (ORDER BY VS.DATACENTER_ACRONYM ASC) AS HARDWARE_DATACENTERS,
        ARRAY_AGG(DISTINCT VS.DATACENTER_ID) AS HARDWARE_DATACENTER_IDS
    FROM BUS_CYBER_RISK_MANAGEMENT.CORE.VW_SYSTEMS S
    LEFT JOIN BUS_CYBER_RISK_MANAGEMENT.CORE.VW_ASSETS VS ON S.SYSTEM_ID = VS.SYSTEM_ID
    GROUP BY S.SYSTEM_ID
    ORDER BY S.SYSTEM_ID
), 
HARDWARE_STATUS AS (
    SELECT 
        SYSTEM_ID, 
        ARRAY_SIZE(HARDWARE_DATACENTER_IDS) AS DATACENTER_COUNT,
        SUM(AWS_PRESENCE_ID) AS AWS_DATACENTER_COUNT
    FROM (
        SELECT 
            SYSTEM_ID,
            HARDWARE_DATACENTER_IDS,
            DC_ID.VALUE,
            CASE 
                WHEN DC_ID.VALUE IN ('56FFF52E-175B-4E48-9B38-669C8BC74899', '5d8a99a8db672340f99cfd721f96190d') 
                THEN 1 
                ELSE 0 
            END AS AWS_PRESENCE_ID
        FROM LAST_SEEN,
        LATERAL FLATTEN(INPUT => HARDWARE_DATACENTER_IDS) AS DC_ID
    ) 
    GROUP BY SYSTEM_ID, HARDWARE_DATACENTER_IDS
)
SELECT 
    L.SYSTEM_ID,
    CASE WHEN LASTSEEN_HWAM IS NOT NULL THEN 'Y' ELSE 'N' END AS HWAM_VISIBLE,
    CASE WHEN LASTSEEN_SWAM IS NOT NULL THEN 'Y' ELSE 'N' END AS SWAM_VISIBLE,
    CASE WHEN LASTSEEN_VUL IS NOT NULL THEN 'Y' ELSE 'N' END AS VUL_VISIBLE,
    HARDWARE_DATACENTERS,
    CASE
        WHEN H.AWS_DATACENTER_COUNT = 0 THEN 'Not HWAM AWS Hosted'
        WHEN H.DATACENTER_COUNT > 0 AND H.DATACENTER_COUNT = H.AWS_DATACENTER_COUNT 
            THEN 'Fully HWAM AWS Hosted'
        WHEN H.AWS_DATACENTER_COUNT > 0 AND H.AWS_DATACENTER_COUNT < H.DATACENTER_COUNT 
            THEN 'Multi HWAM AWS Hosted'
        ELSE 'Not HWAM AWS Hosted'
    END AS HARDWARE_HOST_STATUS,
    CASE WHEN S.SYSTEM_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS AWS_SECHUB_ENABLED,
    LASTSEEN_HWAM,
    LASTSEEN_SWAM,
    LASTSEEN_VUL
FROM LAST_SEEN L 
LEFT JOIN HARDWARE_STATUS H 
    ON L.SYSTEM_ID = H.SYSTEM_ID 
LEFT JOIN BUS_CYBER_RISK_MANAGEMENT.CORE.VW_SYSTEMS S 
    ON S.SYSTEM_ID = L.SYSTEM_ID 
    AND S.COMPONENT_ACRONYM = 'OIT' 
    AND S.AWS_ACCOUNTIDS IS NOT NULL;


;;;;