create or replace secure view SEC_VW_VUL_RISK_TOLERANCE(
	SYSTEM_ID,
	DW_ASSET_ID,
	CVE,
	FIRSTSEEN,
	LASTFOUND,
	ASSET_AGE,
	CVSS,
	SYSTEM_CATEGORY,
	ENVIRONMENT,
	EPSS_PERCENTILE,
	BASESCORE,
	ENV_FACTOR,
	EPSS_MULTIPLIER,
	VULRISKFACTOR
) as
WITH RAW_VALUES AS (
SELECT
v.SYSTEM_ID,
a.DW_ASSET_ID,
V.CVE,
v.firstseen,
v.lastfound,
v.DaysSinceDiscovery as ASSET_age,
v.CVSSV3BASESCORE as cvss,
s.OATO_Category as system_category,
 case 
 when UPPER(LEFT(A.ENVIRONMENT,3)) = 'PRO' THEN 'PROD'
 when UPPER(LEFT(A.ENVIRONMENT,1)) = 'S' THEN 'SANDBOX'
 ELSE
 'DEV'
 END AS ENVIRONMENT,
 E.PERCENTILE AS EPSS_PERCENTILE
FROM BUS_CYBER_RISK_MANAGEMENT.CORE.VW_VulMaster v
LEFT JOIN BUS_CYBER_RISK_MANAGEMENT.CORE.VW_Systems s on s.SYSTEM_ID = v.SYSTEM_ID 
LEFT JOIN REF_LOOKUPS.PUBLIC.SEC_MV_EPSS_SCORES E ON E.CVE_ID = V.CVE
LEFT JOIN BUS_CYBER_RISK_MANAGEMENT.CORE.VW_ASSETS A ON V.DW_ASSET_ID = A.DW_ASSET_ID and A.Is_Scannable=1 and LOWER(v.MitigationStatus) IN ('open','reopened')
), BASESCORE AS (

SELECT
R.*,
(R.ASSET_age * R.CVSS * system_category) AS BASESCORE
FROM RAW_VALUES R
    
), EF AS (
SELECT 
*,
CASE 
WHEN ENVIRONMENT = 'PROD' THEN 1
WHEN ENVIRONMENT = 'DEV' THEN .3
WHEN ENVIRONMENT = 'SANDBOX' THEN .1
ELSE
1
END AS ENV_FACTOR
FROM BASESCORE

), EPSS_MULTI AS (

SELECT 
*,
CASE
WHEN EPSS_PERCENTILE BETWEEN 0 AND .24 THEN 1
WHEN EPSS_PERCENTILE BETWEEN .25 AND .74 THEN 2
WHEN EPSS_PERCENTILE > .75 THEN 3
END AS EPSS_MULTIPLIER
FROM EF
)
SELECT *, (BASESCORE * ENV_FACTOR * EPSS_MULTIPLIER) AS VULRISKFACTOR
FROM EPSS_MULTI
order by SYSTEM_ID, DW_ASSET_ID, CVE
;