create or replace view VW_CVE_VULNERABILITIES(
	DATACENTER_ACRONYM,
	SYSTEM_ACRONYM,
	ASSET_ID_TATTOO,
	FQDN,
	IPV4,
	DEVICETYPE,
	OS,
	BODDUEDATE,
	CVE,
	CVSSV2BASESCORE,
	CVSSV3BASESCORE,
	DATEMITIGATED,
	DATEREOPENED,
	DAYSSINCEDISCOVERY,
	DW_ASSET_ID,
	DW_VUL_ID,
	EPSS,
	EPSS_PERCENTILE,
	EPSS_CVE_DATE,
	EXPLOITAVAILABLE,
	FIRSTSEEN,
	FISMASEVERITY,
	INSERT_DATE,
	IS_FROM_AWS_FEED,
	IS_KEV,
	IS_LEGACY,
	LASTFOUND,
	MITIGATIONSTATUS,
	EXTENDED_MITIGATIONSTATUS,
	NUMERIC_SEVERITY,
	REPOSITORY_ID,
	REPOSITORY_LASTSEEN,
	REPOSITORY_NAME,
	DATACENTER_ID,
	SYSTEM_ID
) COMMENT='CVE based vulnerabilities along with EPSS score\t'
 as
SELECT
a.datacenter_acronym
,a.system_acronym
,a.asset_id_tattoo
,a.fqdn
,a.ipv4
,a.devicetype
,a.OS
,TO_CHAR(kev.BODDUEDATE,'MM/DD/YYYY') as BODDUEDATE
,vm.CVE
,vm.CVSSV2BASESCORE
,vm.CVSSV3BASESCORE
,TO_CHAR(vm.DATEMITIGATED,'MM/DD/YYYY') as DATEMITIGATED
,TO_CHAR(vm.DATEREOPENED,'MM/DD/YYYY') as DATEREOPENED
,vm.DAYSSINCEDISCOVERY
,vm.DW_ASSET_ID
,vm.DW_VUL_ID
,epss.EPSS
,epss.PERCENTILE as EPSS_PERCENTILE
,epss.CVE_DATE as EPSS_CVE_DATE
,vm.EXPLOITAVAILABLE
,TO_CHAR(vm.FIRSTSEEN,'MM/DD/YYYY') as FIRSTSEEN
,vm.FISMASEVERITY
,TO_CHAR(vm.INSERT_DATE,'MM/DD/YYYY') as INSERT_DATE
,vm.IS_FROM_AWS_FEED
,case coalesce(kev.ID,0)
    WHEN 0 THEN 0
    ELSE 1
end::boolean as IS_KEV
,vm.IS_LEGACY
,TO_CHAR(vm.LASTFOUND,'MM/DD/YYYY') as LASTFOUND
,vm.MITIGATIONSTATUS
,vm.EXTENDED_MITIGATIONSTATUS
,vm.NUMERIC_SEVERITY
,vm.REPOSITORY_ID
,TO_CHAR(trh.REPOSITORY_LASTSEEN,'MM/DD/YYYY') as REPOSITORY_LASTSEEN
,vm.REPOSITORY_NAME
,a.DATACENTER_ID
,a.SYSTEM_ID
FROM CORE.VULMASTER vm
JOIN CORE.VW_ASSETS a on a.DW_ASSET_ID = vm.DW_ASSET_ID
LEFT OUTER JOIN CORE.KEV_CATALOG kev on kev.CVE = vm.CVE and kev.IS_DELETED = 0
LEFT OUTER JOIN (select DATACENTER_ID,REPOSITORY_ID,MAX(INSERT_DATE) as REPOSITORY_LASTSEEN
    FROM CORE.TENABLE_REPOSITORYHIST 
    GROUP BY DATACENTER_ID,REPOSITORY_ID) trh on trh.DATACENTER_ID = a.DATACENTER_ID and trh.REPOSITORY_ID = vm.REPOSITORY_ID
LEFT OUTER JOIN REF_LOOKUPS.PUBLIC.SEC_MV_EPSS_SCORES epss on epss.cve_id = vm.cve
WHERE vm.DELETIONREASON IS NULL;