create or replace view VW_CREDENTIALSCAN_V3(
	DATACATEGORY,
	SNAPSHOT_DATE,
	CREDENTIALED_SCAN,
	REPOSITORY_ID,
	REPOSITORY_NAME,
	RAW_DATACENTER_ACRONYM,
	RAW_SYSTEM_ACRONYM,
	IP,
	DNSNAME,
	MDR_PRESENT,
	ASSET_ID_TATTOO,
	CLOUD_ACCOUNT_ID,
	DATACENTER_ACRONYM,
	DATACENTER_ID,
	DEVICEROLE,
	DEVICETYPE,
	DW_ASSET_ID,
	ENVIRONMENT,
	FQDN,
	HOSTNAME,
	INSERT_DATE,
	IPV4,
	IPV6,
	IS_ENDPOINT,
	IS_TENABLE_CREDENTIALED_SCAN,
	LAST_CONFIRMED_TIME,
	LASTASSETUPDATE,
	LASTSEEN_CSM,
	LASTSEEN_HWAM,
	LASTSEEN_SWAM,
	LASTSEEN_VUL,
	MACADDRESS,
	MOTHERBOARD,
	NETBIOSNAME,
	OS,
	OS_CPE,
	OS_VERSION,
	SOURCE_TOOL_CSM,
	SOURCE_TOOL_HWAM,
	SOURCE_TOOL_LASTSEEN,
	SOURCE_TOOL_SWAM,
	SOURCE_TOOL_VUL,
	SYSTEM_ACRONYM,
	SYSTEM_ID,
	TENABLEUUID,
	VULNRISKTOLERANCE,
	CREDENTIALED_FLAG_DIFF,
	DATA_ERROR_ARRAY
) COMMENT='Current Tenable Credentialed Check from plugin 19506'
 as
SELECT snap.DATACATEGORY
,snap.SNAPSHOT_DATE
,CORE.FN_CRM_PARSE_TENABLE_CREDENTIALED_SCAN_V2(PLUGINTEXT) as CREDENTIALED_SCAN
,r.REPOSITORY_ID
,r.REPOSITORY_NAME
,dc.acronym as RAW_DATACENTER_ACRONYM
,s.acronym as RAW_SYSTEM_ACRONYM
,r.IP
,r.DNSNAME
,case when a.dw_asset_id::varchar is null then 'FALSE' else 'TRUE' end as MDR_PRESENT
,a.ASSET_ID_TATTOO
,a.CLOUD_ACCOUNT_ID
,a.DATACENTER_ACRONYM
,a.DATACENTER_ID
,a.DEVICEROLE
,a.DEVICETYPE
,a.DW_ASSET_ID
,a.ENVIRONMENT
,a.FQDN
,a.HOSTNAME
,a.INSERT_DATE
,a.IPV4
,a.IPV6
,a.IS_ENDPOINT
,a.IS_TENABLE_CREDENTIALED_SCAN
,a.LAST_CONFIRMED_TIME
,a.LASTASSETUPDATE
,a.LASTSEEN_CSM
,a.LASTSEEN_HWAM
,a.LASTSEEN_SWAM
,a.LASTSEEN_VUL
,a.MACADDRESS
,a.MOTHERBOARD
,a.NETBIOSNAME
,a.OS
,a.OS_CPE
,a.OS_VERSION
,a.SOURCE_TOOL_CSM
,a.SOURCE_TOOL_HWAM
,a.SOURCE_TOOL_LASTSEEN
,a.SOURCE_TOOL_SWAM
,a.SOURCE_TOOL_VUL
,a.SYSTEM_ACRONYM
,a.SYSTEM_ID
,a.TENABLEUUID
,a.VULNRISKTOLERANCE
,case coalesce(a.dw_asset_id::varchar,'ITSNULL')
    when 'ITSNULL' then 'No MDR, see DATA_ERROR_ARRAY'
    Else case when coalesce(a.IS_TENABLE_CREDENTIALED_SCAN,0) = coalesce(CREDENTIALED_SCAN,0) then 'Same' Else 'Diff' end 
End as Credentialed_Flag_Diff
,array_to_string(data_error_array,',') as DATA_ERROR_ARRAY
FROM core.SNAPSHOT_IDS snap
join core.RAW_TENABLE_VUL r on r.SNAPSHOT_ID = snap.SNAPSHOT_ID
left outer join core.SYSTEMS dc on dc.system_id = r.datacenter_id
left outer join core.SYSTEMS s on s.system_id = r.system_id
left outer join core.VW_ASSETS a on a.dw_asset_id = r.dw_asset_id
where snap.SNAPSHOT_DATE >= current_date() and r.plugin_id = '19506'
;