create or replace view VW_OPEN_PLUGINS(
	DW_VUL_ID,
	DATACENTER_ACRONYM,
	SYSTEM_ACRONYM,
	DW_ASSET_ID,
	ASSET_ID_TATTOO,
	FQDN,
	HOSTNAME,
	IPV4,
	PLUGIN_ID,
	PLUGIN_CVE,
	CVE,
	PLUGIN_MITIGATIONSTATUS,
	CVE_MITIGATIONSTATUS,
	EXTENDED_MITIGATIONSTATUS,
	TOTAL_PLUGIN_COUNT,
	OPEN_PLUGIN_COUNT,
	DELETED_PLUGIN_COUNT,
	FIXED_PLUGIN_COUNT,
	BODDUEDATE,
	CVSSV2BASESCORE,
	CVSSV3BASESCORE,
	DATACENTER_ID,
	DATEMITIGATED,
	DATEMODIFIED,
	DATEREOPENED,
	DAYSSINCEDISCOVERY,
	EXPLOITAVAILABLE,
	FIRSTSEEN,
	FISMASEVERITY,
	INSERT_DATE,
	IS_FROM_AWS_FEED,
	IS_KEV,
	IS_LEGACY,
	LASTFOUND,
	NUMERIC_SEVERITY,
	REPOSITORY_ID,
	REPOSITORY_LASTSEEN,
	REPOSITORY_NAME,
	SYSTEM_ID
) COMMENT='Shows open Tenable vulnerabilities from VULPLUGINS_MASTER and VULMASTER table.\t'
 as
SELECT
vm.dw_vul_id
,a.datacenter_acronym
,a.system_acronym
,vm.DW_ASSET_ID
,a.ASSET_ID_TATTOO
,a.FQDN
,a.HOSTNAME
,a.IPV4
,vpm.PLUGIN_ID
,vpm.PLUGIN_CVE
,vm.CVE
,vpm.mitigationstatus as Plugin_MitigationStatus
,vm.MITIGATIONSTATUS as CVE_Mitigationstatus
,vm.extended_mitigationstatus
,vm.total_plugin_count
,vm.open_plugin_count
,vm.deleted_plugin_count
,vm.fixed_plugin_count
,kev.BODDUEDATE
,vm.CVSSV2BASESCORE
,vm.CVSSV3BASESCORE
,a.DATACENTER_ID
,vm.DATEMITIGATED
,vm.DATEMODIFIED
,vm.DATEREOPENED
,vm.DAYSSINCEDISCOVERY
,vm.EXPLOITAVAILABLE
,vm.FIRSTSEEN
,vm.FISMASEVERITY
,vm.INSERT_DATE
,vm.IS_FROM_AWS_FEED 
,IFF(kev.ID IS NULL,FALSE,TRUE) as IS_KEV
,vm.IS_LEGACY
,vm.LASTFOUND
,vm.NUMERIC_SEVERITY
,vm.REPOSITORY_ID 
,trh.REPOSITORY_LASTSEEN 
,vm.REPOSITORY_NAME 
,a.SYSTEM_ID
FROM (SELECT f.value::string as CVE,v.cve as Plugin_CVE,v.* exclude CVE  FROM CORE.VULPLUGINS_MASTER v, LATERAL flatten(cve) f 
WHERE v.DELETIONREASON IS NULL and UPPER(v.MITIGATIONSTATUS)<>'FIXED') vpm
LEFT JOIN CORE.VULMASTER vm on vpm.DW_ASSET_ID = vm.DW_ASSET_ID and vpm.CVE = vm.CVE and vm.DELETIONREASON IS NULL
LEFT JOIN CORE.VW_ASSETS a on a.DW_ASSET_ID = vm.DW_ASSET_ID
LEFT JOIN CORE.KEV_CATALOG kev on kev.CVE = vm.CVE and kev.IS_DELETED = 0
LEFT JOIN (
select DATACENTER_ID,REPOSITORY_ID,MAX(INSERT_DATE) as REPOSITORY_LASTSEEN
FROM CORE.TENABLE_REPOSITORYHIST GROUP BY DATACENTER_ID,REPOSITORY_ID
) trh on trh.DATACENTER_ID = a.DATACENTER_ID and trh.REPOSITORY_ID = vm.REPOSITORY_ID
;