create or replace view VW_CEDE_SYSTEM_DETAIL_WITH_PRIORITIZATION(
	REPORTDATE,
	AUTHORIZATION_PACKAGE,
	ACRONYM,
	FISMA_SYSTEM,
	TLC_PHASE,
	COMPONENT_ACRONYM,
	CURRENT_HVA_SYS,
	MEF_COUNT,
	MEFSTATUS,
	BUSINESS_OWNER,
	PRIMARY_ISSO,
	SYSTEM_DESCRIPTION,
	SYSTEMDEVELOPERMAINTAINER_SDM,
	PRIMARY_OPERATING_LOCATION,
	SYSTEM_PII_LEVEL,
	NORM_DATA_SENSITIVITY,
	NORM_SECUIRTY_POSTURE2,
	NORM_SYSTEM_CRITICALITY,
	OVERALL_PRIORITIZATION
) COMMENT='Contains System information, PII level and aver all prioritization level'
 as
SELECT a.REPORTDATE
      ,a.AUTHORIZATION_PACKAGE
      ,a.ACRONYM
      ,a.FISMA_SYSTEM
      ,a.TLC_PHASE
      ,a.COMPONENT_ACRONYM
      ,CASE when a.ISCURRENTYEARHVALIST = 'Yes' then 1
	      else 0 end AS current_hva_sys
	  ,CASE when len(a.MISSIONESSENTIALFUNCTIONS_MEFS)  = 365 then 2 
	      when len(a.MISSIONESSENTIALFUNCTIONS_MEFS) = 174 then 1 
	      when len(a.MISSIONESSENTIALFUNCTIONS_MEFS) = 190 then 1 
	      else 0 end as mef_count
      ,a.MEFSTATUS    
      ,a.BUSINESS_OWNER
      ,a.PRIMARY_ISSO
      ,a.SYSTEM_DESCRIPTION
      ,a.SYSTEMDEVELOPERMAINTAINER_SDM
      ,b.PRIMARY_OPERATING_LOCATION
	  ,coalesce(f.SYS_PII_LEVEL,'Undetermined') as system_pii_level
	  ,c.NORM_DATA_SENSITIVITY
	  ,coalesce(d.NORM_SECURITY_POSTURE,0) as norm_secuirty_posture2
	  ,e.NORM_SYSTEM_CRITICALITY
	  ,CASE WHEN c.NORM_DATA_SENSITIVITY>=0 and e.NORM_SYSTEM_CRITICALITY>=0 then 
	  ROUND((c.NORM_DATA_SENSITIVITY*.15) + ((1-coalesce(d.NORM_SECURITY_POSTURE,0)) *.7) + (e.NORM_SYSTEM_CRITICALITY *.15),3) END AS overall_prioritization
  FROM CEDE.VW_CEDE_AUTHORIZATION_PACKAGES a
  LEFT JOIN CEDE.VW_CEDE_AUTHORIZATION_PACKAGES_POL b on b.AUTHORIZATION_PACKAGE =a.AUTHORIZATION_PACKAGE
  LEFT JOIN CEDE.VW_CEDE_PRIORITIZATION_DATA_SENSITIVITY c ON a.AUTHORIZATION_PACKAGE =c.AUTHORIZATION_PACKAGE
  LEFT JOIN CEDE.VW_CEDE_PRIORITIZATION_SECURITY_POSTURE d ON a.AUTHORIZATION_PACKAGE =d.AUTHORIZATION_PACKAGE
  LEFT JOIN CEDE.VW_CEDE_PRIORITIZATION_SYSTEM_CRITICALITY e ON a.AUTHORIZATION_PACKAGE =e.AUTHORIZATION_PACKAGE
  LEFT JOIN CEDE.VW_CEDE_SYSTEM_PII_LEVEL f ON a.AUTHORIZATION_PACKAGE =f.AUTHORIZATION_PACKAGE
  WHERE a.TLC_PHASE = 'Operate' and a.FISMA_SYSTEM = 'Yes'
  ;