create or replace view VW_CEDE_PRIVACY_IMPACT_ASSESSMENT_PIA(
	AUTHORIZATION_PACKAGE,
	ATO_EXPIRATION_DATE,
	PIA_014,
	PII_TYPE,
	PII_CATEGORY,
	LEVEL,
	LEVEL_NUM,
	REPORTDATE
) COMMENT='Contains PIA category and sensitivity level at org hierarchy level'
 as
SELECT 
s.AUTHORIZATION_PACKAGE 
,s.ATO_EXPIRATION_DATE 
,s.PIA_014 
,dt.PII_TYPE 
,dc.PII_CATEGORY 
,dc.LEVEL 
,dc.LEVEL_NUM 
,(select TOP 1 REPORT_DATE from TABLE(CORE.FN_CRM_GET_REPORT_ID(0))) as ReportDate
FROM CORE.VW_SYSTEMS s
JOIN CORE.PII_SYSTEM_PII_TYPES st on st.SYSTEM_ID = s.SYSTEM_ID
JOIN CORE.PII_DATATYPE dt on dt.PII_TYPE = st.PII_TYPE
JOIN CORE.PII_CATEGORY dc on dc.PII_CATEGORY = dt.PII_CATEGORY
;