create or replace view VW_CEDE_CONTROL_DETAIL_WITH_POAM_240212(
	REPORTDATE,
	AUTHORIZATION_PACKAGE,
	ACRONYM,
	FISMA_SYSTEM,
	TLC_PHASE,
	COMPONENT_ACRONYM,
	PRIMARY_OPERATING_LOCATION,
	CURRENT_HVA_SYS,
	MISSIONESSENTIALFUNCTIONS_MEFS,
	MEF_COUNT,
	BUSINESS_OWNER,
	FIPS_199_OVERALL_IMPACT_RATING,
	PRIMARY_ISSO,
	SYSTEM_DESCRIPTION,
	SYSTEMDEVELOPERMAINTAINER_SDM,
	CONTROL_NUMBER,
	TIER,
	CONTROL_NAME,
	OVERALL_CONTROL_STATUS,
	PRIVATE_IMP_UPDATED_DATE,
	PRIVATE_IMPLEMENTATION_DETAILS,
	POAM_ID,
	ALLOCATED_CONTROL,
	OVERALL_STATUS,
	WEAKNESS_RISK_LEVEL,
	SYS_PII_LEVEL
) COMMENT='Contains system details, controls and POAM details'
 as
SELECT e.REPORTDATE
      ,d.AUTHORIZATION_PACKAGE
      ,e.ACRONYM
      ,e.FISMA_SYSTEM
      ,e.TLC_PHASE 
      ,e.COMPONENT_ACRONYM
	  ,k.PRIMARY_OPERATING_LOCATION     
      ,CASE when e.ISCURRENTYEARHVALIST = 'Yes' then 1
	      else 0 end as CURRENT_HVA_SYS
      ,e.MISSIONESSENTIALFUNCTIONS_MEFS
	  ,CASE when len(e.MISSIONESSENTIALFUNCTIONS_MEFS) = 365 then 2 
	      when len(e.MISSIONESSENTIALFUNCTIONS_MEFS) = 174 then 1 
	      when len(e.MISSIONESSENTIALFUNCTIONS_MEFS) = 190 then 1 
	      else 0 end AS MEF_COUNT
      ,e.BUSINESS_OWNER
      ,e.FIPS_199_OVERALL_IMPACT_RATING
      ,e.PRIMARY_ISSO
      ,e.SYSTEM_DESCRIPTION
      ,e.SYSTEMDEVELOPERMAINTAINER_SDM
      ,d.CONTROL_NUMBER
      ,CASE when d.CONTROL_NUMBER IN ('SC-08','SC-28') then 'Encryption' 
	        when d.CONTROL_NUMBER IN ('SC-12','SC-13','SC-17') then 'Encryption Support' 
	        when d.CONTROL_NUMBER IN ('AC-03','AC-06','AC-17','AU-06','IA-02','MP-02','SI-04') then 'Tier 1' 
	        when d.CONTROL_NUMBER IN ('AC-04','AC-20','AU-12','IA-05(02)','SC-07','SC-CMS-01') then 'Tier 2' 
	        when d.CONTROL_NUMBER IN ('AC-06(01)','AC-18','CA-07','CM-03','IA-02(12)','PM-12') then 'Tier 3' 
	  end AS Tier
      ,d.CONTROL_NAME
      ,j.OVERALL_CONTROL_STATUS
      ,j.PRIVATE_IMP_UPDATED_DATE
      ,j.PRIVATE_IMPLEMENTATION_DETAILS
      ,h.POAM_ID
      ,h.ALLOCATED_CONTROL
      ,h.OVERALL_STATUS
      ,h.WEAKNESS_RISK_LEVEL
	  ,Coalesce(l.SYS_PII_LEVEL,'Undetermined') as SYS_PII_LEVEL
  FROM (SELECT 
	c.CONTROL_NUMBER,
	c.CONTROL_NAME,
	b.AUTHORIZATION_PACKAGE
	  FROM (SELECT CONTROL_NUMBER, CONTROL_NAME FROM CEDE.VW_CEDE_ALLOCATED_CONTROLS GROUP BY CONTROL_NUMBER, CONTROL_NAME) c, 
	  (SELECT AUTHORIZATION_PACKAGE FROM CEDE.VW_CEDE_AUTHORIZATION_PACKAGES a WHERE a.TLC_PHASE = 'Operate' and a.FISMA_SYSTEM = 'Yes' GROUP BY AUTHORIZATION_PACKAGE) b) d
  LEFT JOIN CEDE.VW_CEDE_AUTHORIZATION_PACKAGES e ON e.AUTHORIZATION_PACKAGE = d.AUTHORIZATION_PACKAGE
  LEFT JOIN (SELECT f.AUTHORIZATION_PACKAGE
      ,f.POAM_ID
      ,g.ALLOCATED_CONTROL
      ,f.OVERALL_STATUS
      ,f.WEAKNESS_RISK_LEVEL
	  FROM CEDE.VW_CEDE_POAM f 
	  LEFT JOIN CEDE.VW_CEDE_POAMS_CONTROLS g ON f.POAM_ID=g.POAM_ID
	  WHERE f.OVERALL_STATUS !='Completed' and f.OVERALL_STATUS !='Closed For System Disposition') h ON (d.AUTHORIZATION_PACKAGE = h.AUTHORIZATION_PACKAGE and h.ALLOCATED_CONTROL=d.CONTROL_NUMBER)
  LEFT JOIN CEDE.VW_CEDE_ALLOCATED_CONTROLS j ON (j.AUTHORIZATION_PACKAGE=d.AUTHORIZATION_PACKAGE and j.CONTROL_NUMBER=d.CONTROL_NUMBER)
  LEFT JOIN CEDE.VW_CEDE_AUTHORIZATION_PACKAGES_POL k ON k.AUTHORIZATION_PACKAGE=d.AUTHORIZATION_PACKAGE
  LEFT JOIN CEDE.VW_CEDE_SYSTEM_PII_LEVEL l ON d.AUTHORIZATION_PACKAGE=l.AUTHORIZATION_PACKAGE
  ;