create or replace view VW_CEDE_POAMS_CONTROLS(
	ALLOCATED_CONTROL,
	AUTHORIZATION_PACKAGE,
	POAM_ID,
	REPORT_DATE
) COMMENT='Contains POAM related allocated controls'
 as
SELECT c.ALLOCATED_CONTROL 
	,s.AUTHORIZATION_PACKAGE 
	,c.POAM_ID 
    ,r.REPORT_DATE 
FROM CORE.CEDE_MVP_POAMS_Controls c
JOIN CORE.REPORT_IDS r on r.REPORT_ID = c.REPORT_ID
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = c.SYSTEM_ID
;