create or replace view VW_CEDE_AUTHORIZATION_PACKAGES_POL(
	AUTHORIZATION_PACKAGE,
	PRIMARY_OPERATING_LOCATION,
	REPORTDATE
) COMMENT='Contains system primary location information'
 as
SELECT AUTHORIZATION_PACKAGE 
,PRIMARY_OPERATING_LOCATION 
,(select Report_Date from TABLE(CORE.FN_CRM_GET_REPORT_ID(0))) as ReportDate
FROM CORE.VW_SYSTEMS;