create or replace view V_VULN_DASHBOARD_TRENDING(
	ACRONYM,
	COMPONENT_ACRONYM,
	"CVE Count",
	"Unique CVE Count",
	CURRENTMTDSTART,
	DATA_CENTER_NAME,
	DATECREATED,
	DATEMITIGATED,
	DAYSSINCEDISCOVERY,
	EXPLOITAVAILABLE,
	FISMASEVERITY,
	HVASTATUS,
	IS_BOD,
	IS_MARKETPLACE,
	MEFSTATUS,
	MITIGATIONSTATUS,
	MTDVSEOM,
	PREVEOMSTART,
	RANKK,
	REFRESH_DATE,
	REPORT_DATE,
	REPORT_ID,
	TLC_PHASE,
	VULNRISKTOLERANCE
) COMMENT='Contains all the summarized Vulnerabilities for latest 12 month end and current day snapshots at Org Hierarchy level'
 as
SELECT * FROM RPT.TEMP_VULN_TRENDING;