create or replace view VW_HRS_VULNDATA(
	SYSTEM_ID,
	ACRONYM,
	ARCHER_TRACKING_ID,
	AUTH_COMMENTS,
	AUTH_DECISION,
	AUTHORIZATION_PACKAGE,
	BUSINESS_OWNER,
	CIO,
	CISO,
	CLOUD_SERVICE_PROVIDER,
	COMMONNAME,
	COMPONENT_ACRONYM,
	COMPONENT_RISK_REPORTS_OVERSIGHT,
	CONTINGENCYEXPIRATIONDATE,
	CP_TEST_DATE,
	CP_TEST_RESULTS,
	CRA,
	CYBERVET,
	DATE_AUTH_MEMO_EXPIRES,
	DATE_AUTH_MEMO_SIGNED,
	DATEDELETED,
	DATEMODIFIED,
	DCISO,
	DIVISION_ACRONYM,
	E_AUTH_EXP_DATE,
	E_AUTH_LEVEL,
	E_AUTH_RISK_ASSESSMENT_DATE,
	FINANCIAL_SYSTEM,
	FIPS_199_AVAILABILITY_RATING,
	FIPS_199_CONFIDENTIALITY_RATING,
	FIPS_199_INTEGRITY_RATING,
	FIPS_199_OVERALL_IMPACT_RATING,
	FISMA_SYSTEM,
	GROUP_ACRONYM,
	HVA_SCORE,
	HVASTATUS,
	IN_CMS_CLOUD,
	INFORMATION_SYSTEM_TYPE,
	IS_DATACENTER,
	IS_EXCLUDEFROMREPORTING,
	IS_HIGHRISKSYSTEM,
	IS_MARKETPLACE,
	IS_OA_READY,
	IS_OPERATIONALSYSTEM,
	IS_PHANTOMSYSTEM,
	IS_SECURITYHUB_ENABLED,
	ISRA_REVIEW_DATE,
	ISRA_STATUS,
	COUNT,
	ISSO,
	ISSOCS,
	LAST_ACT_DATE,
	LAST_PENTEST_DATE,
	MEF,
	MEF_CONTEXT,
	MEFSTATUS,
	OA_STATUS,
	OATO_CATEGORY,
	PACKAGE_TYPE,
	PIA_EXPIRATION_DATE,
	PII_PHI,
	PRIMARY_ISSO,
	PRIMARY_OPERATING_LOCATION,
	SCA,
	SCA_DATE,
	SDM,
	STE_DATE,
	SYSTEM_DESCRIPTION,
	TLC_PHASE,
	TOTALASSETS,
	TOTALPOAMWITHAPPROVEDRBD,
	NEXT_REQUIRED_CP_TEST_DATE,
	CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID,
	AWS_ACCOUNTIDS,
	ATO_EXPIRATION_DATE,
	ATO_REVIEW_DATE,
	AUTHORIZATION_MEMO_SIGNED_DATE,
	BO_RECOMMENDATION_REVIEW_DATE,
	BO_REVIEW_DATE,
	CISO_REVIEW_DATE,
	COMPONENT_DESCRIPTION,
	COMPONENT_NAME,
	CRA_REVIEW_DATE,
	DIVISION_DESCRIPTION,
	DSPC_REVIEW_DATE,
	DSPPO_REVIEW_DATE,
	FIRST_PUBLISHED_DATE,
	GROUP_DESCRIPTION,
	GROUP_NAME,
	ISSO_REVIEW_DATE,
	ISSO_SUBMISSION_DATE,
	LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE,
	LAST_ACT_SCA_FINAL_REPORT_DATE,
	LAST_PENTEST_CAAT_PROCESSED_FILE_DATE,
	PIA_014,
	PRIMARY_OPERATING_LOCATION_ACRONYM,
	PRIMARY_OPERATING_LOCATION_ID,
	REASON_FOR_ATO_REQUEST,
	SOP_REVIEW_DATE,
	REMEDIATED_VULN,
	DELAYED_VUL,
	FISMASEVERITY,
	CNT
) COMMENT='Contains Summarized Vulnerability data at Component level'
 as
select 
	main.SYSTEM_ID,
	main.Acronym,
	main.Archer_Tracking_ID,
	main.Auth_Comments,
	main.Auth_Decision,
	main.Authorization_Package,
	main.Business_Owner,
	main.CIO,
	main.CISO,
	main.Cloud_Service_Provider,
	main.CommonName,
	main.Component_Acronym,
	main.Component_Risk_Reports_Oversight,
	main.ContingencyExpirationDate,
	main.CP_Test_Date,
	main.CP_Test_Results,
	main.CRA,
	main.CyberVet,
	main.Date_Auth_Memo_Expires,
	main.Date_Auth_Memo_Signed,
	main.dateDeleted,
	main.dateModified,
	main.DCISO,
	main.Division_Acronym,
	--main.DivisionName,
	main.E_AUTH_EXP_DATE,
	main.E_AUTH_LEVEL,
	main.E_AUTH_RISK_ASSESSMENT_DATE,
	main.Financial_System,
	main.FIPS_199_Availability_Rating,
	main.FIPS_199_Confidentiality_Rating,
	main.FIPS_199_Integrity_Rating,
	main.FIPS_199_Overall_Impact_Rating,
	main.FISMA_System,
	main.Group_Acronym,
	main.HVA_Score,
	main.HVAStatus,
	main.In_CMS_Cloud,
	main.Information_System_Type,
	main.Is_DataCenter,
	main.Is_ExcludeFromReporting,
	main.Is_HighRiskSystem,
	main.Is_MarketPlace,
	main.Is_OA_Ready,
	main.Is_OperationalSystem,
	main.Is_PhantomSystem,
	main.Is_SecurityHub_Enabled,
	main.ISRA_REVIEW_DATE,
	main.ISRA_Status,
	main.ISSO Count,
	main.ISSO,
	main.ISSOCS,
	main.Last_ACT_Date,
	main.Last_Pentest_Date,
	main.MEF,
	main.MEF_Context,
	main.MEFStatus,
	main.OA_Status,
	main.OATO_Category,
	main.Package_Type,
	main.PIA_Expiration_Date,
	main.PII_PHI,
	main.Primary_ISSO,
	main.Primary_Operating_Location,
	main.SCA,
	main.SCA_Date,
	main.SDM,
	main.STE_DATE,
	main.System_Description,
	main.TLC_Phase,
	main.TotalAssets,
	main.TotalPOAMwithApprovedRBD,
	main.Next_Required_CP_Test_Date,
	main.Control_Set_Version_Number_System_Provid,
	main.AWS_accountIds,
	main.ATO_EXPIRATION_DATE,
	main.ATO_REVIEW_DATE,
	main.AUTHORIZATION_MEMO_SIGNED_DATE,
	main.BO_RECOMMENDATION_REVIEW_DATE,
	main.BO_REVIEW_DATE,
	main.CISO_REVIEW_DATE,
	main.COMPONENT_DESCRIPTION,
	main.COMPONENT_NAME,
	main.CRA_REVIEW_DATE,
	main.DIVISION_DESCRIPTION,
	main.DSPC_REVIEW_DATE,
	main.DSPPO_REVIEW_DATE,
	main.FIRST_PUBLISHED_DATE,
	main.GROUP_DESCRIPTION,
	main.GROUP_NAME,
	main.ISSO_REVIEW_DATE,
	main.ISSO_SUBMISSION_DATE,
	main.LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE,
	main.LAST_ACT_SCA_FINAL_REPORT_DATE,
	main.LAST_PENTEST_CAAT_PROCESSED_FILE_DATE,
	main.PIA_014,
	main.PRIMARY_OPERATING_LOCATION_ACRONYM,
	main.PRIMARY_OPERATING_LOCATION_ID,
	main.REASON_FOR_ATO_REQUEST,
	main.SOP_REVIEW_DATE

,a.REMEDIATED_VULN
,a.DELAYED_VUL
,a.FISMAseverity
,cnt  from CORE.VW_SYSTEMS main

left outer join (select
s.Component_Acronym,
s.Acronym,
v.FISMAseverity,
vm.datemitigated,
SUM(case when v.MitigationStatus = 'Fixed' and vm.datemitigated between DATEADD(day, -(day(CURRENT_DATE()-2)), dateadd(month, -1, CURRENT_DATE()-1)) and 
DATEADD(day, -(day(CURRENT_DATE())), CURRENT_DATE())   then 1 else 0 end) as Remediated_Vuln,
SUM(case when v.MitigationStatus <> 'Fixed' and  v.DaysSinceDiscovery > 90 then 1 else 0 end) as Delayed_Vul,
count(*) as cnt
-- Delayed should be based on this DaysSinceDiscovery
FROM CORE.VW_VULHIST v 
join (select Report_ID,Report_Date, Is_endOfMonth from (select rank()over(partition by DataCategory order by Report_Date desc) rankkForSnap,Report_ID,Report_Date, Is_endOfMonth from CORE.VW_ReportSnapshots
	where DataCategory= 'HWAM')a where rankkForSnap =1) vsnap
on v.report_id = vsnap.Report_ID
JOIN (select dw_vul_id, datemitigated from CORE.VW_VULMASTER) vm on vm.dw_vul_id = v.dw_vul_id
JOIN (select system_id, component_acronym, acronym from CORE.VW_SYSTEMS) s on s.system_id = v.system_id
where v.FISMAseverity in ('Critical','High') 
GROUP BY s.Component_Acronym
,v.FISMAseverity,Acronym,vm.datemitigated)a

on (a.Component_Acronym = main.Component_Acronym and a.Acronym=main.Acronym)
where TLC_Phase = 'Operate';