create or replace view VW_TRAL_RISKSEVERITYLEVEL(
	SYSTEMRISKCATEGORY,
	DESCRIPTION,
	METRICID,
	METRICNAME,
	TRIGGERDESCRIPTION,
	THRESHOLDDISPLAY,
	THRESHOLD,
	POTENTIALTHREATSOURCES,
	IMPACT,
	LIKELIHOODINITIATION,
	LIKELIHOODADVERSEIMPACT,
	OVERALLLIKELIHOOD,
	RISKSEVERITYLEVEL,
	IMPACTEDCONTROLS,
	RISKRESPONSE
) COMMENT='Trigger Accountability Log: Contains system information, impacted controls, Threshold and Impact'
 as
SELECT * FROM CORE.VW_TRAL_RISKSEVERITYLEVEL;