create or replace view VW_VATOPS_WKLY_SYSTEMS_STATUS(
	REPORT_ID,
	REPORT_DATE,
	SYSTEM_ID,
	SYSTEM_ACRONYM,
	ASSETS,
	ASSETS_SCANNED
) COMMENT='Data used for VAT weekly systems status'
 as
SELECT t.REPORT_ID
    ,t.REPORT_DATE
    ,t.SYSTEM_ID
    ,t.SYSTEM_ACRONYM
    ,t.ASSETS
    ,t.ASSETS ASSETS_SCANNED
FROM (
(select REPORT_ID, REPORT_DATE, SYSTEM_ID, SYSTEM_ACRONYM, count(1) ASSETS 
from CORE.VW_ASSETHIST group by REPORT_ID, SYSTEM_ACRONYM, REPORT_DATE, SYSTEM_ID order by count(1) DESC)
) t
Join (select top 31 REPORT_ID, REPORT_DATE from CORE.REPORT_IDS order by REPORT_ID desc) RI on RI.REPORT_ID = t.REPORT_ID 
order by t.REPORT_ID DESC
;