CREATE OR REPLACE PROCEDURE "SP_CRM_EXEC_MCRRPROC"("MONTH" NUMBER(38,0), "YEAR" NUMBER(38,0), "PREMONTH" NUMBER(38,0), "PREYEAR" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='CRM stored procedure for MCRR'
EXECUTE AS OWNER
AS '

BEGIN
TRUNCATE TABLE RPT.TEMPTABLE_MCRR;
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''CCIIO'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''CCIIO [Market]'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''CCSQ'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''CM'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''CM-MCMG'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''CMCS'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''CMMI'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''CPI'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OACT'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OAGM'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OHEI'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OC'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OEDA'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OFM'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OHC'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OHI'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OIT ESSG wCM'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OIT'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OIT-AMG'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OIT EADG'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OIT ISPG'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OIT IUSG'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OMH'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OPOLE'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OSFLO'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''OSORA'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
CALL RPT.SP_CRM_TEMPTABLE_MCRR(''[Market]'', :MONTH, :YEAR, :PREMONTH, :PREYEAR);
;

return ''Success'';



END;
';