create or replace TABLE ASSETINTERFACE_IPV4 (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	DATACATEGORY VARCHAR(16777216),
	DATEUSEDBYMATCHING TIMESTAMP_LTZ(9),
	DW_ASSET_ID NUMBER(38,0) NOT NULL,
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	IPV4 VARCHAR(16777216),
	LAST_CONFIRMED_TIME TIMESTAMP_LTZ(9) NOT NULL,
	primary key (ID)
)COMMENT='ASSET DW_ASSET_ID, IPv4 and data source.\t'
;