create or replace TABLE ASSETINTERFACE_FQDN (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	DATACATEGORY VARCHAR(16777216),
	DATEUSEDBYMATCHING TIMESTAMP_LTZ(9),
	DW_ASSET_ID NUMBER(38,0) NOT NULL,
	FQDN VARCHAR(16777216),
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	LAST_CONFIRMED_TIME TIMESTAMP_LTZ(9) NOT NULL,
	NORMALIZED_FQDN VARCHAR(16777216),
	primary key (ID)
)COMMENT='ASSET DW_ASSET_ID, FQDN and data source.\t'
;