create or replace TABLE ASSETINTERFACE_HOSTNAME (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	DATACATEGORY VARCHAR(16777216),
	DATEUSEDBYMATCHING TIMESTAMP_LTZ(9),
	DW_ASSET_ID NUMBER(38,0) NOT NULL,
	HOSTNAME VARCHAR(16777216),
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	LAST_CONFIRMED_TIME TIMESTAMP_LTZ(9) NOT NULL,
	NORMALIZED_HOSTNAME VARCHAR(16777216),
	primary key (ID)
)COMMENT='ASSET DW_ASSET_ID, HOSTNAME and data source.\t'
;