create or replace TABLE CRMP_METRICS (
	FISMASEVERITY VARCHAR(16777216) NOT NULL,
	IS_LEGACY BOOLEAN NOT NULL,
	LEVELNAME VARCHAR(16777216) NOT NULL,
	LEVELTYPE VARCHAR(16777216) NOT NULL,
	MITIGATIONSTATUS VARCHAR(16777216) NOT NULL,
	TOTAL NUMBER(38,0) NOT NULL
)COMMENT='High level Cyber Risk Management Performance Metrics per group, system. Component.\t'
;