create or replace TABLE DEVICETYPES (
	DEVICEROLE VARCHAR(16777216) NOT NULL,
	DEVICETYPE VARCHAR(16777216) NOT NULL,
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	IS_CANBETAGGEDWITHFISMAID BOOLEAN,
	IS_SCANNABLE BOOLEAN,
	IS_TATTOOABLE BOOLEAN,
	IS_WORKSTATIONORSERVER BOOLEAN,
	COMMENTS VARCHAR(16777216),
	FISMA_DEVICE_ID NUMBER(38,0),
	primary key (DEVICETYPE)
)COMMENT='Device roles and types mapping and whether tattooable or scannable, etc..\t'
;