create or replace TABLE LEGACY_VULHIST (
	CVSSV2BASESCORE NUMBER(38,1),
	CVSSV3BASESCORE NUMBER(38,1),
	DW_VUL_ID NUMBER(38,0),
	DAYSSINCEDISCOVERY NUMBER(38,0),
	EXPLOITAVAILABLE VARCHAR(16777216),
	FISMASEVERITY VARCHAR(16777216),
	LASTFOUND TIMESTAMP_LTZ(9),
	MITIGATIONSTATUS VARCHAR(16777216),
	DATEMITIGATED TIMESTAMP_LTZ(9),
	REPORT_ID NUMBER(38,0),
	REPORT_DATE TIMESTAMP_LTZ(9)
)COMMENT='History of vulnerability data from VULMASTER from Legacy database.\t'
;