create or replace TABLE PII_SYSTEM_PII_TYPES (
	PII_SYSTEM_PII_TYPES_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	PII_CATEGORY VARCHAR(16777216),
	PII_TYPE VARCHAR(16777216),
	RECORD_DATE TIMESTAMP_LTZ(9) NOT NULL,
	RECORD_SOURCE_DATA VARCHAR(16777216),
	SYSTEM_ID VARCHAR(16777216) NOT NULL,
	primary key (PII_SYSTEM_PII_TYPES_ID)
)COMMENT='PII Data Types per System. Lists out the PII data Types and corrwsponding category in a system \t'
;