create or replace TABLE PII_DATATYPE (
	HHS_POLICY_DESCRIPTION VARCHAR(16777216),
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	PII_CATEGORY VARCHAR(16777216) NOT NULL,
	PII_TYPE VARCHAR(16777216) NOT NULL,
	TYPE_DEFINITION VARCHAR(16777216),
	primary key (PII_TYPE)
)COMMENT='Table of PII Data Types. Maps PII DataType (e.g., Name) to PII category \t'
;