create or replace TABLE SNAPSHOT_IDS (
	SNAPSHOT_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	COMMENTS VARCHAR(16777216),
	DATACATEGORY VARCHAR(16777216) NOT NULL,
	ERROR_COUNT NUMBER(38,0),
	MAX_DATE TIMESTAMP_LTZ(9),
	MIN_DATE TIMESTAMP_LTZ(9),
	RECORD_COUNT NUMBER(38,0),
	RECORDS_WITH_ERRORS NUMBER(38,0),
	RECORDS_WITH_WARNINGS NUMBER(38,0),
	SNAPSHOT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	WARNING_COUNT NUMBER(38,0),
	PARENT_DATACATEGORY VARCHAR(16777216),
	REPORT_ID NUMBER(38,0),
	UNASSIGNED_DW_ASSET_ID NUMBER(38,0),
	IS_FROM_AWS_FEED BOOLEAN,
	primary key (SNAPSHOT_ID)
)COMMENT='Metadata about Snapshot IDs for each data category (AWS HWAM/AWS VUL/AXONIUS/CCIC VUL). Each snapshot ID is associated with date and number of errors or warnings\t'
;