create or replace TABLE TEMP_ASSETS_TO_DELETE (
	DW_ASSET_ID NUMBER(38,0),
	DELETIONREASON VARCHAR(16777216),
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	IS_PHYSICAL_DELETE BOOLEAN
)COMMENT='Temporary Table for Assets that will be deleted\t'
;