create or replace TABLE TENABLE_REPOSITORYHIST (
	TENABLE_REPOSITORYHIST_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	DATACENTER_ID VARCHAR(16777216),
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	LAST_SEEN TIMESTAMP_LTZ(9),
	REPOSITORY_NAME VARCHAR(16777216) NOT NULL,
	IS_FROM_AWS_FEED BOOLEAN,
	REPOSITORY_ID VARCHAR(16777216),
	RAW_TENABLE_VUL_COUNT NUMBER(38,0),
	primary key (TENABLE_REPOSITORYHIST_ID)
)COMMENT='History of Repositories seen in Tenable data. For each tenable Repository, the number of raw vuln is given as well as other information\t'
;