create or replace TABLE TRAL_METRIC (
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	METRICNAME VARCHAR(16777216) NOT NULL,
	POTENTIALTHREATSOURCES VARCHAR(16777216) NOT NULL,
	TRAL_METRIC_ID NUMBER(38,0),
	TRIGGERDESCRIPTION VARCHAR(16777216),
	primary key (METRICNAME)
)COMMENT='TRAL metrics.Table of the 5 TRAL metrics including pen test, vul and asset risk tolerance. TRAL=Trigger Audit Log?\t'
;