create or replace TABLE TRAL_LOG (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	DATEIDENTIFIED DATE NOT NULL,
	DATEMITIGATED DATE,
	INITIALSCORE NUMBER(18,3),
	INSERT_DATE TIMESTAMP_LTZ(9) NOT NULL,
	SUBSEQUENTSCORE NUMBER(18,3),
	SYSTEM_ID VARCHAR(16777216) NOT NULL,
	TRAL_METRIC_ID NUMBER(38,0) NOT NULL,
	DATEMODIFIED TIMESTAMP_LTZ(9),
	primary key (ID)
)COMMENT='The log for the TRAL metrics. For each system ID and applicable TRAL ID, an initial score is identified\t'
;