CREATE OR REPLACE FUNCTION "FN_CRM_PARSE_TENABLE_SCAN_START_DATE"("P_TENABLE_PLUGINTEXT" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Parse TENABLE PLUGINTEXT to yield SCAN_START_DATE'
AS '

CASE CHARINDEX(''Scan Start Date : '',P_TENABLE_PLUGINTEXT,1)
    WHEN 0 THEN ''1900-01-01''
    ELSE REPLACE(SUBSTRING(split_part(SUBSTRING(P_TENABLE_PLUGINTEXT,(CHARINDEX(''Scan Start Date : '',P_TENABLE_PLUGINTEXT,1) + 18),20),CHAR(10),1),1,16),''/'',''-'')
    END

';