CREATE OR REPLACE FUNCTION "FN_CRM_REMOVE_BRACKETS"("P_INSTRING" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Remove brackets and quotes from string'
AS '

REPLACE(
REPLACE(
REPLACE(P_INSTRING,''"'',''''),''['',''''),'']'','''')
   
';