CREATE OR REPLACE FUNCTION "FN_CRM_LOOKUP_ACRONYM"("P_SYSTEM_ACRONYM" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Find SYSTEM_ID based on System Acronym (Official or Common Name)'
AS '
SELECT distinct r.SYSTEM_ID
FROM (
select SYSTEM_ID FROM CORE.SYSTEMS where upper(acronym) = upper(P_SYSTEM_ACRONYM)
UNION ALL
select SYSTEM_ID FROM CORE.SYSTEM_COMMONNAME where upper(COMMONNAME) = upper(P_SYSTEM_ACRONYM)
) r
';