CREATE OR REPLACE FUNCTION "FN_CRM_GET_REPORT_ID"("P_IS_ENDOFMONTH" NUMBER(38,0))
RETURNS TABLE ("REPORT_ID" NUMBER(38,0), "REPORT_DATE" TIMESTAMP_LTZ(9), "IS_ENDOFMONTH" BOOLEAN)
LANGUAGE SQL
COMMENT='Return current REPORT_ID and REPORT_DATE for most current time or most current end-of-month'
AS '
--
-- 240416 CR873 Only return REPORT_ID if morning processes completed successfully
--
SELECT REPORT_ID, REPORT_DATE, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE REPORT_ID = (SELECT MAX(REPORT_ID) FROM CORE.REPORT_IDS where ((P_IS_ENDOFMONTH = 1 and IS_ENDOFMONTH = 1) or (coalesce(P_IS_ENDOFMONTH,0) <> 1)) and IS_VIABLE = 1)
';