CREATE OR REPLACE FUNCTION "FN_CRM_IS_VALID_DRAAS_ASSET_ID_TATTOO"("P_ASSET_ID_TATTOO" VARCHAR(16777216))
RETURNS BOOLEAN
LANGUAGE SQL
COMMENT='Return true when valid DRaaS-CACHE Tenant Tag/ASSET_ID_TATTOO format (CR978)'
AS '
CASE
WHEN (P_ASSET_ID_TATTOO IS NOT NULL and upper(P_ASSET_ID_TATTOO) NOT like ''%-%-MISP%'') THEN
    FALSE
ELSE
    TRUE
END    
';