CREATE OR REPLACE FUNCTION "FN_CRM_GET_SNAPSHOT_ID"("P_DATACATEGORY" VARCHAR(16777216))
RETURNS NUMBER(38,0)
LANGUAGE SQL
COMMENT='Return current snapshot id of datacatagory specified'
AS '
SELECT MAX(SNAPSHOT_ID) FROM CORE.SNAPSHOT_IDS where UPPER(DATACATEGORY) = UPPER(P_DATACATEGORY)
';