CREATE OR REPLACE FUNCTION "FN_CRM_PARSE_DRAAS_ASSET_ID_TATTOO"("P_ASSET_TAG" VARCHAR(16777216))
RETURNS TABLE ("ASSET_ID_TATTOO" VARCHAR(16777216), "DATACENTER_ID" VARCHAR(16777216), "TENANT_ID" VARCHAR(16777216))
LANGUAGE SQL
COMMENT='Return ASSET_ID_TATTOO,DATACENTER_ID,TENANT_ID after parsing P_ASSET_TAG'
AS '
--
-- 240827 create common function for all datastreams that must parse a DRAAS tag
--
SELECT split_part(upper(P_ASSET_TAG),''-'',1) as ASSET_ID_TATTOO
,SUBSTRING(P_ASSET_TAG, (POSITION(''-'',P_ASSET_TAG) + 1), (POSITION(''-MISP'',upper(P_ASSET_TAG)) - LEN(split_part(P_ASSET_TAG,''-'',1)) - 2)) as DATACENTER_ID
,upper(SUBSTRING(P_ASSET_TAG,(POSITION(''-MISP'',upper(P_ASSET_TAG)) + 1),20)) as TENANT_ID
';