CREATE OR REPLACE FUNCTION "FN_CRM_PARSE_TENABLE_AWS_ACCOUNTID"("P_TENABLE_PLUGINTEXT" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Parse TENABLE PLUGINTEXT from plugins 90191 or 90427 to yield AWS ACCOUNTID; 90191 Amazon Web Services EC2 Instance Metadata Enumeration (Unix), 90427 Amazon Web Services EC2 Instance Metadata Enumeration (Windows)'
AS '

CASE CHARINDEX(''accountId: '',P_TENABLE_PLUGINTEXT,1)
    WHEN 0 THEN NULL
    ELSE split_part(SUBSTRING(P_TENABLE_PLUGINTEXT,(CHARINDEX(''accountId: '',P_TENABLE_PLUGINTEXT,1) + 11),20),CHAR(10),1)
    END

';