CREATE OR REPLACE FUNCTION "FN_CRM_GET_REPORT_ID_HIST"("P_NUM_OF_ENDOFMONTH_SNAPSHOTS" NUMBER(38,0), "P_NUM_OF_DAILY_SNAPSHOTS" NUMBER(38,0))
RETURNS TABLE ("REPORT_ID" NUMBER(38,0), "REPORT_DATE" TIMESTAMP_LTZ(9), "IS_ENDOFMONTH" BOOLEAN)
LANGUAGE SQL
COMMENT='Return current REPORT_ID and REPORT_DATE for most current time daily and last 12 end-of-month snapshots'
AS '
--
-- 240416 CR873 Only return REPORT_ID if morning processes completed successfully
--
(SELECT TOP 12 REPORT_ID, REPORT_DATE, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and IS_VIABLE = 1 ORDER BY REPORT_ID DESC)
UNION ALL
(SELECT TOP 1 REPORT_ID, REPORT_DATE, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 0 and IS_VIABLE = 1 ORDER BY REPORT_ID DESC)

';