CREATE OR REPLACE FUNCTION "FN_CRM_PARSE_TENABLE_NESSUS_VERSION"("P_TENABLE_PLUGINTEXT" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Parse TENABLE PLUGINTEXT to yield NESSUS_VERSION'
AS '

CASE CHARINDEX(''Nessus version : '',P_TENABLE_PLUGINTEXT,1)
    WHEN 0 THEN NULL
    ELSE split_part(SUBSTRING(P_TENABLE_PLUGINTEXT,(CHARINDEX(''Nessus version : '',P_TENABLE_PLUGINTEXT,1) + 17),20),CHAR(10),1)
    END

';