CREATE OR REPLACE FUNCTION "FN_CRM_STRIPHTML"("P_HTMLText" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Remove unneeded characters from HTML address - any characters from < to > inclusive - like <p> or </p>'
AS '
-- 231016 added split_part for 11 thru 60, added trim
select TRIM(SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',1),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',2),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',3),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',4),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',5),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',6),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',7),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',8),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',9),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',10),''<'',1)
|| SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',11),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',12),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',13),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',14),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',15),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',16),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',17),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',18),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',19),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',20),''<'',1)
|| SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',21),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',22),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',23),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',24),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',25),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',26),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',27),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',28),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',29),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',30),''<'',1)
|| SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',31),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',32),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',33),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',34),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',35),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',36),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',37),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',38),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',39),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',40),''<'',1)
|| SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',41),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',42),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',43),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',44),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',45),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',46),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',47),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',48),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',49),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',50),''<'',1)
|| SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',51),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',52),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',53),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',54),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',55),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',56),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',57),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',58),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',59),''<'',1) || SPLIT_PART(SPLIT_PART(P_HTMLText,''>'',60),''<'',1))

';