CREATE OR REPLACE FUNCTION "FN_CRM_PARSE_FORESCOUT_ASSET_ID"("P_FORESCOUT_ASSIGNED_LABELS" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Parse AXONIUS FORESCOUT_ASSIGNED_LABELS to yield FORESCOUT_ASSET_ID_TATTOO'
AS '
-- Note: CHR(92)||CHR(110) is 

TRIM(
REPLACE(
REPLACE(
REPLACE(
REPLACE(
REPLACE(
REPLACE(

(CASE 
    WHEN ( CHARINDEX(''/var/CMS/FISMA/Asset_ID/'',P_FORESCOUT_ASSIGNED_LABELS,1) > 0 ) THEN 
        split_part(SUBSTRING(P_FORESCOUT_ASSIGNED_LABELS, CHARINDEX(''/var/CMS/FISMA/Asset_ID/'',P_FORESCOUT_ASSIGNED_LABELS,1), 500),'','',1)
    WHEN ( CHARINDEX(''Asset_ID NEEDS TO BE DEVELOPED FOR WINDOWS'',P_FORESCOUT_ASSIGNED_LABELS,1) > 0 ) THEN 
        split_part(SUBSTRING(P_FORESCOUT_ASSIGNED_LABELS, CHARINDEX(''Asset_ID'',P_FORESCOUT_ASSIGNED_LABELS,1), 500),''CHR(92)||CHR(110)'',1)
    ELSE NULL 
END)

,''/var/CMS/FISMA/Asset_ID/'',''''),CHR(92)||CHR(110),''''),''Asset_ID'',''''),''"'',''''),''['',''''),'']'',''''))

';