CREATE OR REPLACE FUNCTION "FN_CRM_PARSE_FORESCOUT_FISMA_ID_V2"("P_STRING" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Parse Forescout string to yield Primary_FISMA_ID'
AS '

NULLIF(
TRIM(
REVERSE(SUBSTRING(REVERSE(substring(P_STRING,1,(POSITION(''Version: Primary_FISMA_ID'',P_STRING) - 1))),1,((POSITION('':emaN'',REVERSE(substring(P_STRING,1,(POSITION(''Version: Primary_FISMA_ID'',P_STRING) - 1))))) - 1)))
)
,'''') -- NULLIF

';