CREATE OR REPLACE FUNCTION "FN_CRM_GET_REPORT_ID_VULN_DASHBOARD_TRENDING"()
RETURNS TABLE ("RANKK" NUMBER(38,0), "REPORT_ID" NUMBER(38,0), "REPORT_DATE" DATE, "MTDVSEOM" VARCHAR(16777216), "IS_ENDOFMONTH" BOOLEAN)
LANGUAGE SQL
COMMENT='Return current REPORT_ID and REPORT_DATE for most current time (daily) and last 12 end-of-month snapshots'
AS '

SELECT t.RANKK, t.REPORT_ID, t.REPORT_DATE, t.MTDVSEOM, t.IS_ENDOFMONTH FROM
(
(SELECT TOP 1 1 as RANKK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''MTD'' as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 0 ORDER BY REPORT_ID DESC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM'' as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 2 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 3 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 4 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 5 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 6 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 7 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 8 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 9 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 10 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 11 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
UNION ALL
(SELECT TOP 1 dense_rank()over(order by REPORT_ID desc) + 1 as RANNK, REPORT_ID, REPORT_DATE::DATE as REPORT_DATE, ''EOM-'' || (dense_rank()over(order by REPORT_ID desc) - 1)::VARCHAR as MTDVSEOM, IS_ENDOFMONTH FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 and REPORT_ID IN (SELECT TOP 12 REPORT_ID FROM CORE.REPORT_IDS WHERE IS_ENDOFMONTH = 1 ORDER BY REPORT_ID DESC) ORDER BY REPORT_ID ASC)
) t
GROUP BY t.RANKK, t.REPORT_ID, t.REPORT_DATE, t.MTDVSEOM, t.IS_ENDOFMONTH
ORDER BY t.RANKK

';