CREATE OR REPLACE FUNCTION "FN_CRM_PARSE_TENABLE_CREDENTIALED_SCAN"("P_TENABLE_PLUGINTEXT" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Parse TENABLE PLUGINTEXT to yield CREDENTIALED_SCAN'
AS '

CASE CHARINDEX(''Credentialed_Scan'',P_TENABLE_PLUGINTEXT,1)
    WHEN 0 THEN ''FALSE''
    ELSE split_part(SUBSTRING(P_TENABLE_PLUGINTEXT,(CHARINDEX(''Credentialed_Scan:'',P_TENABLE_PLUGINTEXT,1) + 18),10),CHAR(10),1)
    END

';