create or replace view VW_FISMA_AUDIT_DECOMMISSIONED_ASSETS(
	ASSET_ID_TATTOO,
	AWS_INSTANCESTATUS,
	BIGFIX_ASSET_ID,
	BIOS_GUID,
	CLOUD_ID,
	COMPUTER_TYPE,
	DATACENTER_ACRONYM,
	DATACENTER_COMMONNAME,
	DATACENTER_ID,
	DATEDELETED,
	DELETIONREASON,
	DEVICEMODEL,
	DEVICEROLE,
	DEVICETYPE,
	DW_ASSET_ID,
	ENVIRONMENT,
	FQDN,
	HOSTNAME,
	INSERT_DATE,
	IPV4,
	IPV6,
	IS_APPLICABLE,
	IS_SCANNABLE,
	IS_TATTOOABLE,
	LAST_CONFIRMED_TIME,
	LASTASSETUPDATE,
	LASTSEEN_HWAM,
	LASTSEEN_VUL,
	MACADDRESS,
	MOTHERBOARD,
	NETBIOSNAME,
	OS,
	OS_CPE,
	OS_VERSION,
	SOURCE_TOOL_CREATE,
	SOURCE_TOOL_HWAM,
	SOURCE_TOOL_LASTSEEN,
	SOURCE_TOOL_VUL,
	SYSTEM_ACRONYM,
	SYSTEM_COMMONNAME,
	SYSTEM_ID,
	TENABLEUUID,
	TENANT_ID,
	VULNRISKTOLERANCE
) COMMENT='CRITICAL; FISMA Audit request for decommissioned assets.\t'
 as
SELECT 
a.ASSET_ID_TATTOO
,a.AWS_INSTANCESTATUS
,a.BIGFIX_ASSET_ID
,a.BIOS_GUID
,a.CLOUD_ID -- 230712
,a.COMPUTER_TYPE
,dc.ACRONYM as DATACENTER_ACRONYM
,dc.COMMONNAME as DATACENTER_COMMONNAME
,a.DATACENTER_ID
,a.DATEDELETED::date as DATEDELETED
--,a.DATEMODIFIED::date as DATEMODIFIED
,a.DELETIONREASON
,a.DEVICEMODEL
,dr.DEVICEROLE
,a.DEVICETYPE
,a.DW_ASSET_ID
,a.ENVIRONMENT
,aic.FQDN
,aic.HOSTNAME
,a.INSERT_DATE::date as INSERT_DATE
,aic.IPV4
,aic.IPV6
,a.IS_APPLICABLE
,a.IS_SCANNABLE
,a.IS_TATTOOABLE
,a.LAST_CONFIRMED_TIME::date as LAST_CONFIRMED_TIME
,a.LASTASSETUPDATE::date as LASTASSETUPDATE
,a.LASTSEEN_HWAM::date as LASTSEEN_HWAM
,a.LASTSEEN_VUL::date as LASTSEEN_VUL
,aic.MACADDRESS
,a.MOTHERBOARD
,aic.NETBIOSNAME
,a.OS
,a.OS_CPE
,a.OS_VERSION
,a.SOURCE_TOOL_CREATE
,a.SOURCE_TOOL_HWAM
,a.SOURCE_TOOL_LASTSEEN
,a.SOURCE_TOOL_VUL
,s.ACRONYM as SYSTEM_ACRONYM
,s.COMMONNAME as SYSTEM_COMMONNAME
,s.SYSTEM_ID
,a.TENABLEUUID
,a.TENANT_ID
,a.VULNRISKTOLERANCE
FROM CORE.Asset a
join CORE.VW_SYSTEMS dc on upper(dc.SYSTEM_ID) = upper(a.DATACENTER_ID)
join CORE.VW_SYSTEMS s on upper(s.SYSTEM_ID) = upper(a.SYSTEM_ID)
left outer join CORE.DeviceTypes dt on upper(dt.DEVICETYPE) = upper(a.DEVICETYPE)
left outer join CORE.DeviceRoles dr on upper(dr.DEVICEROLE) = upper(dt.DEVICEROLE)
left outer join (select dw_asset_id,MAX(report_id) as Max_REPORT_ID from CORE.ASSETINTERFACECOALESCEDHIST group by dw_asset_id) maic on maic.dw_asset_id = a.dw_asset_id
left outer join CORE.ASSETINTERFACECOALESCEDHIST aic on aic.DW_ASSET_ID = a.DW_ASSET_ID and aic.report_id = maic.Max_REPORT_ID

Where a.Is_Applicable = 0 and a.datedeleted::date >= '2024-02-01'::date;