create or replace view VW_ALERTLOG(
	ID,
	APPL,
	ERRTYPE,
	INSERT_DATE,
	SQLERRM,
	SQLCODE,
	SQLSTATE,
	CUSTOM_ERRMSG
) COMMENT='Visibility of fatal process errors (Historical)\t'
 as
SELECT ID,APPL,ERRTYPE,INSERT_DATE,SQLERRM,SQLCODE,SQLSTATE,CUSTOM_ERRMSG
 FROM CORE.ALERTLOG ORDER BY ID DESC;