create or replace view VW_ASSETINTERFACE_SUMMARY(
	INTERFACEFIELD,
	MIN_LAST_CONFIRMED_TIME,
	MAX_LAST_CONFIRMED_TIME,
	TOTAL
) COMMENT='Diagnostic View to summarize the contents of all ASSETINTERFACE_XXX tables\t'
 as
select 'FQDN' As InterfaceField,min(LAST_CONFIRMED_TIME) as Min_LAST_CONFIRMED_TIME, max(LAST_CONFIRMED_TIME) as Max_LAST_CONFIRMED_TIME, count(1) as Total FROM CORE.ASSETINTERFACE_FQDN	Union all
select 'HOSTNAME'As InterfaceField,min(LAST_CONFIRMED_TIME) as Min_LAST_CONFIRMED_TIME, max(LAST_CONFIRMED_TIME) as Max_LAST_CONFIRMED_TIME, count(1) as Total FROM CORE.ASSETINTERFACE_HOSTNAME	Union all
select 'IPV4'As InterfaceField,min(LAST_CONFIRMED_TIME) as Min_LAST_CONFIRMED_TIME, max(LAST_CONFIRMED_TIME) as Max_LAST_CONFIRMED_TIME, count(1) as Total FROM CORE.ASSETINTERFACE_IPV4	Union all
select 'IPV6'As InterfaceField,min(LAST_CONFIRMED_TIME) as Min_LAST_CONFIRMED_TIME, max(LAST_CONFIRMED_TIME) as Max_LAST_CONFIRMED_TIME, count(1) as Total FROM CORE.ASSETINTERFACE_IPV6	Union all
select 'MACADDRESS'As InterfaceField,min(LAST_CONFIRMED_TIME) as Min_LAST_CONFIRMED_TIME, max(LAST_CONFIRMED_TIME) as Max_LAST_CONFIRMED_TIME, count(1) as Total FROM CORE.ASSETINTERFACE_MACADDRESS	Union all
select 'NETBIOSNAME'As InterfaceField,min(LAST_CONFIRMED_TIME) as Min_LAST_CONFIRMED_TIME, max(LAST_CONFIRMED_TIME) as Max_LAST_CONFIRMED_TIME, count(1) as Total FROM CORE.ASSETINTERFACE_NETBIOSNAME	 
;