create or replace view VW_DUPLICATE_ASSETS(
	QUERY_USED,
	ASSET_ID_TATTOO,
	AWS_ACCOUNTID,
	AWS_INSTANCESTATUS,
	BIGFIX_ASSET_ID,
	BIOS_GUID,
	CLOUD_ID,
	COMPUTER_TYPE,
	DATACENTER_ACRONYM,
	DATACENTER_COMMONNAME,
	DATACENTER_ID,
	DATEMODIFIED,
	DEVICEMODEL,
	DEVICEROLE,
	DEVICETYPE,
	DW_ASSET_ID,
	ENVIRONMENT,
	FQDN,
	HOSTNAME,
	INSERT_DATE,
	IPV4,
	IPV6,
	IS_APPLICABLE,
	IS_FORESCOUT_MANAGED,
	IS_FROM_AWS_FEED,
	IS_SCANNABLE,
	IS_TATTOOABLE,
	IS_TENABLE_CREDENTIALED_SCAN,
	LAST_CONFIRMED_TIME,
	LASTASSETUPDATE,
	LASTSEEN_CSM,
	LASTSEEN_HWAM,
	LASTSEEN_SWAM,
	LASTSEEN_VUL,
	MACADDRESS,
	MOTHERBOARD,
	NETBIOSNAME,
	OS,
	OS_BUILD_NUMBER,
	OS_CPE,
	OS_VERSION,
	SOURCE_TOOL_CREATE,
	SOURCE_TOOL_CSM,
	SOURCE_TOOL_HWAM,
	SOURCE_TOOL_LASTSEEN,
	SOURCE_TOOL_SWAM,
	SOURCE_TOOL_VUL,
	SYSTEM_ACRONYM,
	SYSTEM_COMMONNAME,
	SYSTEM_ID,
	TENABLEUUID,
	TENANT_ID,
	VULNRISKTOLERANCE
) COMMENT='Diagnostic View to report duplicate assets'
 as

 SELECT 'DATACENTER_ID/ASSET_ID_TATTOO' as QUERY_USED,* FROM CORE.VW_ASSETS WHERE DW_ASSET_ID IN (SELECT DISTINCT r2.DW_ASSET_ID
    FROM (select rank()over(partition by r1.DATACENTER_ID,r1.ASSET_ID_TATTOO order by r1.insert_date asc) TheRank,r1.DW_ASSET_ID,r1.INSERT_DATE
        FROM CORE.ASSET r1
        JOIN (select DATACENTER_ID,ASSET_ID_TATTOO 
        FROM CORE.ASSET WHERE ASSET_ID_TATTOO is not null
        GROUP BY DATACENTER_ID,ASSET_ID_TATTOO
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.ASSET_ID_TATTOO = r1.ASSET_ID_TATTOO) r2)

UNION ALL

SELECT 'DATACENTER_ID/NORMALIZED_FQDN' as QUERY_USED,* FROM CORE.VW_ASSETS WHERE DW_ASSET_ID IN (SELECT DISTINCT r2.DW_ASSET_ID
    FROM (select rank()over(partition by r1.DATACENTER_ID,f1.NORMALIZED_FQDN order by r1.LAST_CONFIRMED_TIME desc, r1.DW_ASSET_ID desc) TheRank,r1.DW_ASSET_ID,r1.ASSET_ID_TATTOO
        FROM CORE.ASSET r1
        JOIN CORE.ASSETINTERFACE_FQDN f1 on f1.dw_asset_id = r1.dw_asset_id
        JOIN (select a.DATACENTER_ID,f0.NORMALIZED_FQDN 
            FROM CORE.ASSET a
            JOIN CORE.ASSETINTERFACE_FQDN f0 on f0.dw_asset_id = a.dw_asset_id
        WHERE a.DATACENTER_ID NOT IN ('56FFF52E-175B-4E48-9B38-669C8BC74899','5d8a99a8db672340f99cfd721f96190d','DB0B74DC-610A-4D35-B645-B16059B5D64A')
        GROUP BY a.DATACENTER_ID,f0.NORMALIZED_FQDN
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.NORMALIZED_FQDN = f1.NORMALIZED_FQDN) r2)

UNION ALL

SELECT 'DATACENTER_ID/NORMALIZED_HOSTNAME' as QUERY_USED,* FROM CORE.VW_ASSETS WHERE DW_ASSET_ID IN (SELECT DISTINCT r2.DW_ASSET_ID
    FROM (select rank()over(partition by r1.DATACENTER_ID,f1.NORMALIZED_HOSTNAME order by r1.LAST_CONFIRMED_TIME desc, r1.DW_ASSET_ID desc) TheRank,r1.DW_ASSET_ID,r1.ASSET_ID_TATTOO
        FROM CORE.ASSET r1
        JOIN CORE.ASSETINTERFACE_HOSTNAME f1 on f1.dw_asset_id = r1.dw_asset_id
        JOIN (select a.DATACENTER_ID,f0.NORMALIZED_HOSTNAME 
            FROM CORE.ASSET a
            JOIN CORE.ASSETINTERFACE_HOSTNAME f0 on f0.dw_asset_id = a.dw_asset_id
            where a.DATACENTER_ID NOT IN ('56FFF52E-175B-4E48-9B38-669C8BC74899','5d8a99a8db672340f99cfd721f96190d','DB0B74DC-610A-4D35-B645-B16059B5D64A')
        GROUP BY a.DATACENTER_ID,f0.NORMALIZED_HOSTNAME
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.NORMALIZED_HOSTNAME = f1.NORMALIZED_HOSTNAME) r2)
;