create or replace view VW_LIST_CRM_COLUMNS(
	DATABASENAME,
	DBSCHEMA,
	OBJECTNAME,
	OBJECTTYPE,
	OBJECT_LAST_ALTERED,
	OBJECT_COMMENT,
	COLUMN_NAME,
	COLUMN_DEFAULT,
	IS_NULLABLE,
	DATA_TYPE,
	IS_IDENTITY,
	COLUMN_COMMENT
) COMMENT='View to list all column names of objects available to CRM\t'
 as
SELECT tbl.DATABASENAME,tbl.DBSCHEMA,tbl.OBJECTNAME,tbl.OBJECTTYPE,tbl.LAST_ALTERED as OBJECT_LAST_ALTERED,tbl.COMMENT as OBJECT_COMMENT,crm.COLUMN_NAME, crm.COLUMN_DEFAULT, crm.IS_NULLABLE, crm.DATA_TYPE, crm.IS_IDENTITY,crm.COMMENT as COLUMN_COMMENT
FROM DBA.VW_LIST_CRM_TABLES_AND_VIEWS tbl
LEFT OUTER JOIN (
select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,IS_IDENTITY,COMMENT from INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL 

select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,IS_IDENTITY,COMMENT from APP_ARCHER.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,IS_IDENTITY,COMMENT from APP_AXONIUS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,IS_IDENTITY,COMMENT from APP_CDM.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,IS_IDENTITY,COMMENT from APP_CFACTS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
-- 250218 select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,IS_IDENTITY,COMMENT from APP_SIGNAL.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,IS_IDENTITY,COMMENT from APP_TENABLE.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,IS_IDENTITY,COMMENT from REF_LOOKUPS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA'


) crm on crm.TABLE_CATALOG = tbl.DATABASENAME and crm.TABLE_SCHEMA = tbl.DBSCHEMA and crm.TABLE_NAME = tbl.OBJECTNAME
;