create or replace view VW_LIST_CFACTS_ENUM_VALUES(
	THETABLE,
	ID,
	VALUE
) COMMENT='Get list of APP_CFACTS SEC_VW_ENUM values. List of views generated with VW_LIST_CFACTS_ENUM_VIEWS\t'
 as
SELECT 'SEC_VW_ENUM_ALLOCATED__HYBRID_YES' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ALLOCATED__HYBRID_YES UNION ALL
SELECT 'SEC_VW_ENUM_ALLOCATION_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ALLOCATION_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_ASSESSMENT_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ASSESSMENT_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_AUTHENTICATION_REQUIRED' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_AUTHENTICATION_REQUIRED UNION ALL
SELECT 'SEC_VW_ENUM_AUTHORIZATION_DECISION' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_AUTHORIZATION_DECISION UNION ALL
SELECT 'SEC_VW_ENUM_BACKGROUND_INVESTIGATION' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_BACKGROUND_INVESTIGATION UNION ALL
SELECT 'SEC_VW_ENUM_CLOUD_SERVICE_PROVIDER_1' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_CLOUD_SERVICE_PROVIDER_1 UNION ALL
SELECT 'SEC_VW_ENUM_CONTINGENCY_PLAN_TEST_RESULTS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_CONTINGENCY_PLAN_TEST_RESULTS UNION ALL
SELECT 'SEC_VW_ENUM_CONTROL_FAMILY' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_CONTROL_FAMILY UNION ALL
SELECT 'SEC_VW_ENUM_COPY_OF_SINGLESIGNON_SSO_OU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_COPY_OF_SINGLESIGNON_SSO_OU UNION ALL
SELECT 'SEC_VW_ENUM_COPY_OF_SINGLESIGNON_SSO_OU_1' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_COPY_OF_SINGLESIGNON_SSO_OU_1 UNION ALL
SELECT 'SEC_VW_ENUM_COPY_OF_SINGLESIGNON_SSO_OU_2' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_COPY_OF_SINGLESIGNON_SSO_OU_2 UNION ALL
SELECT 'SEC_VW_ENUM_DOES_THE_SYSTEM_SUPPORT_THE_ACTIVITIES_O' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_DOES_THE_SYSTEM_SUPPORT_THE_ACTIVITIES_O UNION ALL
SELECT 'SEC_VW_ENUM_EAUTHENTICATION_LEVEL' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_EAUTHENTICATION_LEVEL UNION ALL
SELECT 'SEC_VW_ENUM_ENTRY_POINT_USED' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ENTRY_POINT_USED UNION ALL
SELECT 'SEC_VW_ENUM_ENTRY_POINT_USED_NOU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ENTRY_POINT_USED_NOU UNION ALL
SELECT 'SEC_VW_ENUM_ENTRY_POINT_USED_PNOU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ENTRY_POINT_USED_PNOU UNION ALL
SELECT 'SEC_VW_ENUM_ENTRY_POINT_USED_POU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ENTRY_POINT_USED_POU UNION ALL
SELECT 'SEC_VW_ENUM_ENTRY_POINT_USERD_PNOU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ENTRY_POINT_USERD_PNOU UNION ALL
SELECT 'SEC_VW_ENUM_FINAL_APPROVER_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_FINAL_APPROVER_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_FINANCIAL_SYSTEM' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_FINANCIAL_SYSTEM UNION ALL
SELECT 'SEC_VW_ENUM_FISMA_REPORTABLE' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_FISMA_REPORTABLE UNION ALL
SELECT 'SEC_VW_ENUM_FUNDING_SOURCE' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_FUNDING_SOURCE UNION ALL
SELECT 'SEC_VW_ENUM_GVL_YESNO' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_GVL_YESNO UNION ALL
SELECT 'SEC_VW_ENUM_GVL_YES__NO__DEFAULT_NO' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_GVL_YES__NO__DEFAULT_NO UNION ALL
SELECT 'SEC_VW_ENUM_HELPER_PIA014' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_HELPER_PIA014 UNION ALL
SELECT 'SEC_VW_ENUM_HSDW_' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_HSDW_ UNION ALL
SELECT 'SEC_VW_ENUM_INFORMATION_SYSTEM_TYPE' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_INFORMATION_SYSTEM_TYPE UNION ALL
SELECT 'SEC_VW_ENUM_INHERITABLE2' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_INHERITABLE2 UNION ALL
SELECT 'SEC_VW_ENUM_ISRA_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_ISRA_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_IS_THE_PII_THAT_THE_SYSTEM_COLLECTS_MAIN' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_IS_THE_PII_THAT_THE_SYSTEM_COLLECTS_MAIN UNION ALL
SELECT 'SEC_VW_ENUM_IS_THE_SYSTEM_PUBLIC_AKA_INTERNET_FACING' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_IS_THE_SYSTEM_PUBLIC_AKA_INTERNET_FACING UNION ALL
SELECT 'SEC_VW_ENUM_IS_THIS_HVA_NECESSARY_TO_PERFORM_MEF' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_IS_THIS_HVA_NECESSARY_TO_PERFORM_MEF UNION ALL
SELECT 'SEC_VW_ENUM_IS_THIS_SYSTEM_ACCESSED_BY_NONORGANIZATI' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_IS_THIS_SYSTEM_ACCESSED_BY_NONORGANIZATI UNION ALL
SELECT 'SEC_VW_ENUM_MARKETPLACE_SYSTEMS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_MARKETPLACE_SYSTEMS UNION ALL
SELECT 'SEC_VW_ENUM_MFA_INHERITED_OU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_MFA_INHERITED_OU UNION ALL
SELECT 'SEC_VW_ENUM_MILESTONE_STATUS_1' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_MILESTONE_STATUS_1 UNION ALL
SELECT 'SEC_VW_ENUM_MISSION_ESSENTIAL_FUNCTIONS_' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_MISSION_ESSENTIAL_FUNCTIONS_ UNION ALL
SELECT 'SEC_VW_ENUM_MULTIFACTOR_AUTHENTICATION_OPTIONS_ENABL' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_MULTIFACTOR_AUTHENTICATION_OPTIONS_ENABL UNION ALL
SELECT 'SEC_VW_ENUM_NONORGANIZATIONAL_MULTIFACTOR_AUTHENTICA' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_NONORGANIZATIONAL_MULTIFACTOR_AUTHENTICA UNION ALL
SELECT 'SEC_VW_ENUM_OA_ENTRANCE_CRITERIA_MET' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OA_ENTRANCE_CRITERIA_MET UNION ALL
SELECT 'SEC_VW_ENUM_OA_READY' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OA_READY UNION ALL
SELECT 'SEC_VW_ENUM_OA_READY_WITH_HOSTING' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OA_READY_WITH_HOSTING UNION ALL
SELECT 'SEC_VW_ENUM_OA_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OA_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_OA_STATUS2' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OA_STATUS2 UNION ALL
SELECT 'SEC_VW_ENUM_OPERATED_BY' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OPERATED_BY UNION ALL
SELECT 'SEC_VW_ENUM_OPERATING_LOCATION' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OPERATING_LOCATION UNION ALL
SELECT 'SEC_VW_ENUM_OVERALL_CONTROL_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OVERALL_CONTROL_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_OVERALL_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_OVERALL_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_PACKAGE_TYPE' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_PACKAGE_TYPE UNION ALL
SELECT 'SEC_VW_ENUM_PRIVILEGED_MULTIFACTOR_AUTHENTICATION_OP' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_PRIVILEGED_MULTIFACTOR_AUTHENTICATION_OP UNION ALL
SELECT 'SEC_VW_ENUM_PRIVILEGED_NONORGANIZATIONAL_MULTIFACTOR' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_PRIVILEGED_NONORGANIZATIONAL_MULTIFACTOR UNION ALL
SELECT 'SEC_VW_ENUM_RBD_OVERALL_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_RBD_OVERALL_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_REASON_FOR_ATO_REQUEST' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_REASON_FOR_ATO_REQUEST UNION ALL
SELECT 'SEC_VW_ENUM_REVIEW_STATUS_1' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_REVIEW_STATUS_1 UNION ALL
SELECT 'SEC_VW_ENUM_RISK_LEVEL_1' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_RISK_LEVEL_1 UNION ALL
SELECT 'SEC_VW_ENUM_RISK_REVIEW_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_RISK_REVIEW_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_RISK_SUBMISSION_STATUS' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_RISK_SUBMISSION_STATUS UNION ALL
SELECT 'SEC_VW_ENUM_SECURITY_CATEGORY' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_SECURITY_CATEGORY UNION ALL
SELECT 'SEC_VW_ENUM_SINGLESIGNON_SSO' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_SINGLESIGNON_SSO UNION ALL
SELECT 'SEC_VW_ENUM_STATUS_9' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_STATUS_9 UNION ALL
SELECT 'SEC_VW_ENUM_TYPE_OF_MULTIFACTOR_AUTHENTICATION_1' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_TYPE_OF_MULTIFACTOR_AUTHENTICATION_1 UNION ALL
SELECT 'SEC_VW_ENUM_TYPE_OF_MULTIFACTOR_AUTHENTICATION_IN_US' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_TYPE_OF_MULTIFACTOR_AUTHENTICATION_IN_US UNION ALL
SELECT 'SEC_VW_ENUM_USER_INTERFACES' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_USER_INTERFACES UNION ALL
SELECT 'SEC_VW_ENUM_USER_INTERFACESS_NOU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_USER_INTERFACESS_NOU UNION ALL
SELECT 'SEC_VW_ENUM_USER_INTERFACES_PNOU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_USER_INTERFACES_PNOU UNION ALL
SELECT 'SEC_VW_ENUM_USER_INTERFACES_POU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_USER_INTERFACES_POU UNION ALL
SELECT 'SEC_VW_ENUM_WEAKNESS_SEVERITY' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_WEAKNESS_SEVERITY UNION ALL
SELECT 'SEC_VW_ENUM_WHAT_STAGE_OF_IMPLEMENTATION' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_WHAT_STAGE_OF_IMPLEMENTATION UNION ALL
SELECT 'SEC_VW_ENUM_WHAT_STAGE_OF_IMPLEMENTATION_NOU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_WHAT_STAGE_OF_IMPLEMENTATION_NOU UNION ALL
SELECT 'SEC_VW_ENUM_WHAT_STAGE_OF_IMPLEMENTATION_PNOU' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_WHAT_STAGE_OF_IMPLEMENTATION_PNOU UNION ALL
SELECT 'SEC_VW_ENUM_XLC_PHASE' as TheTable, ID, VALUE FROM APP_CFACTS.SHARED.SEC_VW_ENUM_XLC_PHASE
;