create or replace view VW_LIST_EXTERNAL_OBJECTS(
	DATABASENAME,
	DBSCHEMA,
	OBJECTTYPE,
	OBJECTNAME,
	CREATED,
	LAST_ALTERED,
	COMMENT
) COMMENT='View to list all objects available to CRM\t'
 as
select
	v.DATABASENAME,
	v.DBSCHEMA,
	v.OBJECTTYPE,
	v.OBJECTNAME,
    TO_CHAR(v.CREATED,'MM/DD/YYYY HH24:MI') as CREATED,
    TO_CHAR(v.LAST_ALTERED,'MM/DD/YYYY HH24:MI') as LAST_ALTERED,
	v.COMMENT
FROM
(
-- APP_CDM
select PROCEDURE_CATALOG as DatabaseName, PROCEDURE_SCHEMA as DBSchema, 'Procedure' as ObjectType, PROCEDURE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_CDM.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select FUNCTION_CATALOG as DatabaseName, FUNCTION_SCHEMA as DBSchema, 'Function' as ObjectType, FUNCTION_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_CDM.INFORMATION_SCHEMA.FUNCTIONS WHERE FUNCTION_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'View' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_CDM.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'Table' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_CDM.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL
select PIPE_CATALOG as DatabaseName, PIPE_SCHEMA as DBSchema, 'Table' as ObjectType, PIPE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_CDM.INFORMATION_SCHEMA.PIPES WHERE PIPE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select CATALOG_NAME as DatabaseName, SCHEMA_NAME as DBSchema, 'Schema' as ObjectType, SCHEMA_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_CDM.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME <> 'INFORMATION_SCHEMA' UNION ALL
select STAGE_CATALOG as DatabaseName, STAGE_SCHEMA as DBSchema, 'Stage' as ObjectType, STAGE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_CDM.INFORMATION_SCHEMA.STAGES WHERE STAGE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
-- APP_CFACTS
select PROCEDURE_CATALOG as DatabaseName, PROCEDURE_SCHEMA as DBSchema, 'Procedure' as ObjectType, PROCEDURE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_CFACTS.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select FUNCTION_CATALOG as DatabaseName, FUNCTION_SCHEMA as DBSchema, 'Function' as ObjectType, FUNCTION_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_CFACTS.INFORMATION_SCHEMA.FUNCTIONS WHERE FUNCTION_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'View' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_CFACTS.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'Table' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_CFACTS.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL
select PIPE_CATALOG as DatabaseName, PIPE_SCHEMA as DBSchema, 'Table' as ObjectType, PIPE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_CFACTS.INFORMATION_SCHEMA.PIPES WHERE PIPE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select CATALOG_NAME as DatabaseName, SCHEMA_NAME as DBSchema, 'Schema' as ObjectType, SCHEMA_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_CFACTS.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME <> 'INFORMATION_SCHEMA' UNION ALL
select STAGE_CATALOG as DatabaseName, STAGE_SCHEMA as DBSchema, 'Stage' as ObjectType, STAGE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_CFACTS.INFORMATION_SCHEMA.STAGES WHERE STAGE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
-- APP_FORESCOUT
select PROCEDURE_CATALOG as DatabaseName, PROCEDURE_SCHEMA as DBSchema, 'Procedure' as ObjectType, PROCEDURE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_FORESCOUT.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select FUNCTION_CATALOG as DatabaseName, FUNCTION_SCHEMA as DBSchema, 'Function' as ObjectType, FUNCTION_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_FORESCOUT.INFORMATION_SCHEMA.FUNCTIONS WHERE FUNCTION_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'View' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_FORESCOUT.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'Table' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_FORESCOUT.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL
select PIPE_CATALOG as DatabaseName, PIPE_SCHEMA as DBSchema, 'Table' as ObjectType, PIPE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_FORESCOUT.INFORMATION_SCHEMA.PIPES WHERE PIPE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select CATALOG_NAME as DatabaseName, SCHEMA_NAME as DBSchema, 'Schema' as ObjectType, SCHEMA_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_FORESCOUT.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME <> 'INFORMATION_SCHEMA' UNION ALL
select STAGE_CATALOG as DatabaseName, STAGE_SCHEMA as DBSchema, 'Stage' as ObjectType, STAGE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_FORESCOUT.INFORMATION_SCHEMA.STAGES WHERE STAGE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
-- APP_SIGNAL
select PROCEDURE_CATALOG as DatabaseName, PROCEDURE_SCHEMA as DBSchema, 'Procedure' as ObjectType, PROCEDURE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_SIGNAL.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select FUNCTION_CATALOG as DatabaseName, FUNCTION_SCHEMA as DBSchema, 'Function' as ObjectType, FUNCTION_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_SIGNAL.INFORMATION_SCHEMA.FUNCTIONS WHERE FUNCTION_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'View' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_SIGNAL.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'Table' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_SIGNAL.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL
select PIPE_CATALOG as DatabaseName, PIPE_SCHEMA as DBSchema, 'Table' as ObjectType, PIPE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_SIGNAL.INFORMATION_SCHEMA.PIPES WHERE PIPE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select CATALOG_NAME as DatabaseName, SCHEMA_NAME as DBSchema, 'Schema' as ObjectType, SCHEMA_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_SIGNAL.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME <> 'INFORMATION_SCHEMA' UNION ALL
select STAGE_CATALOG as DatabaseName, STAGE_SCHEMA as DBSchema, 'Stage' as ObjectType, STAGE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_SIGNAL.INFORMATION_SCHEMA.STAGES WHERE STAGE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
 -- APP_SNYK
select PROCEDURE_CATALOG as DatabaseName, PROCEDURE_SCHEMA as DBSchema, 'Procedure' as ObjectType, PROCEDURE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_SNYK.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select FUNCTION_CATALOG as DatabaseName, FUNCTION_SCHEMA as DBSchema, 'Function' as ObjectType, FUNCTION_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_SNYK.INFORMATION_SCHEMA.FUNCTIONS WHERE FUNCTION_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'View' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_SNYK.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'Table' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_SNYK.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL
select PIPE_CATALOG as DatabaseName, PIPE_SCHEMA as DBSchema, 'Table' as ObjectType, PIPE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_SNYK.INFORMATION_SCHEMA.PIPES WHERE PIPE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select CATALOG_NAME as DatabaseName, SCHEMA_NAME as DBSchema, 'Schema' as ObjectType, SCHEMA_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_SNYK.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME <> 'INFORMATION_SCHEMA' UNION ALL
select STAGE_CATALOG as DatabaseName, STAGE_SCHEMA as DBSchema, 'Stage' as ObjectType, STAGE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_SNYK.INFORMATION_SCHEMA.STAGES WHERE STAGE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
-- APP_TENABLE
select PROCEDURE_CATALOG as DatabaseName, PROCEDURE_SCHEMA as DBSchema, 'Procedure' as ObjectType, PROCEDURE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_TENABLE.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select FUNCTION_CATALOG as DatabaseName, FUNCTION_SCHEMA as DBSchema, 'Function' as ObjectType, FUNCTION_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_TENABLE.INFORMATION_SCHEMA.FUNCTIONS WHERE FUNCTION_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'View' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from APP_TENABLE.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'Table' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_TENABLE.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL
select PIPE_CATALOG as DatabaseName, PIPE_SCHEMA as DBSchema, 'Table' as ObjectType, PIPE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_TENABLE.INFORMATION_SCHEMA.PIPES WHERE PIPE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select CATALOG_NAME as DatabaseName, SCHEMA_NAME as DBSchema, 'Schema' as ObjectType, SCHEMA_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_TENABLE.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME <> 'INFORMATION_SCHEMA' UNION ALL
select STAGE_CATALOG as DatabaseName, STAGE_SCHEMA as DBSchema, 'Stage' as ObjectType, STAGE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from APP_TENABLE.INFORMATION_SCHEMA.STAGES WHERE STAGE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
-- REF_LOOKUP
 select PROCEDURE_CATALOG as DatabaseName, PROCEDURE_SCHEMA as DBSchema, 'Procedure' as ObjectType, PROCEDURE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from REF_LOOKUPS.INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select FUNCTION_CATALOG as DatabaseName, FUNCTION_SCHEMA as DBSchema, 'Function' as ObjectType, FUNCTION_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from REF_LOOKUPS.INFORMATION_SCHEMA.FUNCTIONS WHERE FUNCTION_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'View' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT 
 from REF_LOOKUPS.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'Table' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from REF_LOOKUPS.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL
select PIPE_CATALOG as DatabaseName, PIPE_SCHEMA as DBSchema, 'Table' as ObjectType, PIPE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from REF_LOOKUPS.INFORMATION_SCHEMA.PIPES WHERE PIPE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select CATALOG_NAME as DatabaseName, SCHEMA_NAME as DBSchema, 'Schema' as ObjectType, SCHEMA_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from REF_LOOKUPS.INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME <> 'INFORMATION_SCHEMA' UNION ALL
select STAGE_CATALOG as DatabaseName, STAGE_SCHEMA as DBSchema, 'Stage' as ObjectType, STAGE_NAME as ObjectName,CREATED,LAST_ALTERED,COMMENT
 from REF_LOOKUPS.INFORMATION_SCHEMA.STAGES WHERE STAGE_SCHEMA <> 'INFORMATION_SCHEMA'
 
) v
WHERE v.DATABASENAME <> 'BUS_CYBER_RISK_MANAGEMENT';
;