create or replace view VW_LIST_CRM_TABLES_AND_VIEWS(
	DATABASENAME,
	DBSCHEMA,
	OBJECTTYPE,
	OBJECTNAME,
	CREATED,
	LAST_ALTERED,
	COMMENT
) COMMENT='View to list all Tables and Views available to CRM\t'
 as
select
	crm.TABLE_CATALOG as DATABASENAME
	,crm.TABLE_SCHEMA as DBSCHEMA
	,crm.OBJECTTYPE
	,crm.TABLE_NAME
    ,substring(crm.CREATED::varchar,1,16) as CREATED
    ,substring(crm.LAST_ALTERED::varchar,1,16) as LAST_ALTERED
	,crm.COMMENT
FROM
(select TABLE_CATALOG,TABLE_SCHEMA,'View' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_SCHEMA IN ('DBA','CEDE','CORE','RPT') UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,'Table' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' and TABLE_SCHEMA IN ('DBA','CEDE','CORE','RPT') UNION ALL

select TABLE_CATALOG,TABLE_SCHEMA,'View' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from APP_CDM.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,'Table' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from APP_CDM.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL

select TABLE_CATALOG,TABLE_SCHEMA,'View' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from APP_CFACTS.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,'Table' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from APP_CFACTS.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL

select TABLE_CATALOG,TABLE_SCHEMA,'View' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from APP_TENABLE.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,'Table' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from APP_TENABLE.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL

select TABLE_CATALOG,TABLE_SCHEMA,'View' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from REF_LOOKUPS.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,'Table' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from REF_LOOKUPS.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL

select TABLE_CATALOG,TABLE_SCHEMA,'View' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from APP_ARCHER.INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG,TABLE_SCHEMA,'Table' as OBJECTTYPE,TABLE_NAME,CREATED,LAST_ALTERED,COMMENT
    from APP_ARCHER.INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW'
 
) crm
--WHERE v.DATABASENAME = 'BUS_CYBER_RISK_MANAGEMENT';
;