create or replace view VW_LIST_CRM_OBJECTS(
	DATABASENAME,
	DBSCHEMA,
	OBJECTTYPE,
	OBJECTNAME,
	CREATED,
	LAST_ALTERED,
	LAST_DDL,
	LAST_DDL_BY,
	OWNER,
	COMMENT
) COMMENT='View to list all objects available to CRM\t'
 as
select
	v.DATABASENAME,
	v.DBSCHEMA,
	v.OBJECTTYPE,
	v.OBJECTNAME,
    substring(v.CREATED::string,1,16) as CREATED,
    substring(v.LAST_ALTERED::string,1,16) as LAST_ALTERED,
    substring(v.LAST_DDL::string,1,16) as LAST_DDL,
    v.LAST_DDL_BY,
    v.OWNER,
	v.COMMENT
FROM
(select DATABASE_NAME as DatabaseName, 'N/A' as DBSchema, 'Database' as ObjectType, DATABASE_NAME as ObjectName,CREATED,LAST_ALTERED,NULL as LAST_DDL,NULL as LAST_DDL_BY,DATABASE_OWNER as OWNER,COMMENT 
 from INFORMATION_SCHEMA.DATABASES UNION ALL
select PROCEDURE_CATALOG as DatabaseName, PROCEDURE_SCHEMA as DBSchema, 'Procedure' as ObjectType, PROCEDURE_NAME as ObjectName,CREATED,LAST_ALTERED,NULL as LAST_DDL,NULL as LAST_DDL_BY,PROCEDURE_OWNER as OWNER,COMMENT 
 from INFORMATION_SCHEMA.PROCEDURES WHERE PROCEDURE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select FUNCTION_CATALOG as DatabaseName, FUNCTION_SCHEMA as DBSchema, 'Function' as ObjectType, FUNCTION_NAME as ObjectName,CREATED,LAST_ALTERED,NULL as LAST_DDL,NULL as LAST_DDL_BY,FUNCTION_OWNER as OWNER,COMMENT
 from INFORMATION_SCHEMA.FUNCTIONS WHERE FUNCTION_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'View' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,LAST_DDL,LAST_DDL_BY,TABLE_OWNER as OWNER,COMMENT
 from INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select TABLE_CATALOG as DatabaseName, TABLE_SCHEMA as DBSchema, 'Table' as ObjectType, TABLE_NAME as ObjectName,CREATED,LAST_ALTERED,LAST_DDL,LAST_DDL_BY,TABLE_OWNER as OWNER,COMMENT
 from INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA <> 'INFORMATION_SCHEMA' and TABLE_TYPE <> 'VIEW' UNION ALL
select PIPE_CATALOG as DatabaseName, PIPE_SCHEMA as DBSchema, 'Pipe' as ObjectType, PIPE_NAME as ObjectName,CREATED,LAST_ALTERED,NULL as LAST_DDL,NULL as LAST_DDL_BY,PIPE_OWNER as OWNER,COMMENT 
 from INFORMATION_SCHEMA.PIPES WHERE PIPE_SCHEMA <> 'INFORMATION_SCHEMA' UNION ALL
select CATALOG_NAME as DatabaseName, SCHEMA_NAME as DBSchema, 'Schema' as ObjectType, SCHEMA_NAME as ObjectName,CREATED,LAST_ALTERED,NULL as LAST_DDL,NULL as LAST_DDL_BY,SCHEMA_OWNER as OWNER,COMMENT 
 from INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME <> 'INFORMATION_SCHEMA' UNION ALL
select STAGE_CATALOG as DatabaseName, STAGE_SCHEMA as DBSchema, 'Stage' as ObjectType, STAGE_NAME as ObjectName,CREATED,LAST_ALTERED,NULL as LAST_DDL,NULL as LAST_DDL_BY,STAGE_OWNER as OWNER,COMMENT 
 from INFORMATION_SCHEMA.STAGES WHERE STAGE_SCHEMA <> 'INFORMATION_SCHEMA'
) v
--WHERE v.DATABASENAME = 'BUS_CYBER_RISK_MANAGEMENT';
;