create or replace view VW_OBJECT_COMMENTS(
	DBSCHEMA,
	OBJECTTYPE,
	OBJECTNAME,
	ALTERSTRING,
	COMMENT
) COMMENT='List of database objects with comments\t'
 as
SELECT DBSCHEMA,OBJECTTYPE,OBJECTNAME
,'Alter ' || OBJECTTYPE || ' ' || DBSCHEMA || '.' || OBJECTNAME || ' SET COMMENT=' as AlterString
,COMMENT
FROM DBA.VW_LIST_CRM_OBJECTS 
WHERE DATABASENAME = 'BUS_CYBER_RISK_MANAGEMENT' 
and UPPER(OBJECTTYPE) <> 'SCHEMA'
--and COMMENT IS NULL
and UPPER(OBJECTTYPE) IN ('FUNCTION','PROCEDURE','TABLE','VIEW')
and DBSCHEMA in ('DBA','CEDE','CORE','RPT')
ORDER BY DBSCHEMA,OBJECTTYPE,OBJECTNAME;