create or replace view VW_RAW_HWAM_ASSET_IDENTIFYING_FIELDS(
	ASSET_ID_TATTOO,
	BIOS_GUID,
	DATACENTER_ID,
	DW_ASSET_ID,
	FQDN,
	HOSTNAME,
	IPV4,
	IPV6,
	MACADDRESS,
	MOTHERBOARD,
	NETBIOSNAME,
	SYSTEM_ID,
	TENANT_ID,
	TEST_DW_ASSET_ID
) as
SELECT DISTINCT
ASSET_ID_TATTOO
,BIOS_GUID
,DATACENTER_ID
,DW_ASSET_ID
,ARRAY_TO_STRING(FQDN,',') as FQDN
,ARRAY_TO_STRING(HOSTNAME,',') as HOSTNAME
,ARRAY_TO_STRING(IPV4,',') as IPV4
,ARRAY_TO_STRING(IPV6,',') as IPV6
,ARRAY_TO_STRING(MACADDRESS,',') as MACADDRESS
,MOTHERBOARD
,ARRAY_TO_STRING(NETBIOSNAME,',') as NETBIOSNAME
--,RAW_HWAM_ID
,SYSTEM_ID
,TENANT_ID
,TEST_DW_ASSET_ID
,FROM CORE.RAW_HWAM
WHERE SNAPSHOT_ID = 2271
--and TEST_DW_ASSET_ID = 0
;