create or replace view VW_RAW_TENABLE_VUL_ASSET_IDENTIFYING_FIELDS(
	ASSET_ID_TATTOO,
	DATACENTER_ID,
	DNSNAME,
	HOSTNAME,
	IP,
	MACADDRESS,
	NETBIOSNAME,
	REPOSITORY_ID,
	SYSTEM_ID,
	TENABLEUUID,
	TENANT_ID,
	TEMP_DW_ASSET_ID,
	TEMP_ASSET_KEY,
	TEST_NUMBER,
	TEST_VARCHAR
) as
SELECT DISTINCT
ASSET_ID_TATTOO
,DATACENTER_ID
,DNSNAME
,HOSTNAME
,IP
,MACADDRESS
,NETBIOSNAME
,REPOSITORY_ID
,SYSTEM_ID
,TENABLEUUID
,TENANT_ID
,TEMP_DW_ASSET_ID
,TEMP_ASSET_KEY
,TEST_NUMBER
,TEST_VARCHAR
FROM CORE.RAW_TENABLE_VUL
where SNAPSHOT_ID IN (2822,2821)
;