create or replace view VW_RAW_TENABLE_VUL_ASSET_ATTRIBUTES(
	RAW_TENABLE_VUL_ID,
	TEMP_DW_ASSET_ID,
	DW_ASSET_ID,
	DW_VUL_ID,
	APPLICABILITYCODE,
	ROWDISPOSITION,
	ASSET_ID_TATTOO,
	AWS_ACCOUNTID,
	AWS_INSTANCE_ID,
	DATACENTER_ACRONYM,
	DATACENTER_ID,
	DATA_ERROR_ARRAY,
	DATA_WARNING_ARRAY,
	DNSNAME,
	HOSTNAME,
	HOSTUNIQUENESS,
	INSERT_DATE,
	IP,
	MACADDRESS,
	NETBIOSNAME,
	PLUGIN_ID,
	PLUGIN_NAME,
	PLUGIN_TAGS,
	PRIMARY_FISMA_ID_DERIVED,
	PRIMARY_FISMA_ID_TATTOO,
	REPOSITORY_ID,
	SNAPSHOT_ID,
	SNAPSHOT_DATE,
	SYSTEM_ACRONYM,
	SYSTEM_ID,
	TATTOO_PLUGIN_ASSET_ID,
	TATTOO_PLUGIN_PRIMARY_FISMA_ID,
	TENABLEUUID
) COMMENT='Diagnostic View to report RAW_TENABLE_VUL but only fields that represent asset attributes (e.g. FQDN)'
 as
SELECT
r.RAW_TENABLE_VUL_ID
,r.TEMP_DW_ASSET_ID
,r.DW_ASSET_ID
,r.DW_VUL_ID
,r.APPLICABILITYCODE
,r.ROWDISPOSITION
,r.ASSET_ID_TATTOO
,r.AWS_ACCOUNTID
,r.AWS_INSTANCE_ID
,dc.acronym as DATACENTER_ACRONYM
,r.DATACENTER_ID
,r.DATA_ERROR_ARRAY
,r.DATA_WARNING_ARRAY
,r.DNSNAME
,r.HOSTNAME
,r.HOSTUNIQUENESS
,r.INSERT_DATE
,r.IP
,r.MACADDRESS
,r.NETBIOSNAME
,r.PLUGIN_ID
,r.PLUGIN_NAME
,r.PLUGIN_TAGS
--,r.PLUGINTEXT
,r.PRIMARY_FISMA_ID_DERIVED
,r.PRIMARY_FISMA_ID_TATTOO
,r.REPOSITORY_ID
,r.SNAPSHOT_ID
,snap.snapshot_date
,s.acronym as SYSTEM_ACRONYM
,r.SYSTEM_ID
,r.TATTOO_PLUGIN_ASSET_ID
,r.TATTOO_PLUGIN_PRIMARY_FISMA_ID
,r.TENABLEUUID
--,r.UNIQUENESS
FROM BUS_CYBER_RISK_MANAGEMENT.CORE.RAW_TENABLE_VUL r
JOIN CORE.SNAPSHOT_IDS snap on snap.snapshot_id = r.snapshot_id
LEFT JOIN CORE.VW_SYSTEMS dc on dc.SYSTEM_ID = r.DATACENTER_ID
LEFT JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = r.SYSTEM_ID
--WHERE r.INSERT_DATE::date = current_date();
;