create or replace view VW_REPORT_IDS(
	REPORT_ID,
	IS_VIABLE,
	IS_ENDOFMONTH,
	REPORT_DATE,
	ASSETS,
	ASSETS_AWS,
	ASSETS_AWS_GOVCLOUD,
	ASSETS_PCT_AWS,
	ASSETS_CREATED_TODAY,
	ASSETS_DELETED_TODAY,
	ASSETS_FORESCOUT_MANAGED,
	ASSETS_NEVER_SCANNED,
	ASSETS_NOT_SCANNED_LAST3DAYS,
	ASSETS_SCANNABLE,
	ASSETS_TENABLE_CREDENTIALED_SCAN,
	ASSETS_UNKNOWN_DEVICETYPE,
	DUPLICATE_DATACENTER_TATTOO_PAIR,
	ENDPOINTS,
	PCT_TENABLE_CREDENTIALED_SCAN,
	PLUGINS_CREATED_TODAY,
	PLUGINS_CRITICAL,
	PLUGINS_DELETED_TODAY,
	PLUGINS_FIXED_TODAY,
	PLUGINS_HIGH,
	PLUGINS_INACTIVE_ASSET_TODAY,
	PLUGINS_LOW,
	PLUGINS_MEDIUM,
	PLUGINS_OPEN,
	PLUGINS_REOPENED,
	SYSTEMS_DEVELOP,
	SYSTEMS_INITIATE,
	SYSTEMS_OPERATE,
	SYSTEMS_RETIRE,
	TEMP_HWAM_UNASSIGNED_DW_ASSET_ID,
	VUL_AWS,
	VUL_PCT_AWS,
	VUL_CRITICAL,
	VUL_DELETED_TODAY,
	VUL_FIXED_TODAY,
	VUL_GOVCLOUD,
	VUL_HIGH,
	VUL_INACTIVE_ASSET_TODAY,
	VUL_LOW,
	VUL_MEDIUM,
	VUL_OPEN,
	VUL_REOPENED,
	COMMENTS
) COMMENT='Enterprise level view of basic daily totals (Systems,Assets,Vulnerbilities, etc.)\t'
 as
select
REPORT_ID
,IS_VIABLE -- 240416 CR873
,IS_ENDOFMONTH
,substring(REPORT_DATE::varchar,1,10) as REPORT_DATE
,ASSETS
,ASSETS_AWS -- 240103
,ASSETS_AWS_GOVCLOUD -- 240103
,((ASSETS_AWS + ASSETS_AWS_GOVCLOUD) / ASSETS) * 100.0 as ASSETS_PCT_AWS -- 240103
,ASSETS_CREATED_TODAY -- 231207
,ASSETS_DELETED_TODAY -- 231207
,ASSETS_FORESCOUT_MANAGED -- 241011
,ASSETS_NEVER_SCANNED
,ASSETS_NOT_SCANNED_LAST3DAYS
,ASSETS_SCANNABLE -- 241011
,ASSETS_TENABLE_CREDENTIALED_SCAN -- 241011
,ASSETS_UNKNOWN_DEVICETYPE
,DUPLICATE_DATACENTER_TATTOO_PAIR
,ENDPOINTS -- 241216
,DIV0(ASSETS_TENABLE_CREDENTIALED_SCAN,ASSETS_SCANNABLE) * 100.0 as PCT_TENABLE_CREDENTIALED_SCAN -- 241011
,PLUGINS_CREATED_TODAY -- 240118
,PLUGINS_CRITICAL -- 240118
,PLUGINS_DELETED_TODAY -- 240118
,PLUGINS_FIXED_TODAY -- 240118
,PLUGINS_HIGH -- 240118
,PLUGINS_INACTIVE_ASSET_TODAY -- 240118
,PLUGINS_LOW -- 240118
,PLUGINS_MEDIUM -- 240118
,PLUGINS_OPEN -- 240118
,PLUGINS_REOPENED -- 240118
,SYSTEMS_DEVELOP
,SYSTEMS_INITIATE
,SYSTEMS_OPERATE
,SYSTEMS_RETIRE
,TEMP_HWAM_UNASSIGNED_DW_ASSET_ID
,VUL_AWS -- 240103
,(VUL_AWS + VUL_GOVCLOUD) / (VUL_CRITICAL + VUL_HIGH + VUL_MEDIUM + VUL_LOW) * 100.0 as VUL_PCT_AWS -- 240103
,VUL_CRITICAL
,VUL_DELETED_TODAY
,VUL_FIXED_TODAY
,VUL_GOVCLOUD -- 240103
,VUL_HIGH
,VUL_INACTIVE_ASSET_TODAY
,VUL_LOW
,VUL_MEDIUM
,VUL_OPEN
,VUL_REOPENED
,COMMENTS
FROM CORE.REPORT_IDS
order by REPORT_ID DESC;