create or replace view VW_RAW_HWAM_EXCEPTIONS(
	RAW_HWAM_ID,
	ASSET_ID_TATTOO,
	AWS_ACCOUNTID,
	AWS_DATACENTER_ID,
	AWS_PRIMARY_FISMA_ID_TATTOO,
	AWS_INSTANCE_ID,
	AXONIUS_ADAPTER_LIST_LENGTH,
	AXONIUS_ADAPTERS,
	AXONIUS_ADAPTERS_UUID,
	AXONIUS_INTERNAL_AXONIUS_ID,
	BIGFIX_ASSET_ID,
	BIGFIX_ASSET_ID_TATTOO,
	BIGFIX_DATACENTER_ID,
	BIGFIX_PRIMARY_FISMA_ID_TATTOO,
	BIOS_GUID,
	CLOUD_ID,
	CLOUD_PROVIDER,
	COMPUTER_TYPE,
	CONNECTION_LABEL,
	DATA_ERROR_ARRAY,
	DATA_WARNING_ARRAY,
	DATACENTER_ID,
	DATECOMPLETED,
	DEVICE_MANUFACTURER,
	DEVICE_TYPE,
	DOMAIN_PREFERRED,
	ENVIRONMENT,
	EVENTTIME,
	FIRST_FETCH_TIME,
	FORESCOUT_ASSET_ID_TATTOO,
	FORESCOUT_ASSIGNED_LABELS,
	FORESCOUT_DATACENTER_ID,
	FORESCOUT_PRIMARY_FISMA_ID,
	FQDN,
	HOSTNAME,
	INSERT_DATE,
	INSTANCESTATUS,
	IPV4,
	IPV6,
	IS_FS_MANAGED,
	IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC,
	IS_WINDOWS_SERVER_PREFERRED,
	LABELS,
	LAST_CONFIRMED_TIME,
	LAST_USED_USERS_COMPANY_ASSOCIATION,
	LAST_USED_USERS_DEPARTMENTS_ASSOCIATION,
	MACADDRESS,
	MOTHERBOARD,
	NETBIOSNAME,
	OS,
	OS_BUILD_PREFERRED,
	OS_CPE,
	OS_DOTTED,
	OS_MAJOR,
	OS_MINOR,
	OS_TYPE_DISTRIBUTION_PREFERRED,
	OS_TYPE_PREFERRED,
	OS_VERSION,
	PRIMARY_FISMA_ID_DERIVED,
	PRIMARY_FISMA_ID_TATTOO,
	REPORTDATE,
	ROWDISPOSITION,
	SITECODE_PREFERRED,
	SNAPSHOT_ID,
	SOURCE_TOOL,
	SUBNETS_PREFERRED,
	SYSTEM_ACRONYM,
	SYSTEM_ID,
	TENABLE_ASSET_ID_TATTOO,
	TENABLE_ASSET_TAGS,
	TENABLE_DATACENTER_ID,
	TENABLE_PRIMARY_FISMA_ID_TATTOO,
	TIME_ZONE,
	VIRTUAL_HOST,
	WINDOWS_PATCH_VERSION,
	BIGFIX_PRIMARY_FISMA_ID_TATTOO_DETAILS,
	DEVICEMODEL,
	DW_ASSET_ID,
	DATACENTER_ACRONYM,
	DATACATEGORY,
	SNAPSHOT_DATE
) COMMENT='View to report RAW_HWAM records that have DATA_ERROR_ARRAY or DATA_WARNING_ARRAY populated (Historical)\t'
 as
SELECT 
 h.RAW_HWAM_ID 
,h.ASSET_ID_TATTOO 
,h.AWS_ACCOUNTID 
,h.AWS_DATACENTER_ID 
,h.AWS_PRIMARY_FISMA_ID_TATTOO 
,h.AWS_INSTANCE_ID 
,h.AXONIUS_ADAPTER_LIST_LENGTH 
,array_to_string(h.AXONIUS_ADAPTERS,',') as AXONIUS_ADAPTERS 
,array_to_string(h.AXONIUS_ADAPTERS_UUID,',') as AXONIUS_ADAPTERS_UUID
,h.AXONIUS_INTERNAL_AXONIUS_ID 
,h.BIGFIX_ASSET_ID 
,h.BIGFIX_ASSET_ID_TATTOO 
,h.BIGFIX_DATACENTER_ID 
,h.BIGFIX_PRIMARY_FISMA_ID_TATTOO   
,array_to_string(h.BIOS_GUID,',')  as BIOS_GUID 
,array_to_string(h.CLOUD_ID,',')  as CLOUD_ID 
,array_to_string(h.CLOUD_PROVIDER,',')  as CLOUD_PROVIDER 
,h.COMPUTER_TYPE 
,array_to_string(h.CONNECTION_LABEL,',')  as CONNECTION_LABEL 
,array_to_string(h.DATA_ERROR_ARRAY,',')  as DATA_ERROR_ARRAY 
,array_to_string(h.DATA_WARNING_ARRAY,',')  as DATA_WARNING_ARRAY 
,h.DATACENTER_ID 
,h.DATECOMPLETED 
,array_to_string(h.DEVICE_MANUFACTURER,',')  as DEVICE_MANUFACTURER 
,h.DEVICE_TYPE 
,h.DOMAIN_PREFERRED 
,h.ENVIRONMENT 
,h.EVENTTIME 
,h.FIRST_FETCH_TIME 
,h.FORESCOUT_ASSET_ID_TATTOO 
,h.FORESCOUT_ASSIGNED_LABELS 
,h.FORESCOUT_DATACENTER_ID 
,h.FORESCOUT_PRIMARY_FISMA_ID 
,array_to_string(h.FQDN,',') as  FQDN
,array_to_string(h.HOSTNAME,',') as  HOSTNAME
,h.INSERT_DATE 
,h.INSTANCESTATUS 
,array_to_string(h.IPV4,',') as IPV4 
,array_to_string(h.IPV6,',') as IPV6 
,h.IS_FS_MANAGED 
,h.IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC 
,h.IS_WINDOWS_SERVER_PREFERRED 
,array_to_string(h.LABELS,',') as  LABELS
,h.LAST_CONFIRMED_TIME 
,array_to_string(h.LAST_USED_USERS_COMPANY_ASSOCIATION,',') as LAST_USED_USERS_COMPANY_ASSOCIATION 
,array_to_string(h.LAST_USED_USERS_DEPARTMENTS_ASSOCIATION,',') as  LAST_USED_USERS_DEPARTMENTS_ASSOCIATION
,array_to_string(h.MACADDRESS,',') as MACADDRESS 
,h.MOTHERBOARD 
,array_to_string(h.NETBIOSNAME,',') as NETBIOSNAME
,h.OS 
,h.OS_BUILD_PREFERRED 
,h.OS_CPE 
,h.OS_DOTTED 
,h.OS_MAJOR 
,h.OS_MINOR 
,h.OS_TYPE_DISTRIBUTION_PREFERRED 
,h.OS_TYPE_PREFERRED 
,h.OS_VERSION 
,h.PRIMARY_FISMA_ID_DERIVED 
,h.PRIMARY_FISMA_ID_TATTOO 
,h.REPORTDATE 
,h.ROWDISPOSITION 
,h.SITECODE_PREFERRED 
,h.SNAPSHOT_ID 
,h.SOURCE_TOOL
,array_to_string(h.SUBNETS_PREFERRED,',') as  SUBNETS_PREFERRED
,h.SYSTEM_ACRONYM 
,h.SYSTEM_ID 
,h.TENABLE_ASSET_ID_TATTOO 
,h.TENABLE_ASSET_TAGS 
,h.TENABLE_DATACENTER_ID 
,h.TENABLE_PRIMARY_FISMA_ID_TATTOO 
,array_to_string(h.TIME_ZONE,',') as  TIME_ZONE
,array_to_string(h.VIRTUAL_HOST,',') as VIRTUAL_HOST
,array_to_string(h.WINDOWS_PATCH_VERSION,',') as WINDOWS_PATCH_VERSION 
,array_to_string(h.BIGFIX_PRIMARY_FISMA_ID_TATTOO_DETAILS,',')  as BIGFIX_PRIMARY_FISMA_ID_TATTOO_DETAILS 
,h.DEVICEMODEL 
,h.DW_ASSET_ID 
,s.ACRONYM DATACENTER_ACRONYM
,snap.datacategory
,snap.snapshot_date
FROM CORE.RAW_HWAM h
JOIN CORE.SNAPSHOT_IDS snap on snap.snapshot_id=h.snapshot_id
LEFT JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID=h.DATACENTER_ID
where (array_size(h.DATA_ERROR_ARRAY) !=0 or array_size(h.DATA_WARNING_ARRAY) !=0);