create or replace view VW_RAW_TENABLE_VUL_ASSET_IDENTIFYING_FIELDS_CMR(
	ASSET_ID_TATTOO,
	DATACENTER_ID,
	DNSNAME,
	HOSTNAME,
	IP,
	MACADDRESS,
	NETBIOSNAME,
	REPOSITORY_ID,
	SYSTEM_ID,
	TENABLEUUID,
	TENANT_ID,
	TEMP_DW_ASSET_ID,
	PLUGIN_ID,
	UNIQUENESS
) as
SELECT DISTINCT
ASSET_ID_TATTOO
,DATACENTER_ID
,DNSNAME
,HOSTNAME
,IP
,MACADDRESS
,NETBIOSNAME
,REPOSITORY_ID
,SYSTEM_ID
,TENABLEUUID
,TENANT_ID
,TEMP_DW_ASSET_ID
,PLUGIN_ID
,UNIQUENESS
--,TEMP_ASSET_KEY
FROM CORE.RAW_TENABLE_VUL
WHERE SNAPSHOT_ID = 2325
;