create or replace view VW_SNAPSHOT_IDS(
	SNAPSHOT_ID,
	REPORT_ID,
	SNAPSHOT_DATE,
	PARENT_DATACATEGORY,
	DATACATEGORY,
	IS_FROM_AWS_FEED,
	RECORD_COUNT,
	RECORDS_WITH_ERRORS,
	RECORDS_WITH_WARNINGS,
	ERROR_COUNT,
	WARNING_COUNT,
	UNASSIGNED_DW_ASSET_ID,
	MAX_DATE,
	MIN_DATE,
	COMMENTS
) COMMENT='Visibility of ingested record counts, errors, warnings for each data category [AWS HWAM/AWS VUL/AXONIUS/CCIC VUL] (Historical)\t'
 as
SELECT 
SNAPSHOT_ID
,REPORT_ID
,SNAPSHOT_DATE::date as SNAPSHOT_DATE
,PARENT_DATACATEGORY
,DATACATEGORY
,IS_FROM_AWS_FEED
,RECORD_COUNT
,RECORDS_WITH_ERRORS
,RECORDS_WITH_WARNINGS
,ERROR_COUNT
,WARNING_COUNT
,UNASSIGNED_DW_ASSET_ID
,substring(MAX_DATE::varchar,1,16) as MAX_DATE
,substring(MIN_DATE::varchar,1,16) as MIN_DATE
,COMMENTS
FROM CORE.SNAPSHOT_IDS ORDER BY SNAPSHOT_ID DESC;