create or replace view VW_TEMP_HWAM_ASSET_IDENTIFYING_FIELDS(
	TEMP_HWAM_ID,
	DATACATEGORY,
	DATACENTER_ACRONYM,
	SYSTEM_ACRONYM,
	TEMP_DW_ASSET_ID,
	DW_ASSET_ID,
	ASSET_ID_TATTOO,
	NORMALIZED_FQDN,
	NORMALIZED_HOSTNAME,
	NORMALIZED_NETBIOSNAME,
	MOTHERBOARD,
	IPV4,
	NORMALIZED_MACADDRESS,
	MATCHMETHOD,
	LAST_CONFIRMED_TIME,
	SNAPSHOT_ID,
	SOURCE_TOOL,
	TENABLEUUID,
	TENANT_ID,
	DATACENTER_ID,
	SYSTEM_ID
) COMMENT='Diagnostic View that shows all fields in TEMP_HWAM table that could potentially identify an asset/device (Current day only)\t'
 as
SELECT
th.TEMP_HWAM_ID
,snap.DATACATEGORY
,dc.ACRONYM as DATACENTER_ACRONYM
,s.ACRONYM as SYSTEM_ACRONYM
,th.TEMP_DW_ASSET_ID
,th.DW_ASSET_ID
,th.ASSET_ID_TATTOO
,th.NORMALIZED_FQDN
,ARRAY_TO_STRING(th.NORMALIZED_HOSTNAME,',') as NORMALIZED_HOSTNAME
,th.NORMALIZED_NETBIOSNAME
,th.MOTHERBOARD
,ARRAY_TO_STRING(th.IPV4,',') as IPV4
,ARRAY_TO_STRING(th.NORMALIZED_MACADDRESS,',') as NORMALIZED_MACADDRESS
,th.MATCHMETHOD
,th.LAST_CONFIRMED_TIME
,th.SNAPSHOT_ID
,th.SOURCE_TOOL
,th.TENABLEUUID
,th.TENANT_ID
,th.DATACENTER_ID
,th.SYSTEM_ID
FROM CORE.TEMP_HWAM th
join CORE.SNAPSHOT_IDS snap on snap.snapshot_id = th.snapshot_id
LEFT OUTER JOIN CORE.SYSTEMS dc on dc.SYSTEM_ID = th.datacenter_id
LEFT OUTER JOIN CORE.SYSTEMS s on s.SYSTEM_ID = th.SYSTEM_ID
order by th.TEMP_HWAM_ID
;