create or replace view VW_TENABLE_REPOSITORYHIST(
	INSERT_DATE,
	ACRONYM,
	DATACENTER_ID,
	LAST_SEEN,
	RAW_TENABLE_VUL_COUNT,
	REPOSITORY_ID,
	REPOSITORY_NAME,
	IS_FROM_AWS_FEED,
	IS_MOST_RECENT_DATE
) COMMENT='View to list all Tenable Repository history. e.g. Each time repo is seen\t'
 as
SELECT 
rh.INSERT_DATE::date as INSERT_DATE
,dc.ACRONYM
,rh.DATACENTER_ID
--,dc.IS_MARKETPLACE
,substring(rh.LAST_SEEN::varchar,1,16) as LAST_SEEN 
,rh.RAW_TENABLE_VUL_COUNT
,rh.REPOSITORY_ID
,rh.REPOSITORY_NAME
,rh.IS_FROM_AWS_FEED
,case coalesce(m.REPOSITORY_ID::varchar,'ItNull')
    when 'ItNull' then 'No'
    Else 'Yes'
End as IS_MOST_RECENT_DATE
FROM CORE.TENABLE_REPOSITORYHIST rh
left outer join CORE.SYSTEMS dc on dc.SYSTEM_ID = rh.DATACENTER_ID

left outer join (select REPOSITORY_ID,DATACENTER_ID,max(INSERT_DATE) as MAX_INSERT_DATE
from CORE.TENABLE_REPOSITORYHIST GROUP BY REPOSITORY_ID,DATACENTER_ID) m on m.REPOSITORY_ID = rh.REPOSITORY_ID and m.DATACENTER_ID = rh.DATACENTER_ID and m.MAX_INSERT_DATE = rh.INSERT_DATE

where rh.REPOSITORY_ID IS NOT NULL
ORDER BY rh.TENABLE_REPOSITORYHIST_ID DESC
;