create or replace view VW_TEMP_ASSET_METADATA(
	DATACATEGORY,
	ASSET_ID_TATTOO,
	AWS_ACCOUNTID,
	DATA_ERROR_ARRAY,
	DATA_WARNING_ARRAY,
	PLUGINTEXT_EC2_INSTANCE_LINUX,
	PLUGINTEXT_EC2_INSTANCE_WINDOWS,
	PLUGINTEXT_ONPREM_TAG_LINUX,
	PLUGINTEXT_ONPREM_TAG_WINDOWS,
	SYSTEM_ID,
	ACRONYM,
	TEMP_DW_ASSET_ID
) COMMENT='Diagnostic View that shows all fields in TEMP_ASSET_METADATA table\t'
 as
select distinct
snap.datacategory
,tam.ASSET_ID_TATTOO
,tam.AWS_ACCOUNTID
,tam.DATA_ERROR_ARRAY
,tam.DATA_WARNING_ARRAY
--,tam.IS_FORESCOUT_MANAGED
--,tam.IS_TENABLE_CREDENTIALED_SCAN
--,tam.NESSUS_VERSION
,tam.PLUGINTEXT_EC2_INSTANCE_LINUX
,tam.PLUGINTEXT_EC2_INSTANCE_WINDOWS
,tam.PLUGINTEXT_ONPREM_TAG_LINUX
,tam.PLUGINTEXT_ONPREM_TAG_WINDOWS
--,tam.PLUGINTEXT_NESSUS_SCAN_INFO
--,tam.SCAN_POLICY_NAME
--,tam.SCAN_POLICY_UID
--,tam.SCAN_START_DATE
--,tam.SNAPSHOT_ID
,tam.SYSTEM_ID
,s.ACRONYM
,tam.TEMP_DW_ASSET_ID
from CORE.TEMP_ASSET_METADATA tam
left outer join CORE.SYSTEMS s on s.system_id = tam.system_id
join CORE.SNAPSHOT_IDS snap on snap.snapshot_id = tam.snapshot_id
--WHERE snap.DATACATEGORY = 'CCIC VUL' and tam.SYSTEM_ID IS NULL
;