create or replace view VW_TOP_10_PLUGIN(
	FISMASEVERITY,
	PLUGIN_ID,
	TOTALASSETS
) COMMENT='Top 10 PLUGIN_IDs for Critical, High, Medium\t'
 as
SELECT t.*
FROM (
(select top 10 FISMASEVERITY,PLUGIN_ID,count(1) TOTALASSETS 
from CORE.VULPLUGINS_MASTER where DELETIONREASON IS NULL and fismaseverity = 'Critical' and MITIGATIONSTATUS <> 'fixed' group by FISMASEVERITY,PLUGIN_ID order by count(1) DESC)
UNION ALL
(select top 10 FISMASEVERITY,PLUGIN_ID,count(1) TOTALASSETS 
from CORE.VULPLUGINS_MASTER where DELETIONREASON IS NULL and fismaseverity = 'High' and MITIGATIONSTATUS <> 'fixed' group by FISMASEVERITY,PLUGIN_ID order by count(1) DESC)
UNION ALL
(select top 10 FISMASEVERITY,PLUGIN_ID,count(1) TOTALASSETS 
from CORE.VULPLUGINS_MASTER where DELETIONREASON IS NULL and fismaseverity = 'Medium' and MITIGATIONSTATUS <> 'fixed' group by FISMASEVERITY,PLUGIN_ID order by count(1) DESC)
) t
order by t.FISMASEVERITY, t.TOTALASSETS DESC
;