create or replace view VW_VULPLUGINS_MASTER_FLATTENED(
	DATACENTER_ACRONYM,
	SYSTEM_ACRONYM,
	DW_ASSET_ID,
	DW_PLUGIN_VUL_ID,
	DW_VUL_ID,
	PLUGIN_ID,
	PLUGIN_NAME,
	CVE,
	PLUGIN_MITIGATIONSTATUS,
	PLUGIN_DATEMITIGATED,
	PLUGIN_DELETIONREASON,
	PLUGIN_DATEDELETED,
	CVE_MITIGATIONSTATUS,
	CVE_DATEMITIGATED,
	EXTENDED_MITIGATIONSTATUS,
	CVE_DELETIONREASON,
	CVE_DATEDELETED,
	CVSSV2BASESCORE,
	CVSSV3BASESCORE,
	DAYSSINCEDISCOVERY,
	EXPLOITAVAILABLE,
	FAMILY_NAME,
	FIRSTSEEN,
	LASTFOUND,
	PLUGIN_FISMASEVERITY,
	CVE_FISMASEVERITY,
	PLUGIN_INSERT_DATE,
	IS_FROM_AWS_FEED,
	IS_TENABLE_CREDENTIALED_SCAN,
	LAST_CONFIRMED_TIME,
	ASSET_ID_TATTOO,
	FQDN,
	HOSTNAME,
	NETBIOSNAME,
	MACADDRESS,
	IPV4,
	PORT,
	IS_KEV,
	KEV_DUEDATE,
	KEV_SHORTDESCRIPTION,
	KEV_VENDORPROJECT,
	KEV_VULNERABILITYNAME,
	REPOSITORY_ID,
	REPOSITORY_LASTSEEN,
	REPOSITORY_NAME,
	PATCHPUB_DATE,
	VULN_PUB_DATE,
	VERSION
) as
SELECT
a.DATACENTER_ACRONYM
,a.SYSTEM_ACRONYM
,vpm.DW_ASSET_ID
,vpm.DW_PLUGIN_VUL_ID
,vm.DW_VUL_ID
,vpm.PLUGIN_ID
,vpm.PLUGIN_NAME
,f.value::string as CVE
,vpm.MITIGATIONSTATUS as PLUGIN_MITIGATIONSTATUS
,vpm.datemitigated as PLUGIN_DATEMITIGATED
,vpm.deletionreason as PLUGIN_DELETIONREASON
,vpm.datedeleted as PLUGIN_DATEDELETED
,vm.MITIGATIONSTATUS as CVE_MITIGATIONSTATUS
,vm.datemitigated as CVE_DATEMITIGATED
,vm.EXTENDED_MITIGATIONSTATUS
,vm.deletionreason as CVE_DELETIONREASON
,vm.datedeleted as CVE_DATEDELETED
,vpm.CVSSV2BASESCORE
,vpm.CVSSV3BASESCORE
,vpm.DAYSSINCEDISCOVERY
,vpm.EXPLOITAVAILABLE
,vpm.FAMILY_NAME
,vpm.FIRSTSEEN::date as FIRSTSEEN
,vpm.LASTFOUND::date as LASTFOUND
,vpm.FISMASEVERITY as PLUGIN_FISMASEVERITY
,vm.FISMASEVERITY as CVE_FISMASEVERITY
,vpm.INSERT_DATE::date as PLUGIN_INSERT_DATE
,vpm.IS_FROM_AWS_FEED
,a.IS_TENABLE_CREDENTIALED_SCAN
,a.last_confirmed_time
,a.asset_id_tattoo
,a.fqdn
,a.hostname
,a.netbiosname
,a.macaddress
,a.ipv4
,vpm.PORT
,case coalesce(kev.ID,0)
    WHEN 0 THEN 0
    ELSE 1
end::boolean as IS_KEV
,kev.BODDUEDATE::date as KEV_DUEDATE
,kev.SHORTDESCRIPTION as KEV_SHORTDESCRIPTION
,kev.VENDORPROJECT as KEV_VENDORPROJECT
,kev.VULNERABILITYNAME as KEV_VULNERABILITYNAME
,vpm.REPOSITORY_ID
,trh.REPOSITORY_LASTSEEN::date as REPOSITORY_LASTSEEN
,vpm.REPOSITORY_NAME
,vpm.PATCHPUB_DATE::date as PATCHPUB_DATE
,vpm.VULN_PUB_DATE::date as VULN_PUB_DATE
--,vpm.DESCRIPTION
--,vpm.SOLUTION
--,vpm.SYNOPSIS
,vpm.VERSION
FROM CORE.VULPLUGINS_MASTER vpm
join table(flatten(cve,outer=>true)) as f
LEFT OUTER JOIN CORE.KEV_CATALOG kev on kev.CVE = f.value::string and kev.IS_DELETED = 0
JOIN CORE.VULMASTER vm on vm.dw_asset_id = vpm.dw_asset_id and vm.CVE = f.value::string
JOIN CORE.VW_ASSETS a on a.DW_ASSET_ID = vpm.DW_ASSET_ID
LEFT OUTER JOIN (select DATACENTER_ID,REPOSITORY_ID,MAX(INSERT_DATE) as REPOSITORY_LASTSEEN
    FROM CORE.TENABLE_REPOSITORYHIST 
    GROUP BY DATACENTER_ID,REPOSITORY_ID) trh on trh.DATACENTER_ID = a.DATACENTER_ID and trh.REPOSITORY_ID = vpm.REPOSITORY_ID
WHERE vpm.repository_id in (94,95,96,97) 

/*
WHERE (a.system_id = '95392439db248410296cfd0e0f961941' -- HRES
    or
    a.datacenter_id = '95392439db248410296cfd0e0f961941') -- HRES
and f.value::string = 'CVE-2024-37891'
*/
order by a.DATACENTER_ACRONYM
,a.SYSTEM_ACRONYM
,a.dw_asset_id
,f.value::string
,vpm.plugin_id
;