CREATE OR REPLACE PROCEDURE "SP_CRM_LOAD_ASSET_V2"("P_SNAPSHOT_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Process RAW_HWAM or RAW_TENABLE_VUL data into ASSET tables'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_LOAD_ASSET_V2'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean := 0;
True boolean := 1;
RowDispositionViable varchar := ''Viable'';
AWS_HWAM varchar := ''AWS HWAM'';
AWS_TENABLE varchar := ''AWS VUL'';
CCIC_TENABLE varchar := ''CCIC VUL'';
AWS_VUL_MITIGATED varchar := ''AWS VUL MITIGATED'';
CCIC_VUL_MITIGATED varchar := ''CCIC VUL MITIGATED'';
FORESCOUT_HWAM varchar := ''FORESCOUT''; -- Added 240329 CR860
CROWDSTRIKE varchar := ''CROWDSTRIKE''; -- Added 240822 CR958
AXONIUS varchar := ''AXONIUS''; -- Added 240917 CR981
MAG_VUL varchar := ''MAG VUL''; -- 241022 CR1012
MAG_VUL_MITIGATED varchar := ''MAG VUL MITIGATED''; -- 241022 CR1012
HWAM varchar := ''HWAM'';
VUL varchar := ''VUL'';
PARENT_DATACATEGORY varchar;
UnknownDeviceType varchar := ''Unknown'';
DATACATEGORY varchar;
RECORD_COUNT NUMBER;

BEGIN
select DATACATEGORY,PARENT_DATACATEGORY into :DATACATEGORY,:PARENT_DATACATEGORY FROM CORE.SNAPSHOT_IDS where SNAPSHOT_ID = :P_SNAPSHOT_ID;
Appl := :Appl || ''('' || DATACATEGORY || '')''; -- This helps to clarify which snapshot we are processing
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

-- 241022 CR1012 add MAG_VUL,MAG_VUL_MITIGATED
-- 240917 CR981 add AXONIUS
-- 240822 CR958 add CROWDSTRIKE
IF (:DATACATEGORY NOT IN (:AWS_HWAM,:AWS_TENABLE,:AWS_VUL_MITIGATED,:CCIC_TENABLE,:CCIC_VUL_MITIGATED,
    :FORESCOUT_HWAM,:CROWDSTRIKE,:AXONIUS,:MAG_VUL,:MAG_VUL_MITIGATED)) THEN
	BEGIN
	Msg := ''Unknown DataCategory - check SNAPSHOT_ID'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
END IF;

BEGIN TRANSACTION; -- 240611 CR903 add transaction
--
-- Write RAW_HWAM or RAW_TENABLE_VUL to common TEMP_HWAM for asset matching/asset creation/asset update
--
IF (upper(:PARENT_DATACATEGORY) = :HWAM) THEN
	BEGIN
    INSERT INTO TEMP_HWAM(
    ASSET_ID_TATTOO
    ,AWS_ACCOUNTID
    ,BIGFIX_ASSET_ID
    ,BIOS_GUID
    ,COMPUTER_TYPE
    ,DATACENTER_ID
    ,DEVICE_TYPE
    ,DEVICEMODEL
    ,ENVIRONMENT
    ,FQDN
    ,HOSTNAME
    ,INSTANCESTATUS
    ,IPV4
    ,IPV6
    ,IS_FORESCOUT_MANAGED
    ,IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC
    ,LAST_CONFIRMED_TIME
    ,MACADDRESS
    ,MOTHERBOARD
    ,NETBIOSNAME
    ,OS
    ,SNAPSHOT_ID
    ,SOURCE_TOOL
    ,SYSTEM_ID
    ,TEMP_DW_ASSET_ID
    ,TENANT_ID
	)
	SELECT
    ASSET_ID_TATTOO
    ,AWS_ACCOUNTID
    ,BIGFIX_ASSET_ID
    ,BIOS_GUID
    ,COMPUTER_TYPE
    ,DATACENTER_ID
    ,DEVICE_TYPE
    ,DEVICEMODEL
    ,ENVIRONMENT
    ,FQDN
    ,HOSTNAME
    ,INSTANCESTATUS
    ,IPV4
    ,IPV6
    ,COALESCE(NULLIF(IS_FS_MANAGED,''''),''0'')::BOOLEAN -- IS_FORESCOUT_MANAGED
    ,IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC
    ,LAST_CONFIRMED_TIME
    ,MACADDRESS
    ,MOTHERBOARD
    ,NETBIOSNAME
    ,OS
    ,SNAPSHOT_ID
    ,SOURCE_TOOL
    ,SYSTEM_ID
    ,TEMP_DW_ASSET_ID
    ,TENANT_ID
    FROM CORE.RAW_HWAM 
    WHERE RAW_HWAM_ID IN 
    (SELECT r2.RAW_HWAM_ID 
    --
    -- 240815 1449 CR-EBF Find TEMP_DW_ASSET_ID with most current (LAST_CONFIRMED_TIME) as expressed in RAW_HWAM_ID
    --
    FROM (select rank()over(partition by r1.TEMP_DW_ASSET_ID order by r1.LAST_CONFIRMED_TIME desc,r1.RAW_HWAM_ID desc) TheRank,r1.TEMP_DW_ASSET_ID,r1.LAST_CONFIRMED_TIME,r1.RAW_HWAM_ID
        FROM CORE.RAW_HWAM r1
        JOIN (select DISTINCT TEMP_DW_ASSET_ID FROM CORE.RAW_HWAM 
        WHERE snapshot_id = :P_SNAPSHOT_ID 
        -- 240826 CR-TBD and ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() 
            and array_size(DATA_ERROR_ARRAY) = 0 and TEMP_DW_ASSET_ID IS NOT NULL) d on d.TEMP_DW_ASSET_ID = r1.TEMP_DW_ASSET_ID
        WHERE r1.snapshot_id = :P_SNAPSHOT_ID 
        -- 240826 CR-TBD and r1.ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() 
        and array_size(r1.DATA_ERROR_ARRAY) = 0) r2 where r2.TheRank = 1);
	END;
ELSE
BEGIN
	INSERT INTO TEMP_HWAM(
    ASSET_ID_TATTOO
    ,AWS_ACCOUNTID
    ,AZURE_SUBSCRIPTION_ID -- 241125 CR1038
    ,DATACENTER_ID
    ,FQDN
    ,HOSTNAME
    ,IPV4
    ,IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC
    ,IS_TENABLE_CREDENTIALED_SCAN
    ,LAST_CONFIRMED_TIME
    ,MACADDRESS
    ,NETBIOSNAME
    ,OS
    ,SNAPSHOT_ID
    ,SOURCE_TOOL
    ,SYSTEM_ID
    ,TEMP_DW_ASSET_ID
    ,TENABLEUUID
    ,TENANT_ID
	)
	SELECT
    ASSET_ID_TATTOO
    ,AWS_ACCOUNTID
    ,AZURE_SUBSCRIPTION_ID -- 241125 CR1038
    ,DATACENTER_ID
    ,DNSNAME::array -- FQDN
    ,HOSTNAME::array -- HOSTNAME
    ,IPS::array -- IPV4
    ,IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC
    ,COALESCE(NULLIF(CREDENTIALED_SCAN,''''),''0'')::BOOLEAN -- IS_TENABLE_CREDENTIALED_SCAN
    ,LAST_SEEN -- LAST_CONFIRMED_TIME
    ,MACADDRESS::array -- MACADDRESS
    ,NETBIOSNAME::array -- NETBIOSNAME
    ,OPERATING_SYSTEM -- OS
    ,SNAPSHOT_ID
    ,SOURCE_TOOL
    ,SYSTEM_ID
    ,TEMP_DW_ASSET_ID
    ,TENABLEUUID
    ,TENANT_ID
    FROM CORE.RAW_TENABLE_VUL
    WHERE RAW_TENABLE_VUL_ID IN 
    (SELECT r2.RAW_TENABLE_VUL_ID 
    --
    -- 240815 1449 CR-EBF Find TEMP_DW_ASSET_ID with most current (LAST_SEEN) as expressed in RAW_TENABLE_VUL_ID
    --
    FROM (select rank()over(partition by r1.TEMP_DW_ASSET_ID order by r1.LAST_SEEN desc,r1.RAW_TENABLE_VUL_ID desc) TheRank,r1.TEMP_DW_ASSET_ID,r1.LAST_SEEN,r1.RAW_TENABLE_VUL_ID
        FROM CORE.RAW_TENABLE_VUL r1
        JOIN (select DISTINCT TEMP_DW_ASSET_ID FROM CORE.RAW_TENABLE_VUL 
        WHERE snapshot_id = :P_SNAPSHOT_ID 
        -- 240826 CR-TBD and ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() 
            and array_size(DATA_ERROR_ARRAY) = 0 and TEMP_DW_ASSET_ID IS NOT NULL) d on d.TEMP_DW_ASSET_ID = r1.TEMP_DW_ASSET_ID
        WHERE r1.snapshot_id = :P_SNAPSHOT_ID 
        -- 240826 CR-TBD and r1.ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() 
        and array_size(r1.DATA_ERROR_ARRAY) = 0) r2 where r2.TheRank = 1);
	END;
END IF;

RECORD_COUNT := SQLROWCOUNT;
Msg := ''TEMP_HWAM rows written='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

COMMIT;

BEGIN TRANSACTION;
--
-- 240606 CR903
--
-- NORMALIZE certain fields to be used in asset matching.
-- ASSET_ID_TATTOO found differences in case depending on the sensor
-- FQDN is almost always a single value so an array is not needed. I found 5 cases over 90 days where there was more than one value but they were bogus
-- HOSTNAME needs to be an array. Had to flatten HOSTNAME in order to do split_part then re-create array.
-- NETBIOSNAME is almost always a single value so an array is not needed. I found 1 case over 90 days where there was more than one value but it was bogus
-- MACADDRESS needs to be an array
--
-- Also note: When testing this sql in a separate worksheet remove one of the back-slashes between the double-dollars
--
UPDATE TEMP_HWAM upd
set ASSET_ID_TATTOO = UPPER(th.ASSET_ID_TATTOO) -- 240622 CR903 Found upper/lower case values depending on sensor
,NORMALIZED_FQDN = UPPER(NULLIF(GET(th.FQDN,0)::varchar,''''))
,NORMALIZED_HOSTNAME = n.NORMALIZED_HOSTNAME -- 240611 CR903
,NORMALIZED_NETBIOSNAME = UPPER(coalesce(NULLIF(split_part(GET(th.NETBIOSNAME,0)::varchar,$$\\$$,2),''''),GET(th.NETBIOSNAME,0)::varchar)) -- Use double-dollars to avoid back-slash escape
,NORMALIZED_MACADDRESS = STRTOK_TO_ARRAY(UPPER(REPLACE(REPLACE(ARRAY_TO_STRING(th.MACADDRESS,''$''),'':'',''''),''-'','''')),''$'')
,MOTHERBOARD = UPPER(th.MOTHERBOARD) -- 240617
FROM (SELECT r.TEMP_HWAM_ID,ARRAY_AGG(NULLIF(REPLACE(UPPER(coalesce(split_part(f.value::string,''.'',1),split_part(GET(r.fqdn,0),''.'',1))),''*'',''''),'''')) as NORMALIZED_HOSTNAME
    FROM TEMP_HWAM r
    join table(flatten(HOSTNAME,outer=>true)) as f
    where r.SNAPSHOT_ID = :P_SNAPSHOT_ID
    GROUP BY r.TEMP_HWAM_ID) n
JOIN TEMP_HWAM th on th.TEMP_HWAM_ID = n.TEMP_HWAM_ID
WHERE upd.TEMP_HWAM_ID = th.TEMP_HWAM_ID;

COMMIT;

--
-- Attempt to match new rows against existing asset records
--
CALL CORE.SP_CRM_MATCH_EXISTING_ASSET_V3(:P_SNAPSHOT_ID); -- 240828 CR-TBD V3  240621 CR903
CALL CORE.SP_CRM_UPDATE_ASSET(:P_SNAPSHOT_ID); -- 240705 CR928 Renamed procedure
CALL CORE.SP_CRM_LOAD_ASSETINTERFACE(:P_SNAPSHOT_ID); -- Update the ASSETINTERFACE_* tables

--
-- Insert ASSET table based on Non-ASSET_ID_TATTOO rows
--
CALL CORE.SP_CRM_CREATE_ASSET_V1(:P_SNAPSHOT_ID); -- 240621 2109 CR903
CALL CORE.SP_CRM_LOAD_ASSETINTERFACE(:P_SNAPSHOT_ID); -- Update the ASSETINTERFACE_* tables

IF (:DATACATEGORY IN (:AWS_HWAM,:FORESCOUT_HWAM,:CROWDSTRIKE,:AXONIUS)) THEN -- 240917 CR981 add AXONIUS, 240822 CR958 add CROWDSTRIKE
	BEGIN
    --
    -- 240727 CR928
    -- At this time only HWAM datastreams provide DEVICETYPE.
    -- AWS is always: Server
    --
    BEGIN TRANSACTION;
    UPDATE ASSET upd
    set DEVICETYPE = t.DEVICE_TYPE
    FROM (SELECT dev.DW_ASSET_ID,dev.DEVICE_TYPE
        FROM (select rank()over(partition by DW_ASSET_ID order by DEVICE_TYPE) TheRank,DW_ASSET_ID,DEVICE_TYPE
        FROM CORE.TEMP_HWAM th
        JOIN CORE.DEVICETYPES dt on UPPER(dt.DEVICETYPE) = UPPER(th.DEVICE_TYPE)
        WHERE th.SNAPSHOT_ID = :P_SNAPSHOT_ID) dev where dev.TheRank = 1) t
    WHERE upd.DEVICETYPE = :UnknownDeviceType and upd.DW_ASSET_ID = t.DW_ASSET_ID;

    RECORD_COUNT := SQLROWCOUNT;
    Msg := ''Updated ASSET.DEVICETYPE='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    COMMIT;   
	END;
END IF;


BEGIN TRANSACTION;

IF (upper(:PARENT_DATACATEGORY) = :VUL) THEN
	BEGIN
    --
    -- Set RAW_TENABLE_VUL.DW_ASSET_ID so SP_CRM_VULMASTER can link vulnerabilities to assets and for traceability
    --
    -- 240828 CR-TBD enhanced WHERE to improve performance
    --
    UPDATE RAW_TENABLE_VUL upd
    set DW_ASSET_ID = t.DW_ASSET_ID
    FROM RAW_TENABLE_VUL r
    JOIN TEMP_HWAM t on t.SNAPSHOT_ID = r.SNAPSHOT_ID and t.TEMP_DW_ASSET_ID = r.TEMP_DW_ASSET_ID
    WHERE upd.RAW_TENABLE_VUL_ID = r.RAW_TENABLE_VUL_ID
    and t.SNAPSHOT_ID = :P_SNAPSHOT_ID 
    and upd.TEMP_DW_ASSET_ID = t.TEMP_DW_ASSET_ID and t.DW_ASSET_ID IS NOT NULL and r.DW_ASSET_ID IS NULL;
    
 -- 240828 CR-TBD   WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and upd.TEMP_DW_ASSET_ID = r.TEMP_DW_ASSET_ID and t.DW_ASSET_ID IS NOT NULL and r.DW_ASSET_ID IS NULL;
   
    UPDATE ASSET upd
    set SOURCE_TOOL_VUL = :DATACATEGORY
    ,LASTMODIFIEDBY_TENABLE = CURRENT_TIMESTAMP()
    ,LASTSEEN_VUL = t.LAST_CONFIRMED_TIME
    FROM TEMP_HWAM t
    WHERE t.SNAPSHOT_ID = :P_SNAPSHOT_ID and upd.DW_ASSET_ID = t.DW_ASSET_ID;
    END;
ELSE
	BEGIN
    --
    -- Set RAW_HWAM.DW_ASSET_ID for traceability
    --
    -- 240828 CR-TBD enhanced WHERE to improve performance
    --
    UPDATE RAW_HWAM upd
    set DW_ASSET_ID = t.DW_ASSET_ID
    FROM RAW_HWAM r
    JOIN TEMP_HWAM t on t.SNAPSHOT_ID = r.SNAPSHOT_ID and t.TEMP_DW_ASSET_ID = r.TEMP_DW_ASSET_ID
    WHERE upd.RAW_HWAM_ID = r.RAW_HWAM_ID
    and t.SNAPSHOT_ID = :P_SNAPSHOT_ID 
    and upd.TEMP_DW_ASSET_ID = t.TEMP_DW_ASSET_ID and t.DW_ASSET_ID IS NOT NULL and r.DW_ASSET_ID IS NULL;

 -- 240828 CR-TBD    WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and upd.TEMP_DW_ASSET_ID = r.TEMP_DW_ASSET_ID and t.DW_ASSET_ID IS NOT NULL and r.DW_ASSET_ID IS NULL;

    IF (upper(:DATACATEGORY) = :AWS_HWAM) THEN
        BEGIN   
        UPDATE ASSET upd
        set SOURCE_TOOL_HWAM = :DATACATEGORY
        ,LASTMODIFIEDBY_AWS = CURRENT_TIMESTAMP()
        ,LASTSEEN_HWAM = t.LAST_CONFIRMED_TIME
        FROM TEMP_HWAM t
        WHERE upd.DW_ASSET_ID = t.DW_ASSET_ID and t.SNAPSHOT_ID = :P_SNAPSHOT_ID;
        END;
    ELSEIF (upper(:DATACATEGORY) = :FORESCOUT_HWAM) THEN -- Added 240329 CR860
        BEGIN 
        UPDATE ASSET upd
        set SOURCE_TOOL_HWAM = :DATACATEGORY
        ,LASTMODIFIEDBY_FORESCOUT = CURRENT_TIMESTAMP()
        ,LASTSEEN_HWAM = t.LAST_CONFIRMED_TIME
        FROM TEMP_HWAM t
        WHERE upd.DW_ASSET_ID = t.DW_ASSET_ID and t.SNAPSHOT_ID = :P_SNAPSHOT_ID;
        END;
    ELSEIF (upper(:DATACATEGORY) = :CROWDSTRIKE) THEN -- Added 240822 CR958
        BEGIN 
        UPDATE ASSET upd
        set SOURCE_TOOL_HWAM = :DATACATEGORY
        ,LASTMODIFIEDBY_CROWDSTRIKE = CURRENT_TIMESTAMP()
        ,LASTSEEN_HWAM = t.LAST_CONFIRMED_TIME
        FROM TEMP_HWAM t
        WHERE upd.DW_ASSET_ID = t.DW_ASSET_ID and t.SNAPSHOT_ID = :P_SNAPSHOT_ID;
        END; 
    ELSEIF (upper(:DATACATEGORY) = :AXONIUS) THEN -- Added 240822 CR958
        BEGIN 
        UPDATE ASSET upd
        set SOURCE_TOOL_HWAM = :DATACATEGORY
        ,LASTMODIFIEDBY_AXONIUS = CURRENT_TIMESTAMP()
        ,LASTSEEN_HWAM = t.LAST_CONFIRMED_TIME
        FROM TEMP_HWAM t
        WHERE upd.DW_ASSET_ID = t.DW_ASSET_ID and t.SNAPSHOT_ID = :P_SNAPSHOT_ID;
        END;
    ELSE
        BEGIN -- Unknown
        UPDATE ASSET upd
        set SOURCE_TOOL_HWAM = :DATACATEGORY
        ,LASTSEEN_HWAM = t.LAST_CONFIRMED_TIME
        FROM TEMP_HWAM t
        WHERE upd.DW_ASSET_ID = t.DW_ASSET_ID and t.SNAPSHOT_ID = :P_SNAPSHOT_ID;
        END;
    END IF;
    END;
END IF;

UPDATE CORE.SNAPSHOT_IDS
set UNASSIGNED_DW_ASSET_ID = (select count(1) from TEMP_HWAM WHERE SNAPSHOT_ID = :P_SNAPSHOT_ID and dw_asset_id IS NULL)
WHERE snapshot_id = :P_SNAPSHOT_ID;

COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';