CREATE OR REPLACE PROCEDURE "SP_CRM_UPDATE_ASSET"("P_SNAPSHOT_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Update ASSET table using TEMP_HWAM data'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_UPDATE_ASSET'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean := 0;
True boolean := 1;
CCIC_VUL_MITIGATED varchar := ''CCIC VUL MITIGATED''; -- 241104 CR1021
DATACATEGORY varchar;
RECORD_COUNT NUMBER;

BEGIN
select DATACATEGORY into :DATACATEGORY FROM CORE.SNAPSHOT_IDS where SNAPSHOT_ID = :P_SNAPSHOT_ID;
Appl := :Appl || ''('' || DATACATEGORY || '')''; -- This helps to clarify which VUL we are processing
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

BEGIN TRANSACTION;

UPDATE ASSET upd
set
ASSET_ID_TATTOO = coalesce(upd.ASSET_ID_TATTOO,src.ASSET_ID_TATTOO) -- Use src value only if existing (upd) value is null
,AWS_ACCOUNTID = coalesce(src.AWS_ACCOUNTID,upd.AWS_ACCOUNTID) -- Retain value if source is null
,AWS_INSTANCESTATUS = coalesce(src.INSTANCESTATUS,upd.AWS_INSTANCESTATUS) -- Retain value if source is null
,AZURE_SUBSCRIPTION_ID = coalesce(src.AZURE_SUBSCRIPTION_ID,upd.AZURE_SUBSCRIPTION_ID) -- 241125 CR1038 -- Retain value if source is null
,COMPUTER_TYPE = coalesce(src.COMPUTER_TYPE,upd.COMPUTER_TYPE) -- Retain value if source is null
,DATEDELETED = NULL -- Asset might have been inactive (aka logically deleted)
,DELETIONREASON = NULL -- Asset might have been inactive (aka logically deleted)
,DEVICEMODEL = coalesce(src.DEVICEMODEL,upd.DEVICEMODEL) -- 230927 Retain value if source is null
,DEVICETYPE = coalesce(src.DEVICE_TYPE,upd.DEVICETYPE) -- Retain value if source is null
,ENVIRONMENT = coalesce(src.ENVIRONMENT,upd.ENVIRONMENT) -- Retain value if source is null
,IS_APPLICABLE = TRUE -- If asset was inactive (aka logically deleted) then reactivate it since we have new data
,IS_FORESCOUT_MANAGED = coalesce(src.IS_FORESCOUT_MANAGED,upd.IS_FORESCOUT_MANAGED) -- 240705 CR931
,IS_TENABLE_CREDENTIALED_SCAN = coalesce(src.IS_TENABLE_CREDENTIALED_SCAN,upd.IS_TENABLE_CREDENTIALED_SCAN) -- 240705 CR931
,LAST_CONFIRMED_TIME = GREATEST(src.LAST_CONFIRMED_TIME,upd.LAST_CONFIRMED_TIME) 
,LASTASSETUPDATE = CURRENT_TIMESTAMP()
,MODIFIEDBY_SNAPSHOT_ID = src.SNAPSHOT_ID
,MODIFIEDBY_TEMP_DW_ASSET_ID = src.TEMP_DW_ASSET_ID -- 240705 CR928
,MOTHERBOARD = coalesce(src.MOTHERBOARD,upd.MOTHERBOARD) -- Retain value if source is null
,OS = coalesce(src.OS,upd.OS) -- Retain value if source is null
,OS_BUILD_NUMBER = coalesce(src.OS_BUILD_NUMBER,upd.OS_BUILD_NUMBER) -- 240821 CR958; and Retain value if source is null
,SOURCE_TOOL_LASTSEEN = src.SOURCE_TOOL
--
-- 241104 CR1021 CCIC VUL MITIGATED does not contain metadata tags and so SYSTEM_ID defaults to DATACENTER_ID and should not
-- 240926 Tested is_freeze_system_id to determine if SYSTEM_ID could be changed. This was a special (one-time) case to facilitate DRaaS re-tagging efforts
--        Prior to 240926 SYSTEM_ID was readily changed by any sensor data
-- 
,SYSTEM_ID = case :DATACATEGORY
    when :CCIC_VUL_MITIGATED then upd.SYSTEM_ID -- Retain SYSTEM_ID (DONT ALLOW IT TO BE CHANGED)
    Else src.SYSTEM_ID -- Its ok to change the system that the asset belongs to
    end
,TENABLEUUID = coalesce(src.TENABLEUUID,upd.TENABLEUUID) -- Retain value if source is null
,TENANT_ID = coalesce(upd.TENANT_ID,src.TENANT_ID) -- 240705 CR928 Use src value only if existing (upd) value is null, 240424 CR880 
from -- 240830 1724 CR-TBD reworked finding unique TEMP_HWAM record that represents the distinct DW_ASSET_ID
(SELECT r2.TEMP_HWAM_ID
    FROM (select rank()over(partition by r1.DW_ASSET_ID order by r1.LAST_CONFIRMED_TIME desc,r1.TEMP_HWAM_ID desc) TheRank,r1.TEMP_HWAM_ID
        FROM CORE.TEMP_HWAM r1
        JOIN (select DW_ASSET_ID
        FROM CORE.TEMP_HWAM WHERE SNAPSHOT_ID = :P_SNAPSHOT_ID and DW_ASSET_ID IS NOT NULL
        GROUP BY DW_ASSET_ID) d on d.DW_ASSET_ID = r1.DW_ASSET_ID) r2 where r2.TheRank = 1) thi
JOIN CORE.TEMP_HWAM src on src.TEMP_HWAM_ID = thi.TEMP_HWAM_ID -- Single record representing the asset to be updated
where src.SNAPSHOT_ID = :P_SNAPSHOT_ID and src.DW_ASSET_ID IS NOT NULL and upd.DW_ASSET_ID = src.DW_ASSET_ID;

-- 240726 CR928
RECORD_COUNT := SQLROWCOUNT;
Msg := ''Updated ASSET='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

COMMIT;


BEGIN TRANSACTION; -- 241114 CR-EBF for diagnostics
INSERT INTO BUS_CYBER_RISK_MANAGEMENT.CORE.ASSET_SNAPSHOT_LOG (
ASSET_DATECREATED
,ASSET_ID_TATTOO
,AWS_ACCOUNTID
,AWS_INSTANCESTATUS
,AZURE_SUBSCRIPTION_ID -- 241125 CR1038
,AXONIUS_INTERNAL_AXONIUS_ID
,BIGFIX_ASSET_ID
,BIOS_GUID
,CLOUD_ID
,COMPUTER_TYPE
,CREATEDBY_RAW_ID
,CREATEDBY_SNAPSHOT_ID
,CREATEDBY_TEMP_DW_ASSET_ID
,DATACENTER_ID
,DATEDELETED
,DATEMODIFIED
,DELETIONREASON
,DEVICEMODEL
,DEVICETYPE
,DW_ASSET_ID
,ENVIRONMENT
,INSERT_DATE
,IS_APPLICABLE
,IS_FORESCOUT_MANAGED
,IS_FREEZE_SYSTEM_ID
,IS_FROM_AWS_FEED
,IS_PRIMARY_FISMA_ID_DERIVED
,IS_SCANNABLE
,IS_TATTOOABLE
,IS_TENABLE_CREDENTIALED_SCAN
,LAST_CONFIRMED_TIME
,LASTASSETUPDATE
,LASTMODIFIEDBY_AWS
,LASTMODIFIEDBY_AXONIUS
,LASTMODIFIEDBY_BIGFIX
,LASTMODIFIEDBY_CROWDSTRIKE
,LASTMODIFIEDBY_FORESCOUT
,LASTMODIFIEDBY_TENABLE
,LASTSEEN_CSM
,LASTSEEN_HWAM
,LASTSEEN_SWAM
,LASTSEEN_VUL
,MODIFIEDBY_RAW_ID
,MODIFIEDBY_SNAPSHOT_ID
,MODIFIEDBY_TEMP_DW_ASSET_ID
,MOTHERBOARD
,OS
,OS_BUILD_NUMBER
,OS_CPE
,OS_VERSION
,PREV_DATEDELETED
,PREV_LAST_CONFIRMED_TIME
,PREV_SYSTEM_ID
,SNAPSHOT_ID
,SOURCE_TOOL_CREATE
,SOURCE_TOOL_CSM
,SOURCE_TOOL_HWAM
,SOURCE_TOOL_LASTSEEN
,SOURCE_TOOL_SWAM
,SOURCE_TOOL_VUL
,SYSTEM_ID
,TENABLEUUID
,TENANT_ID
,VULNRISKTOLERANCE
)
select 
a.INSERT_DATE as ASSET_DATECREATED
,a.ASSET_ID_TATTOO
,a.AWS_ACCOUNTID
,a.AWS_INSTANCESTATUS
,a.AZURE_SUBSCRIPTION_ID -- 241125 CR1038
,a.AXONIUS_INTERNAL_AXONIUS_ID
,a.BIGFIX_ASSET_ID
,a.BIOS_GUID
,a.CLOUD_ID
,a.COMPUTER_TYPE
,a.CREATEDBY_RAW_ID
,a.CREATEDBY_SNAPSHOT_ID
,a.CREATEDBY_TEMP_DW_ASSET_ID
,a.DATACENTER_ID
,a.DATEDELETED
,a.DATEMODIFIED
,a.DELETIONREASON
,a.DEVICEMODEL
,a.DEVICETYPE
,a.DW_ASSET_ID
,a.ENVIRONMENT
,CURRENT_TIMESTAMP() as INSERT_DATE
,a.IS_APPLICABLE
,a.IS_FORESCOUT_MANAGED
,a.IS_FREEZE_SYSTEM_ID
,a.IS_FROM_AWS_FEED
,a.IS_PRIMARY_FISMA_ID_DERIVED
,a.IS_SCANNABLE
,a.IS_TATTOOABLE
,a.IS_TENABLE_CREDENTIALED_SCAN
,a.LAST_CONFIRMED_TIME
,a.LASTASSETUPDATE
,a.LASTMODIFIEDBY_AWS
,a.LASTMODIFIEDBY_AXONIUS
,a.LASTMODIFIEDBY_BIGFIX
,a.LASTMODIFIEDBY_CROWDSTRIKE
,a.LASTMODIFIEDBY_FORESCOUT
,a.LASTMODIFIEDBY_TENABLE
,a.LASTSEEN_CSM
,a.LASTSEEN_HWAM
,a.LASTSEEN_SWAM
,a.LASTSEEN_VUL
,a.MODIFIEDBY_RAW_ID
,a.MODIFIEDBY_SNAPSHOT_ID
,a.MODIFIEDBY_TEMP_DW_ASSET_ID
,a.MOTHERBOARD
,a.OS
,a.OS_BUILD_NUMBER
,a.OS_CPE
,a.OS_VERSION
,a.PREV_DATEDELETED
,a.PREV_LAST_CONFIRMED_TIME
,a.PREV_SYSTEM_ID
,:P_SNAPSHOT_ID
,a.SOURCE_TOOL_CREATE
,a.SOURCE_TOOL_CSM
,a.SOURCE_TOOL_HWAM
,a.SOURCE_TOOL_LASTSEEN
,a.SOURCE_TOOL_SWAM
,a.SOURCE_TOOL_VUL
,a.SYSTEM_ID
,a.TENABLEUUID
,a.TENANT_ID
,a.VULNRISKTOLERANCE
FROM ASSET a
JOIN TEMP_HWAM th on th.dw_asset_id = a.dw_asset_id and th.TEMP_DW_ASSET_ID = a.MODIFIEDBY_TEMP_DW_ASSET_ID and a.MODIFIEDBY_SNAPSHOT_ID = :P_SNAPSHOT_ID; -- 241120

RECORD_COUNT := SQLROWCOUNT;
Msg := ''Insert ASSET_SNAPSHOT_LOG='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';