CREATE OR REPLACE PROCEDURE "SP_CRM_DATAFEED_CHECKER"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Check freshness of datastream feeds'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_DATAFEED_CHECKER'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean := 0;
True boolean := 1;
CCIC_TENABLE_CUMULATIVE_VULNS_COUNT NUMBER;
CCIC_TENABLE_CUMULATIVE_INFO_COUNT NUMBER;
CCIC_TENABLE_MITIGATED_VULNS_COUNT NUMBER;
IUSG_CUMULATIVE_VULNS_COUNT NUMBER;
IUSG_MITIGATED_VULNS_COUNT NUMBER;
HWAM_AWS_COUNT NUMBER;
SDL_FORESCOUT_ASSETS_COUNT NUMBER;

CCIC_TENABLE_CUMULATIVE_VULNS_LASTSEEN DATETIME;
CCIC_TENABLE_CUMULATIVE_INFO_LASTSEEN DATETIME;
CCIC_TENABLE_MITIGATED_VULNS_LASTSEEN DATETIME;
IUSG_CUMULATIVE_VULNS_LASTSEEN DATETIME;
IUSG_MITIGATED_VULNS_LASTSEEN DATETIME;
HWAM_AWS_LASTSEEN DATETIME;
SDL_FORESCOUT_ASSETS_LASTSEEN DATETIME;

RECORD_COUNT NUMBER;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

-- We expect data every day but start 10 days back in case of back-to-back weekend failures

/*
select max(REPORTDATE),count(1) INTO CCIC_TENABLE_CUMULATIVE_VULNS_LASTSEEN,CCIC_TENABLE_CUMULATIVE_VULNS_COUNT 
    from APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_CUMULATIVE_VULNS WHERE REPORTDATE::date > (current_date() - 10)::date;
*/
select m.REPORTDATE,count(1) INTO CCIC_TENABLE_CUMULATIVE_VULNS_LASTSEEN,CCIC_TENABLE_CUMULATIVE_VULNS_COUNT 
FROM (select max(REPORTDATE) as REPORTDATE
    from APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_CUMULATIVE_VULNS WHERE REPORTDATE::date > (current_date() - 10)::date) m
JOIN APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_CUMULATIVE_VULNS v on v.REPORTDATE::date = m.REPORTDATE::date
group by m.REPORTDATE;

Msg := ''SEC_VW_CCIC_TENABLE_CUMULATIVE_VULNS: Lastseen:'' || substring(:CCIC_TENABLE_CUMULATIVE_VULNS_LASTSEEN::varchar,1,16) 
    || '', Count='' || :CCIC_TENABLE_CUMULATIVE_VULNS_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

select max(REPORTDATE),count(1) INTO CCIC_TENABLE_CUMULATIVE_INFO_LASTSEEN,CCIC_TENABLE_CUMULATIVE_INFO_COUNT 
    from APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_CUMULATIVE_INFO WHERE REPORTDATE::date > (current_date() - 10)::date;

Msg := ''SEC_VW_CCIC_TENABLE_CUMULATIVE_INFO: Lastseen:'' || substring(:CCIC_TENABLE_CUMULATIVE_INFO_LASTSEEN::varchar,1,16) 
    || '', Count='' || :CCIC_TENABLE_CUMULATIVE_INFO_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

select max(REPORTDATE),count(1) INTO CCIC_TENABLE_MITIGATED_VULNS_LASTSEEN,CCIC_TENABLE_MITIGATED_VULNS_COUNT
    from APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_MITIGATED_VULNS WHERE REPORTDATE::date > (current_date() - 10)::date;

Msg := ''SEC_VW_CCIC_TENABLE_MITIGATED_VULNS: Lastseen:'' || substring(:CCIC_TENABLE_MITIGATED_VULNS_LASTSEEN::varchar,1,16) 
    || '', Count='' || :CCIC_TENABLE_MITIGATED_VULNS_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

select max(S3_FILE_CREATE),count(1) INTO IUSG_CUMULATIVE_VULNS_LASTSEEN,IUSG_CUMULATIVE_VULNS_COUNT
    from APP_TENABLE.SHARED.SEC_VW_IUSG_CUMULATIVE_VULNS WHERE S3_FILE_CREATE::date > (current_date() - 10)::date;

Msg := ''SEC_VW_IUSG_CUMULATIVE_VULNS: Lastseen:'' || substring(:IUSG_CUMULATIVE_VULNS_LASTSEEN::varchar,1,16) 
    || '', Count='' || :IUSG_CUMULATIVE_VULNS_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

select max(S3_FILE_CREATE),count(1) INTO IUSG_MITIGATED_VULNS_LASTSEEN,IUSG_MITIGATED_VULNS_COUNT
    from APP_TENABLE.SHARED.SEC_VW_IUSG_MITIGATED_VULNS WHERE S3_FILE_CREATE::date > (current_date() - 10)::date;

Msg := ''SEC_VW_IUSG_MITIGATED_VULNS: Lastseen:'' || substring(:IUSG_MITIGATED_VULNS_LASTSEEN::varchar,1,16) 
    || '', Count='' || :IUSG_MITIGATED_VULNS_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    
select max(LAST_CONFIRMED_TIME),count(1) INTO HWAM_AWS_LASTSEEN,HWAM_AWS_COUNT
    from APP_CDM.SHARED.SEC_VW_HWAM_AWS; -- Always assumed to return most current data

Msg := ''SEC_VW_HWAM_AWS: Lastseen:'' || substring(:HWAM_AWS_LASTSEEN::varchar,1,16) 
    || '', Count='' || :HWAM_AWS_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

 select max(S3_FILE_TS),count(1) INTO SDL_FORESCOUT_ASSETS_LASTSEEN,SDL_FORESCOUT_ASSETS_COUNT
    from APP_FORESCOUT.SHARED.SEC_VW_SDL_FORESCOUT_ASSETS WHERE S3_FILE_TS::date > (current_date() - 10)::date;

Msg := ''SDL_FORESCOUT_ASSETS: Lastseen:'' || substring(:SDL_FORESCOUT_ASSETS_LASTSEEN::varchar,1,16) 
    || '', Count='' || :SDL_FORESCOUT_ASSETS_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';