CREATE OR REPLACE PROCEDURE "SP_CRM_WRITE_ASSETHIST"("P_REPORT_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Write active ASSET rows to ASSETHIST.'
EXECUTE AS OWNER
AS '

DECLARE 
Appl varchar := ''SP_CRM_WRITE_ASSETHIST'';
Msg varchar;
RowCount number;
ExceptionMsg varchar := ''Default'';
StartOfProgram timestamp := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
RECORD_COUNT number := 0;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

BEGIN TRANSACTION;

INSERT INTO CORE.ASSETHIST
(ASSET_DATECREATED -- 240624 CR913
,ASSET_ID_TATTOO
,AWS_ACCOUNTID -- 240624 CR913
,AWS_INSTANCESTATUS -- 230525
,AZURE_SUBSCRIPTION_ID -- 241125 CR1038
,BIGFIX_ASSET_ID
,BIOS_GUID
,CLOUD_ID -- 230711
,COMPUTER_TYPE
,DATACENTER_ID
,DATEMODIFIED
,DEVICEMODEL -- 230703
,DEVICETYPE
,DW_ASSET_ID
,ENVIRONMENT
,IS_ENDPOINT -- 241212 CR1052
,IS_FORESCOUT_MANAGED -- 241007 CR984
,IS_FREEZE_SYSTEM_ID -- 241007 CR984
,IS_FROM_AWS_FEED -- 241007 CR984
,IS_PRIMARY_FISMA_ID_DERIVED -- 241007 CR984
,IS_SCANNABLE -- 231221
,IS_TATTOOABLE
,IS_TENABLE_CREDENTIALED_SCAN -- 241007 CR984
,LAST_CONFIRMED_TIME
,LASTASSETUPDATE
,LASTMODIFIEDBY_AWS -- 241007 CR984
,LASTMODIFIEDBY_AXONIUS -- 241007 CR984
,LASTMODIFIEDBY_BIGFIX -- 241007 CR984
,LASTMODIFIEDBY_CROWDSTRIKE -- 241007 CR984
,LASTMODIFIEDBY_FORESCOUT -- 241007 CR984
,LASTMODIFIEDBY_TENABLE -- 241007 CR984
,LASTSEEN_CSM
,LASTSEEN_HWAM
,LASTSEEN_SWAM
,LASTSEEN_VUL
,MOTHERBOARD
,OS
,OS_BUILD_NUMBER -- 241007 CR984
,OS_CPE
,OS_VERSION
,PREV_DATEDELETED -- 241007 CR984
,PREV_LAST_CONFIRMED_TIME -- 241007 CR984
,PREV_SYSTEM_ID -- 241007 CR984
,REPORT_ID
,SOURCE_TOOL_CREATE
,SOURCE_TOOL_CSM
,SOURCE_TOOL_HWAM
,SOURCE_TOOL_LASTSEEN
,SOURCE_TOOL_SWAM
,SOURCE_TOOL_VUL
,SYSTEM_ID
,TENABLEUUID
,TENANT_ID -- 240624 CR913
,VULNRISKTOLERANCE
)
SELECT 
a.INSERT_DATE as ASSET_DATECREATED -- 240624 CR913
,a.ASSET_ID_TATTOO
,a.AWS_ACCOUNTID -- 240624 CR913
,a.AWS_INSTANCESTATUS -- 230525
,a.AZURE_SUBSCRIPTION_ID -- 241125 CR1038
,a.BIGFIX_ASSET_ID
,a.BIOS_GUID
,a.CLOUD_ID -- 230711
,a.COMPUTER_TYPE
,a.DATACENTER_ID
,a.DATEMODIFIED
,a.DEVICEMODEL -- 230703
,a.DEVICETYPE
,a.DW_ASSET_ID
,a.ENVIRONMENT
,a.IS_ENDPOINT -- 241212 CR1052
,a.IS_FORESCOUT_MANAGED -- 241007 CR984
,a.IS_FREEZE_SYSTEM_ID -- 241007 CR984
,a.IS_FROM_AWS_FEED -- 241007 CR984
,a.IS_PRIMARY_FISMA_ID_DERIVED -- 241007 CR984
,a.IS_SCANNABLE -- 231221
,a.IS_TATTOOABLE
,a.IS_TENABLE_CREDENTIALED_SCAN -- 241007 CR984
,a.LAST_CONFIRMED_TIME
,a.LASTASSETUPDATE
,a.LASTMODIFIEDBY_AWS -- 241007 CR984
,a.LASTMODIFIEDBY_AXONIUS -- 241007 CR984
,a.LASTMODIFIEDBY_BIGFIX -- 241007 CR984
,a.LASTMODIFIEDBY_CROWDSTRIKE -- 241007 CR984
,a.LASTMODIFIEDBY_FORESCOUT -- 241007 CR984
,a.LASTMODIFIEDBY_TENABLE -- 241007 CR984
,a.LASTSEEN_CSM
,a.LASTSEEN_HWAM
,a.LASTSEEN_SWAM
,a.LASTSEEN_VUL
,a.MOTHERBOARD
,a.OS
,a.OS_BUILD_NUMBER -- 241007 CR984
,a.OS_CPE
,a.OS_VERSION
,a.PREV_DATEDELETED -- 241007 CR984
,a.PREV_LAST_CONFIRMED_TIME -- 241007 CR984
,a.PREV_SYSTEM_ID -- 241007 CR984
,:P_REPORT_ID
,a.SOURCE_TOOL_CREATE
,a.SOURCE_TOOL_CSM
,a.SOURCE_TOOL_HWAM
,a.SOURCE_TOOL_LASTSEEN
,a.SOURCE_TOOL_SWAM
,a.SOURCE_TOOL_VUL
,a.SYSTEM_ID
,a.TENABLEUUID
,a.TENANT_ID -- 240624 CR913
,a.VULNRISKTOLERANCE
FROM CORE.ASSET a
Where a.Is_Applicable = 1;

COMMIT;


BEGIN TRANSACTION;

INSERT INTO CORE.ASSETINTERFACECOALESCEDHIST
	(DW_ASSET_ID,
	FQDN,
	HOSTNAME,
	IPV4,
	IPV6,
	MACADDRESS,
	NETBIOSNAME,
	REPORT_ID)
SELECT
	a.DW_ASSET_ID
	,aic.FQDN
	,aic.HOSTNAME
	,aic.IPV4
	,aic.IPV6
	,aic.MACADDRESS
	,aic.NETBIOSNAME
	,:P_REPORT_ID
FROM CORE.Asset a
join CORE.AssetInterfaceCoalesced aic on aic.DW_ASSET_ID = a.DW_ASSET_ID
Where a.Is_Applicable = 1;

COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
    
    END;
    
    ';