CREATE OR REPLACE PROCEDURE "SP_CRM_IUSG_TENABLE_VUL"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull AWS (IUSG) Tenable Vulnerability data, update/insert Master Device Record(MDR), update/insert Vulnerability Master'
EXECUTE AS OWNER
AS '

DECLARE
Appl varchar := ''SP_CRM_IUSG_TENABLE_VUL'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
SNAPSHOT_ID number;
RECORD_COUNT NUMBER;
BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

--ExceptionMsg := ''Test Alert Monitoring''; 
--raise CRM_logic_exception;

CALL CORE.SP_CRM_PULL_IUSG_VUL();
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(''AWS VUL'');
CALL CORE.SP_CRM_IDENTIFY_RAW_ASSETS(:SNAPSHOT_ID); -- 240727 CR928
CALL CORE.SP_CRM_LINK_METADATA_V2(:SNAPSHOT_ID); -- 250129 CR1077
CALL CORE.SP_CRM_PREP_RAW_TENABLE_VUL_V3(:SNAPSHOT_ID); -- 241025 CR1012
CALL CORE.SP_CRM_LOAD_ASSET_V2(:SNAPSHOT_ID); -- 240705 CR928
CALL CORE.SP_CRM_LOAD_VULPLUGINS_MASTER(:SNAPSHOT_ID);
CALL CORE.SP_CRM_LOAD_VULPLUGIN(:SNAPSHOT_ID); -- 230419 TEMPORARY UNTIL WE CAN DECOMMISSION CORE.VULPLUGIN

CALL CORE.SP_CRM_PULL_IUSG_VUL_MITIGATED();
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(''AWS VUL MITIGATED'');
CALL CORE.SP_CRM_IDENTIFY_RAW_ASSETS(:SNAPSHOT_ID); -- 240727 CR928
CALL CORE.SP_CRM_LINK_METADATA_V2(:SNAPSHOT_ID); -- 250129 CR1077
CALL CORE.SP_CRM_PREP_RAW_TENABLE_VUL_V3(:SNAPSHOT_ID); -- 241025 CR1012
CALL CORE.SP_CRM_LOAD_ASSET_V2(:SNAPSHOT_ID); -- 240705 CR928
CALL CORE.SP_CRM_UPDATE_VULPLUGINS_MASTER(:SNAPSHOT_ID);

-- 241106 CR1023
CALL CORE.SP_CRM_PULL_MAG_VUL();
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(''MAG VUL'');
CALL CORE.SP_CRM_IDENTIFY_RAW_ASSETS(:SNAPSHOT_ID);
CALL CORE.SP_CRM_IDENTIFY_RAW_ASSETS_TEST(:SNAPSHOT_ID);
CALL CORE.SP_CRM_LINK_METADATA_V2(:SNAPSHOT_ID);
CALL CORE.SP_CRM_PREP_RAW_TENABLE_VUL_V3(:SNAPSHOT_ID); -- 241023 CR1012 V3
CALL CORE.SP_CRM_LOAD_ASSET_V2(:SNAPSHOT_ID);
CALL CORE.SP_CRM_LOAD_VULPLUGINS_MASTER(:SNAPSHOT_ID);

-- 241106 CR1023
CALL CORE.SP_CRM_PULL_MAG_VUL_MITIGATED();
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(''MAG VUL MITIGATED'');
CALL CORE.SP_CRM_IDENTIFY_RAW_ASSETS(:SNAPSHOT_ID);
CALL CORE.SP_CRM_IDENTIFY_RAW_ASSETS_TEST(:SNAPSHOT_ID);
CALL CORE.SP_CRM_LINK_METADATA_V2(:SNAPSHOT_ID);
CALL CORE.SP_CRM_PREP_RAW_TENABLE_VUL_V3(:SNAPSHOT_ID); -- 241023 CR1012 V3
CALL CORE.SP_CRM_LOAD_ASSET_V2(:SNAPSHOT_ID);
CALL CORE.SP_CRM_UPDATE_VULPLUGINS_MASTER(:SNAPSHOT_ID);

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';