CREATE OR REPLACE PROCEDURE "SP_CRM_LOAD_ASSETINTERFACE"("P_SNAPSHOT_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Process TEMP_HWAM data into ASSETINTERFACE_* tables.TEMP_HWAM.DW_ASSET_ID must already be set'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_LOAD_ASSETINTERFACE'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean := 0;
True boolean := 1;
DATACATEGORY varchar;
RECORD_COUNT NUMBER;

-- 230929 added: and r.DATECOMPLETED IS NULL

BEGIN
select DATACATEGORY into :DATACATEGORY FROM CORE.SNAPSHOT_IDS where SNAPSHOT_ID = :P_SNAPSHOT_ID;
Appl := :Appl || ''('' || DATACATEGORY || '')''; -- This helps to clarify which VUL we are processing
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

BEGIN TRANSACTION;
--
-- 240610 CR903 Reworked SELECT to obtain unique TEMP_HWAM
--
MERGE INTO CORE.ASSETINTERFACE_FQDN as target
USING 
(SELECT a.DW_ASSET_ID
	,GET(th.FQDN,0)::varchar as FQDN -- 240610 CR903 single array value is ok
    ,th.NORMALIZED_FQDN 
    ,a.LAST_CONFIRMED_TIME
FROM (SELECT r.DW_ASSET_ID,r.NORMALIZED_FQDN,MAX(TEMP_HWAM_ID) as MAX_TEMP_HWAM_ID
    FROM CORE.TEMP_HWAM r
    WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and NULLIF(r.NORMALIZED_FQDN,'''') IS NOT NULL and r.DATECOMPLETED IS NULL
    GROUP BY r.DW_ASSET_ID,r.NORMALIZED_FQDN) m
    JOIN CORE.TEMP_HWAM th on th.TEMP_HWAM_ID = m.MAX_TEMP_HWAM_ID
    JOIN CORE.ASSET a on a.DW_ASSET_ID = th.DW_ASSET_ID
) as src 

ON (src.DW_ASSET_ID = target.DW_ASSET_ID and src.NORMALIZED_FQDN = target.NORMALIZED_FQDN) -- 240612 CR903

WHEN MATCHED THEN UPDATE SET 
    target.LAST_CONFIRMED_TIME = src.LAST_CONFIRMED_TIME

WHEN NOT MATCHED THEN INSERT (
	DATACATEGORY
	,DATEUSEDBYMATCHING
	,DW_ASSET_ID
	,INSERT_DATE
	,FQDN
    ,NORMALIZED_FQDN -- 240610 CR903
	,LAST_CONFIRMED_TIME
)
VALUES (
	:DATACATEGORY -- DATACATEGORY
	,null -- DATEUSEDBYMATCHING
	,src.DW_ASSET_ID
	,CURRENT_TIMESTAMP() -- INSERT_DATE
	,src.FQDN
    ,src.NORMALIZED_FQDN -- 240610 CR903
	,src.LAST_CONFIRMED_TIME
);

-- 240710 CR928 Msg := ''Merge ASSETINTERFACE_FQDN complete'';
-- 240710 CR928 CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;

BEGIN TRANSACTION;
-----------
--
-- 240611 CR903 Reworked SELECT to obtain unique TEMP_HWAM
--
MERGE INTO CORE.ASSETINTERFACE_HOSTNAME as target
USING 
(SELECT a.DW_ASSET_ID
	,coalesce(GET(th.HOSTNAME,0)::varchar,m.NORMALIZED_HOSTNAME) as HOSTNAME -- 240617 CR903 Use Normalized_Hostname if Hostame is null
    ,m.NORMALIZED_HOSTNAME 
    ,a.LAST_CONFIRMED_TIME
FROM (SELECT r.DW_ASSET_ID,GET(r.NORMALIZED_HOSTNAME,0) as NORMALIZED_HOSTNAME,MAX(TEMP_HWAM_ID) as MAX_TEMP_HWAM_ID
    FROM CORE.TEMP_HWAM r
    WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and NULLIF(GET(r.NORMALIZED_HOSTNAME,0),'''') IS NOT NULL and r.DATECOMPLETED IS NULL
    GROUP BY r.DW_ASSET_ID,GET(r.NORMALIZED_HOSTNAME,0)) m
    JOIN CORE.TEMP_HWAM th on th.TEMP_HWAM_ID = m.MAX_TEMP_HWAM_ID
    JOIN CORE.ASSET a on a.DW_ASSET_ID = th.DW_ASSET_ID
) as src 

ON (src.DW_ASSET_ID = target.DW_ASSET_ID and src.NORMALIZED_HOSTNAME = target.NORMALIZED_HOSTNAME)

WHEN MATCHED THEN UPDATE SET 
    target.LAST_CONFIRMED_TIME = src.LAST_CONFIRMED_TIME

WHEN NOT MATCHED THEN INSERT (
	DATACATEGORY
	,DATEUSEDBYMATCHING
	,DW_ASSET_ID
	,INSERT_DATE
	,HOSTNAME
    ,NORMALIZED_HOSTNAME
	,LAST_CONFIRMED_TIME
)
VALUES (
	:DATACATEGORY -- DATACATEGORY
	,null -- DATEUSEDBYMATCHING
	,src.DW_ASSET_ID
	,CURRENT_TIMESTAMP() -- INSERT_DATE
	,src.HOSTNAME
    ,src.NORMALIZED_HOSTNAME
	,src.LAST_CONFIRMED_TIME
);

-- 240710 CR928 Msg := ''Merge ASSETINTERFACE_HOSTNAME complete'';
-- 240710 CR928 CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;

BEGIN TRANSACTION;

MERGE INTO CORE.ASSETINTERFACE_IPV4 as target
USING (SELECT
	a.DW_ASSET_ID
	,f.value::string as IPV4 -- 230718
	,MAX(a.LAST_CONFIRMED_TIME) as LAST_CONFIRMED_TIME
FROM CORE.TEMP_HWAM r
JOIN CORE.ASSET a on a.DW_ASSET_ID = r.DW_ASSET_ID
JOIN TABLE(flatten(IPV4,outer=>true)) as f
WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and NULLIF(f.value,'''') IS NOT NULL and r.DATECOMPLETED IS NULL
GROUP BY a.DW_ASSET_ID, f.value::string -- 230718
) as src 

ON (src.DW_ASSET_ID = target.DW_ASSET_ID and src.IPV4 = target.IPV4)

WHEN MATCHED THEN UPDATE SET 
    target.LAST_CONFIRMED_TIME = src.LAST_CONFIRMED_TIME

WHEN NOT MATCHED THEN INSERT (
	DATACATEGORY
	,DATEUSEDBYMATCHING
	,DW_ASSET_ID
	,INSERT_DATE
	,IPV4
	,LAST_CONFIRMED_TIME
)
VALUES (
	:DATACATEGORY -- DATACATEGORY
	,null -- DATEUSEDBYMATCHING
	,src.DW_ASSET_ID
	,CURRENT_TIMESTAMP() -- INSERT_DATE
	,src.IPV4
	,src.LAST_CONFIRMED_TIME
);

-- 240710 CR928 Msg := ''Merge ASSETINTERFACE_IPV4 complete'';
-- 240710 CR928 CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;

BEGIN TRANSACTION;

MERGE INTO CORE.ASSETINTERFACE_IPV6 as target
USING (SELECT
	a.DW_ASSET_ID
	,f.value::string as IPV6 -- 230718
	,MAX(a.LAST_CONFIRMED_TIME) as LAST_CONFIRMED_TIME
FROM CORE.TEMP_HWAM r
JOIN CORE.ASSET a on a.DW_ASSET_ID = r.DW_ASSET_ID
JOIN TABLE(flatten(IPV6,outer=>true)) as f
WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and NULLIF(f.value,'''') IS NOT NULL and r.DATECOMPLETED IS NULL
GROUP BY a.DW_ASSET_ID, f.value::string -- 230718
) as src 

ON (src.DW_ASSET_ID = target.DW_ASSET_ID and src.IPV6 = target.IPV6)

WHEN MATCHED THEN UPDATE SET 
    target.LAST_CONFIRMED_TIME = src.LAST_CONFIRMED_TIME

WHEN NOT MATCHED THEN INSERT (
	DATACATEGORY
	,DATEUSEDBYMATCHING
	,DW_ASSET_ID
	,INSERT_DATE
	,IPV6
	,LAST_CONFIRMED_TIME
)
VALUES (
	:DATACATEGORY -- DATACATEGORY
	,null -- DATEUSEDBYMATCHING
	,src.DW_ASSET_ID
	,CURRENT_TIMESTAMP() -- INSERT_DATE
	,src.IPV6
	,src.LAST_CONFIRMED_TIME
);

-- 240710 CR928 Msg := ''Merge ASSETINTERFACE_IPV6 complete'';
-- 240710 CR928 CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;

BEGIN TRANSACTION; -- 230728

MERGE INTO CORE.ASSETINTERFACE_MACADDRESS as target
USING (SELECT
    a.DW_ASSET_ID
    ,f.value::string as MACADDRESS
    ,MAX(a.LAST_CONFIRMED_TIME) as LAST_CONFIRMED_TIME
FROM CORE.TEMP_HWAM r
JOIN CORE.ASSET a on a.DW_ASSET_ID = r.DW_ASSET_ID
JOIN TABLE(flatten(MACADDRESS,outer=>true)) as f
WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and NULLIF(f.value,'''') IS NOT NULL and r.DATECOMPLETED IS NULL
GROUP BY a.DW_ASSET_ID, f.value::string
) as src 

ON (src.DW_ASSET_ID = target.DW_ASSET_ID and src.MACADDRESS = target.MACADDRESS)

WHEN MATCHED THEN UPDATE SET 
    target.LAST_CONFIRMED_TIME = src.LAST_CONFIRMED_TIME

WHEN NOT MATCHED THEN INSERT (
	DATACATEGORY
	,DATEUSEDBYMATCHING
	,DW_ASSET_ID
	,INSERT_DATE
	,MACADDRESS
	,LAST_CONFIRMED_TIME
)
VALUES (
	:DATACATEGORY -- DATACATEGORY
	,null -- DATEUSEDBYMATCHING
	,src.DW_ASSET_ID
	,CURRENT_TIMESTAMP() -- INSERT_DATE
	,src.MACADDRESS
	,src.LAST_CONFIRMED_TIME
);

-- 240710 CR928 Msg := ''Merge ASSETINTERFACE_MACADDRESS complete'';
-- 240710 CR928 CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;

BEGIN TRANSACTION;
--
-- 240606 CR903 Reworked SELECT to obtain unique TEMP_HWAM
--
MERGE INTO CORE.ASSETINTERFACE_NETBIOSNAME as target
USING 
(SELECT a.DW_ASSET_ID
	,GET(th.NETBIOSNAME,0)::varchar as NETBIOSNAME -- 240606 CR903 single array value is ok
    ,th.NORMALIZED_NETBIOSNAME 
    ,a.LAST_CONFIRMED_TIME
FROM (SELECT r.DW_ASSET_ID,r.NORMALIZED_NETBIOSNAME,MAX(TEMP_HWAM_ID) as MAX_TEMP_HWAM_ID
    FROM CORE.TEMP_HWAM r
    WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and NULLIF(r.NORMALIZED_NETBIOSNAME,'''') IS NOT NULL and r.DATECOMPLETED IS NULL
    GROUP BY r.DW_ASSET_ID,r.NORMALIZED_NETBIOSNAME) m
    JOIN CORE.TEMP_HWAM th on th.TEMP_HWAM_ID = m.MAX_TEMP_HWAM_ID
    JOIN CORE.ASSET a on a.DW_ASSET_ID = th.DW_ASSET_ID
) as src 

ON (src.DW_ASSET_ID = target.DW_ASSET_ID and src.NORMALIZED_NETBIOSNAME = target.NORMALIZED_NETBIOSNAME)

WHEN MATCHED THEN UPDATE SET 
    target.LAST_CONFIRMED_TIME = src.LAST_CONFIRMED_TIME

WHEN NOT MATCHED THEN INSERT (
	DATACATEGORY
	,DATEUSEDBYMATCHING
	,DW_ASSET_ID
	,INSERT_DATE
	,NETBIOSNAME
    ,NORMALIZED_NETBIOSNAME -- 240606 CR903
	,LAST_CONFIRMED_TIME
)
VALUES (
	:DATACATEGORY -- DATACATEGORY
	,null -- DATEUSEDBYMATCHING
	,src.DW_ASSET_ID
	,CURRENT_TIMESTAMP() -- INSERT_DATE
	,src.NETBIOSNAME
    ,src.NORMALIZED_NETBIOSNAME -- 240606 CR903
	,src.LAST_CONFIRMED_TIME
);

-- 240710 CR928 Msg := ''Merge ASSETINTERFACE_NETBIOSNAME complete'';
-- 240710 CR928 CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;


UPDATE TEMP_HWAM upd
set DATECOMPLETED = CURRENT_TIMESTAMP()
FROM CORE.TEMP_HWAM r
JOIN CORE.ASSET a on a.DW_ASSET_ID = r.DW_ASSET_ID
WHERE r.SNAPSHOT_ID = :P_SNAPSHOT_ID and r.TEMP_HWAM_ID = upd.TEMP_HWAM_ID;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';