CREATE OR REPLACE PROCEDURE "SP_CRM_WRITE_ASSETINTERFACECOALESCED"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Coalesece AssetInterface records into single records per asset'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_WRITE_ASSETINTERFACECOALESCED'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
RECORD_COUNT number;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

TRUNCATE TABLE CORE.AssetInterfaceCoalesced;

INSERT INTO CORE.AssetInterfaceCoalesced
           (DW_ASSET_ID
           ,FQDN
           ,HOSTNAME
           ,NETBIOSNAME
           ,IPv4
           ,IPv6
           ,MACADDRESS,
		   INSERT_DATE)
SELECT A1.DW_ASSET_ID
      ,F.FQDN
      ,H.HOSTNAME
      ,N.NETBIOSNAME
      ,I4.IPV4
      ,I6.IPV6
      ,M.MACADDRESS
      ,CURRENT_TIMESTAMP() -- INSERT_DATE
FROM CORE.ASSET A1 
LEFT OUTER JOIN (select DW_ASSET_ID, listagg(DISTINCT FQDN, '', '') WITHIN GROUP (ORDER BY FQDN DESC) as FQDN FROM CORE.ASSETINTERFACE_FQDN GROUP BY DW_ASSET_ID) F ON F.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN (select DW_ASSET_ID, listagg(DISTINCT HOSTNAME, '', '') WITHIN GROUP (ORDER BY HOSTNAME DESC) as HOSTNAME FROM CORE.ASSETINTERFACE_HOSTNAME GROUP BY DW_ASSET_ID) H ON H.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN (select DW_ASSET_ID, listagg(DISTINCT NETBIOSNAME, '', '') WITHIN GROUP (ORDER BY NETBIOSNAME DESC) as NETBIOSNAME FROM CORE.ASSETINTERFACE_NETBIOSNAME GROUP BY DW_ASSET_ID) N ON N.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN (select DW_ASSET_ID, listagg(DISTINCT IPV4, '', '') WITHIN GROUP (ORDER BY IPV4 DESC) as IPV4 FROM CORE.ASSETINTERFACE_IPV4 GROUP BY DW_ASSET_ID) I4 ON I4.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN (select DW_ASSET_ID, listagg(DISTINCT IPV6, '', '') WITHIN GROUP (ORDER BY IPV6 DESC) as IPV6 FROM CORE.ASSETINTERFACE_IPV6 GROUP BY DW_ASSET_ID) I6 ON I6.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN (select DW_ASSET_ID, listagg(DISTINCT MACADDRESS, '', '') WITHIN GROUP (ORDER BY MACADDRESS DESC) as MACADDRESS FROM CORE.ASSETINTERFACE_MACADDRESS GROUP BY DW_ASSET_ID) M ON M.DW_ASSET_ID = A1.DW_ASSET_ID
WHERE A1.IS_APPLICABLE = 1
;

/**************************
THIS CODE WORKED PRIOR TO 7/7/23. IT USED TO RUN IN ABOUT 1 MINUTE. AS OF 7/7/23 IT RUNS FOR MORE THAN 18 MINUTES BEFORE IT NEEDS TO BE CANCELED
Bill Lennon noted that on July 5th 6th - Snowflake released GROUP BY: New ALL Keyword
The GROUP BY clause now supports the ALL keyword, which specifies that all expressions in the SELECT list that do not use aggregate functions should be used for grouping.

IT IS UNKNOWN IF THIS RELEASE CAUSED THE CODE TO STOP FUNCTIONING. 

SELECT A1.DW_ASSET_ID
      ,listagg(DISTINCT F.fqdn, '', '')        WITHIN GROUP (ORDER BY F.fqdn DESC) as FQDN
      ,listagg(DISTINCT H.hostname, '', '')    WITHIN GROUP (ORDER BY H.hostname DESC) as HOSTNAME
      ,listagg(DISTINCT N.netbiosname, '', '') WITHIN GROUP (ORDER BY N.netbiosname DESC) as NETBIOSNAME
      ,listagg(DISTINCT I4.ipv4, '', '')       WITHIN GROUP (ORDER BY I4.ipv4 DESC) AS IPV4
      ,listagg(DISTINCT I6.ipv6, '', '')       WITHIN GROUP (ORDER BY I6.ipv6 DESC) AS IPV6
      ,listagg(DISTINCT M.MACADDRESS, '', '')  WITHIN GROUP (ORDER BY M.MACADDRESS DESC) AS MACADDRESS
      ,CURRENT_TIMESTAMP() -- INSERT_DATE
FROM CORE.ASSET A1 
LEFT OUTER JOIN CORE.ASSETINTERFACE_FQDN F        ON F.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN CORE.ASSETINTERFACE_HOSTNAME H    ON H.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN CORE.ASSETINTERFACE_NETBIOSNAME N ON N.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN CORE.ASSETINTERFACE_IPV4 I4       ON I4.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN CORE.ASSETINTERFACE_IPV6 I6       ON I6.DW_ASSET_ID = A1.DW_ASSET_ID
LEFT OUTER JOIN CORE.ASSETINTERFACE_MACADDRESS M  ON M.DW_ASSET_ID = A1.DW_ASSET_ID
WHERE A1.IS_APPLICABLE = 1
GROUP BY A1.DW_ASSET_ID
;
********************/

-- 230918 RECORD_COUNT := SQLROWCOUNT;
-- 230918 Msg := ''AssetInterfaceCoalesced rows written='' || cast(RECORD_COUNT as varchar);
-- 230918 CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);

return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';