CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_CCIC_VUL_V2"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull CCIC TENABLE data into BUS_CYBER_RISK_MANAGEMENT RAW_TENABLE_VUL table'
EXECUTE AS OWNER
AS '
--
-- 
--
declare
Appl varchar := ''SP_CRM_PULL_CCIC_VUL_V2'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
Datacategory varchar := ''CCIC VUL'';
PreviousPullDatetime TIMESTAMP_LTZ(9);
SNAPSHOT_ID number;
RECORD_COUNT number;
MIN_DATE TIMESTAMP_LTZ(9);
MAX_DATE TIMESTAMP_LTZ(9);

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

CALL CORE.SP_CRM_GENERATE_SNAPSHOT_ID(:Datacategory);
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(:Datacategory);

PreviousPullDatetime := (select PARMDATE FROM CORE.CONFIG where PARMNAME = :Datacategory);

Msg := ''Previous pull of '' || :Datacategory || ''='' || :PreviousPullDatetime;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

BEGIN TRANSACTION;

insert into CORE.RAW_TENABLE_VUL(
ACCEPT_RISK_RULE_COMMENT
,ACCEPTRISK
,ACRSCORE
,APPLICABILITYCODE -- 240710 CR928
,ASSET_ID_TATTOO
,ASSETEXPOSURESCORE
,AWS_ACCOUNTID
,AWS_INSTANCE_ID
,BASESCORE
,BID
,CHECKTYPE
,COMPLIANCE_ACTUAL_VALUE
,COMPLIANCE_CHECK_NAME
,COMPLIANCE_ERROR
,COMPLIANCE_RESULT
,CPE
,CREDENTIALED_SCAN
,CUSTOM_SEVERITY
,CVE
,CVSSV2BASESCORE
,CVSSV3BASESCORE
,CVSSV3TEMPORALSCORE
,CVSSV3VECTOR
,CVSSVECTOR
,DATA_ERROR_ARRAY -- 240710 CR928
,DATA_WARNING_ARRAY -- 240710 CR928
,DATACENTER_ID
,DESCRIPTION
,DNSNAME
,EXPLOIT_AVAILABLE
,EXPLOITEASE
,EXPLOITFRAMEWORKS
,FAMILY_ID
,FAMILY_NAME
,FAMILY_TYPE
,FIRST_SEEN
,FISMASEVERITY
,HAS_BEEN_MITIGATED
,HOSTNAME
,HOSTUNIQUENESS
,HOSTUUID
,INSERT_DATE
,IP
,IPS
,KEYDRIVERS
,LAST_SEEN
,MACADDRESS
,MITIGATIONSTATUS
,NETBIOSNAME
,NUMERIC_SEVERITY -- 240710 CR928
,OPERATING_SYSTEM
,PATCHPUB_DATE
,PLUGIN_ID
,PLUGIN_INFO
,PLUGIN_MOD_DATE
,PLUGIN_NAME
,PLUGIN_PUB_DATE
,PLUGINTEXT
,PORT
,PRIMARY_FISMA_ID_DERIVED
,PRIMARY_FISMA_ID_TATTOO
,PROTOCOL
,RECASTRISK
,RECASTRISKRULECOMMENT
,REPORTDATE
,REPOSITORY_DATAFORMAT
,REPOSITORY_DESCRIPTION
,REPOSITORY_ID
,REPOSITORY_NAME
,RISKFACTOR
,ROWDISPOSITION
,SCAN_POLICY_NAME
,SCAN_POLICY_UID
,SCAN_START_DATE
,SEEALSO
,SEVERITY_DESCRIPTION
,SEVERITY_ID
,SEVERITY_NAME
,SNAPSHOT_ID
,SOLUTION
,SOURCE_TOOL
,STATE
,STIGSEVERITY
,SYNOPSIS
,TEMPORAL_SCORE
,TENABLEUUID
,UNIQUENESS
,VERSION
,VPR_SCORE
,VPRCONTEXT
,VULN_PUB_DATE
,XREF
,ASSET_ID_TAG -- 240827 CR-TBD
,FISMA_ID_TAG -- 240827 CR-TBD
) 
SELECT
v.ACCEPT_RISK_RULE_COMMENT
,v.ACCEPTRISK
,v.ACRSCORE
,CORE.FN_CRM_GET_INDICATOR_INITIAL() as APPLICABILITYCODE -- 240710 CR928
,v.ASSET_ID_TATTOO
,v.ASSETEXPOSURESCORE
,null as AWS_ACCOUNTID
,NULL as AWS_INSTANCE_ID
,coalesce(NULLIF(v.BASESCORE,''''),''0'')::NUMBER(38,1) as BASESCORE
,v.BID
,v.CHECKTYPE
,NULL as COMPLIANCE_ACTUAL_VALUE
,NULL as COMPLIANCE_CHECK_NAME
,NULL as COMPLIANCE_ERROR
,NULL as COMPLIANCE_RESULT
,v.CPE
,v.CREDENTIALED_SCAN
,NULL as CUSTOM_SEVERITY
,v.CVE -- 240108 was STRTOK_TO_ARRAY
,coalesce(NULLIF(v.BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV2BASESCORE -- 230419 Naseem found that BASESCORE matches legacy CVSSv2
,coalesce(NULLIF(v.CVSSV3BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV3BASESCORE
,v.CVSSV3TEMPORALSCORE
,v.CVSSV3VECTOR
,v.CVSSVECTOR
,ARRAY_CONSTRUCT() as DATA_ERROR_ARRAY -- 240710 CR928
,ARRAY_CONSTRUCT() as DATA_WARNING_ARRAY -- 240710 CR928
,v.REPOSITORY_DESCRIPTION as DATACENTER_ID
,v.DESCRIPTION
,NULLIF(v.DNSNAME,'''') as DNSNAME -- 240405 1939 added NULLIF
,v.EXPLOIT_AVAILABLE
,v.EXPLOITEASE
,v.EXPLOITFRAMEWORKS
,v.FAMILY_ID
,v.FAMILY_NAME
,v.FAMILY_TYPE
,v.FIRST_SEEN
,NULL as FISMASEVERITY
,v.HAS_BEEN_MITIGATED::boolean as HAS_BEEN_MITIGATED
,NULL as HOSTNAME -- 240405 1939 HOSTNAME is not in view
,v.HOSTUNIQUENESS
,NULL as HOSTUUID
,CURRENT_TIMESTAMP() as INSERT_DATE
,v.IP
,v.IPS
,v.KEYDRIVERS
,v.LAST_SEEN
,NULLIF(v.MACADDRESS,'''') as MACADDRESS -- 240506 corrected spelling 240405 1939 added NULLIF
,case HAS_BEEN_MITIGATED
    when 1 then CORE.FN_CRM_GET_MITIGATIONSTATUS_REOPENED()
    Else CORE.FN_CRM_GET_MITIGATIONSTATUS_OPEN()
End as MITIGATIONSTATUS -- 240710 CR928
,NULLIF(v.NETBIOSNAME,'''') as NETBIOSNAME -- 240405 1939 added NULLIF
,0 as NUMERIC_SEVERITY -- 240710 CR928
,v.OPERATING_SYSTEM
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PATCHPUB_DATE) as PATCHPUB_DATE
,v.PLUGIN_ID
,v.PLUGIN_INFO
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PLUGIN_MOD_DATE) as PLUGIN_MOD_DATE
,v.PLUGIN_NAME
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PLUGIN_PUB_DATE) as PLUGIN_PUB_DATE
,v.PLUGINTEXT
,v.PORT
,NULL as PRIMARY_FISMA_ID_DERIVED
,v.PRIMARY_FISMA_ID as PRIMARY_FISMA_ID_TATTOO
,v.PROTOCOL
,v.RECASTRISK
,NULL as RECASTRISKRULECOMMENT
,v.REPORTDATE -- 240108 is now TIMESTAMP_NTZ(9), was v.REPORTDATE::datetime
,v.REPOSITORY_DATAFORMAT
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,v.REPOSITORY_NAME
,v.RISKFACTOR
,CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() as ROWDISPOSITION -- 240710 CR928
,v.SCAN_POLICY_NAME
,v.SCAN_POLICY_UID
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.SCAN_START_DATE) as SCAN_START_DATE
,v.SEEALSO
,v.SEVERITY_DESCRIPTION
,v.SEVERITY_ID
,v.SEVERITY_NAME
,:SNAPSHOT_ID
,v.SOLUTION
,''Tenable'' as SOURCE_TOOL
,NULL as STATE
,v.STIGSEVERITY
,v.SYNOPSIS
,v.TEMPORAL_SCORE
,v.UUID as TENABLEUUID
,v.UNIQUENESS
,v.VERSION
,v.VPR_SCORE
,v.VPRCONTEXT -- 240108 is now array, was v.VPRCONTEXT::varchar
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.VULN_PUB_DATE) as VULN_PUB_DATE
,v.XREF
,v.ASSET_ID_TATTOO as ASSET_ID_TAG -- 240827 CR-TBD
,v.PRIMARY_FISMA_ID as FISMA_ID_TAG -- 240827 CR-TBD
--
-- We do a UNION ALL on SEC_VW_CCIC_TENABLE_CUMULATIVE_VULNS and SEC_VW_CCIC_TENABLE_CUMULATIVE_INFO
-- because we need the metadata plugins
--
FROM (
SELECT
ACCEPT_RISK_RULE_COMMENT
,ACCEPTRISK
,ACRSCORE
,ASSET_ID_TATTOO
,ASSETEXPOSURESCORE
,BASESCORE
,BID
,CHECKTYPE
,CPE
,CREDENTIALED_SCAN
,CVE
,CVSSV3BASESCORE
,CVSSV3TEMPORALSCORE
,CVSSV3VECTOR
,CVSSVECTOR
,DESCRIPTION
,DNSNAME
,EXPLOIT_AVAILABLE
,EXPLOITEASE
,EXPLOITFRAMEWORKS
,FAMILY_ID
,FAMILY_NAME
,FAMILY_TYPE
,FIRST_SEEN
,HAS_BEEN_MITIGATED
,HOSTUNIQUENESS
,IP
,IPS
,KEYDRIVERS
,LAST_SEEN
,MACADDRESS
,NETBIOSNAME
,OPERATING_SYSTEM
,PATCHPUB_DATE
,PLUGIN_ID
,PLUGIN_INFO
,PLUGIN_MOD_DATE
,PLUGIN_NAME
,PLUGIN_PUB_DATE
,PLUGINTEXT
,PORT
,PRIMARY_FISMA_ID
,PROTOCOL
,RECASTRISK
,REPORTDATE
,REPOSITORY_DATAFORMAT
,REPOSITORY_DESCRIPTION
,REPOSITORY_ID
,REPOSITORY_NAME
,RISKFACTOR
,SCAN_POLICY_NAME
,SCAN_POLICY_UID
,SCAN_START_DATE
,SEEALSO
,SEVERITY_DESCRIPTION
,SEVERITY_ID
,SEVERITY_NAME
,SOLUTION
,STIGSEVERITY
,SYNOPSIS
,TEMPORAL_SCORE
,UUID
,UNIQUENESS
,VERSION
,VPR_SCORE
,VPRCONTEXT
,VULN_PUB_DATE
,XREF
FROM APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_CUMULATIVE_VULNS
WHERE REPORTDATE > :PreviousPullDatetime

UNION ALL

SELECT
ACCEPT_RISK_RULE_COMMENT
,ACCEPTRISK
,ACRSCORE
,ASSET_ID_TATTOO
,ASSETEXPOSURESCORE
,BASESCORE
,BID
,CHECKTYPE
,CPE
,CREDENTIALED_SCAN
,CVE
,CVSSV3BASESCORE
,CVSSV3TEMPORALSCORE
,CVSSV3VECTOR
,CVSSVECTOR
,DESCRIPTION
,DNSNAME
,EXPLOIT_AVAILABLE
,EXPLOITEASE
,EXPLOITFRAMEWORKS
,FAMILY_ID
,FAMILY_NAME
,FAMILY_TYPE
,FIRST_SEEN
,HAS_BEEN_MITIGATED
,HOSTUNIQUENESS
,IP
,IPS
,KEYDRIVERS
,LAST_SEEN
,MACADDRESS
,NETBIOSNAME
,OPERATING_SYSTEM
,PATCHPUB_DATE
,PLUGIN_ID
,PLUGIN_INFO
,PLUGIN_MOD_DATE
,PLUGIN_NAME
,PLUGIN_PUB_DATE
,PLUGINTEXT
,PORT
,PRIMARY_FISMA_ID
,PROTOCOL
,RECASTRISK
,REPORTDATE
,REPOSITORY_DATAFORMAT
,REPOSITORY_DESCRIPTION
,REPOSITORY_ID
,REPOSITORY_NAME
,RISKFACTOR
,SCAN_POLICY_NAME
,SCAN_POLICY_UID
,SCAN_START_DATE
,SEEALSO
,SEVERITY_DESCRIPTION
,SEVERITY_ID
,SEVERITY_NAME
,SOLUTION
,STIGSEVERITY
,SYNOPSIS
,TEMPORAL_SCORE
,UUID
,UNIQUENESS
,VERSION
,VPR_SCORE
,VPRCONTEXT
,VULN_PUB_DATE
,XREF
FROM APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_CUMULATIVE_INFO
WHERE REPORTDATE > :PreviousPullDatetime) v;

COMMIT;

RECORD_COUNT := SQLROWCOUNT;

IF (:RECORD_COUNT = 0) THEN
	BEGIN
	Msg := ''WARNING: There is no VUL data for this snapshot'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
ELSE
    BEGIN
    Msg := :Datacategory || '' inserted into RAW_TENABLE_VUL='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF;

MIN_DATE := (select MIN(REPORTDATE) FROM CORE.RAW_TENABLE_VUL WHERE SNAPSHOT_ID = :SNAPSHOT_ID);
MAX_DATE := (select MAX(REPORTDATE) FROM CORE.RAW_TENABLE_VUL WHERE SNAPSHOT_ID = :SNAPSHOT_ID);

BEGIN TRANSACTION;

If (RECORD_COUNT > 0) THEN
    BEGIN
    update CORE.CONFIG
    set PARMDATE = :MAX_DATE
    where PARMNAME = :Datacategory and :MAX_DATE IS NOT NULL;
    END;
End if;

UPDATE CORE.SNAPSHOT_IDS
set MIN_DATE = :MIN_DATE
,MAX_DATE = :MAX_DATE
,RECORD_COUNT = coalesce(:RECORD_COUNT,0)
 where SNAPSHOT_ID = :SNAPSHOT_ID;

COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';