CREATE OR REPLACE PROCEDURE "SP_CRM_UPDATE_REPORT_IDS"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Update the REPORT_IDS table with enterprise level daily counts. e.g. Systems,Assets,Vulnerabilities'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_UPDATE_REPORT_IDS'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean := 0;
True boolean := 1;
CURRENT_REPORT_ID NUMBER := (SELECT MAX(REPORT_ID) FROM CORE.REPORT_IDS);
RECORD_COUNT NUMBER;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

-- 231228 added to help shed light on asset count changes from day to day
select count(1) into :RECORD_COUNT FROM CORE.ASSET;
Msg :=  ''Unfiltered count of Assets='' || cast(RECORD_COUNT as varchar);
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 


UPDATE CORE.REPORT_IDS -- 231120
SET ASSETS = (select count(1) from CORE.VW_ASSETS)
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240103
SET ASSETS_AWS = (select count(1) from CORE.VW_ASSETS where DATACENTER_ID = ''56FFF52E-175B-4E48-9B38-669C8BC74899'') -- 241011 EBF; Acronym was renamed in CFACTS
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240103
SET ASSETS_AWS_GOVCLOUD = (select count(1) from CORE.VW_ASSETS where DATACENTER_ID = ''5d8a99a8db672340f99cfd721f96190d'') -- 241011 EBF; Acronym was renamed in CFACTS
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231207
SET ASSETS_CREATED_TODAY = (select count(1) from CORE.ASSET WHERE INSERT_DATE::DATE = CURRENT_DATE()) -- 231228 Use ASSET table not VW_ASSETS
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231207
SET ASSETS_DELETED_TODAY = (select count(1) from CORE.ASSET WHERE DATEDELETED::DATE = CURRENT_DATE()) -- Use ASSET table not VW_ASSETS
WHERE REPORT_ID = :CURRENT_REPORT_ID;

select count(1) into :RECORD_COUNT
   FROM (select datacenter_id,asset_id_tattoo 
    from asset where asset_id_tattoo is not null
    group by datacenter_id,asset_id_tattoo having count(1) > 1);

UPDATE CORE.REPORT_IDS 
SET DUPLICATE_DATACENTER_TATTOO_PAIR = :RECORD_COUNT
WHERE REPORT_ID = :CURRENT_REPORT_ID;

select count(1) into :RECORD_COUNT from CORE.TEMP_HWAM where DW_ASSET_ID IS NULL;

UPDATE CORE.REPORT_IDS 
SET TEMP_HWAM_UNASSIGNED_DW_ASSET_ID = :RECORD_COUNT
WHERE REPORT_ID = :CURRENT_REPORT_ID;

select count(1) into :RECORD_COUNT FROM CORE.ASSET where Is_Applicable=1 and DEVICETYPE=''Unknown'' ;

UPDATE CORE.REPORT_IDS 
SET ASSETS_UNKNOWN_DEVICETYPE = :RECORD_COUNT
WHERE REPORT_ID = :CURRENT_REPORT_ID;

select count(1) into :RECORD_COUNT 
FROM CORE.ASSET a 
-- 241213 join DEVICETYPES dt on dt.devicetype = a.devicetype
where a.IS_APPLICABLE = 1 
and a.IS_ENDPOINT = 1 -- 241213
-- 241213 and UPPER(dt.DEVICEROLE) = ''ENDPOINT'' 
and a.LASTSEEN_VUL IS NULL;

UPDATE CORE.REPORT_IDS 
SET ASSETS_NEVER_SCANNED = :RECORD_COUNT
WHERE REPORT_ID = :CURRENT_REPORT_ID;

select count(1) into :RECORD_COUNT 
FROM CORE.ASSET a 
-- 241213 join DEVICETYPES dt on dt.devicetype = a.devicetype
where a.IS_APPLICABLE = 1 
and a.IS_ENDPOINT = 1 -- 241213
-- 241213 and UPPER(dt.DEVICEROLE) = ''ENDPOINT'' 
and a.LASTSEEN_VUL IS NOT NULL and DATEDIFF(day, a.LASTSEEN_VUL, CURRENT_DATE()) > 3;

UPDATE CORE.REPORT_IDS 
SET ASSETS_NOT_SCANNED_LAST3DAYS = :RECORD_COUNT
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_CREATED_TODAY = (select count(1) from CORE.VULPLUGINS_MASTER WHERE INSERT_DATE::DATE = CURRENT_DATE())
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_DELETED_TODAY = (select count(1) from CORE.VULPLUGINS_MASTER WHERE DATEDELETED::DATE = CURRENT_DATE())
WHERE REPORT_ID = :CURRENT_REPORT_ID;

-- Vulnerabilities indirectly considered because Asset record was deleted
UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_INACTIVE_ASSET_TODAY = (select count(1) 
    from CORE.ASSET a
    join CORE.VULPLUGINS_MASTER vm on vm.dw_asset_id = a.dw_asset_id
    where a.datedeleted::date = current_date() and a.is_applicable = 0 and vm.deletionreason IS NULL)
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_FIXED_TODAY = (select count(1) from CORE.VULPLUGINS_MASTER WHERE UPPER(MITIGATIONSTATUS) = ''FIXED'' and DATEMITIGATED::DATE = CURRENT_DATE())
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_OPEN = (select count(1) from CORE.VULPLUGINS_MASTER WHERE UPPER(MITIGATIONSTATUS) = ''OPEN'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_REOPENED = (select count(1) from CORE.VULPLUGINS_MASTER WHERE UPPER(MITIGATIONSTATUS) = ''REOPENED'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_CRITICAL = (select count(1) from CORE.VULPLUGINS_MASTER WHERE UPPER(MITIGATIONSTATUS) IN (''OPEN'',''REOPENED'') AND UPPER(FISMASEVERITY) = ''CRITICAL'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_HIGH = (select count(1) from CORE.VULPLUGINS_MASTER WHERE UPPER(MITIGATIONSTATUS) IN (''OPEN'',''REOPENED'') AND UPPER(FISMASEVERITY) = ''HIGH'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_LOW = (select count(1) from CORE.VULPLUGINS_MASTER WHERE UPPER(MITIGATIONSTATUS) IN (''OPEN'',''REOPENED'') AND UPPER(FISMASEVERITY) = ''LOW'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240118
SET PLUGINS_MEDIUM = (select count(1) from CORE.VULPLUGINS_MASTER WHERE UPPER(MITIGATIONSTATUS) IN (''OPEN'',''REOPENED'') AND UPPER(FISMASEVERITY) = ''MEDIUM'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET SYSTEMS_DEVELOP = (select count(1) from CORE.VW_SYSTEMS WHERE UPPER(TLC_PHASE) = ''DEVELOP'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET SYSTEMS_INITIATE  = (select count(1) from CORE.VW_SYSTEMS WHERE UPPER(TLC_PHASE) = ''INITIATE'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET SYSTEMS_OPERATE = (select count(1) from CORE.VW_SYSTEMS WHERE UPPER(TLC_PHASE) = ''OPERATE'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET SYSTEMS_RETIRE = (select count(1) from CORE.VW_SYSTEMS WHERE UPPER(TLC_PHASE) = ''RETIRE'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240103
SET VUL_AWS = (select count(1) 
    from CORE.VW_ASSETS a
    join CORE.VW_VULMASTER vm on vm.dw_asset_id = a.dw_asset_id
    where UPPER(vm.MITIGATIONSTATUS) <> ''FIXED'' and a.DATACENTER_ID = ''56FFF52E-175B-4E48-9B38-669C8BC74899'') -- 241011 EBF; Acronym was renamed in CFACTS
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 240103
SET VUL_GOVCLOUD = (select count(1) 
    from CORE.VW_ASSETS a
    join CORE.VW_VULMASTER vm on vm.dw_asset_id = a.dw_asset_id
    where UPPER(vm.MITIGATIONSTATUS) <> ''FIXED'' and a.DATACENTER_ID = ''5d8a99a8db672340f99cfd721f96190d'') -- 241011 EBF; Acronym was renamed in CFACTS
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET VUL_FIXED_TODAY = (select count(1) from CORE.VW_VULMASTER WHERE UPPER(MITIGATIONSTATUS) = ''FIXED'' and DATEMITIGATED::DATE = CURRENT_DATE())
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET VUL_OPEN = (select count(1) from CORE.VW_VULMASTER WHERE UPPER(MITIGATIONSTATUS) = ''OPEN'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET VUL_REOPENED = (select count(1) from CORE.VW_VULMASTER WHERE UPPER(MITIGATIONSTATUS) = ''REOPENED'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET VUL_CRITICAL = (select count(1) from CORE.VW_VULMASTER WHERE UPPER(MITIGATIONSTATUS) IN (''OPEN'',''REOPENED'') AND UPPER(FISMASEVERITY) = ''CRITICAL'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET VUL_HIGH = (select count(1) from CORE.VW_VULMASTER WHERE UPPER(MITIGATIONSTATUS) IN (''OPEN'',''REOPENED'') AND UPPER(FISMASEVERITY) = ''HIGH'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET VUL_LOW = (select count(1) from CORE.VW_VULMASTER WHERE UPPER(MITIGATIONSTATUS) IN (''OPEN'',''REOPENED'') AND UPPER(FISMASEVERITY) = ''LOW'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231120
SET VUL_MEDIUM = (select count(1) from CORE.VW_VULMASTER WHERE UPPER(MITIGATIONSTATUS) IN (''OPEN'',''REOPENED'') AND UPPER(FISMASEVERITY) = ''MEDIUM'')
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 231129; Dont use view. It doesnt have DATEDELETED.
SET VUL_DELETED_TODAY = (select count(1) from CORE.VULMASTER WHERE DATEDELETED::DATE = CURRENT_DATE())
WHERE REPORT_ID = :CURRENT_REPORT_ID;

-- Vulnerabilities indirectly considered because Asset record was deleted
UPDATE CORE.REPORT_IDS -- 231129; Dont use view.
SET VUL_INACTIVE_ASSET_TODAY = (select count(1) 
    from CORE.ASSET a
    join CORE.VULMASTER vm on vm.dw_asset_id = a.dw_asset_id
    where a.datedeleted::date = current_date() and a.is_applicable = 0 and vm.deletionreason IS NULL)
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 241011
SET ASSETS_SCANNABLE = (select count(1) from CORE.VW_ASSETS where IS_SCANNABLE = 1)
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 241011
SET ASSETS_TENABLE_CREDENTIALED_SCAN = (select count(1) from CORE.VW_ASSETS where IS_TENABLE_CREDENTIALED_SCAN = 1)
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 241011
SET ASSETS_FORESCOUT_MANAGED  = (select count(1) from CORE.VW_ASSETS where IS_FORESCOUT_MANAGED = 1)
WHERE REPORT_ID = :CURRENT_REPORT_ID;

UPDATE CORE.REPORT_IDS -- 241213
SET ENDPOINTS  = (select count(1) from VW_ASSETS where is_applicable = 1 and is_endpoint = 1)
WHERE REPORT_ID = :CURRENT_REPORT_ID;


CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';