CREATE OR REPLACE PROCEDURE "SP_CRM_GENERATE_SNAPSHOT_ID"("P_DATACATEGORY" VARCHAR(16777216))
RETURNS NUMBER(38,0)
LANGUAGE SQL
COMMENT='Generate next sequential SNAPSHOT_ID for DataCategory'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_GENERATE_SNAPSHOT_ID'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
NEW_SNAPSHOT_ID NUMBER;
REPORT_ID NUMBER;
PARENT_DATACATEGORY VARCHAR;
IS_FROM_AWS_FEED BOOLEAN;

BEGIN

SELECT MAX(REPORT_ID) INTO :REPORT_ID FROM CORE.REPORT_IDS;

SELECT CASE UPPER(:P_DATACATEGORY)
    WHEN ''AWS HWAM'' THEN ''HWAM''
    WHEN ''AWS VUL'' THEN ''VUL''
    WHEN ''AWS VUL MITIGATED'' THEN ''VUL''
    WHEN ''AWS'' THEN ''HWAM''
    WHEN ''AXONIUS'' THEN ''HWAM''
    WHEN ''CCIC VUL'' THEN ''VUL''
    WHEN ''CCIC VUL MITIGATED'' THEN ''VUL''
    WHEN ''CROWDSTRIKE'' THEN ''HWAM'' -- 240820 CR958
    WHEN ''FORESCOUT'' THEN ''HWAM'' -- 240226
    WHEN ''MAG VUL'' THEN ''VUL'' -- 241015 CR-TBD
    WHEN ''MAG VUL MITIGATED'' THEN ''VUL'' -- 241015 CR-TBD
    WHEN ''VUL'' THEN ''VUL''
    ELSE ''UNKNOWN''
END INTO :PARENT_DATACATEGORY;

If (coalesce(NULLIF(:PARENT_DATACATEGORY,''''),''UNKNOWN'') = ''UNKNOWN'') THEN
    BEGIN
    ExceptionMsg := ''P_DATACATEGORY is invalid('' || coalesce(NULLIF(:P_DATACATEGORY,''''),''NULL'') || '')'';
    raise CRM_logic_exception;
    END;
END IF;

-- 240115
SELECT CASE UPPER(:P_DATACATEGORY)
    WHEN ''AWS HWAM'' THEN TRUE
    WHEN ''AWS VUL'' THEN TRUE
    WHEN ''AWS VUL MITIGATED'' THEN TRUE
    WHEN ''AWS'' THEN TRUE
    ELSE FALSE
END INTO :IS_FROM_AWS_FEED;

BEGIN TRANSACTION;
insert into CORE.SNAPSHOT_IDS (COMMENTS,DATACATEGORY,IS_FROM_AWS_FEED,MAX_DATE,MIN_DATE,PARENT_DATACATEGORY,RECORD_COUNT,REPORT_ID,SNAPSHOT_DATE)
VALUES(NULL,:P_DATACATEGORY,:IS_FROM_AWS_FEED,NULL,NULL,:PARENT_DATACATEGORY,NULL,:REPORT_ID,CURRENT_TIMESTAMP());
COMMIT;

SELECT MAX(SNAPSHOT_ID) INTO :NEW_SNAPSHOT_ID FROM CORE.SNAPSHOT_IDS WHERE DATACATEGORY = :P_DATACATEGORY;

Msg := ''Created SnapshotID:'' || :NEW_SNAPSHOT_ID || '', ('' || :P_DATACATEGORY || '')'';
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

RETURN :NEW_SNAPSHOT_ID;

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';