CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_FORESCOUT_NEW"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull FORESCOUT HWAM and SWAM data into RAW_DATA table and prep Forescout specific data'
EXECUTE AS OWNER
AS '
--
-- 240705 CR926 Dedupe Forescout HWAM - This is what facilitated creation of SP_CRM_PULL_FORESCOUT_V2
--
-- 240326 Elliot
-- "Anything with VA in the name is discovered via HPS inspection or nmap interrogation. HWI is usually any discovered fields based on manufacturer, 
-- but I may need to look at that in more detail for a better answer."
--
--
declare
Appl varchar := ''SP_CRM_PULL_FORESCOUT_NEW'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
Datacategory varchar := ''FORESCOUT'';
SNAPSHOT_ID number;
RECORD_COUNT number;
PreviousPullDatetime TIMESTAMP_LTZ(9);
MIN_DATE TIMESTAMP_LTZ(9);
MAX_DATE TIMESTAMP_LTZ(9);

begin
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

/*
CALL CORE.SP_CRM_GENERATE_SNAPSHOT_ID(:Datacategory);
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(:Datacategory);

PreviousPullDatetime := (select PARMDATE FROM CORE.CONFIG where PARMNAME = :Datacategory);
*/

SNAPSHOT_ID := (day(current_date()) || hour(current_timestamp()) || minute(current_timestamp()))::number;
Msg := ''Test SNAPSHOT_ID='' || :SNAPSHOT_ID;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

PreviousPullDatetime := ((current_date() - 1)::date || '' 00:01'')::timestamp;



Msg := ''Previous pull of '' || :Datacategory || ''='' || :PreviousPullDatetime;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

BEGIN TRANSACTION;

insert into CORE.RAW_DATA (
DATACENTER_ID
,FS_FISMA_ID_TAG_WINDOWSINST
,FS_LINUX_FISMA_ID
,FS_FISMA_ID_TAG_GROUPS
,FISMA_ID_TAG -- 240808 CR950
,SYSTEM_ID
,FS_ASSET_ID_TAG_WINDOWSINST
,FS_LINUX_ASSET_ID
,ASSET_ID_TAG -- 240808 CR950
,ASSET_ID_TATTOO
,DATA_ERROR_ARRAY -- 240730 CR942
,DATA_WARNING_ARRAY -- 240730 CR942
,DEVICETYPE
,FQDN
,FS_APPLIANCE_IP
,FS_HWI_MOTHERBOARD
,FS_HWI_PROCESSOR
,FS_LINUX_HOSTNAME
,FS_LINUX_OPERATING_SYSTEM
,FS_LINUX_RUNNING_PROCESSES
,FS_NETBIOS_DOMAIN
,FS_VA_OS
,FS_VA_OS_CPE
,FS_WINDOWS_APPLICATIONS_INSTALLED
,INSERT_DATE
,IPV4
,IPV6
,IS_FS_MANAGED -- 240708
,IS_SYSTEM_ID_DEFAULTED_TO_DC
,MACADDRESS
,MOTHERBOARD
,NETBIOSNAME
,OS
,OS_CPE
,ROWDISPOSITION -- 240730 CR942
,SNAPSHOT_ID
,SOURCE_TOOL
,FS_SENDER_INFO_DATE
,LAST_SEEN
,REPORTDATE
)
SELECT 
CORE.FN_CRM_PARSE_FORESCOUT_DATACENTER_ID(GROUPS) as DATACENTER_ID
,CORE.FN_CRM_PARSE_FORESCOUT_FISMA_ID_V2(WINDOWS_APPLICATIONS_INSTALLED) as FS_FISMA_ID_TAG_WINDOWSINST
,TRIM(CORE.FN_CRM_CLEAN_FORESCOUT_STRING(split_part(LINUX_FISMA_ID,''/var/CMS/FISMA/Primary_FISMA_ID/'',2))) as FS_LINUX_FISMA_ID -- 240705 CR926 fixed to prevent $ in result
,CORE.FN_CRM_PARSE_FORESCOUT_FISMA_ID(GROUPS) as FS_FISMA_ID_TAG_GROUPS
-- 
-- 250107 Elliot indicated GROUPS should continue to be used since sometimes it contains the FISMA ID
-- specifically mapped to the Appliance that the data comes from
--
,coalesce(FS_FISMA_ID_TAG_WINDOWSINST,FS_LINUX_FISMA_ID,FS_FISMA_ID_TAG_GROUPS) as FISMA_ID_TAG -- 240808 CR950
,FISMA_ID_TAG as SYSTEM_ID -- 240808 CR950
,CORE.FN_CRM_PARSE_FORESCOUT_ASSET_ID_V2(WINDOWS_APPLICATIONS_INSTALLED) as FS_ASSET_ID_TAG_WINDOWSINST
,TRIM(CORE.FN_CRM_CLEAN_FORESCOUT_STRING(split_part(LINUX_ASSET_ID,''/var/CMS/FISMA/Asset_ID/'',2))) as FS_LINUX_ASSET_ID -- 240705 CR926 fixed to prevent $ in result
,coalesce(FS_ASSET_ID_TAG_WINDOWSINST,FS_LINUX_ASSET_ID) as ASSET_ID_TAG -- 240808 CR950
,ASSET_ID_TAG as ASSET_ID_TATTOO
,ARRAY_CONSTRUCT() as DATA_ERROR_ARRAY -- 240730 CR942
,ARRAY_CONSTRUCT() as DATA_WARNING_ARRAY -- 240730 CR942
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(ASSET_FUNCTION) as DEVICE_TYPE
,STRTOK_TO_ARRAY(CORE.FN_CRM_CLEAN_FORESCOUT_STRING(DNS_NAME),'','') as FQDN
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(APPLIANCE_IP) as FS_APPLIANCE_IP
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(HWI_MOTHERBOARD) as FS_HWI_MOTHERBOARD
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(HWI_PROCESSOR) as FS_HWI_PROCESSOR
-- LABEL_LIST is not reliable at this time
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(LINUX_HOSTNAME) as FS_LINUX_HOSTNAME
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(LINUX_OPERATING_SYSTEM) as FS_LINUX_OPERATING_SYSTEM
,LINUX_RUNNING_PROCESSES as FS_LINUX_RUNNING_PROCESSES
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(NETBIOS_DOMAIN) as FS_NETBIOS_DOMAIN
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(VA_OS) as FS_VA_OS
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(VA_OS_CPE) as FS_VA_OS_CPE
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(WINDOWS_APPLICATIONS_INSTALLED) as FS_WINDOWS_APPLICATIONS_INSTALLED
,CURRENT_TIMESTAMP() as INSERT_DATE
,STRTOK_TO_ARRAY(CORE.FN_CRM_CLEAN_FORESCOUT_STRING(IPV4),'','') as IPV4
,STRTOK_TO_ARRAY(CORE.FN_CRM_CLEAN_FORESCOUT_STRING(IPV6),'','') as IPV6
,case coalesce((CHARINDEX(''Managed NIX Devices'',GROUPS,1) > 0 or CHARINDEX(''Managed Windows'',GROUPS,1) > 0),0) -- 240708 as per Elliot Levy
        when 0 then ''0''
        Else ''1''
End as IS_FS_MANAGED
,0 as IS_SYSTEM_ID_DEFAULTED_TO_DC -- 240730 CR942
,STRTOK_TO_ARRAY(CORE.FN_CRM_CLEAN_FORESCOUT_STRING(MAC_ADDRESS),'','') as MACADDRESS
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(MOTHERBOARD_SN) as MOTHERBOARD
,STRTOK_TO_ARRAY(CORE.FN_CRM_CLEAN_FORESCOUT_STRING(NETBIOS_HOSTNAME),'','') as NETBIOSNAME
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(OPERATING_SYSTEM) as OS
,CORE.FN_CRM_CLEAN_FORESCOUT_STRING(OS_CPE) as OS_CPE
,CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() as ROWDISPOSITION -- 240730 CR942
,:SNAPSHOT_ID as SNAPSHOT_ID
,:Datacategory as SOURCE_TOOL
,MAX(date_part(year,current_date())::varchar || ''-''
|| case UPPER(substring(SENDER_INFO,1,3))
    WHEN ''JAN'' THEN ''01''
    WHEN ''FEB'' THEN ''02''
    WHEN ''MAR'' THEN ''03''
    WHEN ''APR'' THEN ''04''
    WHEN ''MAY'' THEN ''05''
    WHEN ''JUN'' THEN ''06''
    WHEN ''JUL'' THEN ''07''
    WHEN ''AUG'' THEN ''08''
    WHEN ''SEP'' THEN ''09''
    WHEN ''OCT'' THEN ''10''
    WHEN ''NOV'' THEN ''11''
    WHEN ''DEC'' THEN ''12''
END || ''-'' || substring(SENDER_INFO,5,11) )::datetime as FS_SENDER_INFO_DATE
,FS_SENDER_INFO_DATE as LAST_SEEN
,MIN(S3_FILE_TS) as REPORTDATE -- $$$ WHY THE NEED FOR MIN
FROM APP_FORESCOUT.SHARED.SEC_VW_SDL_FORESCOUT_ASSETS WHERE S3_FILE_TS > :PreviousPullDatetime
group by
DATACENTER_ID
,FS_FISMA_ID_TAG_WINDOWSINST
,FS_LINUX_FISMA_ID
,FS_FISMA_ID_TAG_GROUPS
,FISMA_ID_TAG -- 240808 CR950
,SYSTEM_ID
,FS_ASSET_ID_TAG_WINDOWSINST
,FS_LINUX_ASSET_ID
,ASSET_ID_TAG -- 240808 CR950
,ASSET_ID_TATTOO
,DATA_ERROR_ARRAY -- 240730 CR942
,DATA_WARNING_ARRAY -- 240730 CR942
,DEVICE_TYPE
,FQDN
,FS_APPLIANCE_IP
,FS_HWI_MOTHERBOARD
,FS_HWI_PROCESSOR
,FS_LINUX_HOSTNAME
,FS_LINUX_OPERATING_SYSTEM
,FS_LINUX_RUNNING_PROCESSES
,FS_NETBIOS_DOMAIN
,FS_VA_OS
,FS_VA_OS_CPE
,ROWDISPOSITION -- 240730 CR942
,FS_WINDOWS_APPLICATIONS_INSTALLED
,IPV4
,IPV6
,IS_FS_MANAGED -- 240708
,IS_SYSTEM_ID_DEFAULTED_TO_DC -- 240730 CR942
,MACADDRESS
,MOTHERBOARD
,NETBIOSNAME
,OS
,OS_CPE
;

RECORD_COUNT := SQLROWCOUNT;

COMMIT;

IF (:RECORD_COUNT = 0) THEN
	BEGIN
	Msg := ''WARNING: There is no data for this snapshot'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
ELSE
    BEGIN
    Msg := :Datacategory || '' inserted into RAW_DATA='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF;

MIN_DATE := (select MIN(LAST_SEEN) FROM CORE.RAW_DATA WHERE SNAPSHOT_ID = :SNAPSHOT_ID);
MAX_DATE := (select MAX(LAST_SEEN) FROM CORE.RAW_DATA WHERE SNAPSHOT_ID = :SNAPSHOT_ID);

BEGIN TRANSACTION;

UPDATE CORE.SNAPSHOT_IDS
set MIN_DATE = :MIN_DATE
,MAX_DATE = :MAX_DATE
,RECORD_COUNT = coalesce(:RECORD_COUNT,0)
 where SNAPSHOT_ID = :SNAPSHOT_ID;

/***************** COMMENT WHILE TESTING
UPDATE CORE.CONFIG
set PARMDATE = :MAX_DATE
where PARMNAME = :Datacategory and :MAX_DATE IS NOT NULL;
***************************************************************/
Msg := ''WARNING: Update of CORE.CONFIG disabled while testing'';
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

COMMIT;

-------------------------------------------------------------------------------
--
-- PREP THE DATA
--
-------------------------------------------------------------------------------

BEGIN TRANSACTION;
--
-- 240410 CR 867 Implement DRaaS multi-tenant tag
--
UPDATE CORE.RAW_DATA upd
set ASSET_ID_TATTOO = p.ASSET_ID_TATTOO -- 240827 CR-TBD
,DATACENTER_ID = p.DATACENTER_ID -- 240827 CR-TBD
,TENANT_ID = p.TENANT_ID -- 240827 CR-TBD
FROM CORE.RAW_DATA r
join table(CORE.FN_CRM_PARSE_DRAAS_ASSET_ID_TATTOO(r.ASSET_ID_TAG)) p -- 240827 CR-TBD
where r.SNAPSHOT_ID = :SNAPSHOT_ID 
and CORE.FN_CRM_IS_VALID_DRAAS_ASSET_ID_TATTOO(r.ASSET_ID_TAG) = 1 -- 240827 CR-TBD
and r.ASSET_ID_TAG IS NOT NULL -- 240916 1459 CR-EBF
and upd.RAW_ID = r.RAW_ID;

RECORD_COUNT := SQLROWCOUNT;

Msg := ''Tenant tags assigned='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

COMMIT;

BEGIN TRANSACTION;
-- Clean FS_LINUX_HOSTNAME
UPDATE CORE.RAW_DATA
set FS_LINUX_HOSTNAME = NULL
where SNAPSHOT_ID = :SNAPSHOT_ID and ((upper(FS_LINUX_HOSTNAME) LIKE ''%LAST LOGIN:%'') or upper(FS_LINUX_HOSTNAME) LIKE ''%TOO MANY LOGINS%''
    or upper(FS_LINUX_HOSTNAME) LIKE ''%CONNECTION RESET BY%'');
COMMIT;

BEGIN TRANSACTION;
-- Set HOSTNAME to FS_LINUX_HOSTNAME when HOSTNAME is null
UPDATE CORE.RAW_DATA
set HOSTNAME = STRTOK_TO_ARRAY(FS_LINUX_HOSTNAME)
where SNAPSHOT_ID = :SNAPSHOT_ID and HOSTNAME IS NULL and FS_LINUX_HOSTNAME IS NOT NULL;
COMMIT;

BEGIN TRANSACTION;
-- Extract FS_HWI_MOTHERBOARD
-- Remove leading/trailing forward-slash and period
-- Raw value contains several fields that we may want to use in the future
UPDATE CORE.RAW_DATA
set FS_HWI_MOTHERBOARD = TRIM(SUBSTRING(FS_HWI_MOTHERBOARD,(POSITION(''Serial Number: '',FS_HWI_MOTHERBOARD,1) + 15),(POSITION(''SKU:'',FS_HWI_MOTHERBOARD,1) - POSITION(''Serial Number: '',FS_HWI_MOTHERBOARD,1) - 16 )),''/.'')
where SNAPSHOT_ID = :SNAPSHOT_ID and POSITION(''Serial Number: '',FS_HWI_MOTHERBOARD,1) > 0;
COMMIT;
BEGIN TRANSACTION;
-- Clean FS_HWI_MOTHERBOARD
-- Raw value contains several fields that we may want to use in the future
UPDATE CORE.RAW_DATA
set FS_HWI_MOTHERBOARD = NULL
where SNAPSHOT_ID = :SNAPSHOT_ID and (upper(FS_HWI_MOTHERBOARD) LIKE ''%ERROR%'' or upper(FS_HWI_MOTHERBOARD) LIKE ''%NOT RECOGNIZED%''    
    or FS_HWI_MOTHERBOARD IN (''No Instance(s) Available.'',''Type2 - Board Serial Number'',''None''));
COMMIT;
BEGIN TRANSACTION;
-- Extract MOTHERBOARD
-- Raw value contains several fields that we may want to use in the future
UPDATE CORE.RAW_DATA
set MOTHERBOARD = TRIM(SUBSTRING(MOTHERBOARD,(POSITION(''SerialNumber='',MOTHERBOARD,1) + 13),(POSITION(''Version='',MOTHERBOARD,1) - POSITION(''SerialNumber='',MOTHERBOARD,1) - 14 )),''/.'')
where SNAPSHOT_ID = :SNAPSHOT_ID and POSITION(''SerialNumber='',MOTHERBOARD,1) > 0;
COMMIT;
BEGIN TRANSACTION;
-- Clean MOTHERBOARD
-- Raw value contains several fields that we may want to use in the future
UPDATE CORE.RAW_DATA
set MOTHERBOARD = NULL
where SNAPSHOT_ID = :SNAPSHOT_ID and (upper(MOTHERBOARD) LIKE ''%ERROR%'' or upper(MOTHERBOARD) LIKE ''%NOT RECOGNIZED%''    
    or MOTHERBOARD IN (''No Instance(s) Available.'',''Type2 - Board Serial Number'',''None''));
COMMIT;
BEGIN TRANSACTION;
-- Set MOTHERBOARD to FS_HWI_MOTHERBOARD when MOTHERBOARD is null
UPDATE CORE.RAW_DATA
set MOTHERBOARD = FS_HWI_MOTHERBOARD
where SNAPSHOT_ID = :SNAPSHOT_ID and MOTHERBOARD IS NULL and FS_HWI_MOTHERBOARD IS NOT NULL;
COMMIT;

BEGIN TRANSACTION;
UPDATE CORE.RAW_DATA
set OS = coalesce(OS,FS_VA_OS,FS_LINUX_OPERATING_SYSTEM)
where SNAPSHOT_ID = :SNAPSHOT_ID;
COMMIT;

BEGIN TRANSACTION;
UPDATE CORE.RAW_DATA
set OS_CPE = coalesce(OS_CPE,FS_VA_OS_CPE)
where SNAPSHOT_ID = :SNAPSHOT_ID;
COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';