CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_AWS_HWAM_NEW"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull AWS HWAM data into RAW_DATA table'
EXECUTE AS OWNER
AS '
--
-- 
--
declare
Appl varchar := ''SP_CRM_PULL_AWS_HWAM_NEW'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
Datacategory varchar := ''AWS HWAM'';
PreviousPullDatetime TIMESTAMP_LTZ(9);
SNAPSHOT_ID number;
RECORD_COUNT number;
MIN_DATE TIMESTAMP_LTZ(9);
MAX_DATE TIMESTAMP_LTZ(9);

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

/*
CALL CORE.SP_CRM_GENERATE_SNAPSHOT_ID(:Datacategory);
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(:Datacategory);

PreviousPullDatetime := (select PARMDATE FROM CORE.CONFIG where PARMNAME = :Datacategory);
*/


SNAPSHOT_ID := (day(current_date()) || hour(current_timestamp()) || minute(current_timestamp()))::number;
Msg := ''Test SNAPSHOT_ID='' || :SNAPSHOT_ID;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

PreviousPullDatetime := ((current_date() - 1)::date || '' 00:01'')::timestamp;

Msg := ''Previous pull of '' || :Datacategory || ''='' || :PreviousPullDatetime;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

BEGIN TRANSACTION;
  
insert into CORE.RAW_DATA (
ASSET_ID_TATTOO
,AWS_ACCOUNTID
,AWS_INSTANCE_ID
,COMPUTER_TYPE
,DATA_ERROR_ARRAY
,DATA_WARNING_ARRAY
,DATACENTER_ID
,DEVICETYPE
,ENVIRONMENT
,FQDN
,HOSTNAME
,INSERT_DATE
,INSTANCESTATUS
,IPV4
,IPV6
,LAST_SEEN
,MACADDRESS
,MOTHERBOARD
,NETBIOSNAME
,OS
,OS_VERSION
,REPORTDATE
,ROWDISPOSITION
,SNAPSHOT_ID
,SOURCE_TOOL
,SYSTEM_ID
)
SELECT
src.ASSET_ID_TATTOO
,src.AWS_ACCOUNTID
,src.AWS_INSTANCE_ID
,src.COMPUTER_TYPE
,ARRAY_CONSTRUCT() as DATA_ERROR_ARRAY
,ARRAY_CONSTRUCT() as DATA_WARNING_ARRAY
,src.DATACENTER_ID
,src.DEVICE_TYPE
,src.ENVIRONMENT
,STRTOK_TO_ARRAY(src.FQDN,'','') as FQDN
,src.HOSTNAME
,CURRENT_TIMESTAMP() as INSERT_DATE
,src.INSTANCESTATUS
,src.IPV4
,src.IPV6
,src.LAST_SEEN
,src.MACADDRESS
,src.MOTHERBOARD
,src.NETBIOSNAME
,src.OS
,src.OS_VERSION
,src.REPORTDATE
,CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() as ROWDISPOSITION
,:SNAPSHOT_ID as SNAPSHOT_ID
,src.SOURCE_TOOL
,src.SYSTEM_ID
FROM
(
SELECT 
h.INSTANCEID as ASSET_ID_TATTOO
,h.ACCOUNT_NUMBER as AWS_ACCOUNTID
,h.INSTANCEID as AWS_INSTANCE_ID
,h.COMPUTER_TYPE
,h.DATACENTER_ID
,h.DEVICE_TYPE
,h.ENVIRONMENT
,h.FQDN
,h.HOSTNAME
,h.INSTANCESTATUS
,h.IPV4
,h.IPV6
,h.LAST_CONFIRMED_TIME as LAST_SEEN
,h.MAC as MACADDRESS
,h.MOTHERBOARD_SN as MOTHERBOARD
,h.NETBIOS_HN as NETBIOSNAME
,h.OS
,h.OS_VERSION
,h.REPORT_TIME as REPORTDATE
,h.SOURCE_TOOL
,h.SYSTEM_ID
FROM CORE.VW_HWAM_AWS_V2 h
JOIN CORE.VW_SYSTEMS dc on dc.SYSTEM_ID = h.DATACENTER_ID
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = h.SYSTEM_ID
WHERE NULLIF(h.INSTANCEID,'''') IS NOT NULL

UNION ALL

SELECT 
h.INSTANCEID as ASSET_ID_TATTOO
,h.ACCOUNT_NUMBER as AWS_ACCOUNTID
,h.INSTANCEID as AWS_INSTANCE_ID
,h.COMPUTER_TYPE
,h.DATACENTER_ID::varchar as DATACENTER_ID -- 240725 CR928
,h.DEVICE_TYPE
,h.ENVIRONMENT
,h.FQDN
,STRTOK_TO_ARRAY(h.HOSTNAME,'','') as HOSTNAME
,h.INSTANCESTATUS
,h.IPV4
,h.IPV6
,h.REPORT_TIME::datetime as LAST_SEEN
,h.MAC as MACADDRESS
,NULL as MOTHERBOARD
,NULL as NETBIOSNAME
,h.OS
,h.OS_VERSION
,h.REPORT_TIME::datetime as REPORTDATE
,h.SOURCE_TOOL
,s.SYSTEM_ID
FROM APP_CDM.SHARED.SEC_VW_HWAM_CCSQ h
JOIN CORE.VW_SYSTEMS dc on dc.SYSTEM_ID = h.DATACENTER_ID
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = h.FISMA_ID
WHERE NULLIF(h.INSTANCEID,'''') IS NOT NULL
) src;

RECORD_COUNT := SQLROWCOUNT;

COMMIT;

IF (:RECORD_COUNT = 0) THEN
	BEGIN
	Msg := ''WARNING: There is no data for this snapshot'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
ELSE
    BEGIN
    Msg := :Datacategory || '' inserted into RAW_DATA='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF;

MIN_DATE := (select MIN(LAST_SEEN) FROM CORE.RAW_DATA WHERE SNAPSHOT_ID = :SNAPSHOT_ID);
MAX_DATE := (select MAX(LAST_SEEN) FROM CORE.RAW_DATA WHERE SNAPSHOT_ID = :SNAPSHOT_ID);

BEGIN TRANSACTION;

UPDATE CORE.SNAPSHOT_IDS
set MIN_DATE = :MIN_DATE
,MAX_DATE = :MAX_DATE
,RECORD_COUNT = coalesce(:RECORD_COUNT,0)
 where SNAPSHOT_ID = :SNAPSHOT_ID;

/***************** COMMENT WHILE TESTING
UPDATE CORE.CONFIG
set PARMDATE = :MAX_DATE
where PARMNAME = :Datacategory and :MAX_DATE IS NOT NULL;
***************************************************************/
Msg := ''WARNING: Update of CORE.CONFIG disabled while testing'';
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';