CREATE OR REPLACE PROCEDURE "SP_CRM_GENERATE_IPV4S"("P_SEGMENTID" NUMBER(38,0), "P_STARTINGIP" VARCHAR(16777216), "P_ENDINGIP" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Generate list of IPV4s based on Starting/Ending range'
EXECUTE AS OWNER
AS '

DECLARE
Appl varchar := ''SP_CRM_GENERATE_IPV4S'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
SNAPSHOT_ID number;
RECORD_COUNT NUMBER;
STARTINGIP_OCTET1 NUMBER;
STARTINGIP_OCTET2 NUMBER;
STARTINGIP_OCTET3 NUMBER;
STARTINGIP_OCTET4 NUMBER;
ENDINGIP_OCTET1 NUMBER;
ENDINGIP_OCTET2 NUMBER;
ENDINGIP_OCTET3 NUMBER;
ENDINGIP_OCTET4 NUMBER;
PTR_OCTET1 NUMBER;
PTR_OCTET2 NUMBER;
PTR_OCTET3 NUMBER;
CTR_OCTET1 NUMBER;
CTR_OCTET2 NUMBER;
CTR_OCTET3 NUMBER;
CTR_OCTET4 NUMBER;
NEWIP VARCHAR;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

If (:P_STARTINGIP IS NULL or :P_ENDINGIP IS NULL or :P_STARTINGIP not like ''%.%.%.%'' or :P_ENDINGIP not like ''%.%.%.%'') THEN
	BEGIN
	ExceptionMsg := ''Invalid Start/End IP'';
    raise CRM_logic_exception;
	END;
END IF;

PTR_OCTET1 := CHARINDEX(''.'',:P_STARTINGIP,1);
PTR_OCTET2 := CHARINDEX(''.'',:P_STARTINGIP,:PTR_OCTET1 + 1);
PTR_OCTET3 := CHARINDEX(''.'',:P_STARTINGIP,:PTR_OCTET2 + 1);
Msg := ''PTR_OCTET1='' || PTR_OCTET1 || '',PTR_OCTET2='' || PTR_OCTET2 || '',PTR_OCTET3='' || PTR_OCTET3;
--CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

STARTINGIP_OCTET1 := SUBSTRING(:P_STARTINGIP,1,PTR_OCTET1 - 1);
STARTINGIP_OCTET2 := SUBSTRING(:P_STARTINGIP,:PTR_OCTET1 + 1,:PTR_OCTET2 - :PTR_OCTET1 - 1);
STARTINGIP_OCTET3 := SUBSTRING(:P_STARTINGIP,:PTR_OCTET2 + 1,:PTR_OCTET3 - :PTR_OCTET2 - 1);
STARTINGIP_OCTET4 := SUBSTRING(:P_STARTINGIP,:PTR_OCTET3 + 1,LEN(:P_STARTINGIP) - :PTR_OCTET3 + 1);

Msg := ''STARTINGIP_OCTET1='' || STARTINGIP_OCTET1 || '',STARTINGIP_OCTET2='' || STARTINGIP_OCTET2 || '',STARTINGIP_OCTET3='' || STARTINGIP_OCTET3 || '',STARTINGIP_OCTET4='' || STARTINGIP_OCTET4;
--CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);


PTR_OCTET1 := CHARINDEX(''.'',:P_ENDINGIP,1);
PTR_OCTET2 := CHARINDEX(''.'',:P_ENDINGIP,:PTR_OCTET1 + 1);
PTR_OCTET3 := CHARINDEX(''.'',:P_ENDINGIP,:PTR_OCTET2 + 1);

ENDINGIP_OCTET1 := SUBSTRING(:P_ENDINGIP,1,:PTR_OCTET1 - 1);
ENDINGIP_OCTET2 := SUBSTRING(:P_ENDINGIP,:PTR_OCTET1 + 1,:PTR_OCTET2 - :PTR_OCTET1 - 1);
ENDINGIP_OCTET3 := SUBSTRING(:P_ENDINGIP,:PTR_OCTET2 + 1,:PTR_OCTET3 - :PTR_OCTET2 - 1);
ENDINGIP_OCTET4 := SUBSTRING(:P_ENDINGIP,:PTR_OCTET3 + 1,LEN(:P_ENDINGIP) - :PTR_OCTET3 + 1);

Msg := ''ENDINGIP_OCTET1='' || ENDINGIP_OCTET1 || '',ENDINGIP_OCTET2='' || ENDINGIP_OCTET2 || '',ENDINGIP_OCTET3='' || ENDINGIP_OCTET3 || '',ENDINGIP_OCTET4='' || ENDINGIP_OCTET4;
--CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);


CTR_OCTET1 := STARTINGIP_OCTET1;

WHILE (:CTR_OCTET1 <= :ENDINGIP_OCTET1) DO
	BEGIN
	CTR_OCTET2 := STARTINGIP_OCTET2;

	WHILE (CTR_OCTET2 <= :ENDINGIP_OCTET2) DO
		BEGIN
		CTR_OCTET3 := STARTINGIP_OCTET3;

		WHILE (CTR_OCTET3 <= :ENDINGIP_OCTET3) DO
			BEGIN
			CTR_OCTET4 := STARTINGIP_OCTET4;

			WHILE (CTR_OCTET4 <= :ENDINGIP_OCTET4) DO
				BEGIN
                NEWIP := CTR_OCTET1::varchar || ''.'' || CTR_OCTET2::varchar || ''.'' || CTR_OCTET3::varchar || ''.'' || CTR_OCTET4::varchar;

INSERT INTO CORE.TEMP_IPV4 (ENDRANGE,INSERT_DATE,IPV4,OCTET1,OCTET2,OCTET3,OCTET4,PATH,SEGMENTID,SEGMENTNAME,STARTRANGE)
VALUES(:P_ENDINGIP,CURRENT_TIMESTAMP(),:NEWIP,:CTR_OCTET1,:CTR_OCTET2,:CTR_OCTET3,:CTR_OCTET4,NULL,:P_SEGMENTID,NULL,:P_STARTINGIP);

				CTR_OCTET4 := CTR_OCTET4 + 1;
                END;
				END WHILE; -- 4

			CTR_OCTET3 := CTR_OCTET3 + 1;
            END;
			END WHILE; -- 3

		CTR_OCTET2 := CTR_OCTET2 + 1;
        END;
		END WHILE; -- 2

    CTR_OCTET1 := CTR_OCTET1 + 1;
    END;
	END WHILE; -- 1


CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';