CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_MAG_VUL_MITIGATED"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull MAG TENABLE data into BUS_CYBER_RISK_MANAGEMENT RAW_TENABLE_VUL table'
EXECUTE AS OWNER
AS '
--
-- 
--
declare
Appl varchar := ''SP_CRM_PULL_MAG_VUL_MITIGATED'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
Datacategory varchar := ''MAG VUL MITIGATED'';
PreviousPullDatetime TIMESTAMP_LTZ(9);
SNAPSHOT_ID number;
RECORD_COUNT number;
MIN_DATE TIMESTAMP_LTZ(9);
MAX_DATE TIMESTAMP_LTZ(9);

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

CALL CORE.SP_CRM_GENERATE_SNAPSHOT_ID(:Datacategory);
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(:Datacategory);

PreviousPullDatetime := (select PARMDATE FROM CORE.CONFIG where PARMNAME = :Datacategory);

Msg := ''Previous pull of '' || :Datacategory || ''='' || :PreviousPullDatetime;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

BEGIN TRANSACTION;

insert into CORE.RAW_TENABLE_VUL(
ACCEPT_RISK_RULE_COMMENT
,ACCEPTRISK
,ACRSCORE
,APPLICABILITYCODE
,ASSET_ID_TATTOO
,ASSETEXPOSURESCORE
,AZURE_SUBSCRIPTION_ID -- 241125 CR1038
,BASESCORE
,BID
,CHECKTYPE
,COMPLIANCE_ACTUAL_VALUE
,COMPLIANCE_CHECK_NAME
,COMPLIANCE_ERROR
,COMPLIANCE_RESULT
,CPE
,CREDENTIALED_SCAN
,CUSTOM_SEVERITY
,CVE
,CVSSV2BASESCORE
,CVSSV3BASESCORE
,CVSSV3TEMPORALSCORE
,CVSSV3VECTOR
,CVSSVECTOR
,DATA_ERROR_ARRAY
,DATA_WARNING_ARRAY
,DATACENTER_ID
,DESCRIPTION
,DNSNAME
,EXPLOIT_AVAILABLE
,EXPLOITEASE
,EXPLOITFRAMEWORKS
,FAMILY_ID
,FAMILY_NAME
,FAMILY_TYPE
,FIRST_SEEN
,FISMASEVERITY
,HAS_BEEN_MITIGATED
,HOSTNAME
,HOSTUNIQUENESS
,HOSTUUID
,INSERT_DATE
,IP
,IPS
,KEYDRIVERS
,LAST_SEEN
,MACADDRESS
,MITIGATIONSTATUS
,NETBIOSNAME
,NUMERIC_SEVERITY
,OPERATING_SYSTEM
,PATCHPUB_DATE
,PLUGIN_ID
,PLUGIN_INFO
,PLUGIN_MOD_DATE
,PLUGIN_NAME
,PLUGIN_PUB_DATE
,PLUGINTEXT
,PORT
,PRIMARY_FISMA_ID_DERIVED
,PRIMARY_FISMA_ID_TATTOO
,PROTOCOL
,RECASTRISK
,RECASTRISKRULECOMMENT
,REPORTDATE
,REPOSITORY_DATAFORMAT
,REPOSITORY_DESCRIPTION
,REPOSITORY_ID
,REPOSITORY_NAME
,RISKFACTOR
,ROWDISPOSITION
,SCAN_POLICY_NAME
,SCAN_POLICY_UID
,SCAN_START_DATE
,SEEALSO
,SEVERITY_DESCRIPTION
,SEVERITY_ID
,SEVERITY_NAME
,SNAPSHOT_ID
,SOLUTION
,SOURCE_TOOL
,STATE
,STIGSEVERITY
,SYNOPSIS
,SYSTEM_ID
,TEMPORAL_SCORE
,TENABLEUUID
,UNIQUENESS
,VERSION
,VPR_SCORE
,VPRCONTEXT
,VULN_PUB_DATE
,XREF
,ASSET_ID_TAG
,FISMA_ID_TAG
) 
SELECT
v.ACCEPT_RISK_RULE_COMMENT
,v.ACCEPTRISK
,v.ACRSCORE
,CORE.FN_CRM_GET_INDICATOR_INITIAL() as APPLICABILITYCODE
,v.ASSET_ID_TATTOO
,v.ASSETEXPOSURESCORE
,v.SUBSCRIPTION_ID as AZURE_SUBSCRIPTION_ID -- 241125 CR1038
,coalesce(NULLIF(v.BASESCORE,''''),''0'')::NUMBER(38,1) as BASESCORE
,v.BID
,v.CHECKTYPE
,NULL as COMPLIANCE_ACTUAL_VALUE
,NULL as COMPLIANCE_CHECK_NAME
,NULL as COMPLIANCE_ERROR
,NULL as COMPLIANCE_RESULT
,v.CPE
,v.CREDENTIALED_SCAN
,NULL as CUSTOM_SEVERITY
,v.CVE
,coalesce(NULLIF(v.BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV2BASESCORE -- 230419 Naseem found that BASESCORE matches legacy CVSSv2
,coalesce(NULLIF(v.CVSSV3BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV3BASESCORE
,v.CVSSV3TEMPORALSCORE
,v.CVSSV3VECTOR
,v.CVSSVECTOR
,ARRAY_CONSTRUCT() as DATA_ERROR_ARRAY
,ARRAY_CONSTRUCT() as DATA_WARNING_ARRAY
,coalesce(v.REPOSITORY_DESCRIPTION,''FECCCA8B-8161-4E0A-ACA7-788ED45EB9EE'') as DATACENTER_ID -- SEC_VW_FISMA_LOOKUPS_MAG should have DATACENTER_ID but is NULL
,v.DESCRIPTION
,NULLIF(v.DNSNAME,'''') as DNSNAME
,v.EXPLOIT_AVAILABLE
,v.EXPLOITEASE
,v.EXPLOITFRAMEWORKS
,v.FAMILY_ID
,v.FAMILY_NAME
,v.FAMILY_TYPE
,v.FIRST_SEEN
,CORE.FN_CRM_CHARACTER_SEVERITY(v.FN_NUMERIC_SEVERITY) as FISMASEVERITY -- 241106 CR-TBD
,v.HAS_BEEN_MITIGATED::boolean as HAS_BEEN_MITIGATED
,NULL as HOSTNAME
,v.HOSTUNIQUENESS
,NULL as HOSTUUID
,CURRENT_TIMESTAMP() as INSERT_DATE
,v.IP
,v.IPS
,v.KEYDRIVERS
,v.LAST_SEEN
,NULLIF(v.MACADDRESS,'''') as MACADDRESS
,case HAS_BEEN_MITIGATED
    when 1 then CORE.FN_CRM_GET_MITIGATIONSTATUS_REOPENED()
    Else CORE.FN_CRM_GET_MITIGATIONSTATUS_OPEN()
End as MITIGATIONSTATUS
,NULLIF(v.NETBIOSNAME,'''') as NETBIOSNAME
,v.FN_NUMERIC_SEVERITY as NUMERIC_SEVERITY -- 241106 CR-TBD
,v.OPERATING_SYSTEM
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PATCHPUB_DATE) as PATCHPUB_DATE
,v.PLUGIN_ID
,v.PLUGIN_INFO
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PLUGIN_MOD_DATE) as PLUGIN_MOD_DATE
,v.PLUGIN_NAME
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PLUGIN_PUB_DATE) as PLUGIN_PUB_DATE
,v.PLUGINTEXT
,v.PORT
,NULL as PRIMARY_FISMA_ID_DERIVED
,NULL as PRIMARY_FISMA_ID_TATTOO
,v.PROTOCOL
,v.RECASTRISK
,NULL as RECASTRISKRULECOMMENT
,v.REPORTDATE
,v.REPOSITORY_DATAFORMAT
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,v.REPOSITORY_NAME
,v.RISKFACTOR
,CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() as ROWDISPOSITION
,v.SCAN_POLICY_NAME
,v.SCAN_POLICY_UID
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.SCAN_START_DATE) as SCAN_START_DATE
,v.SEEALSO
,v.SEVERITY_DESCRIPTION
,v.SEVERITY_ID
,v.SEVERITY_NAME
,:SNAPSHOT_ID
,v.SOLUTION
,''Tenable'' as SOURCE_TOOL
,NULL as STATE
,v.STIGSEVERITY
,v.SYNOPSIS
,v.SYSTEM_ID
,v.TEMPORAL_SCORE
,v.UUID as TENABLEUUID
,v.UNIQUENESS
,v.VERSION
,v.VPR_SCORE
,STRTOK_TO_ARRAY(v.VPRCONTEXT,'','') as VPRCONTEXT
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.VULN_PUB_DATE) as VULN_PUB_DATE
,v.XREF
,v.ASSET_ID_TATTOO as ASSET_ID_TAG
,v.SYSTEM_ID as FISMA_ID_TAG
FROM (
SELECT
mag.ACCEPT_RISK_RULE_COMMENT
,mag.ACCEPTRISK
,mag.ACRSCORE
,mag.NAME as ASSET_ID_TATTOO -- 241022 discussion with Greg Beck indicates this should be reliable as a distinct value
,mag.ASSETEXPOSURESCORE
,mag.BASESCORE
,mag.BID
,mag.CHECKTYPE
,mag.CPE
,NULL as CREDENTIALED_SCAN
,mag.CVE
,mag.CVSSV3BASESCORE
,mag.CVSSV3TEMPORALSCORE
,mag.CVSSV3VECTOR
,mag.CVSSVECTOR
,mag.DESCRIPTION
,mag.DNSNAME
,mag.EXPLOIT_AVAILABLE
,mag.EXPLOITEASE
,mag.EXPLOITFRAMEWORKS
,mag.FAMILY_ID
,mag.FAMILY_NAME
,mag.FAMILY_TYPE
,mag.FIRST_SEEN
,mag.HAS_BEEN_MITIGATED
,mag.HOSTUNIQUENESS
,mag.IP
,mag.IPS
,mag.KEYDRIVERS
,mag.LAST_SEEN
,mag.MACADDRESS
,mag.NETBIOSNAME
,CORE.FN_CRM_NUMERIC_SEVERITY(''3.0'',mag.CVSSV3BASESCORE) as FN_NUMERIC_SEVERITY -- 241106 CR-TBD
,mag.OPERATING_SYSTEM
,mag.PATCHPUB_DATE
,mag.PLUGIN_ID
,mag.PLUGIN_INFO
,mag.PLUGIN_MOD_DATE
,mag.PLUGIN_NAME
,mag.PLUGIN_PUB_DATE
,mag.PLUGINTEXT
,mag.PORT
,NULL as PRIMARY_FISMA_ID
,mag.PROTOCOL
,mag.RECASTRISK
,mag.S3_FILE_CREATE as REPORTDATE
,mag.REPOSITORY_DATAFORMAT
,NULLIF(mag.REPOSITORY_DESCRIPTION,'''') as REPOSITORY_DESCRIPTION
,mag.REPOSITORY_ID
,mag.REPOSITORY_NAME
,mag.RISKFACTOR
,NULL as SCAN_POLICY_NAME
,NULL as SCAN_POLICY_UID
,NULL as SCAN_START_DATE
,mag.SEEALSO
,mag.SEVERITY_DESCRIPTION
,mag.SEVERITY_ID
,mag.SEVERITY_NAME
,mag.SOLUTION
,mag.STIGSEVERITY
,mag.SYNOPSIS
,coalesce(NULLIF(lu.FISMA,''''),''SUBSCRIPTION_ID is not in SEC_VW_FISMA_LOOKUPS_MAG'') as SYSTEM_ID
,mag.SUBSCRIPTION_ID -- 241125 CR1038
,mag.TEMPORAL_SCORE
,mag.UUID
,mag.UNIQUENESS
,mag.VERSION
,mag.VPR_SCORE
,mag.VPRCONTEXT
,mag.VULN_PUB_DATE
,mag.XREF
--
-- OTHER MAG COLUMNS NOT USED AT THIS TIME
--
-- DNS_SERVERS -- SPARSE
-- FILENAME -- NOT NEEDED BUT CONSIDER ADDING TO NEW (SINGLE) RAW_DATA TABLE
-- INSTANCEID -- ALWAYS EMPTY
-- IP_CONFIGURATIONS -- EXPLORE
-- MACADDRESS -- MAC_ADDRESS appears to be of more value. This is sparse and does not always match MAC_ADDRESS
-- MAG_INSTANCE_IP_ADDRESS -- MIGHT BE IMPORTANT
-- NAME -- COMPARE TO SUBSCRIPTION_ID; APPEARS TO BE HOSTNAME
-- NETWORK_INTERFACE_ID -- EXPLORE
-- split_part(NETWORK_INTERFACE_ID,''/'',3) as NETWORK_INTERFACE_ID_SUBSCRIPTION_ID 
-- split_part(NETWORK_INTERFACE_ID,''/'',5)
-- split_part(NETWORK_INTERFACE_ID,''/'',9)
-- NETWORK_PRIMARY –- TRUE/FALSE/NULL
-- RAW_VULNS -- DON’T NEED RAW DATA
-- SF_FILE_LOAD -- NOT NEEDED
-- TYPE -- Always: Microsoft.Network/networkInterfaces
-- VIRTUAL_MACHINE_ID -- Not always populated
-- VULNUNIQUENESS -- NOT NEEDED
-- VULNUUID -- ALWAYS EMPTY
FROM APP_TENABLE.SHARED.SEC_VW_IUSG_MAG_MITIGATED_VULNS mag
--
-- Need to use upper function because of case issues in Tenable data
--
LEFT OUTER JOIN REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS_MAG lu on upper(lu.account_number) = upper(mag.SUBSCRIPTION_ID)
WHERE mag.S3_FILE_CREATE > :PreviousPullDatetime
and FN_NUMERIC_SEVERITY > 0 -- 241105 CR1024 filter-out Informational records
) v;

RECORD_COUNT := SQLROWCOUNT;
COMMIT;

BEGIN TRANSACTION;
UPDATE CORE.SNAPSHOT_IDS
set RECORD_COUNT = coalesce(:RECORD_COUNT,0)
where SNAPSHOT_ID = :SNAPSHOT_ID;
COMMIT;

IF (:RECORD_COUNT = 0) THEN
	BEGIN
	Msg := ''WARNING: There is no VUL data for this snapshot'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
END IF;
    
Msg := :Datacategory || '' inserted into RAW_TENABLE_VUL='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

MIN_DATE := (select MIN(REPORTDATE) FROM CORE.RAW_TENABLE_VUL WHERE SNAPSHOT_ID = :SNAPSHOT_ID);
MAX_DATE := (select MAX(REPORTDATE) FROM CORE.RAW_TENABLE_VUL WHERE SNAPSHOT_ID = :SNAPSHOT_ID);

BEGIN TRANSACTION;
update CORE.CONFIG
set PARMDATE = :MAX_DATE
where PARMNAME = :Datacategory and :MAX_DATE IS NOT NULL;

UPDATE CORE.SNAPSHOT_IDS
set MIN_DATE = :MIN_DATE
,MAX_DATE = :MAX_DATE
where SNAPSHOT_ID = :SNAPSHOT_ID;
COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';