CREATE OR REPLACE PROCEDURE "SP_CRM_DELETE_ASSET"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Delete assets from ASSET table and dependent tables using TEMP_ASSETS_TO_DELETE as driver'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_DELETE_ASSET'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean := 0;
True boolean := 1;
RECORD_COUNT NUMBER;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

--
-- UNTIL CR IS CREATED TO DO PHYSICAL DELETIONS IN ALL CASES, USE TEMP_ASSETS_TO_DELETE.IS_PHYSICAL_DELETE TO DETERMINE LOGICAL/PHYSICAL
--

BEGIN TRANSACTION;
--
-- Logically Delete Asset
--
UPDATE CORE.ASSET upd
set Is_Applicable = 0
,dateDeleted = t.INSERT_DATE
,DeletionReason = t.DeletionReason
FROM CORE.TEMP_ASSETS_TO_DELETE t
WHERE upd.DW_ASSET_ID = t.DW_ASSET_ID and t.IS_PHYSICAL_DELETE = 0;
COMMIT;

BEGIN TRANSACTION;
Delete from CORE.ASSET_SOFTWARE where DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1); -- 250117
Delete from CORE.ASSETINTERFACECOALESCED WHERE DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.ASSETINTERFACE_FQDN WHERE DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.ASSETINTERFACE_HOSTNAME WHERE DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.ASSETINTERFACE_IPV4 WHERE DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.ASSETINTERFACE_IPV6 WHERE DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.ASSETINTERFACE_MACADDRESS WHERE DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);;
Delete from CORE.ASSETINTERFACE_NETBIOSNAME WHERE DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.TEMP_SINGLE_ASSETINTERFACE where DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.VULMASTER where DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.VULPLUGINS_MASTER where DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
Delete from CORE.ASSET where DW_ASSET_ID IN (select DISTINCT DW_ASSET_ID from CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1);
COMMIT;

BEGIN TRANSACTION;
--
-- Write to ASSET_LOG all assets that have been deleted.
-- This is needed for audit purposes.
--
INSERT INTO CORE.ASSET_LOG (DW_ASSET_ID,COMMENTS,INSERT_DATE)
SELECT DW_ASSET_ID,(''Logical deletion: '' || DELETIONREASON),CURRENT_TIMESTAMP
FROM CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 0;

RECORD_COUNT := SQLROWCOUNT;
Msg := ''Logical Asset deletions='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

INSERT INTO CORE.ASSET_LOG (DW_ASSET_ID,COMMENTS,INSERT_DATE)
SELECT DW_ASSET_ID,(''Physical deletion: '' || DELETIONREASON),CURRENT_TIMESTAMP
FROM CORE.TEMP_ASSETS_TO_DELETE where IS_PHYSICAL_DELETE = 1;

RECORD_COUNT := SQLROWCOUNT;
Msg := ''Physical Asset deletions='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
COMMIT;

TRUNCATE TABLE CORE.TEMP_ASSETS_TO_DELETE; -- 240927 CR-TBD

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';