CREATE OR REPLACE PROCEDURE "SP_CRM_CREATE_ASSET_V1_TEST"("P_SNAPSHOT_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Process TEMP_HWAM data into ASSET table using unmatched records'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''CORE.SP_CRM_CREATE_ASSET_V1'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean := 0;
True boolean := 1;
UnknownDeviceType varchar := ''Unknown'';
AWS_HWAMDataStream varchar := ''AWS HWAM'';
AWS_TENABLEDataStream varchar := ''AWS VUL'';
DATACATEGORY varchar;
RECORD_COUNT NUMBER;
IS_FROM_AWS_FEED BOOLEAN;
ASSETS_CREATED number;

BEGIN

select DATACATEGORY,IS_FROM_AWS_FEED into :DATACATEGORY,:IS_FROM_AWS_FEED FROM CORE.SNAPSHOT_IDS where SNAPSHOT_ID = :P_SNAPSHOT_ID;
Appl := :Appl || ''('' || DATACATEGORY || '')''; -- This helps to clarify which VUL we are processing
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);


BEGIN TRANSACTION;
--
-- 240826 CR-TBD Separate create of Asset using DATACENTER_ID,ASSET_ID_TATTOO
--
INSERT INTO CORE.ASSET (
	ASSET_ID_TATTOO
	,AWS_ACCOUNTID
	,AWS_INSTANCESTATUS
	,BIGFIX_ASSET_ID
	,BIOS_GUID
	,COMPUTER_TYPE
    ,CREATEDBY_SNAPSHOT_ID
    ,CREATEDBY_TEMP_DW_ASSET_ID -- 240705 CR928
 	,DATACENTER_ID
	,DATEDELETED
	,DATEMODIFIED
	,DELETIONREASON
    ,DEVICEMODEL
    ,DEVICETYPE
	,ENVIRONMENT
	,INSERT_DATE
	,IS_APPLICABLE
    ,IS_FORESCOUT_MANAGED -- 240730 CR931
	,IS_FROM_AWS_FEED
	,IS_PRIMARY_FISMA_ID_DERIVED
	,IS_SCANNABLE
	,IS_TATTOOABLE
    ,IS_TENABLE_CREDENTIALED_SCAN -- 240730 CR931
	,LAST_CONFIRMED_TIME
	,LASTASSETUPDATE
    ,MODIFIEDBY_SNAPSHOT_ID
    ,MODIFIEDBY_TEMP_DW_ASSET_ID -- 240705 CR928   
	,MOTHERBOARD
	,OS
    ,OS_BUILD_NUMBER -- 240821 CR958
	,PREV_DATEDELETED 
	,PREV_LAST_CONFIRMED_TIME
	,SOURCE_TOOL_CREATE
	,SOURCE_TOOL_LASTSEEN
	,SYSTEM_ID
	,TENABLEUUID
	,VULNRISKTOLERANCE
)
SELECT
	src.ASSET_ID_TATTOO
	,src.AWS_ACCOUNTID
	,src.AWS_INSTANCESTATUS
	,NULL -- BIGFIX_ASSET_ID
	,NULL -- BIOS_GUID
	,src.COMPUTER_TYPE
    ,:P_SNAPSHOT_ID
    ,src.MAX_TEMP_DW_ASSET_ID -- 240705 CR928 CREATEDBY_TEMP_DW_ASSET_ID
	,src.DATACENTER_ID
	,NULL -- DATEDELETED
	,NULL -- DATEMODIFIED
	,NULL -- DELETIONREASON,
    ,src.DEVICEMODEL
    ,coalesce(src.DEVICE_TYPE,:UnknownDeviceType) -- DEVICETYPE
	,src.ENVIRONMENT
	,CURRENT_TIMESTAMP() -- INSERT_DATE 
	,TRUE -- IS_APPLICABLE
    ,coalesce(src.IS_FORESCOUT_MANAGED,0) -- 240730 CR931
 	,:IS_FROM_AWS_FEED
	,FALSE -- IS_PRIMARY_FISMA_ID_DERIVED
	,FALSE -- IS_SCANNABLE
	,FALSE -- IS_TATTOOABLE
    ,coalesce(src.IS_TENABLE_CREDENTIALED_SCAN,0) -- 240730 CR931
	,src.LAST_CONFIRMED_TIME
	,CURRENT_TIMESTAMP() -- LASTASSETUPDATE
    ,:P_SNAPSHOT_ID -- 230927 MODIFIEDBY_SNAPSHOT_ID
    ,src.MAX_TEMP_DW_ASSET_ID -- 240705 CR928 MODIFIEDBY_TEMP_DW_ASSET_ID 
	,src.MOTHERBOARD
	,src.OS
    ,src.OS_BUILD_NUMBER -- 240821 CR958
 	,null -- PREV_DATEDELETED 
 	,''1900-01-01 01:00''::datetime -- PREV_LAST_CONFIRMED_TIME
	,src.SOURCE_TOOL -- SOURCE_TOOL_CREATE
	,src.SOURCE_TOOL -- SOURCE_TOOL_LASTSEEN
	,src.SYSTEM_ID
	,src.TENABLEUUID
	,0 -- VULNRISKTOLERANCE
FROM (
SELECT th.ASSET_ID_TATTOO
	,th.AWS_ACCOUNTID
	,th.INSTANCESTATUS as AWS_INSTANCESTATUS
	,th.COMPUTER_TYPE
	,th.DATACENTER_ID
    ,th.DEVICEMODEL
    ,th.DEVICE_TYPE
	,th.ENVIRONMENT
    ,th.IS_FORESCOUT_MANAGED -- 240730 CR931
    ,th.IS_TENABLE_CREDENTIALED_SCAN -- 240730 CR931
	,th.LAST_CONFIRMED_TIME
	,th.MOTHERBOARD
	,th.OS
    ,th.OS_BUILD_NUMBER -- 240821 CR958
    ,th.TEMP_DW_ASSET_ID
	,th.SOURCE_TOOL
	,th.SYSTEM_ID
    ,th.TENABLEUUID
FROM CORE.TEMP_HWAM th
JOIN (select rank()over(partition by r1.DATACENTER_ID,r1.ASSET_ID_TATTOO order by r1.LAST_CONFIRMED_TIME desc,r1.TEMP_HWAM_ID desc) TheRank,r1.TEMP_HWAM_ID
        FROM CORE.TEMP_HWAM r1
        JOIN (select DISTINCT DATACENTER_ID,ASSET_ID_TATTOO 
            FROM CORE.TEMP_HWAM 
            WHERE snapshot_id = :P_SNAPSHOT_ID and ASSET_ID_TATTOO IS NOT NULL) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.ASSET_ID_TATTOO = r1.ASSET_ID_TATTOO
        WHERE r1.snapshot_id = :P_SNAPSHOT_ID and r1.ASSET_ID_TATTOO IS NOT NULL) r2 
        where r2.TheRank = 1 and r2.TEMP_HWAM_ID = th.TEMP_HWAM_ID and th.SNAPSHOT_ID = :P_SNAPSHOT_ID and th.DW_ASSET_ID IS NULL) src;
    
ASSETS_CREATED := SQLROWCOUNT;
Msg := ''ASSET (ASSET_ID_TATTOO) Insert='' || :ASSETS_CREATED;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;


--------------

BEGIN TRANSACTION;

INSERT INTO CORE.ASSET (
	ASSET_ID_TATTOO
	,AWS_ACCOUNTID
	,AWS_INSTANCESTATUS
	,BIGFIX_ASSET_ID
	,BIOS_GUID
	,COMPUTER_TYPE
    ,CREATEDBY_SNAPSHOT_ID
    ,CREATEDBY_TEMP_DW_ASSET_ID -- 240705 CR928
 	,DATACENTER_ID
	,DATEDELETED
	,DATEMODIFIED
	,DELETIONREASON
    ,DEVICEMODEL
    ,DEVICETYPE
	,ENVIRONMENT
	,INSERT_DATE
	,IS_APPLICABLE
    ,IS_FORESCOUT_MANAGED -- 240730 CR931
	,IS_FROM_AWS_FEED
	,IS_PRIMARY_FISMA_ID_DERIVED
	,IS_SCANNABLE
	,IS_TATTOOABLE
    ,IS_TENABLE_CREDENTIALED_SCAN -- 240730 CR931
	,LAST_CONFIRMED_TIME
	,LASTASSETUPDATE
    ,MODIFIEDBY_SNAPSHOT_ID
    ,MODIFIEDBY_TEMP_DW_ASSET_ID -- 240705 CR928   
	,MOTHERBOARD
	,OS
    ,OS_BUILD_NUMBER -- 240821 CR958
	,PREV_DATEDELETED 
	,PREV_LAST_CONFIRMED_TIME
	,SOURCE_TOOL_CREATE
	,SOURCE_TOOL_LASTSEEN
	,SYSTEM_ID
	,TENABLEUUID
	,VULNRISKTOLERANCE
)
SELECT
	src.ASSET_ID_TATTOO
	,src.AWS_ACCOUNTID
	,src.AWS_INSTANCESTATUS
	,NULL -- BIGFIX_ASSET_ID
	,NULL -- BIOS_GUID
	,src.COMPUTER_TYPE
    ,:P_SNAPSHOT_ID
    ,src.MAX_TEMP_DW_ASSET_ID -- 240705 CR928 CREATEDBY_TEMP_DW_ASSET_ID
	,src.DATACENTER_ID
	,NULL -- DATEDELETED
	,NULL -- DATEMODIFIED
	,NULL -- DELETIONREASON,
    ,src.DEVICEMODEL
    ,coalesce(src.DEVICE_TYPE,:UnknownDeviceType) -- DEVICETYPE
	,src.ENVIRONMENT
	,CURRENT_TIMESTAMP() -- INSERT_DATE 
	,TRUE -- IS_APPLICABLE
    ,coalesce(src.IS_FORESCOUT_MANAGED,0) -- 240730 CR931
 	,:IS_FROM_AWS_FEED
	,FALSE -- IS_PRIMARY_FISMA_ID_DERIVED
	,FALSE -- IS_SCANNABLE
	,FALSE -- IS_TATTOOABLE
    ,coalesce(src.IS_TENABLE_CREDENTIALED_SCAN,0) -- 240730 CR931
	,src.LAST_CONFIRMED_TIME
	,CURRENT_TIMESTAMP() -- LASTASSETUPDATE
    ,:P_SNAPSHOT_ID -- 230927 MODIFIEDBY_SNAPSHOT_ID
    ,src.MAX_TEMP_DW_ASSET_ID -- 240705 CR928 MODIFIEDBY_TEMP_DW_ASSET_ID 
	,src.MOTHERBOARD
	,src.OS
    ,src.OS_BUILD_NUMBER -- 240821 CR958
 	,null -- PREV_DATEDELETED 
 	,''1900-01-01 01:00''::datetime -- PREV_LAST_CONFIRMED_TIME
	,src.SOURCE_TOOL -- SOURCE_TOOL_CREATE
	,src.SOURCE_TOOL -- SOURCE_TOOL_LASTSEEN
	,src.SYSTEM_ID
	,src.TENABLEUUID
	,0 -- VULNRISKTOLERANCE
FROM (
SELECT DISTINCT
	ASSET_ID_TATTOO
	,AWS_ACCOUNTID
	,INSTANCESTATUS as AWS_INSTANCESTATUS
	,COMPUTER_TYPE
	,DATACENTER_ID
    ,DEVICEMODEL
    ,DEVICE_TYPE
	,ENVIRONMENT
    ,IS_FORESCOUT_MANAGED -- 240730 CR931
    ,IS_TENABLE_CREDENTIALED_SCAN -- 240730 CR931
	,MAX(TO_TIMESTAMP_LTZ(LAST_CONFIRMED_TIME)) as LAST_CONFIRMED_TIME
	,MOTHERBOARD
	,OS
    ,OS_BUILD_NUMBER -- 240821 CR958
    ,MAX(TEMP_DW_ASSET_ID) as MAX_TEMP_DW_ASSET_ID
	,SOURCE_TOOL
	,SYSTEM_ID
    ,TENABLEUUID
FROM CORE.TEMP_HWAM
where SNAPSHOT_ID = :P_SNAPSHOT_ID and DW_ASSET_ID IS NULL -- 240621 CR930 and ASSET_ID_TATTOO IS NULL
group by ASSET_ID_TATTOO
	,AWS_ACCOUNTID
	,INSTANCESTATUS
	,COMPUTER_TYPE
	,DATACENTER_ID
    ,DEVICEMODEL
    ,DEVICE_TYPE
	,ENVIRONMENT
    ,IS_FORESCOUT_MANAGED -- 240730 CR931
    ,IS_TENABLE_CREDENTIALED_SCAN -- 240730 CR931
	,MOTHERBOARD
	,OS
    ,OS_BUILD_NUMBER -- 240821 CR958
    ,SOURCE_TOOL
	,SYSTEM_ID
    ,TENABLEUUID) src;
    
ASSETS_CREATED := SQLROWCOUNT;
Msg := ''ASSET Insert='' || :ASSETS_CREATED;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;

BEGIN TRANSACTION; -- 240501
--
-- Update TEMP_HWAM with newly created DW_ASSET_ID
--
UPDATE TEMP_HWAM upd
set DW_ASSET_ID = a.DW_ASSET_ID
,DATEMODIFIED = current_timestamp()
,MATCHMETHOD = :Appl -- 240501 1441 to help diagnostics
FROM TEMP_HWAM th
JOIN ASSET a on a.MODIFIEDBY_SNAPSHOT_ID = th.SNAPSHOT_ID and a.MODIFIEDBY_TEMP_DW_ASSET_ID = th.TEMP_DW_ASSET_ID
WHERE upd.TEMP_HWAM_ID = th.TEMP_HWAM_ID and upd.DW_ASSET_ID IS NULL;

RECORD_COUNT := SQLROWCOUNT;

If (:RECORD_COUNT = ASSETS_CREATED) THEN
    BEGIN
    Msg := ''TEMP_HWAM was updated with DW_ASSET_ID of new assets='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
ELSE
    BEGIN
    Msg := ''WARNING: Updated TEMP_HWAM.DW_ASSET_ID differs from Assets Created(Delta)='' || (ASSETS_CREATED - :RECORD_COUNT);
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF;
COMMIT; -- 240501

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';