CREATE OR REPLACE PROCEDURE "SP_CRM_DELETE_DUPLICATE_ASSETS"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Delete duplicate assets'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_DELETE_DUPLICATE_ASSETS'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean := 0;
True boolean := 1;
RECORD_COUNT NUMBER;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);
--
--
-- Since there can be overlap when determining duplicates we will execute SP_CRM_DELETE_ASSET after each population is found
--
--
BEGIN TRANSACTION;
--
-- Search for duplicate DATACENTER_ID/ASSET_ID_TATTOO pairs
-- Rank(1) is most current
-- Delete the Asset record if created after 240905 (when CR974 was completed)
--
INSERT INTO CORE.TEMP_ASSETS_TO_DELETE (DW_ASSET_ID,DELETIONREASON,INSERT_DATE,IS_PHYSICAL_DELETE)
SELECT r2.DW_ASSET_ID,''Duplicate DATACENTER_ID/ASSET_ID_TATTOO pair(Created after CR974)'',CURRENT_TIMESTAMP,1
    FROM (select rank()over(partition by r1.DATACENTER_ID,r1.ASSET_ID_TATTOO order by r1.insert_date asc) TheRank,r1.DW_ASSET_ID,r1.INSERT_DATE
        FROM CORE.ASSET r1
        JOIN (select DATACENTER_ID,ASSET_ID_TATTOO 
        FROM CORE.ASSET WHERE ASSET_ID_TATTOO is not null
        GROUP BY DATACENTER_ID,ASSET_ID_TATTOO
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.ASSET_ID_TATTOO = r1.ASSET_ID_TATTOO) r2 
where r2.TheRank > 1 and r2.insert_date::date > ''2024-09-05''::date;
    
RECORD_COUNT := SQLROWCOUNT;
COMMIT;

If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Duplicate DATACENTER_ID/ASSET_ID_TATTOO(After CR974)='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_DELETE_ASSET();
    END;
END IF; 

BEGIN TRANSACTION;
--
-- Search for duplicate DATACENTER_ID/ASSET_ID_TATTOO pairs
-- Rank(1) is oldest
--
INSERT INTO CORE.TEMP_ASSETS_TO_DELETE (DW_ASSET_ID,DELETIONREASON,INSERT_DATE,IS_PHYSICAL_DELETE)
SELECT r2.DW_ASSET_ID,''Duplicate DATACENTER_ID/ASSET_ID_TATTOO pair'',CURRENT_TIMESTAMP,1
    FROM (select rank()over(partition by r1.DATACENTER_ID,r1.ASSET_ID_TATTOO order by r1.DW_ASSET_ID desc) TheRank,r1.DW_ASSET_ID
        FROM CORE.ASSET r1
        JOIN (select DATACENTER_ID,ASSET_ID_TATTOO 
        FROM CORE.ASSET WHERE ASSET_ID_TATTOO is not null
        GROUP BY DATACENTER_ID,ASSET_ID_TATTOO
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.ASSET_ID_TATTOO = r1.ASSET_ID_TATTOO) r2 where r2.TheRank > 1;
    
RECORD_COUNT := SQLROWCOUNT;
COMMIT;

If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Duplicate DATACENTER_ID/ASSET_ID_TATTOO='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_DELETE_ASSET();
    END;
END IF; 

BEGIN TRANSACTION;
--
-- Search for duplicate DATACENTER_ID/NORMALIZED_FQDN pairs, retaining Asset record that has ASSET_ID_TATTOO
-- Rank(1) is most current
--
INSERT INTO CORE.TEMP_ASSETS_TO_DELETE (DW_ASSET_ID,DELETIONREASON,INSERT_DATE,IS_PHYSICAL_DELETE)
SELECT r2.DW_ASSET_ID,''Duplicate DATACENTER_ID/NORMALIZED_FQDN pair, retain ASSET_ID_TATTOO'',CURRENT_TIMESTAMP,1
    FROM (select rank()over(partition by r1.DATACENTER_ID,f1.NORMALIZED_FQDN order by r1.LAST_CONFIRMED_TIME desc, r1.DW_ASSET_ID desc) TheRank,r1.DW_ASSET_ID,r1.ASSET_ID_TATTOO
        FROM CORE.ASSET r1
        JOIN ASSETINTERFACE_FQDN f1 on f1.dw_asset_id = r1.dw_asset_id
        JOIN (select a.DATACENTER_ID,f0.NORMALIZED_FQDN 
            FROM CORE.ASSET a
            JOIN ASSETINTERFACE_FQDN f0 on f0.dw_asset_id = a.dw_asset_id
        GROUP BY a.DATACENTER_ID,f0.NORMALIZED_FQDN
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.NORMALIZED_FQDN = f1.NORMALIZED_FQDN) r2 
where r2.TheRank > 1 and r2.ASSET_ID_TATTOO is null;

RECORD_COUNT := SQLROWCOUNT;
COMMIT;

If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Duplicate DATACENTER_ID/NORMALIZED_FQDN(retain ASSET_ID_TATTOO)='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_DELETE_ASSET();
    END;
END IF; 

BEGIN TRANSACTION;
--
-- Search for duplicate DATACENTER_ID/NORMALIZED_FQDN pairs
-- Since we already deleted the duplicate FQDN while retaining ASSET_ID_TATTOO we now want to delete any FQDN 
-- AWS (56FFF52E-175B-4E48-9B38-669C8BC74899) is exempt
-- Q-NET (DB0B74DC-610A-4D35-B645-B16059B5D64A) is exempt
-- AWS GovCloud (5d8a99a8db672340f99cfd721f96190d) is exempt
--
-- Rank(1) is oldest
--
INSERT INTO CORE.TEMP_ASSETS_TO_DELETE (DW_ASSET_ID,DELETIONREASON,INSERT_DATE,IS_PHYSICAL_DELETE)
SELECT r2.DW_ASSET_ID,''Duplicate DATACENTER_ID/NORMALIZED_FQDN pair'',CURRENT_TIMESTAMP,1
    FROM (select rank()over(partition by r1.DATACENTER_ID,f1.NORMALIZED_FQDN order by r1.LAST_CONFIRMED_TIME desc, r1.DW_ASSET_ID desc) TheRank,r1.DW_ASSET_ID
        FROM CORE.ASSET r1
        JOIN ASSETINTERFACE_FQDN f1 on f1.dw_asset_id = r1.dw_asset_id
        JOIN (select a.DATACENTER_ID,f0.NORMALIZED_FQDN 
            FROM CORE.ASSET a
            JOIN ASSETINTERFACE_FQDN f0 on f0.dw_asset_id = a.dw_asset_id
        WHERE a.DATACENTER_ID NOT IN (''56FFF52E-175B-4E48-9B38-669C8BC74899'',''5d8a99a8db672340f99cfd721f96190d'',''DB0B74DC-610A-4D35-B645-B16059B5D64A'')
        GROUP BY a.DATACENTER_ID,f0.NORMALIZED_FQDN
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.NORMALIZED_FQDN = f1.NORMALIZED_FQDN) r2 
where r2.TheRank > 1;

RECORD_COUNT := SQLROWCOUNT;
COMMIT;

If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Duplicate DATACENTER_ID/NORMALIZED_FQDN='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_DELETE_ASSET();
    END;
END IF; 

BEGIN TRANSACTION;
--
-- Search for duplicate DATACENTER_ID/NORMALIZED_HOSTNAME pairs, retaining Asset record that has ASSET_ID_TATTOO
-- AWS (56FFF52E-175B-4E48-9B38-669C8BC74899) is exempt
-- Q-NET (DB0B74DC-610A-4D35-B645-B16059B5D64A) is exempt
-- AWS GovCloud (5d8a99a8db672340f99cfd721f96190d) is exempt
--
-- TheRank > 0 is to obtain all duplicates
--
INSERT INTO CORE.TEMP_ASSETS_TO_DELETE (DW_ASSET_ID,DELETIONREASON,INSERT_DATE,IS_PHYSICAL_DELETE)
SELECT r2.DW_ASSET_ID,''Duplicate DATACENTER_ID/NORMALIZED_HOSTNAME pair, retain ASSET_ID_TATTOO'',CURRENT_TIMESTAMP,1
    FROM (select rank()over(partition by r1.DATACENTER_ID,f1.NORMALIZED_HOSTNAME order by r1.LAST_CONFIRMED_TIME desc, r1.DW_ASSET_ID desc) TheRank,r1.DW_ASSET_ID,r1.ASSET_ID_TATTOO
        FROM CORE.ASSET r1
        JOIN ASSETINTERFACE_HOSTNAME f1 on f1.dw_asset_id = r1.dw_asset_id
        JOIN (select a.DATACENTER_ID,f0.NORMALIZED_HOSTNAME 
            FROM CORE.ASSET a
            JOIN ASSETINTERFACE_HOSTNAME f0 on f0.dw_asset_id = a.dw_asset_id
            where a.DATACENTER_ID NOT IN (''56FFF52E-175B-4E48-9B38-669C8BC74899'',''5d8a99a8db672340f99cfd721f96190d'',''DB0B74DC-610A-4D35-B645-B16059B5D64A'')
        GROUP BY a.DATACENTER_ID,f0.NORMALIZED_HOSTNAME
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.NORMALIZED_HOSTNAME = f1.NORMALIZED_HOSTNAME) r2 
where r2.TheRank > 1 and r2.ASSET_ID_TATTOO is null;

RECORD_COUNT := SQLROWCOUNT;
COMMIT;

If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Duplicate DATACENTER_ID/NORMALIZED_HOSTNAME='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_DELETE_ASSET();
    END;
END IF;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';