CREATE OR REPLACE PROCEDURE "SP_CRM_CHECK_ASSETS"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Check for asset issues e.g. duplicates'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_CHECK_ASSETS'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
TheRowCount NUMBER := 0;
False boolean := 0;
True boolean := 1;
RECORD_COUNT NUMBER;
RECORDS_WITH_ERRORS NUMBER;
RECORDS_WITH_WARNINGS NUMBER;
ERROR_COUNT NUMBER;
WARNING_COUNT NUMBER;
SNAPSHOT_ID NUMBER;
DATACATEGORY VARCHAR;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

TRUNCATE TABLE CORE.TEMP_ASSET_ISSUE;


BEGIN TRANSACTION;
-- Search for duplicate DATACENTER_ID/ASSET_ID_TATTOO pairs
-- Oldest is Rank=1
INSERT INTO CORE.TEMP_ASSET_ISSUE(DW_ASSET_ID,INSERT_DATE,ISSUE_MSG)
SELECT r2.DW_ASSET_ID,CURRENT_TIMESTAMP,''Duplicate DATACENTER_ID/ASSET_ID_TATTOO pair''
    FROM (select rank()over(partition by r1.DATACENTER_ID,r1.ASSET_ID_TATTOO order by r1.DW_ASSET_ID desc) TheRank,r1.DW_ASSET_ID
        FROM CORE.ASSET r1
        JOIN (select DATACENTER_ID,ASSET_ID_TATTOO 
        FROM CORE.ASSET WHERE ASSET_ID_TATTOO is not null
        GROUP BY DATACENTER_ID,ASSET_ID_TATTOO
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.ASSET_ID_TATTOO = r1.ASSET_ID_TATTOO) r2 where r2.TheRank > 1;
    
RECORD_COUNT := SQLROWCOUNT;
If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Duplicate DATACENTER_ID/ASSET_ID_TATTOO='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF; 
COMMIT;

BEGIN TRANSACTION;
-- Search for duplicate DATACENTER_ID/NORMALIZED_FQDN pairs
-- Retain Asset record that has ASSET_ID_TATTOO
INSERT INTO CORE.TEMP_ASSET_ISSUE(DW_ASSET_ID,INSERT_DATE,ISSUE_MSG)
SELECT r2.DW_ASSET_ID,CURRENT_TIMESTAMP,''Duplicate DATACENTER_ID/NORMALIZED_FQDN pair''
    FROM (select rank()over(partition by r1.DATACENTER_ID,f1.NORMALIZED_FQDN order by r1.LAST_CONFIRMED_TIME desc, r1.DW_ASSET_ID desc) TheRank,r1.DW_ASSET_ID,r1.ASSET_ID_TATTOO
        FROM CORE.ASSET r1
        JOIN ASSETINTERFACE_FQDN f1 on f1.dw_asset_id = r1.dw_asset_id
        JOIN (select a.DATACENTER_ID,f0.NORMALIZED_FQDN 
            FROM CORE.ASSET a
            JOIN ASSETINTERFACE_FQDN f0 on f0.dw_asset_id = a.dw_asset_id
        GROUP BY a.DATACENTER_ID,f0.NORMALIZED_FQDN
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.NORMALIZED_FQDN = f1.NORMALIZED_FQDN) r2 
where r2.TheRank > 1 and r2.ASSET_ID_TATTOO is null;

RECORD_COUNT := SQLROWCOUNT;
If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Duplicate DATACENTER_ID/NORMALIZED_FQDN='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF; 
COMMIT;


/***********
BEGIN TRANSACTION;
-- Search for duplicate DATACENTER_ID/NORMALIZED_HOSTNAME pairs
INSERT INTO CORE.TEMP_ASSET_ISSUE(DW_ASSET_ID,INSERT_DATE,ISSUE_MSG)
SELECT r2.DW_ASSET_ID,CURRENT_TIMESTAMP,''Duplicate (Active) DATACENTER_ID/NORMALIZED_HOSTNAME pair''
    FROM (select rank()over(partition by r1.DATACENTER_ID,f1.NORMALIZED_HOSTNAME order by r1.LAST_CONFIRMED_TIME desc,r1.DW_ASSET_ID desc) TheRank,r1.LAST_CONFIRMED_TIME,r1.DW_ASSET_ID
        FROM CORE.ASSET r1
        JOIN ASSETINTERFACE_HOSTNAME f1 on f1.dw_asset_id = r1.dw_asset_id
        JOIN (select a.DATACENTER_ID,f0.NORMALIZED_HOSTNAME 
            FROM CORE.ASSET a
            JOIN ASSETINTERFACE_HOSTNAME f0 on f0.dw_asset_id = a.dw_asset_id
            WHERE a.IS_APPLICABLE = 1
        GROUP BY a.DATACENTER_ID,f0.NORMALIZED_HOSTNAME
        HAVING count(1) > 1) d on d.DATACENTER_ID = r1.DATACENTER_ID and d.NORMALIZED_HOSTNAME = f1.NORMALIZED_HOSTNAME and r1.IS_APPLICABLE = 1) r2 where r2.TheRank > 1;

RECORD_COUNT := SQLROWCOUNT;
If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Duplicate DATACENTER_ID/NORMALIZED_HOSTNAME='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF;
COMMIT;
**************/

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';