CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_SYSTEMSAWSACCOUNTS"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull list of AWS account IDs associated with the FISMA ID'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_PULL_SYSTEMSAWSACCOUNTS'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
TheRowCount NUMBER := 0;
BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

select count(1) into :TheRowCount FROM REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS;
-- 230801 select count(1) into :TheRowCount FROM REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS; -- 230811 RBAC for DBLOOKUPS

IF (TheRowCount = 0) THEN
	BEGIN
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,''WARNING: REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS is empty'');
    END;
ELSE
    BEGIN
    BEGIN TRANSACTION;

    TRUNCATE TABLE CORE.SYSTEMSAWSACCOUNTS;
    
    Insert into CORE.SYSTEMSAWSACCOUNTS (AWS_ACCOUNTID,	INSERT_DATE, SYSTEM_ID)
    select ACCOUNT_NUMBER,CURRENT_TIMESTAMP(),FISMA 
    from REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS WHERE FISMA IS NOT NULL and ACCOUNT_NUMBER IS NOT NULL; --230801 as per Naseem
    -- 230801 from REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS WHERE FISMA IS NOT NULL and ACCOUNT_NUMBER IS NOT NULL;
    
    COMMIT;
    END;
END IF;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';