CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_MAG_VUL_NEW"("P_DATACATEGORY" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull MAG TENABLE data into RAW_DATA table'
EXECUTE AS OWNER
AS '
--
-- 
--
declare
Appl varchar := ''SP_CRM_PULL_MAG_VUL_NEW'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
Datacategory varchar;
PreviousPullDatetime TIMESTAMP_LTZ(9);
SNAPSHOT_ID number;
RECORD_COUNT number;
MIN_DATE TIMESTAMP_LTZ(9);
MAX_DATE TIMESTAMP_LTZ(9);

/**********************************************************************************
SELECT DISTINCT IP
,ARRAY_TO_STRING(ARRAY_DISTINCT(STRTOK_TO_ARRAY(IPS,'','')),'','') as DISTINCT_IPS 
FROM RAW_TENABLE_VUL WHERE NULLIF(IP,'''') <> NULLIF(DISTINCT_IPS,'''')
ZERO ROWS SO IPS FIELD IS NOT NEEDED
**********************************************************************************/

BEGIN
Datacategory := :P_DATACATEGORY;

Appl := :Appl || ''('' || :Datacategory || '')'';
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

/*
CALL CORE.SP_CRM_GENERATE_SNAPSHOT_ID(:Datacategory);
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(:Datacategory);

PreviousPullDatetime := (select PARMDATE FROM CORE.CONFIG where PARMNAME = :Datacategory);
*/

SNAPSHOT_ID := (day(current_date()) || hour(current_timestamp()) || minute(current_timestamp()))::number;
Msg := ''Test SNAPSHOT_ID='' || :SNAPSHOT_ID;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

PreviousPullDatetime := ((current_date() - 1)::date || '' 00:01'')::timestamp;


Msg := ''Previous pull of '' || :Datacategory || ''='' || :PreviousPullDatetime;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

IF (:Datacategory NOT IN (''MAG VUL'',''MAG VUL MITIGATED'')) THEN
    BEGIN
    ExceptionMsg := ''Datacategory cannot be used in this SP'';
    raise CRM_logic_exception;
    END;
END IF;

IF (:Datacategory = ''MAG VUL'') THEN
    BEGIN
    BEGIN TRANSACTION;
    
    INSERT INTO CORE.RAW_DATA(
    ACCEPT_RISK_RULE_COMMENT
	,ACCEPTRISK
	,ACRSCORE
	,APPLICABILITYCODE
	,ASSET_ID_TATTOO
	,ASSETEXPOSURESCORE
    ,AZURE_SUBSCRIPTION_ID
	,BASESCORE
	,BID
	,CHECKTYPE
	,CPE
--	,CREDENTIALED_SCAN
	,CVE
	,CVSSV2BASESCORE
	,CVSSV3BASESCORE
	,CVSSV3TEMPORALSCORE
	,CVSSV3VECTOR
	,CVSSVECTOR
	,DATA_ERROR_ARRAY
	,DATA_WARNING_ARRAY
	,DATACENTER_ID
	,DESCRIPTION
	,EXPLOIT_AVAILABLE
	,EXPLOITEASE
	,EXPLOITFRAMEWORKS
	,FAMILY_ID
	,FAMILY_NAME
	,FAMILY_TYPE
	,FIRST_SEEN
	,FQDN
	,HAS_BEEN_MITIGATED
	,HOSTUNIQUENESS
	,HOSTUUID
	,INSERT_DATE
	,IP
	,KEYDRIVERS
	,LAST_SEEN
	,MACADDRESS
	,MITIGATIONSTATUS
	,NETBIOSNAME
	,NUMERIC_SEVERITY
    ,FISMASEVERITY -- Placed here for convenience
	,OS
	,PATCHPUB_DATE
	,PLUGIN_ID
	,PLUGIN_INFO
	,PLUGIN_MOD_DATE
	,PLUGIN_NAME
	,PLUGIN_PUB_DATE
	,PLUGINTEXT
	,PORT
--	,PRIMARY_FISMA_ID_DERIVED
	,PROTOCOL
	,RECASTRISK
	,RECASTRISKRULECOMMENT
	,REPORTDATE
	,REPOSITORY_DATAFORMAT
	,REPOSITORY_DESCRIPTION
	,REPOSITORY_ID
	,REPOSITORY_NAME
	,RISKFACTOR
	,ROWDISPOSITION
	,SEEALSO
	,SEVERITY_DESCRIPTION
	,SEVERITY_ID
	,SEVERITY_NAME
	,SNAPSHOT_ID
	,SOLUTION
	,SOURCE_TOOL
	,STIGSEVERITY
	,SYNOPSIS
	,SYSTEM_ID
	,TEMPORAL_SCORE
	,TENABLEUUID
	,UNIQUENESS
	,VERSION
	,VPR_SCORE
	,VPRCONTEXT
	,VULN_PUB_DATE
    ,VULNUNIQUENESS -- IUSG
    ,VULNUUID -- IUSG
	,XREF
) 
    SELECT
    v.ACCEPT_RISK_RULE_COMMENT
	,v.ACCEPTRISK
	,v.ACRSCORE
    ,CORE.FN_CRM_GET_INDICATOR_INITIAL() as APPLICABILITYCODE
	,v.ASSET_ID_TATTOO
	,v.ASSETEXPOSURESCORE
    ,v.SUBSCRIPTION_ID as AZURE_SUBSCRIPTION_ID
    ,coalesce(NULLIF(v.BASESCORE,''''),''0'')::NUMBER(38,1) as BASESCORE
	,v.BID
	,v.CHECKTYPE
	,v.CPE
--	,v.CREDENTIALED_SCAN
	,v.CVE
    ,coalesce(NULLIF(v.BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV2BASESCORE
    ,coalesce(NULLIF(v.CVSSV3BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV3BASESCORE
	,v.CVSSV3TEMPORALSCORE
	,v.CVSSV3VECTOR
	,v.CVSSVECTOR
    ,ARRAY_CONSTRUCT() as DATA_ERROR_ARRAY
    ,ARRAY_CONSTRUCT() as DATA_WARNING_ARRAY
    ,coalesce(v.REPOSITORY_DESCRIPTION,''FECCCA8B-8161-4E0A-ACA7-788ED45EB9EE'') as DATACENTER_ID -- SEC_VW_FISMA_LOOKUPS_MAG should have DATACENTER_ID but is NULL
	,v.DESCRIPTION
	,v.EXPLOIT_AVAILABLE
	,v.EXPLOITEASE
	,v.EXPLOITFRAMEWORKS
	,v.FAMILY_ID
	,v.FAMILY_NAME
	,v.FAMILY_TYPE
	,v.FIRST_SEEN
    ,STRTOK_TO_ARRAY(NULLIF(v.DNSNAME,''''),'','') as FQDN
    ,v.HAS_BEEN_MITIGATED::boolean as HAS_BEEN_MITIGATED
	,v.HOSTUNIQUENESS
	,v.HOSTUUID
    ,CURRENT_TIMESTAMP() as INSERT_DATE
	,v.IP
	-- ,v.IPS
	,v.KEYDRIVERS 
	,v.LAST_SEEN
    ,STRTOK_TO_ARRAY(NULLIF(v.MACADDRESS,''''),'','') as MACADDRESS
    ,case HAS_BEEN_MITIGATED
        when 1 then CORE.FN_CRM_GET_MITIGATIONSTATUS_REOPENED()
        Else CORE.FN_CRM_GET_MITIGATIONSTATUS_OPEN()
    End as MITIGATIONSTATUS
    ,STRTOK_TO_ARRAY(NULLIF(v.NETBIOSNAME,''''),'','') as NETBIOSNAME
    ,v.FN_NUMERIC_SEVERITY
    ,CORE.FN_CRM_CHARACTER_SEVERITY(v.FN_NUMERIC_SEVERITY) as FISMASEVERITY -- Placed here for convenience
	,v.OPERATING_SYSTEM
    ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PATCHPUB_DATE) as PATCHPUB_DATE
	,v.PLUGIN_ID
	,v.PLUGIN_INFO
    ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PLUGIN_MOD_DATE) as PLUGIN_MOD_DATE
	,v.PLUGIN_NAME
    ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PLUGIN_PUB_DATE) as PLUGIN_PUB_DATE
	,v.PLUGINTEXT
	,v.PORT
--	,v.PRIMARY_FISMA_ID
	,v.PROTOCOL
	,v.RECASTRISK
	,v.RECASTRISKRULECOMMENT
	,v.REPORTDATE
	,v.REPOSITORY_DATAFORMAT
	,v.REPOSITORY_DESCRIPTION
	,v.REPOSITORY_ID
	,v.REPOSITORY_NAME
	,v.RISKFACTOR
    ,CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() as ROWDISPOSITION
	-- ,v.SCAN_POLICY_NAME
	-- ,v.SCAN_POLICY_UID
    -- ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.SCAN_START_DATE) as SCAN_START_DATE
	,v.SEEALSO
	,v.SEVERITY_DESCRIPTION
	,v.SEVERITY_ID
	,v.SEVERITY_NAME
    ,:SNAPSHOT_ID
	,v.SOLUTION
    ,''Tenable'' as SOURCE_TOOL
	,v.STIGSEVERITY
	,v.SYNOPSIS
    ,v.SYSTEM_ID -- IUSG
	,v.TEMPORAL_SCORE
    ,v.UUID as TENABLEUUID
	,v.UNIQUENESS
    ,v.VERSION
	,v.VPR_SCORE
	,v.VPRCONTEXT
    ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.VULN_PUB_DATE) as VULN_PUB_DATE
    ,v.VULNUNIQUENESS -- IUSG
    ,v.VULNUUID -- IUSG
	,v.XREF
    FROM (SELECT
    mag.ACCEPT_RISK_RULE_COMMENT
	,mag.ACCEPTRISK
	,mag.ACRSCORE
    ,mag.name as ASSET_ID_TATTOO -- 241022 discussion with Greg Beck indicates this should be reliable as a distinct value
   	,mag.ASSETEXPOSURESCORE
	,mag.BASESCORE
	,mag.BID
	,mag.CHECKTYPE
	,mag.CPE
--	,mag.CREDENTIALED_SCAN
	,mag.CVE
	,mag.CVSSV3BASESCORE
	,mag.CVSSV3TEMPORALSCORE
	,mag.CVSSV3VECTOR
	,mag.CVSSVECTOR
    ,mag.DESCRIPTION
	,mag.DNSNAME
	,mag.EXPLOIT_AVAILABLE
	,mag.EXPLOITEASE
	,mag.EXPLOITFRAMEWORKS
	,mag.FAMILY_ID
	,mag.FAMILY_NAME
	,mag.FAMILY_TYPE
	,mag.FIRST_SEEN
	,mag.HAS_BEEN_MITIGATED
	,mag.HOSTUNIQUENESS
	,mag.HOSTUUID
	,mag.IP
	,mag.IPS
	,mag.KEYDRIVERS 
	,mag.LAST_SEEN
	,mag.MACADDRESS
	,mag.NETBIOSNAME
    ,CORE.FN_CRM_NUMERIC_SEVERITY(''3.0'',mag.CVSSV3BASESCORE) as FN_NUMERIC_SEVERITY
	,mag.OPERATING_SYSTEM
	,mag.PATCHPUB_DATE
	,mag.PLUGIN_ID
	,mag.PLUGIN_INFO
	,mag.PLUGIN_MOD_DATE
	,mag.PLUGIN_NAME
	,mag.PLUGIN_PUB_DATE
	,mag.PLUGINTEXT
	,mag.PORT
--	,mag.PRIMARY_FISMA_ID
	,mag.PROTOCOL
	,mag.RECASTRISK
	,mag.RECASTRISKRULECOMMENT
	,mag.S3_FILE_CREATE as REPORTDATE -- IUSG differs from CCIC
	,mag.REPOSITORY_DATAFORMAT
	,mag.REPOSITORY_DESCRIPTION
	,mag.REPOSITORY_ID
	,mag.REPOSITORY_NAME
	,mag.RISKFACTOR
--	,mag.SCAN_POLICY_NAME
--	,mag.SCAN_POLICY_UID
--	,mag.SCAN_START_DATE
	,mag.SEEALSO
	,mag.SEVERITY_DESCRIPTION
	,mag.SEVERITY_ID
	,mag.SEVERITY_NAME
	,mag.SOLUTION
	,mag.STIGSEVERITY
	,mag.SYNOPSIS
    ,coalesce(NULLIF(lu.FISMA,''''),''SUBSCRIPTION_ID is not in SEC_VW_FISMA_LOOKUPS_MAG'') as SYSTEM_ID
    ,mag.SUBSCRIPTION_ID
   	,mag.TEMPORAL_SCORE
	,mag.UNIQUENESS
	,mag.UUID
	,mag.VERSION
	,mag.VPR_SCORE
    ,STRTOK_TO_ARRAY(mag.VPRCONTEXT,'','') as VPRCONTEXT -- IUSG differs from CCIC
	,mag.VULN_PUB_DATE
    ,mag.VULNUNIQUENESS -- IUSG
    ,mag.VULNUUID -- IUSG
	,mag.XREF
    --
    -- OTHER MAG COLUMNS NOT USED AT THIS TIME
    --
    -- DNS_SERVERS -- SPARSE
    -- FILENAME -- NOT NEEDED BUT CONSIDER ADDING TO NEW (SINGLE) RAW_DATA TABLE
    -- INSTANCEID -- ALWAYS EMPTY
    -- IP_CONFIGURATIONS -- EXPLORE -- HAS FQDN WHICH HAS NOT BEEN OTHERWISE PARSED
    -- MACADDRESS -- MAC_ADDRESS appears to be of more value. This is sparse and does not always match MAC_ADDRESS
    -- MAG_INSTANCE_IP_ADDRESS -- MIGHT BE IMPORTANT
    -- NAME -- COMPARE TO SUBSCRIPTION_ID; APPEARS TO BE HOSTNAME
    -- NETWORK_INTERFACE_ID -- EXPLORE
    -- split_part(NETWORK_INTERFACE_ID,''/'',3) as NETWORK_INTERFACE_ID_SUBSCRIPTION_ID 
    -- split_part(NETWORK_INTERFACE_ID,''/'',5)
    -- split_part(NETWORK_INTERFACE_ID,''/'',9)
    -- NETWORK_PRIMARY –- TRUE/FALSE/NULL
    -- RAW_VULNS -- DON’T NEED RAW DATA
    -- SF_FILE_LOAD -- NOT NEEDED
    -- TYPE -- Always: Microsoft.Network/networkInterfaces
    -- VIRTUAL_MACHINE_ID -- Not always populated
    -- VULNUNIQUENESS -- NOT NEEDED
    -- VULNUUID -- ALWAYS EMPTY
    FROM APP_TENABLE.SHARED.SEC_VW_IUSG_MAG_CUMULATIVE_VULNS mag
    --
    -- Need to use upper function because of case issues in Tenable data
    --
    LEFT OUTER JOIN REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS_MAG lu on upper(lu.account_number) = upper(mag.SUBSCRIPTION_ID)
    WHERE mag.S3_FILE_CREATE > :PreviousPullDatetime
    and (
    FN_NUMERIC_SEVERITY > 0 -- 241105 CR1024 filter-out Informational records
    or mag.PLUGIN_ID = ''19506'' -- 240128 CR1076 reinstate plugin which was excluded under CR1024
    )  
    ) v;

    RECORD_COUNT := SQLROWCOUNT;

    COMMIT;
    END;
ELSE -- MAG VUL MITITGATED
    BEGIN
    BEGIN TRANSACTION;
    
    INSERT INTO CORE.RAW_DATA(
    ACCEPT_RISK_RULE_COMMENT
	,ACCEPTRISK
	,ACRSCORE
	,APPLICABILITYCODE
	,ASSET_ID_TATTOO
	,ASSETEXPOSURESCORE
    ,AZURE_SUBSCRIPTION_ID
	,BASESCORE
	,BID
	,CHECKTYPE
	,CPE
--	,CREDENTIALED_SCAN
	,CVE
	,CVSSV2BASESCORE
	,CVSSV3BASESCORE
	,CVSSV3TEMPORALSCORE
	,CVSSV3VECTOR
	,CVSSVECTOR
	,DATA_ERROR_ARRAY
	,DATA_WARNING_ARRAY
	,DATACENTER_ID
	,DESCRIPTION
	,EXPLOIT_AVAILABLE
	,EXPLOITEASE
	,EXPLOITFRAMEWORKS
	,FAMILY_ID
	,FAMILY_NAME
	,FAMILY_TYPE
	,FIRST_SEEN
	,FQDN
	,HAS_BEEN_MITIGATED
	,HOSTUNIQUENESS
	,HOSTUUID
	,INSERT_DATE
	,IP
	,KEYDRIVERS
	,LAST_SEEN
	,MACADDRESS
	,MITIGATIONSTATUS
	,NETBIOSNAME
	,NUMERIC_SEVERITY
    ,FISMASEVERITY -- Placed here for convenience
	,OS
	,PATCHPUB_DATE
	,PLUGIN_ID
	,PLUGIN_INFO
	,PLUGIN_MOD_DATE
	,PLUGIN_NAME
	,PLUGIN_PUB_DATE
	,PLUGINTEXT
	,PORT
--	,PRIMARY_FISMA_ID_DERIVED
	,PROTOCOL
	,RECASTRISK
	,RECASTRISKRULECOMMENT
	,REPORTDATE
	,REPOSITORY_DATAFORMAT
	,REPOSITORY_DESCRIPTION
	,REPOSITORY_ID
	,REPOSITORY_NAME
	,RISKFACTOR
	,ROWDISPOSITION
	,SEEALSO
	,SEVERITY_DESCRIPTION
	,SEVERITY_ID
	,SEVERITY_NAME
	,SNAPSHOT_ID
	,SOLUTION
	,SOURCE_TOOL
	,STIGSEVERITY
	,SYNOPSIS
	,SYSTEM_ID
	,TEMPORAL_SCORE
	,TENABLEUUID
	,UNIQUENESS
	,VERSION
	,VPR_SCORE
	,VPRCONTEXT
	,VULN_PUB_DATE
    ,VULNUNIQUENESS -- IUSG
    ,VULNUUID -- IUSG
	,XREF
) 
    SELECT
    v.ACCEPT_RISK_RULE_COMMENT
	,v.ACCEPTRISK
	,v.ACRSCORE
    ,CORE.FN_CRM_GET_INDICATOR_INITIAL() as APPLICABILITYCODE
	,v.ASSET_ID_TATTOO
	,v.ASSETEXPOSURESCORE
    ,v.SUBSCRIPTION_ID as AZURE_SUBSCRIPTION_ID
    ,coalesce(NULLIF(v.BASESCORE,''''),''0'')::NUMBER(38,1) as BASESCORE
	,v.BID
	,v.CHECKTYPE
	,v.CPE
--	,v.CREDENTIALED_SCAN
	,v.CVE
    ,coalesce(NULLIF(v.BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV2BASESCORE
    ,coalesce(NULLIF(v.CVSSV3BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV3BASESCORE
	,v.CVSSV3TEMPORALSCORE
	,v.CVSSV3VECTOR
	,v.CVSSVECTOR
    ,ARRAY_CONSTRUCT() as DATA_ERROR_ARRAY
    ,ARRAY_CONSTRUCT() as DATA_WARNING_ARRAY
    ,coalesce(v.REPOSITORY_DESCRIPTION,''FECCCA8B-8161-4E0A-ACA7-788ED45EB9EE'') as DATACENTER_ID -- SEC_VW_FISMA_LOOKUPS_MAG should have DATACENTER_ID but is NULL
	,v.DESCRIPTION
	,v.EXPLOIT_AVAILABLE
	,v.EXPLOITEASE
	,v.EXPLOITFRAMEWORKS
	,v.FAMILY_ID
	,v.FAMILY_NAME
	,v.FAMILY_TYPE
	,v.FIRST_SEEN
    ,STRTOK_TO_ARRAY(NULLIF(v.DNSNAME,''''),'','') as FQDN
    ,v.HAS_BEEN_MITIGATED::boolean as HAS_BEEN_MITIGATED
	,v.HOSTUNIQUENESS
	,v.HOSTUUID
    ,CURRENT_TIMESTAMP() as INSERT_DATE
	,v.IP
	-- ,v.IPS
	,v.KEYDRIVERS 
	,v.LAST_SEEN
    ,STRTOK_TO_ARRAY(NULLIF(v.MACADDRESS,''''),'','') as MACADDRESS
    ,case HAS_BEEN_MITIGATED
        when 1 then CORE.FN_CRM_GET_MITIGATIONSTATUS_REOPENED()
        Else CORE.FN_CRM_GET_MITIGATIONSTATUS_OPEN()
    End as MITIGATIONSTATUS
    ,STRTOK_TO_ARRAY(NULLIF(v.NETBIOSNAME,''''),'','') as NETBIOSNAME
    ,v.FN_NUMERIC_SEVERITY
    ,CORE.FN_CRM_CHARACTER_SEVERITY(v.FN_NUMERIC_SEVERITY) as FISMASEVERITY -- Placed here for convenience
	,v.OPERATING_SYSTEM
    ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PATCHPUB_DATE) as PATCHPUB_DATE
	,v.PLUGIN_ID
	,v.PLUGIN_INFO
    ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PLUGIN_MOD_DATE) as PLUGIN_MOD_DATE
	,v.PLUGIN_NAME
    ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.PLUGIN_PUB_DATE) as PLUGIN_PUB_DATE
	,v.PLUGINTEXT
	,v.PORT
--	,v.PRIMARY_FISMA_ID
	,v.PROTOCOL
	,v.RECASTRISK
	,v.RECASTRISKRULECOMMENT
	,v.REPORTDATE
	,v.REPOSITORY_DATAFORMAT
	,v.REPOSITORY_DESCRIPTION
	,v.REPOSITORY_ID
	,v.REPOSITORY_NAME
	,v.RISKFACTOR
    ,CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() as ROWDISPOSITION
	-- ,v.SCAN_POLICY_NAME
	-- ,v.SCAN_POLICY_UID
    -- ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.SCAN_START_DATE) as SCAN_START_DATE
	,v.SEEALSO
	,v.SEVERITY_DESCRIPTION
	,v.SEVERITY_ID
	,v.SEVERITY_NAME
    ,:SNAPSHOT_ID
	,v.SOLUTION
    ,''Tenable'' as SOURCE_TOOL
	,v.STIGSEVERITY
	,v.SYNOPSIS
    ,v.SYSTEM_ID -- IUSG
	,v.TEMPORAL_SCORE
    ,v.UUID as TENABLEUUID
	,v.UNIQUENESS
    ,v.VERSION
	,v.VPR_SCORE
	,v.VPRCONTEXT
    ,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(v.VULN_PUB_DATE) as VULN_PUB_DATE
    ,v.VULNUNIQUENESS -- IUSG
    ,v.VULNUUID -- IUSG
	,v.XREF
    FROM (SELECT
    mag.ACCEPT_RISK_RULE_COMMENT
	,mag.ACCEPTRISK
	,mag.ACRSCORE
    ,mag.name as ASSET_ID_TATTOO -- 241022 discussion with Greg Beck indicates this should be reliable as a distinct value
   	,mag.ASSETEXPOSURESCORE
	,mag.BASESCORE
	,mag.BID
	,mag.CHECKTYPE
	,mag.CPE
--	,mag.CREDENTIALED_SCAN
	,mag.CVE
	,mag.CVSSV3BASESCORE
	,mag.CVSSV3TEMPORALSCORE
	,mag.CVSSV3VECTOR
	,mag.CVSSVECTOR
    ,mag.DESCRIPTION
	,mag.DNSNAME
	,mag.EXPLOIT_AVAILABLE
	,mag.EXPLOITEASE
	,mag.EXPLOITFRAMEWORKS
	,mag.FAMILY_ID
	,mag.FAMILY_NAME
	,mag.FAMILY_TYPE
	,mag.FIRST_SEEN
	,mag.HAS_BEEN_MITIGATED
	,mag.HOSTUNIQUENESS
	,mag.HOSTUUID
	,mag.IP
	,mag.IPS
	,mag.KEYDRIVERS 
	,mag.LAST_SEEN
	,mag.MACADDRESS
	,mag.NETBIOSNAME
    ,CORE.FN_CRM_NUMERIC_SEVERITY(''3.0'',mag.CVSSV3BASESCORE) as FN_NUMERIC_SEVERITY
	,mag.OPERATING_SYSTEM
	,mag.PATCHPUB_DATE
	,mag.PLUGIN_ID
	,mag.PLUGIN_INFO
	,mag.PLUGIN_MOD_DATE
	,mag.PLUGIN_NAME
	,mag.PLUGIN_PUB_DATE
	,mag.PLUGINTEXT
	,mag.PORT
--	,mag.PRIMARY_FISMA_ID
	,mag.PROTOCOL
	,mag.RECASTRISK
	,mag.RECASTRISKRULECOMMENT
	,mag.S3_FILE_CREATE as REPORTDATE -- IUSG differs from CCIC
	,mag.REPOSITORY_DATAFORMAT
	,mag.REPOSITORY_DESCRIPTION
	,mag.REPOSITORY_ID
	,mag.REPOSITORY_NAME
	,mag.RISKFACTOR
--	,mag.SCAN_POLICY_NAME
--	,mag.SCAN_POLICY_UID
--	,mag.SCAN_START_DATE
	,mag.SEEALSO
	,mag.SEVERITY_DESCRIPTION
	,mag.SEVERITY_ID
	,mag.SEVERITY_NAME
	,mag.SOLUTION
	,mag.STIGSEVERITY
	,mag.SYNOPSIS
    ,coalesce(NULLIF(lu.FISMA,''''),''SUBSCRIPTION_ID is not in SEC_VW_FISMA_LOOKUPS_MAG'') as SYSTEM_ID
    ,mag.SUBSCRIPTION_ID
   	,mag.TEMPORAL_SCORE
	,mag.UNIQUENESS
	,mag.UUID
	,mag.VERSION
	,mag.VPR_SCORE
    ,STRTOK_TO_ARRAY(mag.VPRCONTEXT,'','') as VPRCONTEXT -- IUSG differs from CCIC
	,mag.VULN_PUB_DATE
    ,mag.VULNUNIQUENESS -- IUSG
    ,mag.VULNUUID -- IUSG
	,mag.XREF
    --
    -- OTHER MAG COLUMNS NOT USED AT THIS TIME
    --
    -- DNS_SERVERS -- SPARSE
    -- FILENAME -- NOT NEEDED BUT CONSIDER ADDING TO NEW (SINGLE) RAW_DATA TABLE
    -- INSTANCEID -- ALWAYS EMPTY
    -- IP_CONFIGURATIONS -- EXPLORE -- HAS FQDN WHICH HAS NOT BEEN OTHERWISE PARSED
    -- MACADDRESS -- MAC_ADDRESS appears to be of more value. This is sparse and does not always match MAC_ADDRESS
    -- MAG_INSTANCE_IP_ADDRESS -- MIGHT BE IMPORTANT
    -- NAME -- COMPARE TO SUBSCRIPTION_ID; APPEARS TO BE HOSTNAME
    -- NETWORK_INTERFACE_ID -- EXPLORE
    -- split_part(NETWORK_INTERFACE_ID,''/'',3) as NETWORK_INTERFACE_ID_SUBSCRIPTION_ID 
    -- split_part(NETWORK_INTERFACE_ID,''/'',5)
    -- split_part(NETWORK_INTERFACE_ID,''/'',9)
    -- NETWORK_PRIMARY –- TRUE/FALSE/NULL
    -- RAW_VULNS -- DON’T NEED RAW DATA
    -- SF_FILE_LOAD -- NOT NEEDED
    -- TYPE -- Always: Microsoft.Network/networkInterfaces
    -- VIRTUAL_MACHINE_ID -- Not always populated
    -- VULNUNIQUENESS -- NOT NEEDED
    -- VULNUUID -- ALWAYS EMPTY
    FROM APP_TENABLE.SHARED.SEC_VW_IUSG_MAG_MITIGATED_VULNS mag
    --
    -- Need to use upper function because of case issues in Tenable data
    --
    LEFT OUTER JOIN REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS_MAG lu on upper(lu.account_number) = upper(mag.SUBSCRIPTION_ID)
    WHERE mag.S3_FILE_CREATE > :PreviousPullDatetime
    and FN_NUMERIC_SEVERITY > 0 -- 241105 CR1024 filter-out Informational records
    ) v;

    RECORD_COUNT := SQLROWCOUNT;

    COMMIT;
    END; 
END IF;


IF (:RECORD_COUNT = 0) THEN
	BEGIN
	Msg := ''WARNING: There is no data for this snapshot'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
ELSE
    BEGIN
    Msg := :Datacategory || '' inserted into RAW_DATA='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF;

MIN_DATE := (select MIN(LAST_SEEN) FROM CORE.RAW_DATA WHERE SNAPSHOT_ID = :SNAPSHOT_ID);
MAX_DATE := (select MAX(LAST_SEEN) FROM CORE.RAW_DATA WHERE SNAPSHOT_ID = :SNAPSHOT_ID);

BEGIN TRANSACTION;

UPDATE CORE.SNAPSHOT_IDS
set MIN_DATE = :MIN_DATE
,MAX_DATE = :MAX_DATE
,RECORD_COUNT = coalesce(:RECORD_COUNT,0)
 where SNAPSHOT_ID = :SNAPSHOT_ID;

/***************** COMMENT WHILE TESTING
UPDATE CORE.CONFIG
set PARMDATE = :MAX_DATE
where PARMNAME = :Datacategory and :MAX_DATE IS NOT NULL;
***************************************************************/
Msg := ''WARNING: Update of CORE.CONFIG disabled while testing'';
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';