CREATE OR REPLACE PROCEDURE "SP_CRM_LOAD_VULPLUGIN"("P_SNAPSHOT_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Load/Update VULPLUGIN table'
EXECUTE AS OWNER
AS '
declare
Appl varchar := ''SP_CRM_LOAD_VULPLUGIN'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
ApplicabilityCode_Actionable varchar := ''Actionable'';
DATACATEGORY VARCHAR;
RECORD_COUNT number;

BEGIN
select DATACATEGORY into :DATACATEGORY FROM CORE.SNAPSHOT_IDS where SNAPSHOT_ID = :P_SNAPSHOT_ID;
Appl := :Appl || ''('' || DATACATEGORY || '')''; -- This helps to clarify which VUL we are processing
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

Msg := ''WARNING: DECOMMISSION THIS SP ONCE VULPLUGIN TABLE HAS BEEN DECOMMISSION'';
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

BEGIN TRANSACTION;

MERGE INTO CORE.VULPLUGIN as target
USING (SELECT
DISTINCT -- 230821 0948
r.DESCRIPTION
,vm.DW_VUL_ID
,r.FAMILY_NAME
,vm.LASTFOUND
,r.PATCHPUB_DATE
,r.PLUGIN_ID
,r.PLUGIN_INFO
,r.PLUGIN_MOD_DATE
,r.PLUGIN_NAME
,r.PLUGIN_PUB_DATE
,r.SOLUTION
,r.SYNOPSIS
,r.VERSION
,r.VULN_PUB_DATE

from VW_VULMASTER vm
join RAW_TENABLE_VUL r on r.dw_asset_id = vm.dw_asset_id
join table(flatten(r.cve,outer=>true)) as f
where f.value::string is not null
and f.value::string = vm.CVE
and r.SNAPSHOT_ID = :P_SNAPSHOT_ID
and r.APPLICABILITYCODE = :ApplicabilityCode_Actionable

) as src 

ON (src.DW_VUL_ID = target.DW_VUL_ID and src.PLUGIN_ID = target.PLUGIN_ID)

WHEN MATCHED THEN UPDATE SET 
target.DESCRIPTION = src.DESCRIPTION
,target.FAMILY_NAME = src.FAMILY_NAME
,target.LASTFOUND = src.LASTFOUND
,target.PATCHPUB_DATE = src.PATCHPUB_DATE
,target.PLUGIN_INFO = src.PLUGIN_INFO
,target.PLUGIN_MOD_DATE = src.PLUGIN_MOD_DATE
,target.PLUGIN_NAME = src.PLUGIN_NAME
,target.PLUGIN_PUB_DATE = src.PLUGIN_PUB_DATE
,target.SOLUTION = src.SOLUTION
,target.SYNOPSIS = src.SYNOPSIS
,target.VERSION = src.VERSION
,target.VULN_PUB_DATE = src.VULN_PUB_DATE

WHEN NOT MATCHED THEN INSERT (
DESCRIPTION
,DW_VUL_ID
,FAMILY_NAME
,INSERT_DATE
,LASTFOUND
,PATCHPUB_DATE
,PLUGIN_ID
,PLUGIN_INFO
,PLUGIN_MOD_DATE
,PLUGIN_NAME
,PLUGIN_PUB_DATE
,SOLUTION
,SYNOPSIS
,VERSION
,VULN_PUB_DATE
)
VALUES (
src.DESCRIPTION
,src.DW_VUL_ID
,src.FAMILY_NAME
,CURRENT_TIMESTAMP() -- INSERT_DATE
,src.LASTFOUND
,src.PATCHPUB_DATE
,src.PLUGIN_ID
,src.PLUGIN_INFO
,src.PLUGIN_MOD_DATE
,src.PLUGIN_NAME
,src.PLUGIN_PUB_DATE
,src.SOLUTION
,src.SYNOPSIS
,src.VERSION
,src.VULN_PUB_DATE
);

--Msg := ''Merge ASSETINTERFACE_FQDN complete'';
--CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END;
';