CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_AWS_HWAM_V2"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull AWS HWAM data into RAW_HWAM table'
EXECUTE AS OWNER
AS '
--
-- 
--
declare
Appl varchar := ''SP_CRM_PULL_AWS_HWAM_V2'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
Datacategory varchar := ''AWS HWAM'';
PreviousPullDatetime TIMESTAMP_LTZ(9);
SNAPSHOT_ID number;
RECORD_COUNT number;
MIN_DATE TIMESTAMP_LTZ(9);
MAX_DATE TIMESTAMP_LTZ(9);

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

CALL CORE.SP_CRM_GENERATE_SNAPSHOT_ID(:Datacategory);
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(:Datacategory);

PreviousPullDatetime := (select PARMDATE FROM CORE.CONFIG where PARMNAME = :Datacategory);

Msg := ''Previous pull of '' || :Datacategory || ''='' || :PreviousPullDatetime;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

BEGIN TRANSACTION;
  
insert into CORE.RAW_HWAM (
ASSET_ID_TATTOO
,AWS_ACCOUNTID
,AWS_DATACENTER_ID
,AWS_PRIMARY_FISMA_ID_TATTOO
,AWS_INSTANCE_ID
,COMPUTER_TYPE
,DATA_ERROR_ARRAY
,DATA_WARNING_ARRAY
,DATACENTER_ID
,DEVICE_TYPE
,ENVIRONMENT
,FISMA_UUID
,FQDN
,HOSTNAME
,INSERT_DATE
,INSTANCESTATUS
,IPV4
,IPV6
,IS_FS_MANAGED
,IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC
,LAST_CONFIRMED_TIME
,MACADDRESS
,MOTHERBOARD
,NETBIOSNAME
,OS
,OS_VERSION
,PRIMARY_FISMA_ID_DERIVED
,REPORTDATE
,ROWDISPOSITION
,SNAPSHOT_ID
,SOURCE_TOOL
,SYSTEM_ACRONYM
,SYSTEM_ID
)
--
-- USING SYSTEM_ID MULTIPLE TIMES NEEDS TO BE ELIMIMINATED
--
select
src.ASSET_ID_TATTOO
,src.AWS_ACCOUNTID
,src.AWS_DATACENTER_ID
,src.AWS_PRIMARY_FISMA_ID_TATTOO
,src.AWS_INSTANCE_ID
,src.COMPUTER_TYPE
,ARRAY_CONSTRUCT() as DATA_ERROR_ARRAY
,ARRAY_CONSTRUCT() as DATA_WARNING_ARRAY
,src.DATACENTER_ID
,src.DEVICE_TYPE
,src.ENVIRONMENT
,src.FISMA_UUID
,STRTOK_TO_ARRAY(src.FQDN,'','') as FQDN
,src.HOSTNAME
,CURRENT_TIMESTAMP() as INSERT_DATE
,src.INSTANCESTATUS
,src.IPV4
,src.IPV6
,0 as IS_FS_MANAGED
,0 as IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC -- Initialize
,src.LAST_CONFIRMED_TIME
,src.MACADDRESS
,src.MOTHERBOARD
,src.NETBIOSNAME
,src.OS
,src.OS_VERSION
,src.PRIMARY_FISMA_ID_DERIVED
,src.REPORTDATE
,CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() as ROWDISPOSITION
,:SNAPSHOT_ID as SNAPSHOT_ID
,src.SOURCE_TOOL
,src.SYSTEM_ACRONYM
,src.SYSTEM_ID
FROM
(
SELECT 
h.INSTANCEID as ASSET_ID_TATTOO
,h.ACCOUNT_NUMBER as AWS_ACCOUNTID
,h.DATACENTER_ID as AWS_DATACENTER_ID -- 240725 CR928
,h.SYSTEM_ID as AWS_PRIMARY_FISMA_ID_TATTOO
,h.INSTANCEID as AWS_INSTANCE_ID
,h.COMPUTER_TYPE
,h.DATACENTER_ID -- 240725 CR928
,h.DEVICE_TYPE
,h.ENVIRONMENT
,h.FISMA_UUID
,h.FQDN
,h.HOSTNAME
,h.INSTANCESTATUS
,h.IPV4
,h.IPV6
,h.LAST_CONFIRMED_TIME
,h.MAC as MACADDRESS
,h.MOTHERBOARD_SN as MOTHERBOARD
,h.NETBIOS_HN as NETBIOSNAME
,h.OS
,h.OS_VERSION
,h.SYSTEM_ID as PRIMARY_FISMA_ID_DERIVED -- -- 240528 CR901 see AWS_PRIMARY_FISMA_ID_TATTOO above
,h.REPORT_TIME as REPORTDATE
,h.SOURCE_TOOL
,h.SYSTEM_ACRONYM
,h.SYSTEM_ID -- 240725 CR928
FROM CORE.VW_HWAM_AWS_V2 h -- 240725 CR928
JOIN CORE.VW_SYSTEMS dc on dc.SYSTEM_ID = h.DATACENTER_ID -- 240726 CR928
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = h.SYSTEM_ID -- 240726 CR928
WHERE NULLIF(h.INSTANCEID,'','') IS NOT NULL -- 240726 CR928

UNION ALL

SELECT 
h.INSTANCEID as ASSET_ID_TATTOO
,h.ACCOUNT_NUMBER as AWS_ACCOUNTID
,h.DATACENTER_ID as AWS_DATACENTER_ID
,h.FISMA_ID as AWS_PRIMARY_FISMA_ID_TATTOO
,h.INSTANCEID as AWS_INSTANCE_ID
,h.COMPUTER_TYPE
,h.DATACENTER_ID::varchar as DATACENTER_ID -- 240725 CR928
,h.DEVICE_TYPE
,h.ENVIRONMENT
,NULL as FISMA_UUID
,h.FQDN
,STRTOK_TO_ARRAY(h.HOSTNAME,'','') as HOSTNAME
,h.INSTANCESTATUS
,h.IPV4
,h.IPV6
,h.REPORT_TIME::datetime as LAST_CONFIRMED_TIME
,h.MAC as MACADDRESS
,NULL as MOTHERBOARD
,NULL as NETBIOSNAME
,h.OS
,h.OS_VERSION
,h.FISMA_ID as PRIMARY_FISMA_ID_DERIVED
,h.REPORT_TIME::datetime as REPORTDATE
,h.SOURCE_TOOL
,h.SYSTEM_ACRONYM
,h.FISMA_ID as SYSTEM_ID
FROM APP_CDM.SHARED.SEC_VW_HWAM_CCSQ h
JOIN CORE.VW_SYSTEMS dc on dc.SYSTEM_ID = h.DATACENTER_ID
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = h.FISMA_ID
WHERE NULLIF(h.INSTANCEID,'','') IS NOT NULL
) src;

RECORD_COUNT := SQLROWCOUNT;

IF (:RECORD_COUNT = 0) THEN
	BEGIN
	Msg := ''WARNING: There is no HWAM data for this snapshot'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
ELSE
    BEGIN
    Msg := :Datacategory || '' inserted into RAW_HWAM='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF;

MIN_DATE := (select MIN(LAST_CONFIRMED_TIME) FROM APP_CDM.SHARED.SEC_VW_HWAM_AWS);  -- RBAC 20230803/20230808
MAX_DATE := (select MAX(LAST_CONFIRMED_TIME) FROM APP_CDM.SHARED.SEC_VW_HWAM_AWS);  -- RBAC 20230803/20230808

If (:RECORD_COUNT > 0) THEN -- 240726 prefixed RECORD_COUNT with colon
    BEGIN
    update CORE.CONFIG
    set PARMDATE = :MAX_DATE
    where PARMNAME = :Datacategory and :MAX_DATE IS NOT NULL;
    END;
End if;

UPDATE CORE.SNAPSHOT_IDS
set MIN_DATE = :MIN_DATE
,MAX_DATE = :MAX_DATE
,RECORD_COUNT = coalesce(:RECORD_COUNT,0)
 where SNAPSHOT_ID = :SNAPSHOT_ID;
 
COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';