CREATE OR REPLACE PROCEDURE "SP_CRM_INITIATE"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Initialize CRM database by generating a REPORT_ID (snapshot identifier) and pull fundamental data like CFACTS'
EXECUTE AS OWNER
AS '

DECLARE
Appl varchar := ''SP_CRM_INITIATE'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
REPORT_ID number;
RECORD_COUNT NUMBER;
BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

--ExceptionMsg := ''Test Alert Monitoring''; 
--raise CRM_logic_exception;

CALL CORE.SP_CRM_GENERATE_REPORT_ID();
REPORT_ID := (SELECT MAX(REPORT_ID) FROM CORE.REPORT_IDS); -- 240418 1326 CR873 New REPORT_ID is set IS_VIABLE = FALSE by default

CALL CORE.SP_CRM_PULL_CFACTS(:REPORT_ID);
CALL CORE.SP_CRM_UPDATE_PRIMARY_OP_LOC();
CALL CORE.SP_CRM_PULL_SYSTEMSAWSACCOUNTS();

If (hour(current_timestamp()) between 2 and 6) then -- 231108 WORKAROUND TO PREVENT PRE-MATURE DELETIONS OF ASSETS WHEN PROCESS IS RE-RUN IN THE SAME DAY
    BEGIN
    BEGIN TRANSACTION; -- 230703 PREV_LAST_CONFIRMED_TIME is used in SP_CRM_ASSETAGING

    UPDATE CORE.ASSET 
    set PREV_LAST_CONFIRMED_TIME = LAST_CONFIRMED_TIME
    ,PREV_SYSTEM_ID = SYSTEM_ID; -- 240926 CR-TBD Needed for diagnostics

    RECORD_COUNT := SQLROWCOUNT;
    Msg := ''ASSET.PREV_LAST_CONFIRMED_TIME set='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

    COMMIT;
    END;
Else
	BEGIN
	Msg := ''Outside normal run-time, ASSET.PREV_LAST_CONFIRMED_TIME not updated'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
	END;
END IF;


TRUNCATE TABLE CORE.TEMP_ASSETS_TO_DELETE; -- 240816
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,''TRUNCATE TABLE CORE.TEMP_ASSETS_TO_DELETE'');

--
-- TEMP_HWAM is used by SP_CRM_LOAD_ASSET_V2 for asset matching
--
TRUNCATE TABLE CORE.TEMP_HWAM;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,''TRUNCATE TABLE CORE.TEMP_HWAM'');

TRUNCATE TABLE CORE.TEMP_ASSET_METADATA; -- 240708 CR928
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,''TRUNCATE TABLE CORE.TEMP_ASSET_METADATA''); -- 240708 CR928

TRUNCATE TABLE CORE.TEMP_ASSET_SOFTWARE; -- 240806
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,''TRUNCATE TABLE CORE.TEMP_ASSET_SOFTWARE''); -- 240806

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';