CREATE OR REPLACE PROCEDURE "SP_CRM_PREP_RAW_HWAM_V2"("P_SNAPSHOT_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Prep/Validate RAW_HWAM data'
EXECUTE AS OWNER
AS '
DECLARE
Appl varchar := ''SP_CRM_PREP_RAW_HWAM_V2'';
ExceptionMsg varchar := ''Default'';
Msg varchar;
StartOfProcedure datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
TheRowCount NUMBER := 0;
False boolean := 0;
True boolean := 1;
AXONIUS varchar := ''AXONIUS'';
FORESCOUT varchar := ''FORESCOUT''; -- 241209 CR1048
RECORD_COUNT NUMBER;
RECORDS_WITH_ERRORS NUMBER;
RECORDS_WITH_WARNINGS NUMBER;
ERROR_COUNT NUMBER;
WARNING_COUNT NUMBER;
SNAPSHOT_ID NUMBER;
DATACATEGORY VARCHAR;

--
-- As of 9/22/2023 Axonius has the following adapters
-- 1.	active_directory_adapter
-- 2.	aws_adapter
-- 3.	bigfix_adapter
-- 4.	bigfix_inventory_adapter
-- 5.	counter_act_adapter
-- 6.	crowd_strike_adapter
-- 7.	epo_adapter
-- 8.	esx_adapter
-- 9.	mssql_adapter
-- 10.	sccm_adapter
-- 11.	splunk_adapter
-- 12.	tenable_security_center_adapter
--

BEGIN
SNAPSHOT_ID := :P_SNAPSHOT_ID;
select DATACATEGORY into :DATACATEGORY FROM CORE.SNAPSHOT_IDS where SNAPSHOT_ID = :SNAPSHOT_ID;
Appl := :Appl || ''('' || DATACATEGORY || '')''; -- This helps to clarify which HWAM we are processing
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

--
-- 240730 CR942
-- Moved initialization of RAW_HWAM to respective PULL stored procedure so the fields are 
-- initialized upon write to RAW_HWAM
--

select count(1) into :TheRowCount FROM CORE.RAW_HWAM where SNAPSHOT_ID = :SNAPSHOT_ID and RowDisposition = CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE();

IF (:TheRowCount = 0) THEN
	BEGIN
	Msg := ''WARNING: There is no HWAM data for this snapshot'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
END IF;

---------------------------------------------------------------------
--
-- DETERMINE/POPULATE: DATACENTER_ID, SYSTEM_ID, ASSET_ID_TATTOO
--
---------------------------------------------------------------------


-- Determine DATACENTER_ID
-- 230620 added NULLIF
-- 240726 CR928 UPDATE CORE.RAW_HWAM
-- 240726 CR928 set DATACENTER_ID = coalesce(NULLIF(AWS_DATACENTER_ID,''''),NULLIF(TENABLE_DATACENTER_ID,''''),NULLIF(BIGFIX_DATACENTER_ID,''''))
-- 240726 CR928 where SNAPSHOT_ID = :SNAPSHOT_ID and DATACENTER_ID IS NULL;

--
-- 240424 CR879 “Integrate SecOps FISMA_UUID into SDW AWS HWAM datastream”
--
UPDATE CORE.RAW_HWAM
set SYSTEM_ID = FISMA_UUID
where SNAPSHOT_ID = :SNAPSHOT_ID and NULLIF(FISMA_UUID,'''') IS NOT NULL and SYSTEM_ID IS NULL;

RECORD_COUNT := SQLROWCOUNT;

If (RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Assigned SYSTEM_ID using FISMA_UUID='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
End if;

-- Determine SYSTEM_ID
UPDATE CORE.RAW_HWAM
set SYSTEM_ID = coalesce(NULLIF(AWS_PRIMARY_FISMA_ID_TATTOO,''''),NULLIF(TENABLE_PRIMARY_FISMA_ID_TATTOO,''''),NULLIF(BIGFIX_PRIMARY_FISMA_ID_TATTOO,''''))
where SNAPSHOT_ID = :SNAPSHOT_ID and SYSTEM_ID IS NULL;

-- Assign SYSTEM_ID (if not already assigned) based on SYSTEM_ACRONYM (Should match official value found in SYSTEMS.ACRONYM)
UPDATE CORE.RAW_HWAM
set SYSTEM_ID = s.SYSTEM_ID
FROM CORE.RAW_HWAM r
JOIN CORE.SYSTEMS s on upper(s.acronym) = upper(r.SYSTEM_ACRONYM)
where r.RAW_HWAM_ID = CORE.RAW_HWAM.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and r.SYSTEM_ID IS NULL and r.SYSTEM_ACRONYM IS NOT NULL;

-- Assign SYSTEM_ID based on COMMONNAME (if SYSTEM_ID not already assigned)
-- THE COMMONNAME FIELD IS MANUALLY MAINTAINED AND IS NOT IN A SPECIFIC CFACTS FIELD.
-- WE WILL USE THIS TO IMPROVE SYSTEM REPORTING AND TO PROVIDE DATA QUALITY WARNINGS OF ITS USE UPSTREAM
UPDATE CORE.RAW_HWAM
set SYSTEM_ID = c.SYSTEM_ID
,DATA_WARNING_ARRAY = ARRAY_APPEND(r.DATA_WARNING_ARRAY,''Used COMMONNAME lookup to find SYSTEM_ACRONYM'')
FROM CORE.RAW_HWAM r
JOIN CORE.SYSTEM_COMMONNAME c on upper(c.COMMONNAME) = upper(r.system_acronym)
where r.RAW_HWAM_ID = CORE.RAW_HWAM.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and r.SYSTEM_ID IS NULL and r.SYSTEM_ACRONYM IS NOT NULL;

RECORD_COUNT := SQLROWCOUNT;

If (RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''Assigned SYSTEM_ID using COMMONNAME lookup='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
End if;

-- Determine ASSET_ID_TATTOO
UPDATE CORE.RAW_HWAM
set ASSET_ID_TATTOO = coalesce(AWS_INSTANCE_ID,BIGFIX_ASSET_ID_TATTOO,TENABLE_ASSET_ID_TATTOO)
where SNAPSHOT_ID = :SNAPSHOT_ID and ASSET_ID_TATTOO IS NULL;

---------------------------------------------------------------------
--
-- CLEAN: DATACENTER_ID, SYSTEM_ID, ASSET_ID_TATTOO
--
---------------------------------------------------------------------

-- Clean DATACENTER_ID
UPDATE CORE.RAW_HWAM h
set DATACENTER_ID = TRIM(REPLACE(REPLACE(REPLACE(DATACENTER_ID,''"'',''''),''['',''''),'']'',''''))
where SNAPSHOT_ID = :SNAPSHOT_ID
and DATACENTER_ID IS NOT NULL and (DATACENTER_ID LIKE ''%"%'' or DATACENTER_ID LIKE ''%[%'' or DATACENTER_ID LIKE ''%]%'');

-- Clean SYSTEM_ID
UPDATE CORE.RAW_HWAM h
set SYSTEM_ID = TRIM(REPLACE(REPLACE(REPLACE(SYSTEM_ID,''"'',''''),''['',''''),'']'',''''))
where SNAPSHOT_ID = :SNAPSHOT_ID
and SYSTEM_ID IS NOT NULL and (SYSTEM_ID LIKE ''%"%'' or SYSTEM_ID LIKE ''%[%'' or SYSTEM_ID LIKE ''%]%'');

-- Clean ASSET_ID_TATTOO
UPDATE CORE.RAW_HWAM h
set ASSET_ID_TATTOO = TRIM(REPLACE(REPLACE(REPLACE(ASSET_ID_TATTOO,''"'',''''),''['',''''),'']'',''''))
where SNAPSHOT_ID = :SNAPSHOT_ID
and ASSET_ID_TATTOO IS NOT NULL and (ASSET_ID_TATTOO LIKE ''%"%'' or ASSET_ID_TATTOO LIKE ''%[%'' or ASSET_ID_TATTOO LIKE ''%]%'');

  
---------------------------------------------------------------------
--
-- VALIDATE: DATACENTER_ID, SYSTEM_ID, ASSET_ID_TATTOO
--
---------------------------------------------------------------------

-- DATACENTER_ID invalid format or length
UPDATE CORE.RAW_HWAM h
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''DATACENTER_ID has invalid format or length'')
where SNAPSHOT_ID = :SNAPSHOT_ID and DATACENTER_ID IS NOT NULL and (DATACENTER_ID LIKE ''%,%'' or LEN(DATACENTER_ID) > 36);

--
-- When a duplicate datacenter/asset_id_tattoo is found then flag record as an error.
-- This case first discovered with AWS accounts 368332260651 and 568826666399 which pertain to system BatCave
--
UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(r.DATA_ERROR_ARRAY,''Duplicate datacenter/asset_id_tattoo combination'')
FROM CORE.RAW_HWAM r
JOIN (select t.asset_id_tattoo -- 230706 added this layer
    FROM (select datacenter_id, asset_id_tattoo
        FROM CORE.RAW_HWAM
        where SNAPSHOT_ID = :SNAPSHOT_ID and NULLIF(asset_id_tattoo,'''') IS NOT NULL -- 230706 added asset_id_tattoo check
        group by datacenter_id, asset_id_tattoo
        having count(1) > 1) t
    group by t.asset_id_tattoo
    having count(1) > 1) dup on dup.asset_id_tattoo = r.asset_id_tattoo
where r.RAW_HWAM_ID = CORE.RAW_HWAM.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID;

-- DATACENTER_ID is Null or Empty
UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''Empty DATACENTER_ID'')
where SNAPSHOT_ID = :SNAPSHOT_ID and NULLIF(DATACENTER_ID,'''') IS NULL;

-- DATACENTER_ID does not exist
UPDATE CORE.RAW_HWAM upd
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(r.DATA_ERROR_ARRAY,''DATACENTER_ID does not exist'')
FROM CORE.RAW_HWAM r
LEFT OUTER JOIN CORE.SYSTEMS dc on upper(dc.system_id) = upper(r.DATACENTER_ID)
where r.RAW_HWAM_ID = upd.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and NULLIF(r.DATACENTER_ID,'''') IS NOT NULL and dc.SYSTEM_ID IS NULL;

--
-- 240917 CR981
-- When DATACENTER_ID is HIGLAS but DATACATEGORY is not AXONIUS then reject the data
--
UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''HIGLAS HWAM only permitted via AXONIUS'')
where SNAPSHOT_ID = :SNAPSHOT_ID and NULLIF(DATACENTER_ID,'''') = ''C9B9A131-F974-49BD-BBFF-1B0235747C0E'' and :DATACATEGORY <> :AXONIUS;

-- Validate SYSTEM_ACRONYM as an FYI. For the present time we also check to see if the acronym is a CommonName (not found in CFACTS)
UPDATE CORE.RAW_HWAM upd
set DATA_WARNING_ARRAY = ARRAY_APPEND(r.DATA_WARNING_ARRAY,''SYSTEM_ACRONYM does not exist'')
FROM CORE.RAW_HWAM r
LEFT OUTER JOIN CORE.SYSTEMS s on upper(s.acronym) = upper(r.SYSTEM_ACRONYM)
LEFT OUTER JOIN CORE.SYSTEM_COMMONNAME c on upper(c.COMMONNAME) = upper(r.system_acronym)
where r.RAW_HWAM_ID = upd.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and r.SYSTEM_ACRONYM IS NOT NULL and (s.SYSTEM_ID IS NULL and c.SYSTEM_ID IS NULL);

-- Check to see if BIGFIX_PRIMARY_FISMA_ID_TATTOO_DETAILS contains different FISMA_IDs
-- Note: Only distinct values are in BIGFIX_PRIMARY_FISMA_ID_TATTOO_DETAILS at this point
UPDATE CORE.RAW_HWAM
set DATA_WARNING_ARRAY = ARRAY_APPEND(DATA_WARNING_ARRAY,''BIGFIX_PRIMARY_FISMA_ID_TATTOO contains '' 
    || ARRAY_SIZE(BIGFIX_PRIMARY_FISMA_ID_TATTOO_DETAILS)::varchar || '' different values'')
where SNAPSHOT_ID = :SNAPSHOT_ID and ARRAY_SIZE(BIGFIX_PRIMARY_FISMA_ID_TATTOO_DETAILS) > 1;

-- Validate SYSTEM_ID
UPDATE CORE.RAW_HWAM upd
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(r.DATA_ERROR_ARRAY,''Invalid PRIMARY_FISMA_ID'')
FROM CORE.RAW_HWAM r
LEFT OUTER JOIN CORE.SYSTEMS s on upper(s.system_id) = upper(r.SYSTEM_ID)
where r.RAW_HWAM_ID = upd.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and r.SYSTEM_ID IS NOT NULL and s.SYSTEM_ID IS NULL;


-- Validate DRaaS-CACHE. We expect all DRaaS assets to have the tenant tag format except for non-tattooable assets like network devices
-- 240912 CR978
UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''Invalid DRaaS-CACHE ASSET_ID_TAG'')
where SNAPSHOT_ID = :P_SNAPSHOT_ID 
and DATACENTER_ID = ''441a2d4fdbfbab00560cf9531f961911''
and CORE.FN_CRM_IS_VALID_DRAAS_ASSET_ID_TATTOO(ASSET_ID_TAG) = 0;

-- 240912 CR978
UPDATE CORE.RAW_HWAM
set DATA_WARNING_ARRAY = ARRAY_APPEND(DATA_WARNING_ARRAY,''DRaaS-CACHE ASSET_ID_TAG is empty'')
where SNAPSHOT_ID = :P_SNAPSHOT_ID 
and DATACENTER_ID = ''441a2d4fdbfbab00560cf9531f961911''
and ASSET_ID_TAG IS NULL;

-- 230728
--
-- Of the available (not null) DATACENTER_IDs are they all the same regardless of sensor.
-- 
UPDATE CORE.RAW_HWAM
set DATA_WARNING_ARRAY = ARRAY_APPEND(DATA_WARNING_ARRAY,''DATACENTER_ID differs across sensors'')
where SNAPSHOT_ID = :SNAPSHOT_ID 
and ARRAY_SIZE(ARRAY_DISTINCT(ARRAY_COMPACT(ARRAY_CONSTRUCT(lower(NULLIF(AWS_DATACENTER_ID,'''')),lower(NULLIF(TENABLE_DATACENTER_ID,''''))
,lower(NULLIF(BIGFIX_DATACENTER_ID,'''')))))) > 1;

--
-- Of the available (not null) FISMA IDs are they all the same regardless of sensor.
-- Found cases where Forescout (derived FISMA ID) and Tenable (FISMA ID is tattooed on asset) have different FISMA IDs
-- 230620 1345 added NULLIF
UPDATE CORE.RAW_HWAM
set DATA_WARNING_ARRAY = ARRAY_APPEND(DATA_WARNING_ARRAY,''FISMA_ID differs across sensors'')
where SNAPSHOT_ID = :SNAPSHOT_ID 
and ARRAY_SIZE(ARRAY_DISTINCT(ARRAY_COMPACT(ARRAY_CONSTRUCT(lower(NULLIF(AWS_PRIMARY_FISMA_ID_TATTOO,'''')),lower(NULLIF(TENABLE_PRIMARY_FISMA_ID_TATTOO,''''))
,lower(NULLIF(BIGFIX_PRIMARY_FISMA_ID_TATTOO,'''')))))) > 1;

UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''Invalid ASSET_ID_TATTOO'')
where SNAPSHOT_ID = :SNAPSHOT_ID and NULLIF(ASSET_ID_TATTOO,'''') IS NOT NULL -- 240917 CR-EBF added NULLIF
and CORE.FN_CRM_IS_VALID_ASSET_ID_TATTOO(ASSET_ID_TATTOO) = FALSE;

-- 230728
--
-- Of the available (not null) ASSET_ID_TATTOOs are they all the same regardless of sensor.
-- 
UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''ASSET_ID_TATTOO differs across sensors'')
where SNAPSHOT_ID = :SNAPSHOT_ID 
and ARRAY_SIZE(ARRAY_DISTINCT(ARRAY_COMPACT(ARRAY_CONSTRUCT(lower(NULLIF(AWS_INSTANCE_ID,'''')),lower(NULLIF(TENABLE_ASSET_ID_TATTOO,''''))
,lower(NULLIF(BIGFIX_ASSET_ID_TATTOO,'''')))))) > 1;



If (:DATACATEGORY = :FORESCOUT) THEN -- 241209 CR1048
    BEGIN
    UPDATE CORE.RAW_HWAM
    set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
    ,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''Forescout has Windows AND Linux asset ID populated'')
    where SNAPSHOT_ID = :SNAPSHOT_ID 
    and NULLIF(FS_ASSET_ID_TAG_WINDOWSINST,'''') IS NOT NULL and NULLIF(FS_LINUX_ASSET_ID,'''') IS NOT NULL;   
    END;
END IF;



-- 230731
UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''No IP available'')
where SNAPSHOT_ID = :SNAPSHOT_ID and ARRAY_SIZE(IPV4) = 0 AND ARRAY_SIZE(IPV6) = 0;

-- 230927
UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''(ASSET_ID_TATTOO/FQDN/HOSTNAME/NETBIOSNAME) are null'')
where SNAPSHOT_ID = :P_SNAPSHOT_ID 
and ASSET_ID_TATTOO IS NULL and FQDN IS NULL and HOSTNAME IS NULL and NETBIOSNAME IS NULL;

-- 231214 The AWS ACCOUNTID should/must always be in the SEC_VW_FISMA_LOOKUPS
UPDATE CORE.RAW_HWAM upd
set DATA_WARNING_ARRAY = ARRAY_APPEND(r.DATA_WARNING_ARRAY,''AWS ACCOUNTID is not in SEC_VW_FISMA_LOOKUPS'')
FROM CORE.RAW_HWAM r
left outer join CORE.VW_AWS_CAMPDB_LOOKUP ref on ref.ACCOUNT_NUMBER = r.AWS_ACCOUNTID -- 240710 CR928
-- 240710 CR928 left outer join REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS ref on ref.ACCOUNT_NUMBER = r.AWS_ACCOUNTID
WHERE r.RAW_HWAM_ID = upd.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and r.AWS_ACCOUNTID IS NOT NULL and ref.ACCOUNT_NUMBER IS NULL;

-- 240726 CR928 changed from warning to error
UPDATE CORE.RAW_HWAM upd
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(r.DATA_ERROR_ARRAY,''SEC_VW_FISMA_LOOKUPS contains invalid FISMA ID('' || coalesce(NULLIF(ref.SYSTEM_ID,''''),''NULL'') || '')'') -- 240710 CR928
FROM CORE.RAW_HWAM r
join CORE.VW_AWS_CAMPDB_LOOKUP ref on ref.ACCOUNT_NUMBER = r.AWS_ACCOUNTID -- 240710 CR928
left outer join CORE.SYSTEMS s on upper(s.SYSTEM_ID) = upper(ref.SYSTEM_ID) -- 240710 CR928
WHERE r.RAW_HWAM_ID = upd.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and r.AWS_ACCOUNTID IS NOT NULL and s.SYSTEM_ID IS NULL;

-- 240728 CR928
UPDATE CORE.RAW_HWAM upd
set DATA_WARNING_ARRAY = ARRAY_APPEND(r.DATA_WARNING_ARRAY,''New DEVICETYPE found ('' || r.DEVICE_TYPE || '')'')
FROM CORE.RAW_HWAM r
left outer join CORE.DEVICETYPES dt on dt.DEVICETYPE = r.DEVICE_TYPE
WHERE r.RAW_HWAM_ID = upd.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and NULLIF(r.DEVICE_TYPE,'''') IS NOT NULL and dt.DEVICETYPE IS NULL;

-- 230627
-- SYSTEM_ID could not be assigned using system ID related data contained within the RAW_HWAM record.
-- See if MDR(Asset) record already exists and use its SYSTEM_ID
UPDATE CORE.RAW_HWAM upd
set SYSTEM_ID = a.SYSTEM_ID
,DATA_WARNING_ARRAY = ARRAY_APPEND(r.DATA_WARNING_ARRAY,''SYSTEM_ID obtained from ASSET table based on ASSET_ID_TATTOO'')
FROM CORE.RAW_HWAM r
JOIN CORE.ASSET a on a.DATACENTER_ID = r.DATACENTER_ID and a.ASSET_ID_TATTOO = r.ASSET_ID_TATTOO
where r.RAW_HWAM_ID = upd.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and r.SYSTEM_ID IS NULL;

RECORD_COUNT := SQLROWCOUNT;
Msg := ''SYSTEM_ID from ASSET table used='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

--
-- When no SYSTEM_ID is available default it to the DATACENTER_ID
--
UPDATE CORE.RAW_HWAM upd
set SYSTEM_ID = r.DATACENTER_ID
,IS_PRIMARY_FISMA_ID_DEFAULTED_TO_DC = :True
,DATA_WARNING_ARRAY = ARRAY_APPEND(r.DATA_WARNING_ARRAY,''SYSTEM_ID defaulted to DATACENTER_ID'')
FROM CORE.RAW_HWAM r
JOIN CORE.SYSTEMS dc on dc.SYSTEM_ID = r.DATACENTER_ID
where r.RAW_HWAM_ID = upd.RAW_HWAM_ID and r.SNAPSHOT_ID = :SNAPSHOT_ID and r.SYSTEM_ID IS NULL;

RECORD_COUNT := SQLROWCOUNT;

If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''SYSTEM_ID defaulted to DATACENTER_ID='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);   
    END;
END IF;

UPDATE CORE.RAW_HWAM
set ROWDISPOSITION = CORE.FN_CRM_GET_ROWDISPOSITION_ERROR()
,DATA_ERROR_ARRAY = ARRAY_APPEND(DATA_ERROR_ARRAY,''SYSTEM_ID could not be assigned'')
where SNAPSHOT_ID = :SNAPSHOT_ID and SYSTEM_ID IS NULL and ARRAY_SIZE(DATA_ERROR_ARRAY) = 0; -- 240727 CR928 added ARRAY_SIZE check

RECORD_COUNT := SQLROWCOUNT;

If (:RECORD_COUNT > 0) THEN
    BEGIN
    Msg := ''RESEARCH WHY SYSTEM_ID NOT ASSIGNED DESPITE NO ERRORS='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);   
    END;
END IF;

-- TENABLE_ASSET_TAGS does not have (version Asset_ID)
UPDATE CORE.RAW_HWAM
set DATA_WARNING_ARRAY = ARRAY_APPEND(DATA_WARNING_ARRAY,''TENABLE_ASSET_TAGS does not have (version Asset_ID)'')
where SNAPSHOT_ID = :SNAPSHOT_ID and TENABLE_ASSET_TAGS IS NOT NULL and TENABLE_ASSET_ID_TATTOO IS NULL;

-- TENABLE_ASSET_TAGS does not have (version Primary_FISMA_ID
UPDATE CORE.RAW_HWAM
set DATA_WARNING_ARRAY = ARRAY_APPEND(DATA_WARNING_ARRAY,''TENABLE_ASSET_TAGS does not have (version Primary_FISMA_ID)'')
where SNAPSHOT_ID = :SNAPSHOT_ID and TENABLE_ASSET_TAGS IS NOT NULL and TENABLE_PRIMARY_FISMA_ID_TATTOO IS NULL;

--
-- UPDATE SNAPSHOT_IDS with Error and Warning counts
--
select SUM(ARRAY_SIZE(DATA_ERROR_ARRAY)),SUM(ARRAY_SIZE(DATA_WARNING_ARRAY)) into :ERROR_COUNT,:WARNING_COUNT FROM CORE.RAW_HWAM where SNAPSHOT_ID = :SNAPSHOT_ID;
select count(1) into :RECORDS_WITH_ERRORS FROM CORE.RAW_HWAM where SNAPSHOT_ID = :SNAPSHOT_ID and ARRAY_SIZE(DATA_ERROR_ARRAY) > 0;
select count(1) into :RECORDS_WITH_WARNINGS FROM CORE.RAW_HWAM where SNAPSHOT_ID = :SNAPSHOT_ID and ARRAY_SIZE(DATA_WARNING_ARRAY) > 0;

UPDATE SNAPSHOT_IDS
set ERROR_COUNT = :ERROR_COUNT
,RECORDS_WITH_ERRORS = :RECORDS_WITH_ERRORS
,RECORDS_WITH_WARNINGS = :RECORDS_WITH_WARNINGS
,WARNING_COUNT = :WARNING_COUNT
WHERE SNAPSHOT_ID = :SNAPSHOT_ID;


CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';