CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_IUSG_VUL"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull AWS (IUSG) TENABLE data into BUS_CYBER_RISK_MANAGEMENT RAW_TENABLE_VUL table'
EXECUTE AS OWNER
AS '
--
-- 
--
declare
Appl varchar := ''SP_CRM_PULL_IUSG_VUL'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
Datacategory varchar := ''AWS VUL''; -- 240115
PreviousPullDatetime TIMESTAMP_LTZ(9);
SNAPSHOT_ID number;
RECORD_COUNT number;
MIN_DATE TIMESTAMP_LTZ(9);
MAX_DATE TIMESTAMP_LTZ(9);

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

CALL CORE.SP_CRM_GENERATE_SNAPSHOT_ID(:Datacategory);
SNAPSHOT_ID := CORE.FN_CRM_GET_SNAPSHOT_ID(:Datacategory);

PreviousPullDatetime := (select PARMDATE FROM CORE.CONFIG where PARMNAME = :Datacategory);

Msg := ''Previous pull of '' || :Datacategory || ''='' || :PreviousPullDatetime;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);

BEGIN TRANSACTION;

insert into CORE.RAW_TENABLE_VUL(
ACCEPT_RISK_RULE_COMMENT
,ACCEPTRISK
,ACRSCORE
,APPLICABILITYCODE -- 240710 CR928
,ASSET_ID_TATTOO
,ASSETEXPOSURESCORE
,AWS_ACCOUNTID
,AWS_INSTANCE_ID
,BASESCORE
,BID
,CHECKTYPE
,COMPLIANCE_ACTUAL_VALUE
,COMPLIANCE_CHECK_NAME
,COMPLIANCE_ERROR
,COMPLIANCE_RESULT
,CPE
,CREDENTIALED_SCAN
,CUSTOM_SEVERITY
,CVE
,CVSSV2BASESCORE
,CVSSV3BASESCORE
,CVSSV3TEMPORALSCORE
,CVSSV3VECTOR
,CVSSVECTOR
,DATA_ERROR_ARRAY -- 240710 CR928
,DATA_WARNING_ARRAY -- 240710 CR928
,DATACENTER_ID
,DESCRIPTION
,DNSNAME
,EXPLOIT_AVAILABLE
,EXPLOITEASE
,EXPLOITFRAMEWORKS
,FAMILY_ID
,FAMILY_NAME
,FAMILY_TYPE
,FIRST_SEEN
,FISMASEVERITY
,HAS_BEEN_MITIGATED
,HOSTNAME
,HOSTUNIQUENESS
,HOSTUUID
,INSERT_DATE
,IP
,IPS
,KEYDRIVERS
,LAST_SEEN
,MACADDRESS
,MITIGATIONSTATUS
,NETBIOSNAME
,NUMERIC_SEVERITY -- 240710 CR928
,OPERATING_SYSTEM
,PATCHPUB_DATE
,PLUGIN_ID
,PLUGIN_INFO
,PLUGIN_MOD_DATE
,PLUGIN_NAME
,PLUGIN_PUB_DATE
,PLUGINTEXT
,PORT
,PRIMARY_FISMA_ID_DERIVED
,PRIMARY_FISMA_ID_TATTOO
,PROTOCOL
,RECASTRISK
,RECASTRISKRULECOMMENT
,REPORTDATE
,REPOSITORY_DATAFORMAT
,REPOSITORY_DESCRIPTION
,REPOSITORY_ID
,REPOSITORY_NAME
,RISKFACTOR
,ROWDISPOSITION
,SCAN_POLICY_NAME
,SCAN_POLICY_UID
,SCAN_START_DATE
,SEEALSO
,SEVERITY_DESCRIPTION
,SEVERITY_ID
,SEVERITY_NAME
,SNAPSHOT_ID
,SOLUTION
,SOURCE_TOOL
,STATE
,STIGSEVERITY
,SYNOPSIS
,SYSTEM_ID -- 240724 CR940
,TEMPORAL_SCORE
,TENABLEUUID
,UNIQUENESS
,VERSION
,VPR_SCORE
,VPRCONTEXT
,VULN_PUB_DATE
,XREF
,ASSET_ID_TAG -- 240827 CR-TBD
,FISMA_ID_TAG -- 240827 CR-TBD
) 
SELECT
ACCEPT_RISK_RULE_COMMENT
,ACCEPTRISK
,ACRSCORE
,CORE.FN_CRM_GET_INDICATOR_INITIAL() as APPLICABILITYCODE -- 240710 CR928
,instanceid as ASSET_ID_TATTOO -- 240528 CR901
,ASSETEXPOSURESCORE
,accountid as AWS_ACCOUNTID
,instanceid as AWS_INSTANCE_ID
,coalesce(NULLIF(BASESCORE,''''),''0'')::NUMBER(38,1) as BASESCORE
,BID
,CHECKTYPE
,NULL as COMPLIANCE_ACTUAL_VALUE
,NULL as COMPLIANCE_CHECK_NAME
,NULL as COMPLIANCE_ERROR
,NULL as COMPLIANCE_RESULT
,CPE
,NULL as CREDENTIALED_SCAN
,NULL as CUSTOM_SEVERITY
,CVE
,coalesce(NULLIF(BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV2BASESCORE
,coalesce(NULLIF(CVSSV3BASESCORE,''''),''0'')::NUMBER(38,1) as CVSSV3BASESCORE
,CVSSV3TEMPORALSCORE
,CVSSV3VECTOR
,CVSSVECTOR
,ARRAY_CONSTRUCT() as DATA_ERROR_ARRAY -- 240710 CR928
,ARRAY_CONSTRUCT() as DATA_WARNING_ARRAY -- 240710 CR928
,coalesce(DATACENTER_ID,''InstanceID not in SEC_VW_HWAM_AWS'') as DATACENTER_ID -- 240724 CR940
,DESCRIPTION
,DNSNAME
,EXPLOIT_AVAILABLE
,EXPLOITEASE
,EXPLOITFRAMEWORKS
,FAMILY_ID
,FAMILY_NAME
,FAMILY_TYPE
,FIRST_SEEN
,NULL as FISMASEVERITY
,coalesce(NULLIF(HAS_BEEN_MITIGATED,''''),''0'')::NUMBER as HAS_BEEN_MITIGATED
,NULL as HOSTNAME
,HOSTUNIQUENESS
,HOSTUUID
,CURRENT_TIMESTAMP() as INSERT_DATE
,IP
,IPS
,KEYDRIVERS
,LAST_SEEN
,MACADDRESS
,case HAS_BEEN_MITIGATED
    when 1 then CORE.FN_CRM_GET_MITIGATIONSTATUS_REOPENED()
    Else CORE.FN_CRM_GET_MITIGATIONSTATUS_OPEN()
End as MITIGATIONSTATUS -- 240710 CR928
,NETBIOSNAME
,0 as NUMERIC_SEVERITY -- 240710 CR928
,OPERATING_SYSTEM
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(PATCHPUB_DATE) as PATCHPUB_DATE
,PLUGIN_ID
,PLUGIN_INFO
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(PLUGIN_MOD_DATE) as PLUGIN_MOD_DATE
,PLUGIN_NAME
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(PLUGIN_PUB_DATE) as PLUGIN_PUB_DATE
,PLUGINTEXT
,PORT
,NULL as PRIMARY_FISMA_ID -- 240528 CR901
,NULL as PRIMARY_FISMA_ID_TATTOO
,PROTOCOL
,RECASTRISK
,RECASTRISKRULECOMMENT
,S3_FILE_CREATE as REPORTDATE
,REPOSITORY_DATAFORMAT
,REPOSITORY_DESCRIPTION
,REPOSITORY_ID
,REPOSITORY_NAME
,RISKFACTOR
,CORE.FN_CRM_GET_ROWDISPOSITION_VIABLE() as ROWDISPOSITION -- 240710 CR928
,NULL as SCAN_POLICY_NAME
,NULL as SCAN_POLICY_UID
,NULL as SCAN_START_DATE
,SEEALSO
,SEVERITY_DESCRIPTION
,SEVERITY_ID
,SEVERITY_NAME
,:SNAPSHOT_ID
,SOLUTION
,''Tenable'' as SOURCE_TOOL
,NULL as STATE
,STIGSEVERITY
,SYNOPSIS
,coalesce(SYSTEM_ID,''Not in FISMA_LOOKUP'') as THE_SYSTEM_ID -- 240724 CR940
,TEMPORAL_SCORE
,UUID as TENABLEUUID
,UNIQUENESS
,VERSION
,VPR_SCORE
,STRTOK_TO_ARRAY(VPRCONTEXT,'','') as VPRCONTEXT
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(VULN_PUB_DATE) as VULN_PUB_DATE
,XREF
,instanceid as ASSET_ID_TAG -- 240827 CR-TBD
,THE_SYSTEM_ID as FISMA_ID_TAG -- 240827 CR-TBD
FROM CORE.VW_IUSG_CUMULATIVE_VULNS -- 240724 CR940
WHERE S3_FILE_CREATE > :PreviousPullDatetime;

COMMIT;

RECORD_COUNT := SQLROWCOUNT;

IF (:RECORD_COUNT = 0) THEN
	BEGIN
	Msg := ''WARNING: There is no VUL data for this snapshot'';
	CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
	END;
ELSE
    BEGIN
    Msg := :Datacategory || '' inserted into RAW_TENABLE_VUL='' || :RECORD_COUNT;
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    END;
END IF;

MIN_DATE := (select MIN(REPORTDATE) FROM CORE.RAW_TENABLE_VUL WHERE SNAPSHOT_ID = :SNAPSHOT_ID);
MAX_DATE := (select MAX(REPORTDATE) FROM CORE.RAW_TENABLE_VUL WHERE SNAPSHOT_ID = :SNAPSHOT_ID);

BEGIN TRANSACTION;

If (RECORD_COUNT > 0) THEN
    BEGIN
    update CORE.CONFIG
    set PARMDATE = :MAX_DATE
    where PARMNAME = :Datacategory and :MAX_DATE IS NOT NULL;
    END;
End if;

UPDATE CORE.SNAPSHOT_IDS
set MIN_DATE = :MIN_DATE
,MAX_DATE = :MAX_DATE
,RECORD_COUNT = coalesce(:RECORD_COUNT,0)
 where SNAPSHOT_ID = :SNAPSHOT_ID;

COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END
';