CREATE OR REPLACE PROCEDURE "SP_UPDATE_PRIMARY_OP_LOC2"()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Insert new Primary_Operating_Location(s) into PrimaryOpLoc table'
EXECUTE AS OWNER
AS '
BEGIN
LET DefaultID := CORE.FN_CRM_GETUID_DEFAULT();
return DefaultID;
END
';