create or replace database BUS_CYBER_RISK_MANAGEMENT COMMENT='A separate data repository that is structured to provide focused processing of raw CMS IT system security data sourced from the CMS Security Data Lake (SDL). The SDL ingests raw security sensor data, which requires necessary data transformation and processing to serve CMS business needs. The DW performs CMS IT unique asset matching, data parsing, data enrichment, data quality checks, and other processing that is necessary to support risk-based business operations, including supporting security and compliance dashboarding and reporting. The DW is deployed within the CMS ecosystem connected to the SDL. The DW extracts a subset of SDL data via Snowflake queries where it is then staged and processed. The DW also has a reporting process for business and stakeholder use.';

create or replace schema CORE;

CREATE OR REPLACE PROCEDURE "SP_CRM_PULL_CFACTS"("P_REPORT_ID" NUMBER(38,0))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
COMMENT='Pull CFACTS data into BUS_CYBER_RISK_MANAGEMENT'
EXECUTE AS OWNER
AS '
declare
Appl varchar := ''SP_CRM_PULL_CFACTS'';
ExceptionMsg varchar;
Msg varchar;
StartOfProgram datetime := current_timestamp();
CRM_logic_exception exception (-20002, ''Raised CRM_logic_exception.'');
False boolean DEFAULT 0;
True boolean DEFAULT 1;
RECORD_COUNT number;

BEGIN
CALL CORE.SP_CRM_START_PROCEDURE (:Appl);

----------------------------------------------------------------------
--            CHECK TO SEE IF CFACTS DATA IS AVAILABLE AND CURRENT
----------------------------------------------------------------------

/****************************************************************************************************************************
THE BASELINE WAS ESTABLISHED 11/07/2024 WITH THE FOLLOWING:

CREATE TABLE EXPECTED_CFACTS_COLUMNS as
SELECT v.TABLE_CATALOG,v.TABLE_SCHEMA,v.TABLE_NAME,c.COLUMN_NAME,c.DATA_TYPE
FROM APP_CFACTS.INFORMATION_SCHEMA.VIEWS v
LEFT OUTER JOIN (select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,DATA_TYPE 
    from APP_CFACTS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = ''SHARED'' ) c on c.TABLE_CATALOG = v.TABLE_CATALOG 
    and c.TABLE_SCHEMA = v.TABLE_SCHEMA and c.TABLE_NAME = v.TABLE_NAME
WHERE v.TABLE_SCHEMA = ''SHARED'' and v.CREATED::date = current_date()
;

****************************************************************************************************************************/

--
-- 241105 CR1023
-- Ensure that all CFACTS data is available and current.
-- Check also helps to trap CFACTS field name changes or data type.
-- 241107 replaced LAST_ALTERED with CREATED
--
select count(1) INTO :RECORD_COUNT from CORE.EXPECTED_CFACTS_COLUMNS expected
LEFT OUTER JOIN (SELECT v.TABLE_CATALOG,v.TABLE_SCHEMA,v.TABLE_NAME,v.LAST_DDL,c.COLUMN_NAME,c.DATA_TYPE
    FROM APP_CFACTS.INFORMATION_SCHEMA.VIEWS v
    LEFT OUTER JOIN (select TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,DATA_TYPE 
        from APP_CFACTS.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = ''SHARED'' ) c on c.TABLE_CATALOG = v.TABLE_CATALOG 
        and c.TABLE_SCHEMA = v.TABLE_SCHEMA and c.TABLE_NAME = v.TABLE_NAME
     WHERE v.TABLE_SCHEMA = ''SHARED'' and v.CREATED::date = current_date()) cur on cur.TABLE_CATALOG = expected.TABLE_CATALOG 
        and cur.TABLE_SCHEMA = expected.TABLE_SCHEMA and cur.TABLE_NAME = expected.TABLE_NAME
        and cur.COLUMN_NAME = expected.COLUMN_NAME 
        and cur.DATA_TYPE = expected.DATA_TYPE
WHERE cur.COLUMN_NAME IS NULL;
   
IF (:RECORD_COUNT <> 0) THEN
    BEGIN
    --
    -- Send warning message to security-datalake-crm-sdw-alerts when not all CFACTS data is available
    --
    Msg := ''WARNING: APP_CFACTS.SHARED views are incomplete. '' || :RECORD_COUNT || '' columns are missing. SDW CFACTS data will remain unchanged.'';
    CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg);
    
    select CORE.SF_SEND_SLACK_MESSAGE(:Msg);

    CALL CORE.SP_CRM_END_PROCEDURE (:Appl);
	RETURN :Msg;
    END;
END IF;


----------------------------------------------------------------------
--            SYSTEMS
----------------------------------------------------------------------
BEGIN TRANSACTION;
MERGE INTO CORE.SYSTEMS t USING (
SELECT
	ACRONYM,
    ACTUAL_DECOMMISION_DATE, -- 231218
	ARCHER_TRACKING_ID,
	ATO_EXPIRATION_DATE,
	ATO_REVIEW_DATE,
	AUTH_COMMENTS,
	AUTH_DECISION,
	AUTHORIZATION_MEMO_SIGNED_DATE,
	AUTHORIZATION_PACKAGE_NAME,
	BO_RECOMMENDATION_REVIEW_DATE,
	BO_REVIEW_DATE,
	BUSINESS_OWNER,
	CIO,
	CISO,
	CISO_REVIEW_DATE,
	CLOUD_SERVICE_PROVIDER,
	COMPONENT_ACRONYM,
	COMPONENT_DESCRIPTION,
	COMPONENT_NAME,
	COMPONENT_RISK_REPORTS_OVERSIGHT,
	CONTINGENCYEXPIRATIONDATE,
	CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID,
	CP_TEST_DATE,
	CP_TEST_RESULTS,
	CRA,
	CRA_REVIEW_DATE,
	CYBERVET,
	DATE_AUTH_MEMO_EXPIRES,
	DATE_AUTH_MEMO_SIGNED,
	DCISO,
	DIVISION_ACRONYM,
	DIVISION_DESCRIPTION,
	DIVISION_NAME,
	DSPC_REVIEW_DATE,
	DSPPO_REVIEW_DATE,
	E_AUTH_EXP_DATE,
	E_AUTH_LEVEL,
	E_AUTH_RISK_ASSESSMENT_DATE,
	FINANCIAL_SYSTEM,
	FIPS_199_AVAILABILITY_RATING,
	FIPS_199_CONFIDENTIALITY_RATING,
	FIPS_199_INTEGRITY_RATING,
	FIPS_199_OVERALL_IMPACT_RATING,
	FIRST_PUBLISHED_DATE,
	FISMA_SYSTEM,
	GROUP_ACRONYM,
	GROUP_DESCRIPTION,
	GROUP_NAME,
	HVA_SCORE,
	HVASTATUS,
	INFORMATION_SYSTEM_TYPE,
	IS_MARKETPLACE,
	IS_OA_READY,
	ISRA_REVIEW_DATE,
	ISRA_STATUS,
	ISSO,
	ISSO_COUNT,
	ISSO_REVIEW_DATE,
	ISSO_SUBMISSION_DATE,
	ISSOCS,
	LAST_ACT_DATE,
    LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE, -- 230428 
	LAST_ACT_SCA_FINAL_REPORT_DATE,
    LAST_PENTEST_CAAT_PROCESSED_FILE_DATE,  -- 230428 
	LAST_PENTEST_DATE,
	MEF,
	MEF_CONTEXT,
	NEXT_REQUIRED_CP_TEST_DATE,
	OA_STATUS,
    OPERATED_BY, -- 250103 CR1059
	PACKAGE_TYPE,
    PIA_014,
	PIA_EXPIRATION_DATE,
	PRIMARY_ISSO,
	NULLIF(PRIMARY_OPERATING_LOCATION,'''') as PRIMARY_OPERATING_LOCATION,
	REASON_FOR_ATO_REQUEST,
	SCA,
	SCA_DATE,
	SDM,
	SOP_REVIEW_DATE,
	STE_DATE,
    CORE.FN_CRM_STRIPHTML(SYSTEM_DESCRIPTION) as SYSTEM_DESCRIPTION, -- 231012
	SYSTEM_ID,
	TLC_PHASE   
FROM CORE.VW_CFACTS_SYSTEMS    
)s ON (s.System_ID = t.System_ID)
WHEN MATCHED THEN UPDATE SET 
    t.ACRONYM = s.ACRONYM
    ,t.ACTUAL_DECOMMISION_DATE = s.ACTUAL_DECOMMISION_DATE -- 231218
	,t.ARCHER_TRACKING_ID = s.ARCHER_TRACKING_ID
    ,t.ATO_EXPIRATION_DATE = s.ATO_EXPIRATION_DATE
    ,t.ATO_REVIEW_DATE = s.ATO_REVIEW_DATE
	,t.AUTH_COMMENTS = s.AUTH_COMMENTS
	,t.AUTH_DECISION = s.AUTH_DECISION
    ,t.AUTHORIZATION_MEMO_SIGNED_DATE = s.AUTHORIZATION_MEMO_SIGNED_DATE
	,t.AUTHORIZATION_PACKAGE = s.AUTHORIZATION_PACKAGE_NAME
    ,t.BO_RECOMMENDATION_REVIEW_DATE = s.BO_RECOMMENDATION_REVIEW_DATE
    ,t.BO_REVIEW_DATE = s.BO_REVIEW_DATE
	,t.BUSINESS_OWNER = s.BUSINESS_OWNER
	,t.CIO = s.CIO
	,t.CISO = s.CISO
    ,t.CISO_REVIEW_DATE = s.CISO_REVIEW_DATE
	,t.CLOUD_SERVICE_PROVIDER = s.CLOUD_SERVICE_PROVIDER
    ,t.COMPONENT_ACRONYM = s.COMPONENT_ACRONYM
	,t.COMPONENT_DESCRIPTION = s.COMPONENT_DESCRIPTION
	,t.COMPONENT_NAME = s.COMPONENT_NAME
	,t.COMPONENT_RISK_REPORTS_OVERSIGHT = s.COMPONENT_RISK_REPORTS_OVERSIGHT
	,t.CONTINGENCYEXPIRATIONDATE = s.CONTINGENCYEXPIRATIONDATE
	,t.CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID = s.CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID
	,t.CP_TEST_DATE = s.CP_TEST_DATE
	,t.CP_TEST_RESULTS = s.CP_TEST_RESULTS
	,t.CRA = s.CRA
    ,t.CRA_REVIEW_DATE = s.CRA_REVIEW_DATE
	,t.CYBERVET = s.CYBERVET
	,t.DATE_AUTH_MEMO_EXPIRES = s.DATE_AUTH_MEMO_EXPIRES
	,t.DATE_AUTH_MEMO_SIGNED = s.DATE_AUTH_MEMO_SIGNED
	,t.DCISO = s.DCISO
    ,t.DIVISION_ACRONYM = s.DIVISION_ACRONYM
	,t.DIVISION_DESCRIPTION = s.DIVISION_DESCRIPTION
	,t.DIVISION_NAME = s.DIVISION_NAME
    ,t.DSPC_REVIEW_DATE = s.DSPC_REVIEW_DATE
    ,t.DSPPO_REVIEW_DATE = s.DSPPO_REVIEW_DATE
	,t.E_AUTH_EXP_DATE = s.E_AUTH_EXP_DATE
	,t.E_AUTH_LEVEL = s.E_AUTH_LEVEL
	,t.E_AUTH_RISK_ASSESSMENT_DATE = s.E_AUTH_RISK_ASSESSMENT_DATE
	,t.FINANCIAL_SYSTEM = s.FINANCIAL_SYSTEM
	,t.FIPS_199_AVAILABILITY_RATING = s.FIPS_199_AVAILABILITY_RATING
	,t.FIPS_199_CONFIDENTIALITY_RATING = s.FIPS_199_CONFIDENTIALITY_RATING
	,t.FIPS_199_INTEGRITY_RATING = s.FIPS_199_INTEGRITY_RATING
	,t.FIPS_199_OVERALL_IMPACT_RATING = s.FIPS_199_OVERALL_IMPACT_RATING
	,t.FIRST_PUBLISHED_DATE = s.FIRST_PUBLISHED_DATE
	,t.FISMA_SYSTEM = s.FISMA_SYSTEM
    ,t.GROUP_ACRONYM = s.GROUP_ACRONYM
	,t.GROUP_DESCRIPTION = s.GROUP_DESCRIPTION
	,t.GROUP_NAME = s.GROUP_NAME
	,t.HVA_SCORE = s.HVA_SCORE
	,t.HVASTATUS = s.HVASTATUS
	,t.INFORMATION_SYSTEM_TYPE = s.INFORMATION_SYSTEM_TYPE
	,t.IS_MARKETPLACE = s.IS_MARKETPLACE
	,t.IS_OA_READY = s.IS_OA_READY
	,t.ISRA_REVIEW_DATE = s.ISRA_REVIEW_DATE
	,t.ISRA_STATUS = s.ISRA_STATUS
	,t.ISSO = s.ISSO
	,t.ISSO_COUNT = s.ISSO_COUNT
    ,t.ISSO_REVIEW_DATE = s.ISSO_REVIEW_DATE
    ,t.ISSO_SUBMISSION_DATE = s.ISSO_SUBMISSION_DATE
	,t.ISSOCS = s.ISSOCS
	,t.LAST_ACT_DATE = s.LAST_ACT_DATE
    ,t.LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE = s.LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE -- 230428 
	,t.LAST_ACT_SCA_FINAL_REPORT_DATE = s.LAST_ACT_SCA_FINAL_REPORT_DATE
    ,t.LAST_PENTEST_CAAT_PROCESSED_FILE_DATE = s.LAST_PENTEST_CAAT_PROCESSED_FILE_DATE  -- 230428    
	,t.LAST_PENTEST_DATE = s.LAST_PENTEST_DATE
	,t.MEF = s.MEF
	,t.MEF_CONTEXT = s.MEF_CONTEXT
	,t.NEXT_REQUIRED_CP_TEST_DATE = s.NEXT_REQUIRED_CP_TEST_DATE
	,t.OA_STATUS = s.OA_STATUS
    ,t.OPERATED_BY = s.OPERATED_BY -- 250103 CR1059
	,t.PACKAGE_TYPE = s.PACKAGE_TYPE
    ,t.PIA_014 = s.PIA_014 -- 230621
	,t.PIA_EXPIRATION_DATE = s.PIA_EXPIRATION_DATE
	,t.PRIMARY_ISSO = s.PRIMARY_ISSO
	,t.PRIMARY_OPERATING_LOCATION = s.PRIMARY_OPERATING_LOCATION
    ,t.REASON_FOR_ATO_REQUEST = s.REASON_FOR_ATO_REQUEST
	,t.SCA = s.SCA
	,t.SCA_DATE = s.SCA_DATE
	,t.SDM = s.SDM
    ,t.SOP_REVIEW_DATE = s.SOP_REVIEW_DATE
	,t.STE_DATE = s.STE_DATE
	,t.SYSTEM_DESCRIPTION = s.SYSTEM_DESCRIPTION
--	,t.SYSTEM_ID = s.SYSTEM_ID
	,t.TLC_PHASE = s.TLC_PHASE
WHEN NOT MATCHED THEN INSERT
    (ACRONYM
    ,ACTUAL_DECOMMISION_DATE -- 231218
	,ARCHER_TRACKING_ID
    ,ATO_EXPIRATION_DATE
    ,ATO_REVIEW_DATE
	,AUTH_COMMENTS
	,AUTH_DECISION
    ,AUTHORIZATION_MEMO_SIGNED_DATE
	,AUTHORIZATION_PACKAGE
    ,BO_RECOMMENDATION_REVIEW_DATE
    ,BO_REVIEW_DATE
	,BUSINESS_OWNER
	,CIO
	,CISO
    ,CISO_REVIEW_DATE
	,CLOUD_SERVICE_PROVIDER
	,COMPONENT_ACRONYM
	,COMPONENT_DESCRIPTION
	,COMPONENT_NAME
	,COMPONENT_RISK_REPORTS_OVERSIGHT
	,CONTINGENCYEXPIRATIONDATE
	,CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID
	,CP_TEST_DATE
	,CP_TEST_RESULTS
	,CRA
    ,CRA_REVIEW_DATE
	,CYBERVET
	,DATE_AUTH_MEMO_EXPIRES
	,DATE_AUTH_MEMO_SIGNED
	,DATEDELETED
	,DATEMODIFIED
	,DCISO
	,DIVISION_ACRONYM
	,DIVISION_DESCRIPTION
	,DIVISION_NAME
    ,DSPC_REVIEW_DATE
    ,DSPPO_REVIEW_DATE
	,E_AUTH_EXP_DATE
	,E_AUTH_LEVEL
	,E_AUTH_RISK_ASSESSMENT_DATE
	,FINANCIAL_SYSTEM
	,FIPS_199_AVAILABILITY_RATING
	,FIPS_199_CONFIDENTIALITY_RATING
	,FIPS_199_INTEGRITY_RATING
	,FIPS_199_OVERALL_IMPACT_RATING
	,FIRST_PUBLISHED_DATE
	,FISMA_SYSTEM
	,GROUP_ACRONYM
	,GROUP_DESCRIPTION
	,GROUP_NAME
	,HVA_SCORE
	,HVASTATUS
	,IN_CMS_CLOUD
	,INFORMATION_SYSTEM_TYPE
    ,INSERT_DATE
	,IS_DATACENTER
	,IS_EXCLUDEFROMREPORTING
	,IS_HIGHRISKSYSTEM
	,IS_MARKETPLACE
	,IS_OA_READY
	,IS_OPERATIONALSYSTEM
	,IS_PHANTOMSYSTEM
	,IS_SECURITYHUB_ENABLED
	,ISRA_REVIEW_DATE
	,ISRA_STATUS
	,ISSO
	,ISSO_COUNT
    ,ISSO_REVIEW_DATE
    ,ISSO_SUBMISSION_DATE
	,ISSOCS
	,LAST_ACT_DATE
    ,LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE -- 230428 
	,LAST_ACT_SCA_FINAL_REPORT_DATE
    ,LAST_PENTEST_CAAT_PROCESSED_FILE_DATE  -- 230428
	,LAST_PENTEST_DATE
	,MEF
	,MEF_CONTEXT
	,MEFSTATUS
	,NEXT_REQUIRED_CP_TEST_DATE
	,OA_STATUS
	,OATO_CATEGORY
    ,OPERATED_BY -- 250103 CR1059
	,PACKAGE_TYPE
    ,PIA_014 -- 230621
	,PIA_EXPIRATION_DATE
	,PII_PHI
	,PRIMARY_ISSO
	,PRIMARY_OPERATING_LOCATION
    ,REASON_FOR_ATO_REQUEST
	,PRIMARY_OPERATING_LOCATION_ID
	,SCA
	,SCA_DATE
	,SDM
    ,SOP_REVIEW_DATE
	,STE_DATE
	,SYSTEM_DESCRIPTION
	,SYSTEM_ID
	,TLC_PHASE
	,TOTALPOAMWITHAPPROVEDRBD
)
VALUES (
    s.ACRONYM
    ,s.ACTUAL_DECOMMISION_DATE -- 231218
	,s.ARCHER_TRACKING_ID
    ,s.ATO_EXPIRATION_DATE
    ,s.ATO_REVIEW_DATE
	,s.AUTH_COMMENTS
	,s.AUTH_DECISION
    ,s.AUTHORIZATION_MEMO_SIGNED_DATE
	,s.AUTHORIZATION_PACKAGE_NAME
    ,s.BO_RECOMMENDATION_REVIEW_DATE
    ,s.BO_REVIEW_DATE
	,s.BUSINESS_OWNER
	,s.CIO
	,s.CISO
    ,s.CISO_REVIEW_DATE
	,s.CLOUD_SERVICE_PROVIDER
    ,s.COMPONENT_ACRONYM
	,s.COMPONENT_DESCRIPTION
	,s.COMPONENT_NAME
	,s.COMPONENT_RISK_REPORTS_OVERSIGHT
	,s.CONTINGENCYEXPIRATIONDATE
	,s.CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID
	,s.CP_TEST_DATE
	,s.CP_TEST_RESULTS
	,s.CRA
    ,s.CRA_REVIEW_DATE
	,s.CYBERVET
	,s.DATE_AUTH_MEMO_EXPIRES
	,s.DATE_AUTH_MEMO_SIGNED
    ,NULL -- DATEDELETED
    ,NULL -- DATEMODIFIED
	,s.DCISO
    ,s.DIVISION_ACRONYM
	,s.DIVISION_DESCRIPTION
	,s.DIVISION_NAME
    ,s.DSPC_REVIEW_DATE
    ,s.DSPPO_REVIEW_DATE
	,s.E_AUTH_EXP_DATE
	,s.E_AUTH_LEVEL
	,s.E_AUTH_RISK_ASSESSMENT_DATE
	,s.FINANCIAL_SYSTEM
	,s.FIPS_199_AVAILABILITY_RATING
	,s.FIPS_199_CONFIDENTIALITY_RATING
	,s.FIPS_199_INTEGRITY_RATING
	,s.FIPS_199_OVERALL_IMPACT_RATING
	,s.FIRST_PUBLISHED_DATE
	,s.FISMA_SYSTEM
    ,s.GROUP_ACRONYM
	,s.GROUP_DESCRIPTION
	,s.GROUP_NAME
	,s.HVA_SCORE
	,s.HVASTATUS
    ,NULL -- IN_CMS_CLOUD
	,s.INFORMATION_SYSTEM_TYPE
    ,CURRENT_TIMESTAMP()
    ,:false -- IS_DATACENTER
	,:false -- IS_EXCLUDEFROMREPORTING
	,:false -- IS_HIGHRISKSYSTEM
	,s.IS_MARKETPLACE
	,s.IS_OA_READY
	,:false -- IS_OPERATIONALSYSTEM
	,:false -- IS_PHANTOMSYSTEM
	,:false -- IS_SECURITYHUB_ENABLED
	,s.ISRA_REVIEW_DATE
	,s.ISRA_STATUS
	,s.ISSO
	,s.ISSO_COUNT
    ,s.ISSO_REVIEW_DATE
    ,s.ISSO_SUBMISSION_DATE
	,s.ISSOCS
	,s.LAST_ACT_DATE
    ,s.LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE -- 230428 
	,s.LAST_ACT_SCA_FINAL_REPORT_DATE
    ,s.LAST_PENTEST_CAAT_PROCESSED_FILE_DATE  -- 230428 
	,s.LAST_PENTEST_DATE
	,s.MEF
	,s.MEF_CONTEXT
    ,NULL -- MEFSTATUS
	,s.NEXT_REQUIRED_CP_TEST_DATE
	,s.OA_STATUS
    ,NULL -- OATO_CATEGORY
    ,s.OPERATED_BY -- 250103 CR1059
	,s.PACKAGE_TYPE
    ,s.PIA_014 -- 230621
	,s.PIA_EXPIRATION_DATE
    ,NULL -- PII_PHI
	,s.PRIMARY_ISSO
	,s.PRIMARY_OPERATING_LOCATION
    ,s.REASON_FOR_ATO_REQUEST
    ,NULL -- PRIMARY_OPERATING_LOCATION_ID
	,s.SCA
	,s.SCA_DATE
	,s.SDM
    ,s.SOP_REVIEW_DATE
	,s.STE_DATE
	,s.SYSTEM_DESCRIPTION
	,s.SYSTEM_ID
	,s.TLC_PHASE
    ,0 -- TOTALPOAMWITHAPPROVEDRBD
);

Msg := ''Merge SYSTEMS complete'';
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 
COMMIT;

select count(1) into :RECORD_COUNT FROM CORE.SYSTEMS GROUP BY SYSTEM_ID having count(1) > 1;
IF (coalesce(:RECORD_COUNT,0) > 1) THEN
	BEGIN
    -- THERE SHOULD NEVER BE TWO RECORDS WITH THE SAME SYSTEM_ID
    ExceptionMsg := ''DUPLICATE SYSTEM_ID IN SYSTEMS TABLE''; 
    raise CRM_logic_exception;
	END;
END IF;

--
-- Set IS_EXCLUDEFROMREPORTING Boolean to True as required.
-- CFACTS or Reporting teams (rarely) want to flag a CFACTS system to no
-- be included in FISMA Reporting. These are usually test records.
--
BEGIN TRANSACTION;
UPDATE CORE.SYSTEMS
set IS_EXCLUDEFROMREPORTING = 1
WHERE SYSTEM_ID IN
(
''11''
,''123456789101112131415''
,''N/A''
,''TBD''
);
COMMIT;

BEGIN TRANSACTION;
--
-- Initialize booleans that might change over time
--
UPDATE Systems
SET Is_OperationalSystem = :False
,Is_HighRiskSystem = :False;
       
-- Set Is_OperationalSystem to True to simplify reporting filters
--     
UPDATE Systems
SET Is_OperationalSystem = :True
where TLC_Phase = ''Operate''
and Package_Type = ''Information System''
and Information_System_Type IN 
(''Major Application''
,''General Support System''
,''Minor Application \\[Stand Alone\\]'' 
,''Minor Application \\[Child\\]'');
      
-- Set Is_HighRiskSystem to True to simply reporting filters
--
UPDATE Systems
SET Is_HighRiskSystem = :True
where Is_OperationalSystem = :True
and ((HVAStatus is not null and HVAStatus = ''Yes'') 
or (MEF_Context is not null and MEF_Context <> ''N/A'') 
or FIPS_199_Overall_Impact_Rating = ''High'');
  
-- Initialize fields that are re-evaluated each run
--
UPDATE Systems
SET In_CMS_Cloud = ''No''
,MEFStatus = NULL
,OATO_Category = 0
,PII_PHI = NULL
,TotalPOAMwithApprovedRBD = 0; 
   
UPDATE Systems
SET In_CMS_Cloud = ''Yes''
where Cloud_Service_Provider like ''%Amazon Web Services%''; 
            
UPDATE Systems
SET MEFStatus = ''Yes''
where MEF_Context IS NOT NULL 
and upper(MEF_Context) <> ''N/A''; -- 231013 added upper
      
UPDATE Systems upd -- Added upd 230531
SET PII_PHI = ''Yes''
FROM Systems s
JOIN (select distinct SYSTEM_ID
    FROM CORE.PII_SYSTEM_PII_TYPES st 
    WHERE UPPER(PII_Category) IN (''PII'',''PHI'')) p on p.SYSTEM_ID = s.System_ID
WHERE upd.SYSTEM_ID = s.SYSTEM_ID; -- Added where clause 230531
      
UPDATE Systems
SET OATO_Category = 3
WHERE (HVAStatus IS NOT NULL and HVAStatus = ''Yes'')
or (MEFStatus IS NOT NULL and MEFStatus = ''Yes'')
or (FIPS_199_Overall_Impact_Rating IS NOT NULL and FIPS_199_Overall_Impact_Rating = ''High'');

UPDATE Systems
SET OATO_Category = 2
WHERE OATO_Category = 0
and ((PII_PHI IS NOT NULL and PII_PHI = ''Yes'')
or (Financial_System IS NOT NULL and Financial_System = ''Yes'')
or (FIPS_199_Overall_Impact_Rating IS NOT NULL and FIPS_199_Overall_Impact_Rating = ''Moderate''));
      
-- As per Teresa, default to 1 to catch other possible issues
UPDATE Systems
SET OATO_Category = 1
WHERE OATO_Category = 0;
      
-- 210928 2153 TotalPOAMwithApprovedRBD used in CRMP metrics (V_CRMP_TotalNumberRiskAcceptance)
UPDATE Systems upd -- Added upd 230531
set TotalPOAMwithApprovedRBD = t.TotalPOAMwithApprovedRBD
FROM Systems s
JOIN (SELECT s.System_ID,count(1) as TotalPOAMwithApprovedRBD
    FROM APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE a 
    INNER JOIN Systems s on s.SYSTEM_ID = a.IDUID
    INNER JOIN APP_CFACTS.SHARED.SEC_VW_POAMs_Authorization_Package_x_Authorization_Package_POAMs pa ON a.ContentId=pa.Authorization_Package_POAMs_ContentId
    INNER JOIN APP_CFACTS.SHARED.SEC_VW_POAMs p ON p.ContentId=pa.POAMs_Authorization_Package_ContentId
    INNER JOIN APP_CFACTS.SHARED.SEC_VW_POAMs_Risk_Acceptance_RBD_POAMs_x_Risk_Acceptance_RBD_POAMs pr ON p.ContentId=pr.POAMs_Risk_Acceptance_RBD_POAMs_ContentId
    INNER JOIN APP_CFACTS.SHARED.SEC_VW_Risk_Acceptance_RBD r on pr.Risk_Acceptance_RBD_POAMs_ContentId=r.ContentId
    INNER JOIN APP_CFACTS.SHARED.SEC_VW_Risk_Acceptance_RBD_Overall_Status rs ON rs.ParentContentId=r.ContentId
    INNER JOIN APP_CFACTS.SHARED.SEC_VW_enum_RBD_Overall_Status ers on rs.Value=ers.Id
    Where upper(ers.Value)=''APPROVED WITH SIGNATURE'' -- 231017 add upper; Also CFACTS changed on or about 7/28/23. value used to be plural (Approved with Signatures)
    group by s.System_ID) t on t.System_ID = s.System_ID
WHERE upd.SYSTEM_ID = s.SYSTEM_ID; -- Added where clause 230531

--
-- SYSTEM_COMMONNAME is a supplemental table that provides the Common Name used to reference a system.
-- This value is not contained in CFACTS as an official value. It is simply used in everyday language for convenience. 
-- When a new system is added then the CommonName is the same as the official Acronym until such time as a manual
-- change is made within this table
--
INSERT into CORE.SYSTEM_COMMONNAME (COMMONNAME,SYSTEM_ID)
SELECT s.ACRONYM, s.SYSTEM_ID
FROM CORE.SYSTEMS s
LEFT OUTER JOIN CORE.SYSTEM_COMMONNAME c on c.SYSTEM_ID = s.SYSTEM_ID
where c.SYSTEM_ID IS NULL;

RECORD_COUNT := SQLROWCOUNT;
Msg := ''SYSTEMS table updated'';
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

-- 230607
-- SecurityHub data is provided manually and so the SYSTEM_SECURITYHUB_ENABLED table is a simple list
-- of systems that have SecurityHub enabled
--
UPDATE Systems upd
SET IS_SECURITYHUB_ENABLED = 1
FROM Systems s
JOIN CORE.SYSTEM_SECURITYHUB_ENABLED sh on sh.SYSTEM_ID = s.System_ID
WHERE upd.SYSTEM_ID = s.SYSTEM_ID;
COMMIT;

Msg := ''SYSTEMS update complete'';
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 

----------------------------------------------------------------------
--            ALLOCATEDCONTROL
----------------------------------------------------------------------
TRUNCATE TABLE CORE.ALLOCATEDCONTROL;

BEGIN TRANSACTION;
INSERT INTO CORE.ALLOCATEDCONTROL
	(ALLOCATION_STATUS
	,CONTROL_ELEMENT
	,CONTROL_ELEMENT_NUMBER
	,CONTROL_FAMILY
	,CONTROL_NAME
	,CONTROL_NUMBER
	,CONTROL_NUMBER_COMBO
	,CONTROL_SET_VERSION_NUMBER
	,HYBRID_CONTROL
	,INHERITABLE_BY_OTHER_SYSTEMS
	,LAST_ACT_DATE
	,LAST_ASSESSMENT_DATE
	,LAST_PENTEST_DATE
	,LAST_SCA_DATE
	,OVERALL_CONTROL_STATUS
	,PRIVATE_IMP_UPDATED_DATE
    ,PRIVATE_IMPLEMENTATION_DETAILS -- 230622
    ,REPORT_ID
	,RESPONSIBILITY
	,SHARED_IMP_UPDATED_DATE
	,SIGNIFICANT_CONTROL_CHANGE
	,SIGNIFICANT_CONTROL_CHANGE_DETAILS
	,SYSTEM_ID
	,TRACKING_ID
)
SELECT
	ALLOCATION_STATUS
	,CONTROL_ELEMENT
	,CONTROL_ELEMENT_NUMBER
	,CONTROL_FAMILY
	,CONTROL_NAME
	,CONTROL_NUMBER
	,CONTROL_NUMBER_COMBO
	,CONTROL_SET_VERSION_NUMBER
	,HYBRID_CONTROL
	,INHERITABLE_BY_OTHER_SYSTEMS
	,LAST_ACT_DATE
	,LAST_ASSESSMENT_DATE
	,LAST_PENTEST_DATE
	,LAST_SCA_DATE
	,OVERALL_CONTROL_STATUS
	,PRIVATE_IMP_UPDATED_DATE
    ,PRIVATE_IMPLEMENTATION_DETAILS -- 230622
    ,:P_Report_ID as REPORT_ID
	,RESPONSIBILITY
	,SHARED_IMP_UPDATED_DATE
	,SIGNIFICANT_CONTROL_CHANGE
	,SIGNIFICANT_CONTROL_CHANGE_DETAILS
	,SYSTEM_ID
	,TRACKING_ID
FROM CORE.VW_CFACTS_ALLOCATEDCONTROL
WHERE SYSTEM_ID IS NOT NULL;
COMMIT;

----------------------------------------------------------------------
--            CAATHIST
----------------------------------------------------------------------
BEGIN TRANSACTION;
INSERT INTO CORE.CAATHIST
	(ACT_CAAT_FILEPROCESSEDDATE
	,ASSESSMENT_AUDIT_COMPANY
	,CAAT_ID
	,DATE_IDENTIFIED
	,FINDING_DESCRIPTION
	,FINDING_ID
	,FINDING_TITLE
	,RELATED_POAMS
    ,REPORT_ID
	,SOURCE_AUDIT_TYPE
	,SYSTEM_ID
	,TEST_METHOD
	,TEST_OBJECTIVE
	,TEST_RESULT
	,WEAKNESS_DESCRIPTION
)
SELECT
	ACT_CAAT_FILEPROCESSEDDATE
	,ASSESSMENTAUDIT_COMPANY
	,CAAT_ID
	,DATE_IDENTIFIED
	,FINDING_DESCRIPTION
	,FINDING_ID
	,FINDING_TITLE
	,RELATED_POAMS
    ,:P_Report_ID as REPORT_ID
	,SOURCE_AUDIT_TYPE_2
	,SYSTEM_ID
	,TEST_METHOD
	,TEST_OBJECTIVE
	,TEST_RESULT
	,WEAKNESS_DESCRIPTION
FROM CORE.VW_CFACTS_CAAT
WHERE SYSTEM_ID IS NOT NULL;
COMMIT;

----------------------------------------------------------------------
--            CEDE_MVP_POAMS_CONTROLS
-- Added 230621
----------------------------------------------------------------------
TRUNCATE TABLE CORE.CEDE_MVP_POAMS_CONTROLS;

BEGIN TRANSACTION;
INSERT INTO CORE.CEDE_MVP_POAMS_CONTROLS (
	ALLOCATED_CONTROL,
	OVERALL_STATUS,
	POAM_ID,
	REPORT_ID,
    SYSTEM_ID,
	WEAKNESS_RISK_LEVEL
)
SELECT 
Alloc.Control_Number --as Allocated Control
,eOverallStatus.Value --as Overall Status 
,p.POAM_ID
,:P_Report_ID
,s.SYSTEM_ID
,eRiskLevel.Value --as Weakness Risk Level
FROM APP_CFACTS.SHARED.SEC_VW_POAMs p
INNER JOIN APP_CFACTS.SHARED.SEC_VW_POAMs_Authorization_Package_x_Authorization_Package_POAMs pa ON p.ContentId = pa.POAMs_Authorization_Package_ContentId
INNER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package a ON a.ContentId=pa.Authorization_Package_POAMs_ContentId
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = a.IDUID
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_POAMs_Overall_Status pOverallStatus on pOverallStatus.ParentContentId = p.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Status_9 eOverallStatus on eOverallStatus.Id = pOverallStatus.Value
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_POAMs_Weakness_Risk_Level_1 pRiskLevel on pRiskLevel.ParentContentId = p.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Risk_Level_1 eRiskLevel on eRiskLevel.ID = pRiskLevel.Value
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Allocated_Controls_Control_Standards_POAM_x_POAMs_Allocated_Control pAlloc on pAlloc.POAMs_Allocated_Control_ContentId = p.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Allocated_Controls_Control_Standards Alloc on Alloc.ContentId = pAlloc.Allocated_Controls_POAM_ContentId;
COMMIT;

----------------------------------------------------------------------
--            MILESTONEHIST
----------------------------------------------------------------------
BEGIN TRANSACTION;
INSERT INTO CORE.MILESTONEHIST
	(ACTUAL_COMPLETION_DATE
	,CHANGES_TO_MILESTONE
	,ESTIMATED_COMPLETION_DATE
	,LAST_UPDATED
	,MILESTONE_DESCRIPTION
	,MILESTONE_ID
	,MILESTONE_NAME
	,MILESTONE_STATUS
	,POAM_ID
    ,REPORT_ID
	,SCHEDULED_COMPLETION_DATE
	,SYSTEM_ID
)
SELECT
	ACTUAL_COMP_DATE
	,CHANGES2MS
	,EST_COMP_DATE
	,LAST_UPDATED
	,MS_DESC
	,MS_ID
	,MS_NAME
	,MS_STATUS
	,POAM_ID
    ,:P_Report_ID as REPORT_ID
	,SCHED_COMP_DATE
	,SYSTEM_ID
FROM CORE.VW_CFACTS_MILESTONE
WHERE SYSTEM_ID IS NOT NULL;
COMMIT;

----------------------------------------------------------------------
--            PIAHIST
----------------------------------------------------------------------
BEGIN TRANSACTION;
INSERT INTO CORE.PIAHIST
	(DUE_DATE
    ,FINAL_APPROVER
    ,FINAL_APPROVER_DATE
    ,FINAL_APPROVER_STATUS
    ,HHS_PIA_REVIEW_DATE
    ,HHS_PIA_STATUS
    ,OVERALL_STATUS
    ,PIA_TRACKING_ID
    ,REPORT_ID
    ,REVIEW_DATE
    ,REVIEW_STATUS
    ,REVIEWER
    ,SUBMISSION_DATE
    ,SUBMISSION_STATUS
    ,SUBMITTER
    ,SYSTEM_ID
)
SELECT
    DUE_DATE
    ,FINAL_APPROVER
    ,FINAL_APPROVER_DATE
    ,FINAL_APPROVER_STATUS
    ,HHS_PIA_REVIEW_DATE
    ,HHS_PIA_STATUS
    ,OVERALL_STATUS
    ,PIA_TRACKING_ID
    ,:P_Report_ID as REPORT_ID
    ,REVIEW_DATE
    ,REVIEW_STATUS
    ,REVIEWER
    ,SUBMISSION_DATE
    ,SUBMISSION_STATUS
    ,SUBMITTER
    ,SYSTEM_ID
FROM CORE.VW_CFACTS_PIA
where SYSTEM_ID IS NOT NULL; -- 230317 added in SDL environment
COMMIT;

----------------------------------------------------------------------
--           POAMHIST
----------------------------------------------------------------------
BEGIN TRANSACTION;
INSERT INTO CORE.POAMHIST
	(ACTUAL_COMPLETION_DATE,
	ACTUAL_LABOR_COST,
	CAAT,
	CAAT_ID,
    CVE,
	DAYS_OPEN,
	ESTIMATED_COMPLETION_DATE,
	FUNDING_SOURCE,
	LABOR_ESTIMATE,
	OVERALL_STATUS,
	POAM_CLOSED_DATE,
	POAM_ID,
	POAM_OWNER,
	POAM_REVIEWER,
    REPORT_ID,
	REVIEW_COMMENTS,
	REVIEW_DATE,
	REVIEW_STATUS,
	SCHEDULED_COMPLETION_DATE,
	SUBMISSION_STATUS,
	SYSTEM_ID,
	TARGET,
	WEAKNESS_CREATION_DATE,
	WEAKNESS_ID,
	WEAKNESS_POC,
	WEAKNESS_RISK_LEVEL,
	WEAKNESS_SEVERITY
)
SELECT
	ACTUAL_COMPLETION_DATE
	,ACTUAL_LABOR_COST
	,CAAT
	,CAAT_ID   
    ,IFF(FINDING_ID LIKE ''KEV%'',REPLACE(FINDING_ID,''KEV'',''CVE''),IFF(FINDING_ID LIKE ''CVE%'',FINDING_ID,NULL)) as CVE --231019 CR#775
	,DAYS_OPEN
	,ESTIMATED_COMPLETION_DATE
	,FUNDING_SOURCE
	,LABOR_ESTIMATE
	,OVERALL_STATUS
	,POAM_CLOSED_DATE
	,POAM_ID
	,POAM_OWNER
	,POAM_REVIEWER
	,:P_Report_ID as REPORT_ID
	,REVIEW_COMMENTS
	,REVIEW_DATE
	,REVIEW_STATUS
	,SCHEDULED_COMPLETION_DATE
	,SUBMISSION_STATUS
	,SYSTEM_ID
	,TARGET
	,WEAKNESS_CREATION_DATE
	,WEAKNESS_ID
	,WEAKNESS_POC
	,WEAKNESS_RISK_LEVEL
	,WEAKNESS_SEVERITY
FROM CORE.VW_CFACTS_POAM
WHERE SYSTEM_ID IS NOT NULL;

RECORD_COUNT := SQLROWCOUNT;
Msg := ''Inserted into POAMHIST='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 
COMMIT;

----------------------------------------------------------------------
--           SYSTEMSHIST
----------------------------------------------------------------------
BEGIN TRANSACTION;

INSERT INTO CORE.SYSTEMSHIST
    (ACRONYM
    ,ACTUAL_DECOMMISION_DATE --240904 CR965
	,ARCHER_TRACKING_ID
    ,ATO_EXPIRATION_DATE --240904 CR965
    ,ATO_REVIEW_DATE --240904 CR965
	,AUTH_COMMENTS
	,AUTH_DECISION
    ,AUTHORIZATION_MEMO_SIGNED_DATE --240904 CR965
	,AUTHORIZATION_PACKAGE
    ,BO_RECOMMENDATION_REVIEW_DATE --240904 CR965
    ,BO_REVIEW_DATE --240904 CR965
	,BUSINESS_OWNER
	,CIO
	,CISO
    ,CISO_REVIEW_DATE --240904 CR965
	,CLOUD_SERVICE_PROVIDER
	,COMPONENT_ACRONYM
	,COMPONENT_DESCRIPTION
	,COMPONENT_NAME
	,COMPONENT_RISK_REPORTS_OVERSIGHT
	,CONTINGENCYEXPIRATIONDATE
	,CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID
	,CP_TEST_DATE
	,CP_TEST_RESULTS
	,CRA
    ,CRA_REVIEW_DATE --240904 CR965
	,CYBERVET
	,DATE_AUTH_MEMO_EXPIRES
	,DATE_AUTH_MEMO_SIGNED
	,DATEDELETED
	,DATEMODIFIED
	,DCISO
    ,DIRECTOR_COMMENT --240904 CR965
    ,DIRECTOR_COMMENT2 --240904 CR965
	,DIVISION_ACRONYM
	,DIVISION_DESCRIPTION
	,DIVISION_NAME
    ,DSPC_REVIEW_DATE --240904 CR965
    ,DSPPO_REVIEW_DATE --240904 CR965
	,E_AUTH_EXP_DATE
	,E_AUTH_LEVEL
	,E_AUTH_RISK_ASSESSMENT_DATE
	,FINANCIAL_SYSTEM
	,FIPS_199_AVAILABILITY_RATING
	,FIPS_199_CONFIDENTIALITY_RATING
	,FIPS_199_INTEGRITY_RATING
	,FIPS_199_OVERALL_IMPACT_RATING
	,FIRST_PUBLISHED_DATE
	,FISMA_SYSTEM
	,GROUP_ACRONYM
	,GROUP_DESCRIPTION
	,GROUP_NAME
	,HVA_SCORE
	,HVASTATUS
	,IN_CMS_CLOUD
	,INFORMATION_SYSTEM_TYPE
    ,IS_CCSQ --240904 CR965
	,IS_DATACENTER
	,IS_EXCLUDEFROMREPORTING
	,IS_HIGHRISKSYSTEM
	,IS_MARKETPLACE
	,IS_OA_READY
	,IS_OPERATIONALSYSTEM
	,IS_PHANTOMSYSTEM
	,IS_SECURITYHUB_ENABLED
	,ISRA_REVIEW_DATE
	,ISRA_STATUS
	,ISSO
	,ISSO_COUNT
    ,ISSO_REVIEW_DATE --240904 CR965
    ,ISSO_SUBMISSION_DATE --240904 CR965
	,ISSOCS
    ,LAST_ACT_DATE
    ,LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE -- 230428 
	,LAST_ACT_SCA_FINAL_REPORT_DATE
    ,LAST_PENTEST_CAAT_PROCESSED_FILE_DATE  -- 230428
	,LAST_PENTEST_DATE
	,MEF
	,MEF_CONTEXT
	,MEFSTATUS
	,NEXT_REQUIRED_CP_TEST_DATE
	,OA_STATUS
	,OATO_CATEGORY
    ,OPERATED_BY -- 250103 CR1059
	,PACKAGE_TYPE
    ,PIA_014 -- 230623
	,PIA_EXPIRATION_DATE
	,PII_PHI
	,PRIMARY_ISSO
	,PRIMARY_OPERATING_LOCATION
	,PRIMARY_OPERATING_LOCATION_ID
    ,REASON_FOR_ATO_REQUEST --240904 CR965
	,REPORT_ID
	,SCA
	,SCA_DATE
	,SDM
    ,SOP_REVIEW_DATE --240904 CR965
	,STE_DATE
    ,SYSTEM_CREATION_DATE --240904 CR965
	,SYSTEM_DESCRIPTION
	,SYSTEM_ID
	,TLC_PHASE
	,TOTALPOAMWITHAPPROVEDRBD
)
SELECT
ACRONYM
    ,ACTUAL_DECOMMISION_DATE --240904 CR965
	,ARCHER_TRACKING_ID
    ,ATO_EXPIRATION_DATE --240904 CR965
    ,ATO_REVIEW_DATE --240904 CR965
	,AUTH_COMMENTS
	,AUTH_DECISION
	,AUTHORIZATION_MEMO_SIGNED_DATE --240904 CR965
	,AUTHORIZATION_PACKAGE
    ,BO_RECOMMENDATION_REVIEW_DATE --240904 CR965
    ,BO_REVIEW_DATE --240904 CR965
	,BUSINESS_OWNER
	,CIO
	,CISO
    ,CISO_REVIEW_DATE --240904 CR965
	,CLOUD_SERVICE_PROVIDER
	,COMPONENT_ACRONYM
	,COMPONENT_DESCRIPTION
	,COMPONENT_NAME
	,COMPONENT_RISK_REPORTS_OVERSIGHT
	,CONTINGENCYEXPIRATIONDATE
	,CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID
	,CP_TEST_DATE
	,CP_TEST_RESULTS
	,CRA
    ,CRA_REVIEW_DATE --240904 CR965
	,CYBERVET
	,DATE_AUTH_MEMO_EXPIRES
	,DATE_AUTH_MEMO_SIGNED
	,DATEDELETED
	,DATEMODIFIED
	,DCISO
    ,DIRECTOR_COMMENT --240904 CR965
    ,DIRECTOR_COMMENT2 --240904 CR965
	,DIVISION_ACRONYM
	,DIVISION_DESCRIPTION
	,DIVISION_NAME
    ,DSPC_REVIEW_DATE --240904 CR965
    ,DSPPO_REVIEW_DATE --240904 CR965
	,E_AUTH_EXP_DATE
	,E_AUTH_LEVEL
	,E_AUTH_RISK_ASSESSMENT_DATE
	,FINANCIAL_SYSTEM
	,FIPS_199_AVAILABILITY_RATING
	,FIPS_199_CONFIDENTIALITY_RATING
	,FIPS_199_INTEGRITY_RATING
	,FIPS_199_OVERALL_IMPACT_RATING
	,FIRST_PUBLISHED_DATE
	,FISMA_SYSTEM
	,GROUP_ACRONYM
	,GROUP_DESCRIPTION
	,GROUP_NAME
	,HVA_SCORE
	,HVASTATUS
	,IN_CMS_CLOUD
	,INFORMATION_SYSTEM_TYPE
    ,IS_CCSQ --240904 CR965
	,IS_DATACENTER
	,IS_EXCLUDEFROMREPORTING
	,IS_HIGHRISKSYSTEM
	,IS_MARKETPLACE
	,IS_OA_READY
	,IS_OPERATIONALSYSTEM
	,IS_PHANTOMSYSTEM
	,IS_SECURITYHUB_ENABLED
	,ISRA_REVIEW_DATE
	,ISRA_STATUS
	,ISSO
	,ISSO_COUNT
    ,ISSO_REVIEW_DATE --240904 CR965
    ,ISSO_SUBMISSION_DATE --240904 CR965
	,ISSOCS
    ,LAST_ACT_DATE
    ,LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE -- 230428 
	,LAST_ACT_SCA_FINAL_REPORT_DATE
    ,LAST_PENTEST_CAAT_PROCESSED_FILE_DATE  -- 230428
	,LAST_PENTEST_DATE
	,MEF
	,MEF_CONTEXT
	,MEFSTATUS
	,NEXT_REQUIRED_CP_TEST_DATE
	,OA_STATUS
	,OATO_CATEGORY
    ,OPERATED_BY -- 250103 CR1059
	,PACKAGE_TYPE
    ,PIA_014 -- 230623
	,PIA_EXPIRATION_DATE
	,PII_PHI
	,PRIMARY_ISSO
	,PRIMARY_OPERATING_LOCATION
	,PRIMARY_OPERATING_LOCATION_ID
    ,REASON_FOR_ATO_REQUEST --240904 CR965
	,:P_Report_ID as REPORT_ID
	,SCA
	,SCA_DATE
	,SDM
    ,SOP_REVIEW_DATE --240904 CR965
	,STE_DATE
    ,INSERT_DATE AS SYSTEM_CREATION_DATE --240904 CR965
	,SYSTEM_DESCRIPTION
	,SYSTEM_ID
	,TLC_PHASE
	,TOTALPOAMWITHAPPROVEDRBD
FROM CORE.SYSTEMS;

RECORD_COUNT := SQLROWCOUNT;
Msg := ''Inserted into SYSTEMSHIST='' || :RECORD_COUNT;
CALL CORE.SP_CRM_WRITE_MSGLOG (:Appl,:Msg); 
COMMIT;


----------------------------------------------------------------------
--            CFACTS_USERMAPPING
----------------------------------------------------------------------
TRUNCATE TABLE CORE.CFACTS_USERMAPPING;

BEGIN TRANSACTION;
INSERT INTO CORE.CFACTS_USERMAPPING
	(ACRONYM
	,ROLE
	,SYSTEM_ID
	,USER_ID
)
SELECT
    ACRONYM
	,ROLE
	,SYSTEM_ID
	,USER_ID
FROM CORE.VW_CFACTS_USERMAPPING;
COMMIT;

CALL CORE.SP_CRM_END_PROCEDURE (:Appl);

return ''Success'';

EXCEPTION
  when statement_error then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Statement_Error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when CRM_logic_exception then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''CRM_logic_exception'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
  when other then
    insert into CORE.ALERTLOG (APPL,CUSTOM_ERRMSG,ERRTYPE,SQLCODE,SQLERRM,SQLSTATE) VALUES(:APPL,:ExceptionMsg,''Other error'',:SQLCODE,:SQLERRM,:SQLSTATE);
    raise;
END;
';