create or replace secure view SEC_VW_CRM_MDR_EXPORT(
	ASSET_ID_TATTOO,
	DEVICEMODEL,
	DEVICEROLE,
	DEVICETYPE,
	DW_ASSET_ID,
	FISMA_ID,
	FQDN,
	HOSTNAME,
	IPV4,
	IPV6,
	IS_TENABLE_CREDENTIALED_SCAN,
	LAST_SEEN,
	MACADDRESS,
	MDR_FIRST_SEEN,
	MOTHERBOARD,
	NETBIOSNAME,
	OS,
	OS_CPE,
	VENDOR
) COMMENT='Export CRM MDR TO HHS'
 as
SELECT 
a.ASSET_ID_TATTOO
,a.DEVICEMODEL
,dr.DEVICEROLE
,a.DEVICETYPE
,a.DW_ASSET_ID
,s.SYSTEM_ID as FISMA_ID
,aic.FQDN
,aic.HOSTNAME
,aic.IPV4
,aic.IPV6
,a.IS_TENABLE_CREDENTIALED_SCAN
,a.LAST_CONFIRMED_TIME as LAST_SEEN
,aic.MACADDRESS
,a.INSERT_DATE as MDR_FIRST_SEEN
,a.MOTHERBOARD
,aic.NETBIOSNAME
,a.OS
,a.OS_CPE
,a.SOURCE_TOOL_LASTSEEN as VENDOR
FROM CORE.ASSET a
--join CORE.VW_SYSTEMS dc on upper(dc.SYSTEM_ID) = upper(a.DATACENTER_ID)
join CORE.VW_SYSTEMS s on upper(s.SYSTEM_ID) = upper(a.SYSTEM_ID)
left outer join CORE.DEVICETYPES dt on upper(dt.DEVICETYPE) = upper(a.DEVICETYPE)
left outer join CORE.DEVICEROLES dr on upper(dr.DEVICEROLE) = upper(dt.DEVICEROLE)
left outer join CORE.AssetInterfaceCoalesced aic on aic.DW_ASSET_ID = a.DW_ASSET_ID
Where a.IS_APPLICABLE = 1;