create or replace view VW_ASSETS(
	ASSET_ID_TATTOO,
	AWS_ACCOUNTID,
	AWS_INSTANCESTATUS,
	AZURE_SUBSCRIPTION_ID,
	BIGFIX_ASSET_ID,
	BIOS_GUID,
	CLOUD_ACCOUNT_ID,
	CLOUD_ID,
	COMPUTER_TYPE,
	DATACENTER_ACRONYM,
	DATACENTER_COMMONNAME,
	DATACENTER_ID,
	DATEMODIFIED,
	DEVICEMODEL,
	DEVICEROLE,
	DEVICETYPE,
	DW_ASSET_ID,
	ENVIRONMENT,
	FQDN,
	HOSTNAME,
	INSERT_DATE,
	IPV4,
	IPV6,
	IS_APPLICABLE,
	IS_FORESCOUT_MANAGED,
	IS_FROM_AWS_FEED,
	IS_ENDPOINT,
	IS_SCANNABLE,
	IS_TATTOOABLE,
	IS_TENABLE_CREDENTIALED_SCAN,
	LAST_CONFIRMED_TIME,
	LASTASSETUPDATE,
	LASTSEEN_CSM,
	LASTSEEN_HWAM,
	LASTSEEN_SWAM,
	LASTSEEN_VUL,
	MACADDRESS,
	MOTHERBOARD,
	NETBIOSNAME,
	OS,
	OS_BUILD_NUMBER,
	OS_CPE,
	OS_VERSION,
	SOURCE_TOOL_CREATE,
	SOURCE_TOOL_CSM,
	SOURCE_TOOL_HWAM,
	SOURCE_TOOL_LASTSEEN,
	SOURCE_TOOL_SWAM,
	SOURCE_TOOL_VUL,
	SYSTEM_ACRONYM,
	SYSTEM_COMMONNAME,
	SYSTEM_ID,
	TENABLEUUID,
	TENANT_ID,
	VULNRISKTOLERANCE
) COMMENT='CRITICAL; View reports active assets from ASSET (MDR) table. It is used throughout CRM\t'
 as
SELECT 
a.ASSET_ID_TATTOO
,a.AWS_ACCOUNTID -- 240530 CR902
,a.AWS_INSTANCESTATUS
,a.AZURE_SUBSCRIPTION_ID -- 241125 CR1038
,a.BIGFIX_ASSET_ID
,a.BIOS_GUID
,coalesce(a.AWS_ACCOUNTID,a.AZURE_SUBSCRIPTION_ID) as CLOUD_ACCOUNT_ID -- 241122 CR1038
,a.CLOUD_ID
,a.COMPUTER_TYPE
,dc.ACRONYM as DATACENTER_ACRONYM
,dc.COMMONNAME as DATACENTER_COMMONNAME
,a.DATACENTER_ID
,a.DATEMODIFIED
,a.DEVICEMODEL
,dr.DEVICEROLE
,a.DEVICETYPE
,a.DW_ASSET_ID
,a.ENVIRONMENT
,aic.FQDN
,aic.HOSTNAME
,a.INSERT_DATE
,aic.IPV4
,aic.IPV6
,a.IS_APPLICABLE
,a.IS_FORESCOUT_MANAGED -- 240709 CR931
,a.IS_FROM_AWS_FEED -- 240709 CR931
,a.IS_ENDPOINT -- 241212 CR1052
,a.IS_SCANNABLE
,a.IS_TATTOOABLE
,a.IS_TENABLE_CREDENTIALED_SCAN -- 240709 CR931
,a.LAST_CONFIRMED_TIME
,a.LASTASSETUPDATE
,a.LASTSEEN_CSM
,a.LASTSEEN_HWAM
,a.LASTSEEN_SWAM
,a.LASTSEEN_VUL
,aic.MACADDRESS
,a.MOTHERBOARD
,aic.NETBIOSNAME
,a.OS
,a.OS_BUILD_NUMBER -- 240821 CR958
,a.OS_CPE
,a.OS_VERSION
,a.SOURCE_TOOL_CREATE
,a.SOURCE_TOOL_CSM
,a.SOURCE_TOOL_HWAM
,a.SOURCE_TOOL_LASTSEEN
,a.SOURCE_TOOL_SWAM
,a.SOURCE_TOOL_VUL
,s.ACRONYM as SYSTEM_ACRONYM
,s.COMMONNAME as SYSTEM_COMMONNAME
,s.SYSTEM_ID
,a.TENABLEUUID
,a.TENANT_ID -- CR880 DRaaS Tenant_ID
,a.VULNRISKTOLERANCE
FROM CORE.Asset a
join CORE.VW_SYSTEMS dc on upper(dc.SYSTEM_ID) = upper(a.DATACENTER_ID)
join CORE.VW_SYSTEMS s on upper(s.SYSTEM_ID) = upper(a.SYSTEM_ID)
left outer join CORE.DeviceTypes dt on upper(dt.DEVICETYPE) = upper(a.DEVICETYPE)
left outer join CORE.DeviceRoles dr on upper(dr.DEVICEROLE) = upper(dt.DEVICEROLE)
left outer join CORE.AssetInterfaceCoalesced aic on aic.DW_ASSET_ID = a.DW_ASSET_ID

Where a.Is_Applicable = 1;