create or replace view VW_ASSET_SOFTWARE_BUS_MARKETPLACE_MSI(
	COMPONENT_ACRONYM,
	GROUP_ACRONYM,
	HVASTATUS,
	IS_MARKETPLACE,
	MEFSTATUS,
	OATO_CATEGORY,
	TLC_PHASE,
	SYSTEM_ACRONYM,
	SYSTEM_ID,
	ASSET_ID_TATTOO,
	AWS_INSTANCESTATUS,
	DATE_ASSET_CREATED,
	DATACENTER_ACRONYM,
	DATACENTER_ID,
	DEVICEROLE,
	DEVICETYPE,
	DW_ASSET_ID,
	ENVIRONMENT,
	FQDN,
	HOSTNAME,
	IPV4,
	IPV6,
	IS_SCANNABLE,
	IS_TENABLE_CREDENTIALED_SCAN,
	LASTSEEN_HWAM,
	MACADDRESS,
	NETBIOSNAME,
	OS,
	OS_VERSION,
	SOURCE_TOOL_LASTSEEN,
	DATE_SOFTWARE_CREATED,
	DATE_INSTALLED,
	DW_SWAM_ID,
	FIRSTSEEN,
	LASTSEEN,
	MAJOR,
	MINOR,
	SOFTWARENAME,
	SOURCE_TOOL,
	SWAM_CATEGORY,
	SWAM_SUBCATEGORY,
	VENDOR,
	VERSION
) COMMENT='Software associated with each Marketplace asset\t'
 as
select
--
-- System identifying data
--
s.COMPONENT_ACRONYM
,s.GROUP_ACRONYM
,s.HVASTATUS
,s.IS_MARKETPLACE
,s.MEFSTATUS
,s.OATO_CATEGORY
,s.TLC_PHASE
,a.SYSTEM_ACRONYM
,a.SYSTEM_ID
--
-- Asset identifying data
--
,a.ASSET_ID_TATTOO
,a.AWS_INSTANCESTATUS
,TO_CHAR(a.INSERT_DATE,'MM/DD/YYYY') as DATE_ASSET_CREATED
,a.DATACENTER_ACRONYM
,a.DATACENTER_ID
,a.DEVICEROLE
,a.DEVICETYPE
,a.DW_ASSET_ID
,upper(a.environment) as ENVIRONMENT
,a.FQDN
,a.HOSTNAME
,a.IPV4
,a.IPV6
,a.IS_SCANNABLE
,a.IS_TENABLE_CREDENTIALED_SCAN
,a.LASTSEEN_HWAM
,a.MACADDRESS
,a.NETBIOSNAME
,a.OS
,a.OS_VERSION
,a.SOURCE_TOOL_LASTSEEN
--
-- Software
--
,TO_CHAR(soft.INSERT_DATE,'MM/DD/YYYY') as DATE_SOFTWARE_CREATED
,TO_CHAR(soft.DATEINSTALLED,'MM/DD/YYYY') as DATE_INSTALLED
,soft.DW_SWAM_ID -- Unique ID representing one Asset/Software
,TO_CHAR(soft.FIRSTSEEN,'MM/DD/YYYY') as FIRSTSEEN
,TO_CHAR(soft.LASTSEEN,'MM/DD/YYYY') as LASTSEEN
,soft.MAJOR
,soft.MINOR
--,soft.PRODUCTNAME
,soft.SOFTWARENAME
,soft.SOURCE_TOOL
,soft.SWAM_CATEGORY
,soft.SWAM_SUBCATEGORY
,soft.VENDOR
,soft.VERSION
FROM CORE.VW_ASSETS a
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = a.SYSTEM_ID
JOIN CORE.ASSET_SOFTWARE soft on soft.DW_ASSET_ID = a.DW_ASSET_ID
;