create or replace view VW_AWS_CAMPDB_LOOKUP_V2(
	DATE,
	ACCOUNT_NUMBER,
	DATACENTER_ID,
	DATACENTER_ACRONYM,
	CAMP_SYSTEM_ACRONYM,
	VERIFIED_SYSTEM_ACRONYM,
	VERIFIED_SYSTEM_ID,
	VERIFIED_TLC_PHASE,
	SEC_VW_FISMA_LOOKUPS_FISMA,
	APP_PHASE_NAME,
	ACCOUNT_NAME,
	ACCOUN_TYPE,
	LONG_APP_NAME,
	SHORT_APP_NAME,
	APP_LIVE_STATUS,
	ADO_TECH_MANAGER_EMAIL,
	ENV_NAME,
	MARKETPLACE,
	MEDIC_OE_EFFECT,
	OE_EFFECT,
	PLATFORM_NAME,
	PROJ_PHASE,
	ID,
	FILE_NAME,
	FILE_LAST_MODIFIED
) COMMENT='CRITICAL; Replacement for SEC_VW_FISMA_CAMP which comes from CAMP DB. Validates/Resolves SYSTEM_ACRONYM if common-name\t'
 as
SELECT 
--
-- SEC_VW_FISMA_CAMP has following critical columns:
-- a) ACCOUNT_NUMBER (AWS account number and MAG SUBSCRIPTION_ID)
--    Use upper function on ACCOUNT_NUMBER to resolve case issues i.e. Normalize the ACCOUNT_NUMBER
-- b) SYSTEM_ACRONYM which is not the preferred column for identifying FISMA System because of human inconsistencies (e.g. case or use of common acronym)
--    Instead we will join SEC_VW_FISMA_CAMP to SEC_VW_FISMA_LOOKUPS based on ACCOUNT_NUMBER to obtain the FISMA (ID)
--
-- SEC_VW_FISMA_LOOKUPS contains DATA_CENTER (ID)
--
-- CAMP DB (source) can have/has user induced errors. Plan is to send CFACTS data to CAMP DB to obtain consistency.
-- We use UPPER function to improve the odds of matching DATACENTER_ID and SYSTEM_ID.
--
camp.DATE
,camp.ACCOUNT_NUMBER
,lua.DATACENTER_ID
,lua.DATACENTER_ACRONYM
,camp.SYSTEM_ACRONYM as CAMP_SYSTEM_ACRONYM
,lua.VERIFIED_SYSTEM_ACRONYM
,lua.VERIFIED_SYSTEM_ID
,lua.VERIFIED_TLC_PHASE
,lua.SEC_VW_FISMA_LOOKUPS_FISMA
,camp.APP_PHASE_NAME
,camp.ACCOUNT_NAME
,camp.ACCOUN_TYPE
,camp.LONG_APP_NAME
,camp.SHORT_APP_NAME
,camp.APP_LIVE_STATUS
,camp.ADO_TECH_MANAGER_EMAIL
,camp.ENV_NAME
,camp.MARKETPLACE
,camp.MEDIC_OE_EFFECT
,camp.OE_EFFECT
,camp.PLATFORM_NAME
,camp.PROJ_PHASE
,camp.ID
,camp.FILE_NAME
,camp.FILE_LAST_MODIFIED
FROM REF_LOOKUPS.PUBLIC.SEC_VW_FISMA_CAMP camp

LEFT OUTER JOIN (select DISTINCT flu.ACCOUNT_NUMBER,flu.DATA_CENTER as DATACENTER_ID
    ,dc.ACRONYM as DATACENTER_ACRONYM
    ,flu.FISMA as SEC_VW_FISMA_LOOKUPS_FISMA
    ,coalesce(s.ACRONYM,sa.ACRONYM,sc.ACRONYM,'Cant determine CAMPDB SYSTEM_ACRONYM') as VERIFIED_SYSTEM_ACRONYM
    ,coalesce(s.SYSTEM_ID,sa.SYSTEM_ID,sc.SYSTEM_ID,'Cant determine CAMPDB SYSTEM_ID') as VERIFIED_SYSTEM_ID
    ,coalesce(s.TLC_PHASE,sa.TLC_PHASE,sc.TLC_PHASE,'Cant determine CAMPDB TLC_PHASE') as VERIFIED_TLC_PHASE
    FROM REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS flu
    LEFT OUTER JOIN CORE.VW_SYSTEMS dc on upper(dc.SYSTEM_ID) = upper(flu.DATA_CENTER)
    LEFT OUTER JOIN CORE.VW_SYSTEMS s on upper(s.SYSTEM_ID) = upper(flu.FISMA)
    LEFT OUTER JOIN CORE.VW_SYSTEMS sa on upper(sa.ACRONYM) = upper(flu.SYSTEM_ACRONYM)
    LEFT OUTER JOIN CORE.VW_SYSTEMS sc on upper(sc.COMMONNAME) = upper(flu.SYSTEM_ACRONYM)) lua on upper(lua.ACCOUNT_NUMBER) = upper(camp.ACCOUNT_NUMBER)
/*
 LEFT OUTER JOIN (select DISTINCT flu.ACCOUNT_NUMBER,flu.DATA_CENTER as DATACENTER_ID
    ,dc.ACRONYM as DATACENTER_ACRONYM
    ,flu.FISMA as SEC_VW_FISMA_LOOKUPS_FISMA
    ,coalesce(s.ACRONYM,sa.ACRONYM,sc.ACRONYM,'Cant determine CAMPDB SYSTEM_ACRONYM') as VERIFIED_SYSTEM_ACRONYM
    ,coalesce(s.SYSTEM_ID,sa.SYSTEM_ID,sc.SYSTEM_ID,'Cant determine CAMPDB SYSTEM_ID') as VERIFIED_SYSTEM_ID
    ,coalesce(s.TLC_PHASE,sa.TLC_PHASE,sc.TLC_PHASE,'Cant determine CAMPDB TLC_PHASE') as VERIFIED_TLC_PHASE
    FROM REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS flu
    LEFT OUTER JOIN CORE.VW_SYSTEMS dc on upper(dc.SYSTEM_ID) = upper(flu.DATA_CENTER)
    LEFT OUTER JOIN CORE.VW_SYSTEMS s on upper(s.SYSTEM_ID) = upper(flu.FISMA)
    LEFT OUTER JOIN CORE.VW_SYSTEMS sa on upper(sa.ACRONYM) = upper(flu.SYSTEM_ACRONYM)
    LEFT OUTER JOIN CORE.VW_SYSTEMS sc on upper(sc.COMMONNAME) = upper(flu.SYSTEM_ACRONYM)) lus on upper(lus.VERIFIED_SYSTEM_ACRONYM) = upper(camp.SYSTEM_ACRONYM) 
    */
;