create or replace view VW_APP_ARCHER_SYSTEMS(
	ACRONYM,
	ACTUAL_DECOMMISION_DATE,
	ARCHER_TRACKING_ID,
	ATO_EXPIRATION_DATE,
	ATO_REVIEW_DATE,
	AUTH_COMMENTS,
	AUTH_DECISION,
	AUTHORIZATION_MEMO_SIGNED_DATE,
	AUTHORIZATION_PACKAGE_NAME,
	BO_RECOMMENDATION_REVIEW_DATE,
	BO_REVIEW_DATE,
	BUSINESS_OWNER,
	CIO,
	CISO,
	CISO_REVIEW_DATE,
	CLOUD_SERVICE_PROVIDER,
	COMPONENT_ACRONYM,
	COMPONENT_DESCRIPTION,
	COMPONENT_NAME,
	COMPONENT_RISK_REPORTS_OVERSIGHT,
	CONTINGENCYEXPIRATIONDATE,
	CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID,
	CP_TEST_DATE,
	CP_TEST_RESULTS,
	CRA,
	CRA_REVIEW_DATE,
	CYBERVET,
	DATE_AUTH_MEMO_EXPIRES,
	DATE_AUTH_MEMO_SIGNED,
	DCISO,
	DIVISION_ACRONYM,
	DIVISION_DESCRIPTION,
	DIVISION_NAME,
	DSPC_REVIEW_DATE,
	DSPPO_REVIEW_DATE,
	E_AUTH_EXP_DATE,
	E_AUTH_LEVEL,
	E_AUTH_RISK_ASSESSMENT_DATE,
	FINANCIAL_SYSTEM,
	FIPS_199_AVAILABILITY_RATING,
	FIPS_199_CONFIDENTIALITY_RATING,
	FIPS_199_INTEGRITY_RATING,
	FIPS_199_OVERALL_IMPACT_RATING,
	FIRST_PUBLISHED_DATE,
	FISMA_SYSTEM,
	GROUP_ACRONYM,
	GROUP_DESCRIPTION,
	GROUP_NAME,
	HVA_SCORE,
	HVASTATUS,
	INFORMATION_SYSTEM_TYPE,
	IS_MARKETPLACE,
	IS_OA_READY,
	ISRA_REVIEW_DATE,
	ISRA_STATUS,
	ISSO,
	ISSO_COUNT,
	ISSO_REVIEW_DATE,
	ISSO_SUBMISSION_DATE,
	ISSOCS,
	LAST_ACT_DATE,
	LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE,
	LAST_ACT_SCA_FINAL_REPORT_DATE,
	LAST_PENTEST_CAAT_PROCESSED_FILE_DATE,
	LAST_PENTEST_DATE,
	MEF,
	MEF_CONTEXT,
	NEXT_REQUIRED_CP_TEST_DATE,
	OA_STATUS,
	OPERATED_BY,
	PACKAGE_TYPE,
	PIA_014,
	PIA_EXPIRATION_DATE,
	PRIMARY_ISSO,
	PRIMARY_OPERATING_LOCATION,
	REASON_FOR_ATO_REQUEST,
	SCA,
	SCA_DATE,
	SDM,
	SOP_REVIEW_DATE,
	STE_DATE,
	SYSTEM_DESCRIPTION,
	SYSTEM_ID,
	TLC_PHASE
) COMMENT='APP_ARCHER (CFACTS) System detail'
 as
WITH
/*
W_ATO as (-- There can be multiple records per FISMA System so find the most current
    select t.*
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_ATO_REQUEST_REPORT t
    JOIN (select rank()over(partition by IDUID order by _content_id desc) TheRank,_content_id
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_ATO_REQUEST_REPORT) r1 on r1._content_id = t._content_id 
    WHERE r1.TheRank = 1),
*/
W_ATO as (select INFORMATION_SYSTEM_OR_PACKAGE[0].ContentId::varchar as system_contentId, *
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_ATO_REQUEST_REPORT),    
W_BO as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => CONTROL_OWNER_CO:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_CIO as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => AUTHORIZING_OFFICIAL_AO:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_CISO as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => CHIEF_INFORMATION_SECURITY_OFFICER_CISO:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_COMPRISK as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES -- Component Report POC
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => COMPONENT_RISK_REPORTS_OVERSIGHT:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),  
W_CRA as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => CYBER_RISK_ADVISOR_CRA:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_DCISO as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => INFORMATION_SYSTEM_OWNER_ISO:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_DIVISION as (select division,component_acronym,component_name_,description,division_acronym,group_name
    ,f.value:ContentId::string as system_contentId
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_DIVISION_REPORT
    join table(flatten(AUTHORIZATION_PACKAGES,outer=>true)) as f),
W_INFOTYPES as (select infotypes.*,f.value:ContentId::string as system_contentId
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_INFORMATION_TYPES_REPORT infotypes
    join table(flatten(AUTHORIZATION_PACKAGE,outer=>true)) as f
    where tracking_id = 220862 -- Financial, budgetary, commercial, proprietary and trade secret information
    ),
W_ISSO as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES -- 250303 Sort
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => INFORMATION_SYSTEM_SECURITY_OFFICER_ISSO:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_ISSOCS as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => ISSO_CONTRACTOR_SUPPORT_ISSOCS:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_PIA as (select AUTHORIZATION_PACKAGE[0].ContentId::varchar as system_contentId, *
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_PRIVACY_IMPACT_ASSESSMENT_PIA_REPORT),    
W_PRIMARY_CRA as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => DSPC_POC:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_PRIMARY_ISSO as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => PRIMARY_INFORMATION_SYSTEM_SECURITY_OFFI:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID),
W_SCA as (SELECT IDUID ,listagg(GROUP_LIST.value:DisplayName::string,';') as GROUP_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => SECURITY_CONTROL_ASSESSOR_SCA:Groups) GROUP_LIST
  GROUP BY IDUID),
W_SDM as (SELECT IDUID, listagg(u.DISPLAYNAME,';') WITHIN GROUP (order by u.DISPLAYNAME) as USER_NAMES
    from APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
    LATERAL FLATTEN(input => INFORMATION_SYSTEM_ADMINISTRATOR_ISA:Users) USER_LIST
    JOIN APP_ARCHER.PRIVATE.__META_USERS u on u.username = USER_LIST.value:UserName::string
    GROUP BY IDUID)

SELECT
--
-- TODO
-- Resolve multiple ATO records
-- Resolve multiple GROUP records
-- Resolve multiple __REPORT_CONTENT_CFACTS_SDL_INFORMATION_TYPES_REPORT records
-- Resolve HVA_SCORE
--
ap.ACRONYM as ACRONYM
,ap.ACTUAL_DECOMMISION_DATE as ACTUAL_DECOMMISION_DATE
,ap._content_id as ARCHER_TRACKING_ID
-- maybe wrong,ato.PACKAGE_ATO_EXPIRATION_DATE as ATO_EXPIRATION_DATE

,ato.ATO_EXPIRATION_DATE as ATO_EXPIRATION_DATE

--,case when try_to_date(ato.COPY_OF_BO_REQUEST_REVIEW_DATE_1,'MMMM DD, YYYY') is not null then TO_DATE(ato.COPY_OF_BO_REQUEST_REVIEW_DATE_1,'MMMM DD, YYYY') Else null end as ATO_REVIEW_DATE
,ato.COPY_OF_BO_REQUEST_REVIEW_DATE_1 as ATO_REVIEW_DATE

,ato.ATO_MEMO_TEXT as AUTH_COMMENTS
,ap.AUTHORIZATION_DECISION[0]::varchar as AUTH_DECISION
-- might be wrong ,ac.DATE_AUTHORIZATION_MEMO_SIGNED as AUTHORIZATION_MEMO_SIGNED_DATE
,ato.CIO_SUBMITTED_DATE as AUTHORIZATION_MEMO_SIGNED_DATE

,ap.AUTHORIZATION_PACKAGE_NAME as AUTHORIZATION_PACKAGE_NAME
-- maybe wrong ,ato.BUSINESS_OWNER_APPROVED_DATE as BO_RECOMMENDATION_REVIEW_DATE

,ato.COPY_OF_BO_REQUEST_REVIEW__DUE_DATE as BO_RECOMMENDATION_REVIEW_DATE

-- maybe wrong ,ra.BUSINESS_OWNER_REVIEW_DATE as BO_REVIEW_DATE

,ato.BO_SUBMITTED_DATE as BO_REVIEW_DATE

,bo.USER_NAMES as BUSINESS_OWNER
,cio.USER_NAMES as CIO
,ciso.USER_NAMES as CISO
-- maybe wrong,ra.CISO_REVIEW_DATE as CISO_REVIEW_DATE

,ato.CISO_SUBMITTED_DATE as CISO_REVIEW_DATE

,array_to_string(ap.CLOUDSERVICEPROVIDERS,',') as CLOUD_SERVICE_PROVIDER -- 250303
,ap.COMPONENT_ACRONYM as COMPONENT_ACRONYM
,comp.DESCRIPTION as COMPONENT_DESCRIPTION
,ap.COMPONENT_NAME_ as COMPONENT_NAME
,cro.USER_NAMES as COMPONENT_RISK_REPORTS_OVERSIGHT
,ap.LAST_CONTINGENCY_PLAN_EXPIRATION_DATE as CONTINGENCYEXPIRATIONDATE
,ap.CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID as CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID
,ap.LAST_CONTINGENCY_PLAN_TEST_DATE as CP_TEST_DATE
,ap.CONTINGENCY_PLAN_TEST_RESULTS[0]::varchar as CP_TEST_RESULTS
,cra.USER_NAMES as CRA
,ato.CRA_SUBMITTED_DATE as CRA_REVIEW_DATE
,pcra.USER_NAMES as CYBERVET -- This differs from CRA in CFACTS view. Is it same as DSPC_POC / Primary Cyber Risk Advisor (CRA)
-- maybe wrong,ato.PACKAGE_ATO_EXPIRATION_DATE as DATE_AUTH_MEMO_EXPIRES

,ato.ATO_EXPIRATION_DATE as DATE_AUTH_MEMO_EXPIRES
,case when try_to_date(ato.ATO_MEMO_DATE,'MMMM DD, YYYY') is not null then TO_DATE(ato.ATO_MEMO_DATE,'MMMM DD, YYYY') Else null end as DATE_AUTH_MEMO_SIGNED
,dciso.USER_NAMES as DCISO
,div.DIVISION_ACRONYM as DIVISION_ACRONYM
,CORE.FN_CRM_CLEANSTRING(div.DESCRIPTION) as DIVISION_DESCRIPTION
,ap.DIVISION_NAME as DIVISION_NAME
-- maybe wrong,ra.DSPC_REVIEW_DATE as DSPC_REVIEW_DATE
,ato.DSPC_SUBMITTED_DATE as DSPC_REVIEW_DATE

-- maybe wrong,ato.DSPPO_APPROVED_DATE as DSPPO_REVIEW_DATE

,ato.DSPPO_SUBMITTED_DATE as DSPPO_REVIEW_DATE
,ap.EAUTHENTICATION_EXPIRATION_DATE as E_AUTH_EXP_DATE -- 250303
,ap.EAUTHENTICATION_LEVEL[0]::varchar as E_AUTH_LEVEL
,ap.EAUTHENTICATION_DATE as E_AUTH_RISK_ASSESSMENT_DATE -- 250303
,ap.FINANCIAL_SYSTEM[0]::varchar as FINANCIAL_SYSTEM
,infotype.AVAILABILITY_RATING[0]::varchar as FIPS_199_AVAILABILITY_RATING
,infotype.CONFIDENTIALITY_RATING[0]::varchar as FIPS_199_CONFIDENTIALITY_RATING
,infotype.INTEGRITY_RATING[0]::varchar as FIPS_199_INTEGRITY_RATING
,cedar.FINAL_SECURITY_CATEGORY[0]::varchar as FIPS_199_OVERALL_IMPACT_RATING
,ap.FIRST_PUBLISHED as FIRST_PUBLISHED_DATE
,ap.FISMA_REPORTABLE[0]::varchar as FISMA_SYSTEM
,'FAKE' as GROUP_ACRONYM
,'FAKE' as GROUP_DESCRIPTION
,ap.GROUP_NAME as GROUP_NAME
,ap.BASELINE_HIGHEST_DEVICE_RISK_SCORE as HVA_SCORE
,ap.IS_THIS_SYSTEM_ON_THE_HVA_TRACKING_LIST[0]::varchar as HVASTATUS
,ap.INFORMATION_SYSTEM_TYPE[0]::varchar as INFORMATION_SYSTEM_TYPE

,case IFNULL(ap.MARKETPLACE_SYSTEMS[0]::varchar,'0') When 'Yes' then '1' Else '0' End as IS_MARKETPLACE

,NULL as IS_OA_READY -- NO LONGER NEEDED BECAUSE SDW NOW DETERMINES THIS

,ato.DATE_ISRA_LAST_UPDATED_OR_REVIEWED as ISRA_REVIEW_DATE

-- maybe wrong,,ap.LAST_ISRA_COMPLETION_DATE as ISRA_REVIEW_DATE
,ap.ISRA_STATUS[0]::varchar as ISRA_STATUS
,isso.USER_NAMES as ISSO
,array_size(INFORMATION_SYSTEM_SECURITY_OFFICER_ISSO:Users) as ISSO_COUNT
,ato.ISSO_REVIEW_DUE_DATE as ISSO_REVIEW_DATE
,ato.ISSO_SUBMITTED_DATE as ISSO_SUBMISSION_DATE
,issocs.USER_NAMES as ISSOCS
,ap.LAST_ACT_DATE as LAST_ACT_DATE
,ap.LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE as LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE
,ap.LAST_ACT_SCA_FINAL_REPORT_DATE as LAST_ACT_SCA_FINAL_REPORT_DATE
,ap.LAST_PENTEST_CAAT_PROCESSED_FILE_DATE as LAST_PENTEST_CAAT_PROCESSED_FILE_DATE
,ap.LAST_PENTEST_DATE as LAST_PENTEST_DATE
,ap.IS_THIS_HVA_NECESSARY_TO_PERFORM_MEF[0]::varchar as MEF
,ap.MISSION_ESSENTIAL_FUNCTIONS_[0]::varchar as MEF_CONTEXT -- Multiple values possible
-- MEFStatus is determined in SP_CRM_PULL_CFACTS
,ap.NEXT_REQUIRED_CONTINGENCY_PLAN_TEST_DATE as NEXT_REQUIRED_CP_TEST_DATE
,ap.OA_STATUS[0]::varchar as OA_STATUS
,ap.OPERATED_BY[0]::varchar as OPERATED_BY
,ap.PACKAGE_TYPE[0]::varchar as PACKAGE_TYPE
,pia.HELPER_PIA014[0]::varchar as PIA_014
,ap.PIA_EXPIRATION_DATE as PIA_EXPIRATION_DATE
,pisso.USER_NAMES as PRIMARY_ISSO
,ARRAY_TO_STRING(ap.OPERATING_LOCATION,',') as PRIMARY_OPERATING_LOCATION
,ato.REASON_FOR_ATO_REQUEST[0]::varchar as REASON_FOR_ATO_REQUEST
,sca.GROUP_NAMES as SCA
,ap.SCA_DATE as SCA_DATE
,sdm.USER_NAMES as SDM
,ato.SDM_REVIEW_DUE_DATE as SOP_REVIEW_DATE -- 250303 VW_CFACTS_SYSTEMS was using SDM_REVIEW_DUE_DATE
,ap.STE_DATE as STE_DATE
,CORE.FN_CRM_CLEANSTRING(ap.SYSTEMDESCRIPTION_TRUNCATED) as SYSTEM_DESCRIPTION
,ap.IDUID as SYSTEM_ID
,ap.TLC_PHASE[0]::varchar as TLC_PHASE
FROM APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT ap
LEFT OUTER JOIN APP_ARCHER.PRIVATE.__REPORT_CONTENT_CEDAR_EASI_INTEGRATION_NO_FILTERS_ cedar on cedar.IDUID = ap.IDUID
LEFT OUTER JOIN APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_ALLOCATED_CONTROLS_REPORT ac on ac._content_id = ap._CONTENT_ID
--
-- ALERT: component_acronym is not unique and component_name is not unique
--
LEFT OUTER JOIN APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_COMPONENT_REPORT comp on comp.component_acronym = ap.component_acronym
--
-- Division does appear to be unique
-- LEFT OUTER JOIN APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_DIVISION_REPORT div on div.division = ap.division_name
--
-- Alert: group_name is not unique and group_acronym is not unique
--
--LEFT OUTER JOIN APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_GROUP_REPORT grp on grp.group_name = ap.group_name

LEFT OUTER JOIN W_ATO ato on ato.system_contentId = ap._CONTENT_ID
LEFT OUTER JOIN W_BO bo on bo.IDUID = ap.IDUID
LEFT OUTER JOIN W_CIO cio on cio.IDUID = ap.IDUID
LEFT OUTER JOIN W_CISO ciso on ciso.IDUID = ap.IDUID
LEFT OUTER JOIN W_COMPRISK cro on cro.IDUID = ap.IDUID
LEFT OUTER JOIN W_CRA cra on cra.IDUID = ap.IDUID
LEFT OUTER JOIN W_DCISO dciso on dciso.IDUID = ap.IDUID
LEFT OUTER JOIN W_DIVISION div on div.system_contentId = ap._CONTENT_ID
LEFT OUTER JOIN W_INFOTYPES infotype on infotype.system_contentId = ap._CONTENT_ID
LEFT OUTER JOIN W_ISSO isso on isso.IDUID = ap.IDUID
LEFT OUTER JOIN W_ISSOCS issocs on issocs.IDUID = ap.IDUID
LEFT OUTER JOIN W_PIA pia on pia.system_contentId = ap._CONTENT_ID
LEFT OUTER JOIN W_PRIMARY_CRA pcra on pcra.IDUID = ap.IDUID
LEFT OUTER JOIN W_PRIMARY_ISSO pisso on pisso.IDUID = ap.IDUID
LEFT OUTER JOIN W_SCA sca on sca.IDUID = ap.IDUID
LEFT OUTER JOIN W_SDM sdm on sdm.IDUID = ap.IDUID

LEFT OUTER JOIN APP_ARCHER.PRIVATE.__REPORT_CONTENT_CFACTS_SDL_RISK_ACCEPTANCE_RBD_REPORT ra on ra.SYSTEM_TRACKING_ID = ap._content_id
WHERE ap.IDUID IS NOT NULL
;