create or replace view VW_APP_ARCHER_ALLOCATEDCONTROL_TEST(
	ALLOCATION_STATUS,
	CONTROL_ELEMENT_NUMBER,
	CONTROL_FAMILY,
	CONTROL_NAME,
	CONTROL_NUMBER,
	CONTROL_NUMBER_COMBO,
	CONTROL_SET_VERSION_NUMBER,
	LAST_ACT_DATE,
	LAST_ASSESSMENT_DATE,
	LAST_PENTEST_DATE,
	LAST_SCA_DATE,
	OVERALL_CONTROL_STATUS,
	PRIVATE_IMP_UPDATED_DATE,
	PRIVATE_IMPLEMENTATION_DETAILS,
	RESPONSIBILITY,
	SHARED_IMP_UPDATED_DATE,
	SIGNIFICANT_CONTROL_CHANGE_DETAILS,
	SYSTEM_ID,
	TRACKING_ID
) COMMENT='APP_ARCHER (CFACTS) Parent level view of controls allocated to a system.'
 as 
SELECT
ac.ALLOCATION_STATUS[0]::varchar as ALLOCATION_STATUS
-- NEWQ,ac.CONTROL as CONTROL_ELEMENT -- Long description
,ac.CONTROL_ELEMENT_NUMBER as CONTROL_ELEMENT_NUMBER -- Has enhancement e.g. PM-03a
,ac.CONTROL_FAMILY[0]::varchar as CONTROL_FAMILY
,ac.CONTROL_NAME as CONTROL_NAME
,ac.CONTROL_NUMBER as CONTROL_NUMBER
,ac.CONTROL_ELEMENT_NUMBER_COMBO as CONTROL_NUMBER_COMBO
,ap.CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID as CONTROL_SET_VERSION_NUMBER 
-- NEWQ ,ac.ALLOCATED__HYBRID_YES[0]::varchar as HYBRID_CONTROL
-- NEWQ ,ac.INHERITABLE[0]::varchar as INHERITABLE_BY_OTHER_SYSTEMS
,ac.LAST_ACT_DATE as LAST_ACT_DATE
,ac.LAST_ASSESSMENT_DATE as LAST_ASSESSMENT_DATE
,ac.LAST_PENTEST_DATE as LAST_PENTEST_DATE
,ac.LAST_ACTSCA_FINAL_REPORT_DATE as LAST_SCA_DATE
,ac.OVERALL_CONTROL_ELEMENT_STATUS[0]::varchar as OVERALL_CONTROL_STATUS
,ac.IMPLEMENTATION_DETAILS_LAST_UPDATED as PRIVATE_IMP_UPDATED_DATE
,ac.PRIVATE_ALLOCATED_IMPLEMENTATION_DETAILS as PRIVATE_IMPLEMENTATION_DETAILS
,ac.RESPONSIBILITY as RESPONSIBILITY
,ac.SHARED_IMPLEMENTATION_DETAILS_UPDATED_DA as SHARED_IMP_UPDATED_DATE
-- NEWQ ,ac.SIGNIFICANT_CONTROL_CHANGE[0]::varchar as SIGNIFICANT_CONTROL_CHANGE -- Y/N in APP_CFACTS
,ac.SIGNIFICANT_CONTROL_CHANGE_DETAILS as SIGNIFICANT_CONTROL_CHANGE_DETAILS -- APP_CFACTS.SHARED.SEC_VW_ALLOCATED_CONTROLS_CONTROL_STANDARDS
,ap.IDUID as SYSTEM_ID
,ac.TRACKING_ID as TRACKING_ID
FROM APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT ap
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_ALLOCATED_CONTROLS_ELEMENTS_REPORT ac on ac.FISMA_ID = ap.IDUID


-- __REPORT_CONTENT_CFACTS_SDL_ALLOCATED_CONTROLS_ELEMENTS_REPORT.SIGNIFICANT_CONTROL_CHANGE_DETAILS
-- __REPORT_CONTENT_CFACTS_SDL_ALLOCATED_CONTROLS_ELEMENTS_REPORT.CONTROL_ELEMENT_NUMBER

;