create or replace view VW_APP_ARCHER_USERMAPPING(
	ACRONYM,
	COMPONENT_ACRONYM,
	GROUP_ACRONYM,
	ROLE,
	SYSTEM_ID,
	USER_ID,
	USER_LEVEL_ROLE
) COMMENT='Map APP_ARCHER (CFACTS) users to system, component, group and role'
 as
SELECT s.ACRONYM
,s.COMPONENT_ACRONYM 
,s.GROUP_ACRONYM
,user_sys.ROLE
,s.SYSTEM_ID
,u.username as USER_ID
,r.name as USER_LEVEL_ROLE
FROM APP_ARCHER.DEV_PRIVATE.__META_USERS u
LEFT OUTER JOIN APP_ARCHER.DEV_PRIVATE.__META_ROLE_MEMBERSHIPS rm on rm.USERID = u.ID
LEFT OUTER JOIN APP_ARCHER.DEV_PRIVATE.__META_ROLES r on r.ID = rm.ROLEID
LEFT OUTER JOIN (

SELECT IDUID as FISMA_ID, 'CISO' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => CHIEF_INFORMATION_SECURITY_OFFICER_CISO:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'BO' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => CONTROL_OWNER_CO:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'Component Report POC' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => COMPONENT_RISK_REPORTS_OVERSIGHT:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'CRA' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => CYBER_RISK_ADVISOR_CRA:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'Primary CRA' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => DSPC_POC:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'SDM' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => INFORMATION_SYSTEM_ADMINISTRATOR_ISA:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'Deputy CISO' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => INFORMATION_SYSTEM_OWNER_ISO:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'ISSO' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => INFORMATION_SYSTEM_SECURITY_OFFICER_ISSO:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'ISSOCS' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => ISSO_CONTRACTOR_SUPPORT_ISSOCS:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'Primary ISSO' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => PRIMARY_INFORMATION_SYSTEM_SECURITY_OFFI:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'SA' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => SECURITY_CONTROL_ASSESSOR_SCA:Users) USER_LIST
--
-- Additional tables added 2/25/25
--
UNION ALL
SELECT IDUID as FISMA_ID, 'SRO' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => SYSTEM_OBSERVER:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'CIO' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => AUTHORIZING_OFFICIAL_AO:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'DCIO' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => DEPUTY_CHIEF_INFORMATION_OFFICER_DCIO:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'GTL' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => GOVERNMENT_TECHNICAL_LEAD_GTL:Users) USER_LIST
UNION ALL
SELECT IDUID as FISMA_ID, 'Default Record Permissions' ROLE, USER_LIST.value:UserName::string as USER_ID
from APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT,
LATERAL FLATTEN(input => DEFAULT_RECORD_PERMISSIONS:Users) USER_LIST
--
-- Group/User relationship
--
UNION ALL
SELECT NULL as FISMA_ID, 'TESTGROUP: ISPG Fed Staff' ROLE, u.username  as USER_ID
FROM APP_ARCHER.DEV_PRIVATE.__META_GROUP_MEMBERSHIPS gm
JOIN APP_ARCHER.DEV_PRIVATE.__META_USERS u on u.ID = gm.userid
WHERE gm.GROUPID = 102
UNION ALL
SELECT NULL as FISMA_ID, 'TESTGROUP: ISPG Contractor Staff' ROLE, u.username  as USER_ID
FROM APP_ARCHER.DEV_PRIVATE.__META_GROUP_MEMBERSHIPS gm
JOIN APP_ARCHER.DEV_PRIVATE.__META_USERS u on u.ID = gm.userid
WHERE gm.GROUPID = 216
UNION ALL
SELECT NULL as FISMA_ID, 'TESTGROUP: CMS Read Only' ROLE, u.username  as USER_ID
FROM APP_ARCHER.DEV_PRIVATE.__META_GROUP_MEMBERSHIPS gm
JOIN APP_ARCHER.DEV_PRIVATE.__META_USERS u on u.ID = gm.userid
WHERE gm.GROUPID = 130

) user_sys on user_sys.USER_ID = u.username
left outer join CORE.VW_SYSTEMS s on s.SYSTEM_ID = user_sys.FISMA_ID
WHERE u.ACCOUNTSTATUS in (1) -- 1,2,3

/*
--
-- FROM Jen
--
CHIEF_INFORMATION_SECURITY_OFFICER_CISO	Chief Information Security Officer (CISO)
CONTROL_OWNER_CO	Business Owner (BO)
COMPONENT_RISK_REPORTS_OVERSIGHT	Component Risk Reports Oversight
CYBER_RISK_ADVISOR_CRA	Cyber Risk Advisor (CRA)
DSPC_POC	Primary Cyber Risk Advisor (CRA)
INFORMATION_SYSTEM_ADMINISTRATOR_ISA	System Developer Maintainer (SDM)
INFORMATION_SYSTEM_OWNER_ISO	Deputy Chief Information Security Officer (DCISO)
INFORMATION_SYSTEM_SECURITY_OFFICER_ISSO	Information System Security Officer (ISSO)
ISSO_CONTRACTOR_SUPPORT_ISSOCS	ISSO Contractor Support (ISSOCS)
PRIMARY_INFORMATION_SYSTEM_SECURITY_OFFI	Primary Information System Security Offiver (ISSO)
SECURITY_CONTROL_ASSESSOR_SCA	Security Assessor (SA)
	
Added to integration	
SYSTEM_OBSERVER	System Read Only (SRO)
AUTHORIZING_OFFICIAL_AO	Chief Information Officer (CIO)
DEPUTY_CHIEF_INFORMATION_OFFICER_DCIO	Deputy Chief Information Officer (DCIO)
GOVERNMENT_TECHNICAL_LEAD_GTL	Government Technical Lead (GTL)
DEFAULT_RECORD_PERMISSIONS	Default Record Permissions
--------------------------------------------
select ROLE,count(1) Total from vw_cfacts_usermapping GROUP BY ROLE ORDER BY ROLE
ROLE	TOTAL
BO	351
CIO	384
CISO	384
CMS Read Only	140
CRA	257
Component Report POC	2819
Deputy CISO	384
ISPG Contractor Staff	114
ISPG Fed Staff	48
ISSO	1403
ISSO CS	1040
Primary CRA	586
Primary ISSO	346
SDM	337
*/

;