create or replace view VW_APP_ARCHER_PIA(
	DUE_DATE,
	FINAL_APPROVER,
	FINAL_APPROVER_DATE,
	FINAL_APPROVER_STATUS,
	HHS_PIA_REVIEW_DATE,
	HHS_PIA_STATUS,
	OVERALL_STATUS,
	PIA_TRACKING_ID,
	REVIEW_DATE,
	REVIEW_STATUS,
	REVIEWER,
	SUBMISSION_DATE,
	SUBMISSION_STATUS,
	SUBMITTER,
	SYSTEM_ID
) COMMENT='APP_ARCHER (CFACTS) Detail Privacy Impact Assessment (PIA).'
 as
SELECT
p.DUE_DATE as DUE_DATE
,p.FINAL_APPROVER__NEW:Users[0]:FirstName::varchar || ' ' || p.FINAL_APPROVER__NEW:Users[0]:LastName::varchar as FINAL_APPROVER
,p.FINAL_APPROVER_DATE as FINAL_APPROVER_DATE
,p.FINAL_APPROVER_STATUS[0]::varchar as FINAL_APPROVER_STATUS
,p.HHS_PIA_STATUS_DATE_ as HHS_PIA_REVIEW_DATE
,p.HSDW_ as HHS_PIA_STATUS
,p.OVERALL_STATUS[0]::varchar as OVERALL_STATUS
,p.PIA_ID as PIA_TRACKING_ID
,p.FINAL_APPROVER_DATE as REVIEW_DATE
,p.REVIEW_STATUS_1[0]::varchar as REVIEW_STATUS
,p.FINAL_APPROVER__NEW:Users[0]:FirstName::varchar || ' ' || p.FINAL_APPROVER__NEW:Users[0]:LastName::varchar as REVIEWER
,p.SUBMIT_DATE as SUBMISSION_DATE
,p.SUBMISSION_STATUS[0]::varchar as SUBMISSION_STATUS
,p.SUBMITTER:Users[0]:FirstName::varchar || ' ' || p.SUBMITTER:Users[0]:LastName::varchar as SUBMITTER
,ap.IDUID as SYSTEM_ID
FROM APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT ap
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_PRIVACY_IMPACT_ASSESSMENT_PIA_REPORT p on p.name_of_component[0]:ContentId = ap._content_id;