create or replace view VW_ASSETHIST(
	ASSET_ID_TATTOO,
	AWS_ACCOUNTID,
	AWS_INSTANCESTATUS,
	AZURE_SUBSCRIPTION_ID,
	BIGFIX_ASSET_ID,
	BIOS_GUID,
	CLOUD_ACCOUNT_ID,
	COMPUTER_TYPE,
	DATACENTER_ACRONYM,
	DATACENTER_COMMONNAME,
	DATACENTER_ID,
	DATEMODIFIED,
	DEVICEROLE,
	DEVICETYPE,
	DW_ASSET_ID,
	ENVIRONMENT,
	FQDN,
	HOSTNAME,
	ASSETHIST_ID,
	ASSET_DATECREATED,
	IPV4,
	IPV6,
	IS_ENDPOINT,
	IS_FORESCOUT_MANAGED,
	IS_SCANNABLE,
	IS_TATTOOABLE,
	IS_TENABLE_CREDENTIALED_SCAN,
	LAST_CONFIRMED_TIME,
	LASTASSETUPDATE,
	LASTSEEN_CSM,
	LASTSEEN_HWAM,
	LASTSEEN_SWAM,
	LASTSEEN_VUL,
	MACADDRESS,
	MOTHERBOARD,
	NETBIOSNAME,
	OS,
	OS_CPE,
	OS_VERSION,
	REPORT_DATE,
	REPORT_ID,
	SOURCE_TOOL_CREATE,
	SOURCE_TOOL_CSM,
	SOURCE_TOOL_HWAM,
	SOURCE_TOOL_LASTSEEN,
	SOURCE_TOOL_SWAM,
	SOURCE_TOOL_VUL,
	SYSTEM_ACRONYM,
	SYSTEM_COMMONNAME,
	SYSTEM_ID,
	TENABLEUUID,
	VULNRISKTOLERANCE
) COMMENT='Shows detail asset history '
 as
SELECT 
ah.ASSET_ID_TATTOO
,ah.AWS_ACCOUNTID -- 240624 CR913 added to ASSETHIST but need to coordinate wt Reporting Team for view change
,ah.AWS_INSTANCESTATUS
,ah.AZURE_SUBSCRIPTION_ID -- 241125 CR1038
,ah.BIGFIX_ASSET_ID
,ah.BIOS_GUID
,coalesce(ah.AWS_ACCOUNTID,ah.AZURE_SUBSCRIPTION_ID) as CLOUD_ACCOUNT_ID -- 241125 CR1038
,ah.COMPUTER_TYPE
,dc.ACRONYM as DATACENTER_ACRONYM
,dc.COMMONNAME as DATACENTER_COMMONNAME
,ah.DATACENTER_ID
,ah.DATEMODIFIED
,dr.DEVICEROLE
,dt.DEVICETYPE
,ah.DW_ASSET_ID
,ah.ENVIRONMENT
,aich.FQDN
,aich.HOSTNAME
,ah.ID as ASSETHIST_ID
,ah.ASSET_DATECREATED -- 240624 CR913 was a.INSERT_DATE
,aich.IPV4
,aich.IPV6
,ah.IS_ENDPOINT -- 241212 CR1052
,ah.IS_FORESCOUT_MANAGED -- 241011 CR1001
,ah.IS_SCANNABLE
,ah.IS_TATTOOABLE
,ah.IS_TENABLE_CREDENTIALED_SCAN -- 241011 CR1001
,ah.LAST_CONFIRMED_TIME
,ah.LASTASSETUPDATE
,ah.LASTSEEN_CSM
,ah.LASTSEEN_HWAM
,ah.LASTSEEN_SWAM
,ah.LASTSEEN_VUL
,aich.MACADDRESS
,ah.MOTHERBOARD
,aich.NETBIOSNAME
,ah.OS
,ah.OS_CPE
,ah.OS_VERSION
,r.REPORT_DATE
,r.REPORT_ID
,ah.SOURCE_TOOL_CREATE
,ah.SOURCE_TOOL_CSM
,ah.SOURCE_TOOL_HWAM
,ah.SOURCE_TOOL_LASTSEEN
,ah.SOURCE_TOOL_SWAM
,ah.SOURCE_TOOL_VUL
,s.ACRONYM as SYSTEM_ACRONYM
,s.COMMONNAME as SYSTEM_COMMONNAME
,ah.SYSTEM_ID -- 241024 CR-EBF was s.SYSTEM_ID which yielded null when system retired
,ah.TENABLEUUID
-- ,ah.TENANT_ID -- 240624 CR913 added to ASSETHIST but need to coordinate wt Reporting Team for view change
,ah.VULNRISKTOLERANCE
FROM CORE.REPORT_IDS r
JOIN CORE.ASSETHIST ah on ah.REPORT_ID = r.REPORT_ID
-- 240624 CR913 left outer join CORE.ASSET a on a.DW_ASSET_ID = ah.DW_ASSET_ID
left outer join CORE.DEVICETYPES dt on dt.DEVICETYPE = ah.DEVICETYPE
left outer join CORE.DEVICEROLES dr on dr.DEVICEROLE = dt.DEVICEROLE
left outer join CORE.ASSETINTERFACECOALESCEDHIST aich on aich.REPORT_ID = ah.REPORT_ID and aich.DW_ASSET_ID = ah.DW_ASSET_ID
left outer join CORE.VW_SYSTEMS dc on dc.SYSTEM_ID = ah.DATACENTER_ID
left outer join CORE.VW_SYSTEMS s on s.SYSTEM_ID = ah.SYSTEM_ID
;