create or replace view VW_APP_ARCHER_POAM(
	ACTUAL_COMPLETION_DATE,
	ACTUAL_LABOR_COST,
	CAAT,
	CAAT_ID,
	DAYS_OPEN,
	ESTIMATED_COMPLETION_DATE,
	FINDING_ID,
	FUNDING_SOURCE,
	LABOR_ESTIMATE,
	OVERALL_STATUS,
	POAM_CLOSED_DATE,
	POAM_ID,
	POAM_OWNER,
	POAM_REVIEWER,
	REVIEW_COMMENTS,
	REVIEW_DATE,
	REVIEW_STATUS,
	SCHEDULED_COMPLETION_DATE,
	SOURCE_AUDIT_TYPE_2,
	SUBMISSION_STATUS,
	SYSTEM_ID,
	TARGET,
	WEAKNESS_CREATION_DATE,
	WEAKNESS_ID,
	WEAKNESS_POC,
	WEAKNESS_RISK_LEVEL,
	WEAKNESS_SEVERITY
) COMMENT='APP_ARCHER (CFACTS) Parent level view of POAMs for a system.'
 as
SELECT
p.ACTUAL_COMPLETION_DATE as ACTUAL_COMPLETION_DATE
,p.ACTUAL_LABOR_COST as ACTUAL_LABOR_COST
,'CAAT-' || p.CAAT_ID as CAAT
,p.CAAT_ID as CAAT_ID
,p.DAYS_OPEN as DAYS_OPEN
,p.ESTIMATED_COMPLETION_DATE as ESTIMATED_COMPLETION_DATE
,p.FINDING_ID as FINDING_ID
,p.FUNDING_SOURCE[0]::varchar as FUNDING_SOURCE
,p.LABOR_ESTIMATE as LABOR_ESTIMATE
,p.OVERALL_STATUS[0]::varchar as OVERALL_STATUS
,p.POAM_CLOSED_DATE as POAM_CLOSED_DATE
,p.POAM_ID as POAM_ID
,p.POAM_OWNER_1:Users[0]:FirstName::varchar || ' ' || p.POAM_OWNER_1:Users[0]:LastName::varchar as POAM_OWNER
,p.POAM_REVIEWER:Users[0]:FirstName::varchar || ' ' || p.POAM_REVIEWER:Users[0]:LastName::varchar as POAM_REVIEWER
,p.REVIEW_COMMENTS as REVIEW_COMMENTS
,p.REVIEW_DATE as REVIEW_DATE
,p.REVIEW_STATUS[0]::varchar as REVIEW_STATUS
,p.SCHEDULED_COMPLETION_DATE as SCHEDULED_COMPLETION_DATE
,p.SOURCE_AUDIT_TYPE_2 as SOURCE_AUDIT_TYPE_2
,p.SUBMISSION_STATUS[0]::varchar as SUBMISSION_STATUS
,ap.IDUID as SYSTEM_ID
,p.CONTROL_NUMBER as TARGET
,p.CFACTS_10_WEAKNESS_CREATION_DATE as WEAKNESS_CREATION_DATE
,p.WEAKNESS_ID_NUMBER as WEAKNESS_ID
,p.WEAKNESS_POC_ROLE:Users[0]:FirstName::varchar || ' ' || p.WEAKNESS_POC_ROLE:Users[0]:LastName::varchar as WEAKNESS_POC
,p.WEAKNESS_RISK_LEVEL_1[0]::varchar as WEAKNESS_RISK_LEVEL
,p.WEAKNESS_SEVERITY[0]::varchar as WEAKNESS_SEVERITY
FROM APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT ap
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_POA_M_REPORT p on p.FISMA_ID = ap.IDUID;