create or replace view VW_APP_ARCHER_ALLOCATEDCONTROL_V2(
	ALLOCATION_STATUS,
	CONTROL_ELEMENT,
	CONTROL_ELEMENT_NUMBER,
	CONTROL_FAMILY,
	CONTROL_NAME,
	CONTROL_NUMBER,
	CONTROL_NUMBER_COMBO,
	CONTROL_SET_VERSION_NUMBER,
	HYBRID_CONTROL,
	INHERITABLE_BY_OTHER_SYSTEMS,
	LAST_ACT_DATE,
	LAST_ASSESSMENT_DATE,
	LAST_PENTEST_DATE,
	LAST_SCA_DATE,
	OVERALL_CONTROL_STATUS,
	PRIVATE_IMP_UPDATED_DATE,
	PRIVATE_IMPLEMENTATION_DETAILS,
	RESPONSIBILITY,
	SHARED_IMP_UPDATED_DATE,
	SIGNIFICANT_CONTROL_CHANGE,
	SIGNIFICANT_CONTROL_CHANGE_DETAILS,
	SYSTEM_ID,
	TRACKING_ID
) COMMENT='APP_ARCHER (CFACTS) Parent level view of controls allocated to a system.'
 as 
SELECT
ac.ALLOCATION_STATUS[0]::varchar as ALLOCATION_STATUS
,ac.CONTROL as CONTROL_ELEMENT -- Long description
,ace.CONTROL_ELEMENT_NUMBER as CONTROL_ELEMENT_NUMBER -- Has enhancement e.g. PM-03a
,ac.CONTROL_FAMILY[0]::varchar as CONTROL_FAMILY
,ac.CONTROL_NAME as CONTROL_NAME
,ac.CONTROL_NUMBER as CONTROL_NUMBER
,ac.CONTROL_NUMBER_COMBO as CONTROL_NUMBER_COMBO
,ap.CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID as CONTROL_SET_VERSION_NUMBER 
,ac.ALLOCATED__HYBRID_YES[0]::varchar as HYBRID_CONTROL
,ac.INHERITABLE[0]::varchar as INHERITABLE_BY_OTHER_SYSTEMS
,ac.LAST_ACT_DATE as LAST_ACT_DATE
,ac.ASSESSMENT_DATE as LAST_ASSESSMENT_DATE
,ac.LAST_PENTEST_DATE as LAST_PENTEST_DATE
,ac.LAST_ACT_SCA_FINAL_REPORT_DATE as LAST_SCA_DATE
,ac.OVERALL_CONTROL_STATUS[0]::varchar as OVERALL_CONTROL_STATUS
,ac.IMPLEMENTATION_LAST_UPDATED as PRIVATE_IMP_UPDATED_DATE
,ac.IMPLEMENTATION_DETAILS as PRIVATE_IMPLEMENTATION_DETAILS
,ac.RESPONSIBILITY as RESPONSIBILITY
,ac.SHARED_IMPLEMENTATION_DETAILS_UPDATED_ as SHARED_IMP_UPDATED_DATE
,ac.SIGNIFICANT_CONTROL_CHANGE[0]::varchar as SIGNIFICANT_CONTROL_CHANGE -- Y/N in APP_CFACTS
,ace.SIGNIFICANT_CONTROL_CHANGE_DETAILS as SIGNIFICANT_CONTROL_CHANGE_DETAILS -- APP_CFACTS.SHARED.SEC_VW_ALLOCATED_CONTROLS_CONTROL_STANDARDS
,ap.IDUID as SYSTEM_ID
,ac.TRACKING_ID as TRACKING_ID
FROM APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT ap
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_ALLOCATED_CONTROLS_REPORT ac on ac.FISMA_ID = ap.IDUID
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_ALLOCATED_CONTROLS_ELEMENTS_REPORT ace on ace.FISMA_ID = ap.IDUID
and ace.CONTROL_NUMBER = ac.CONTROL_NUMBER
;