create or replace view VW_APP_ARCHER_CAAT(
	ACT_CAAT_FILEPROCESSEDDATE,
	ASSESSMENTAUDIT_COMPANY,
	CAAT_ID,
	DATE_IDENTIFIED,
	FINDING_DESCRIPTION,
	FINDING_ID,
	FINDING_TITLE,
	RELATED_POAMS,
	SOURCE_AUDIT_TYPE_2,
	SYSTEM_ID,
	TEST_METHOD,
	TEST_OBJECTIVE,
	TEST_RESULT,
	WEAKNESS_DESCRIPTION
) COMMENT='APP_ARCHER (CFACTS) Parent level view of CMS Assessment and Audit Tracking for a system.'
 as
SELECT
cat.ACT_SCA_PROCESSED_FILE_DATE as ACT_CAAT_FILEPROCESSEDDATE
,cat.CONTRACTOR as ASSESSMENTAUDIT_COMPANY
,cat.TRACKING_ID as CAAT_ID
,cat.DATE_IDENTIFIED as DATE_IDENTIFIED
,cat.FINDING_DESCRIPTION as FINDING_DESCRIPTION
,cat.FINDING_ID as FINDING_ID
,cat.FINDING_TITLE as FINDING_TITLE
,p.POAM_ID as RELATED_POAMS
,cat.AUDIT_TYPE_2[0]::varchar as SOURCE_AUDIT_TYPE_2
,ap.IDUID as SYSTEM_ID
,cat.TEST_METHOD[0]::varchar as TEST_METHOD
,cat.TEST_OBJECTIVE as TEST_OBJECTIVE
,cat.TEST_RESULTS[0]::varchar as TEST_RESULT
,cat.WEAKNESS_DESCRIPTION as WEAKNESS_DESCRIPTION
FROM APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT ap
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_CMS_ASSESSMENT_AUDIT_TRACKING_CAAT_REPORT cat on cat.information_system_or_program_name[0]:ContentId = ap._content_id
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_POA_M_REPORT p on p.CAAT_ID = cat._content_id
/*
,p.SUBMITTER:Users[0]:FirstName::varchar || ' ' || p.SUBMITTER:Users[0]:LastName::varchar as SUBMITTER
,ap.IDUID as SYSTEM_ID
FROM APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT ap
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_PRIVACY_IMPACT_ASSESSMENT_PIA_REPORT p on p.name_of_component[0]:ContentId = ap._content_id;
*/
;