create or replace view VW_ASSET_SOFTWARE(
	DW_SWAM_ID,
	ASSET_ID_TATTOO,
	DATEINSTALLED,
	DATACENTER_ACRONYM,
	DATACENTER_ID,
	DEVICETYPE,
	DW_ASSET_ID,
	FIRSTSEEN,
	INSERT_DATE,
	IS_FROM_AWS_FEED,
	IS_FORESCOUT_MANAGED,
	IS_SCANNABLE,
	IS_TENABLE_CREDENTIALED_SCAN,
	LASTSEEN,
	MAJOR,
	MINOR,
	SOFTWARENAME,
	SOURCE_TOOL,
	SWAM_CATEGORY,
	SWAM_SUBCATEGORY,
	SYSTEM_ACRONYM,
	SYSTEM_ID,
	VENDOR,
	VERSION
) COMMENT='Software associated with each asset\t'
 as
select
soft.DW_SWAM_ID
,a.ASSET_ID_TATTOO
,TO_CHAR(soft.DATEINSTALLED,'MM/DD/YYYY') as DATEINSTALLED
,a.DATACENTER_ACRONYM
,a.DATACENTER_ID
,a.DEVICETYPE
,soft.DW_ASSET_ID
,TO_CHAR(soft.FIRSTSEEN,'MM/DD/YYYY') as FIRSTSEEN
,TO_CHAR(soft.INSERT_DATE,'MM/DD/YYYY') as INSERT_DATE
,a.IS_FROM_AWS_FEED -- 240709 CR931
,a.IS_FORESCOUT_MANAGED -- 240709 CR931
,a.IS_SCANNABLE -- 240709 CR931
,a.IS_TENABLE_CREDENTIALED_SCAN -- 240709 CR931
,TO_CHAR(soft.LASTSEEN,'MM/DD/YYYY') as LASTSEEN
,soft.MAJOR
,soft.MINOR
--,soft.PRODUCTNAME
,soft.SOFTWARENAME
,soft.SOURCE_TOOL
,soft.SWAM_CATEGORY
,soft.SWAM_SUBCATEGORY
,a.SYSTEM_ACRONYM
,a.SYSTEM_ID
,soft.VENDOR
,soft.VERSION
FROM CORE.VW_ASSETS a
JOIN CORE.ASSET_SOFTWARE soft on soft.DW_ASSET_ID = a.DW_ASSET_ID
;