create or replace view VW_APP_ARCHER_MILESTONE(
	ACTUAL_COMP_DATE,
	CHANGES2MS,
	EST_COMP_DATE,
	LAST_UPDATED,
	MS_DESC,
	MS_ID,
	MS_NAME,
	MS_STATUS,
	POAM_ID,
	SCHED_COMP_DATE,
	SYSTEM_ID
) COMMENT='APP_ARCHER (CFACTS) Parent level view of POAM Milestones for a system.'
 as 
SELECT
m.ACTUAL_COMPLETION_DATE as ACTUAL_COMP_DATE
,m.CHANGES_TO_MILESTONE as CHANGES2MS
,m.ESTIMATED_COMPLETION_DATE as EST_COMP_DATE
,m.LAST_UPDATED as LAST_UPDATED
,m.MILESTONE_DESCRIPTION as MS_DESC
,m.TRACKING_ID as MS_ID
,m.MILESTONE_NAME as MS_NAME
,m.MILESTONE_STATUS_1[0]::varchar as MS_STATUS
,p.POAM_ID as POAM_ID
,m.SCHEDULED_COMPLETION_DATE as SCHED_COMP_DATE
,ap.IDUID as SYSTEM_ID
FROM APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_AUTHORIZATION_PACKAGE_REPORT ap
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_POA_M_REPORT p on p.FISMA_ID = ap.IDUID
JOIN APP_ARCHER.DEV_PRIVATE.__REPORT_CONTENT_CFACTS_SDL_MILESTONES_REPORT m on m.POAMS_MILESTONE[0]:ContentId = p._content_id;