create or replace view VW_CFACTS_SYSTEMS(
	ACRONYM,
	ACTUAL_DECOMMISION_DATE,
	ARCHER_TRACKING_ID,
	ATO_EXPIRATION_DATE,
	ATO_REVIEW_DATE,
	AUTH_COMMENTS,
	AUTH_DECISION,
	AUTHORIZATION_MEMO_SIGNED_DATE,
	AUTHORIZATION_PACKAGE_NAME,
	BO_RECOMMENDATION_REVIEW_DATE,
	BO_REVIEW_DATE,
	BUSINESS_OWNER,
	CIO,
	CISO,
	CISO_REVIEW_DATE,
	CLOUD_SERVICE_PROVIDER,
	COMPONENT_ACRONYM,
	COMPONENT_DESCRIPTION,
	COMPONENT_NAME,
	COMPONENT_RISK_REPORTS_OVERSIGHT,
	CONTINGENCYEXPIRATIONDATE,
	CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID,
	CP_TEST_DATE,
	CP_TEST_RESULTS,
	CRA,
	CRA_REVIEW_DATE,
	CYBERVET,
	DATE_AUTH_MEMO_EXPIRES,
	DATE_AUTH_MEMO_SIGNED,
	DCISO,
	DIVISION_ACRONYM,
	DIVISION_DESCRIPTION,
	DIVISION_NAME,
	DSPC_REVIEW_DATE,
	DSPPO_REVIEW_DATE,
	E_AUTH_EXP_DATE,
	E_AUTH_LEVEL,
	E_AUTH_RISK_ASSESSMENT_DATE,
	FINANCIAL_SYSTEM,
	FIPS_199_AVAILABILITY_RATING,
	FIPS_199_CONFIDENTIALITY_RATING,
	FIPS_199_INTEGRITY_RATING,
	FIPS_199_OVERALL_IMPACT_RATING,
	FIRST_PUBLISHED_DATE,
	FISMA_SYSTEM,
	GROUP_ACRONYM,
	GROUP_DESCRIPTION,
	GROUP_NAME,
	HVA_SCORE,
	HVASTATUS,
	INFORMATION_SYSTEM_TYPE,
	IS_MARKETPLACE,
	IS_OA_READY,
	ISRA_REVIEW_DATE,
	ISRA_STATUS,
	ISSO,
	ISSO_COUNT,
	ISSO_REVIEW_DATE,
	ISSO_SUBMISSION_DATE,
	ISSOCS,
	LAST_ACT_DATE,
	LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE,
	LAST_ACT_SCA_FINAL_REPORT_DATE,
	LAST_PENTEST_CAAT_PROCESSED_FILE_DATE,
	LAST_PENTEST_DATE,
	MEF,
	MEF_CONTEXT,
	NEXT_REQUIRED_CP_TEST_DATE,
	OA_STATUS,
	OPERATED_BY,
	PACKAGE_TYPE,
	PIA_014,
	PIA_EXPIRATION_DATE,
	PRIMARY_ISSO,
	PRIMARY_OPERATING_LOCATION,
	REASON_FOR_ATO_REQUEST,
	SCA,
	SCA_DATE,
	SDM,
	SOP_REVIEW_DATE,
	STE_DATE,
	SYSTEM_DESCRIPTION,
	SYSTEM_ID,
	TLC_PHASE
) COMMENT='Systems detail directly from CFACTS.'
 as
WITH aControlOwner as (
SELECT ParentContentId, listagg(DisplayName,',')  as text
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Control_Owner_CO
Group by ParentContentId
),
CloudServiceProviders as (
SELECT APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Cloud_Service_Provider_1.ParentContentId, 
TRIM(listagg(APP_CFACTS.SHARED.SEC_VW_enum_Cloud_Service_Provider_1.Value, ';')) AS text -- 231012 added TRIM
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Cloud_Service_Provider_1 
JOIN APP_CFACTS.SHARED.SEC_VW_enum_Cloud_Service_Provider_1  on APP_CFACTS.SHARED.SEC_VW_enum_Cloud_Service_Provider_1.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Cloud_Service_Provider_1.Value
Group by APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Cloud_Service_Provider_1.ParentContentId
),
e_csp as (
SELECT distinct APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId, CloudServiceProviders.text as CloudServiceProviders
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package join CloudServiceProviders on (CloudServiceProviders.ParentContentId = APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId)
),
CRROs as (
select r.ParentContentId, listagg(r.DisplayName,';') AS text -- 231012 added ;
FROM (SELECT ParentContentId, DisplayName 
    FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Component_Risk_Reports_Oversight
    order by ParentContentId, lower(DisplayName)) r -- 231012 added sort
group by r.ParentContentId
), 
ap_crro as (
SELECT distinct APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId, CRROs.text as CRROs
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package  join CRROs on (CRROs.ParentContentId = APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId)
),
CRAs as (
select r.ParentContentId, listagg(r.DisplayName,';') AS text -- 231012 added ;
FROM (SELECT ParentContentId, DisplayName 
    FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_DSPC_POC
    order by ParentContentId, lower(DisplayName)) r -- 231012 added sort
group by r.ParentContentId
),
ap_cras as (
SELECT DISTINCT APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId, CRAs.text as CRAs
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package join CRAs on CRAs.ParentContentId = APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId
),
CyberVets as (
select r.ParentContentId, listagg(r.DisplayName,';') AS text
FROM (SELECT ParentContentId, DisplayName 
        FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Cyber_Risk_Advisor_CRA
        order by ParentContentId, lower(DisplayName)) r -- 231012 added sort
group by r.ParentContentId
),
ap_cybervet as (
SELECT DISTINCT APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId, CyberVets.text as CyberVets
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package join CyberVets on CyberVets.ParentContentId = APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId
),
ISSOs as (
select r.ParentContentId, listagg(r.DisplayName,';') AS text
FROM (SELECT ParentContentId, DisplayName 
        FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Security_Officer_ISSO
        order by ParentContentId, lower(DisplayName)) r -- 231012 added sort
group by r.ParentContentId
),
ap_isso as (
SELECT DISTINCT APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId, ISSOs.text as ISSOs
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package join ISSOs on ISSOs.ParentContentId = APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId
),
ISSOCS as (
select r.ParentContentId, listagg(r.DisplayName,';') AS text
FROM (SELECT ParentContentId, DisplayName 
        FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_ISSO_Contractor_Support_ISSOCS
        order by ParentContentId, lower(DisplayName)) r -- 231012 added sort
group by r.ParentContentId
),
ap_issocs as (
SELECT DISTINCT APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId, ISSOCS.text as ISSOCS
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package  join ISSOCS on issocs.ParentContentId = APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId
),
MEFs as (
SELECT APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Mission_Essential_Functions_.ParentContentId, listagg(APP_CFACTS.SHARED.SEC_VW_enum_Mission_Essential_Functions_.Value,',') AS text
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Mission_Essential_Functions_ 
JOIN APP_CFACTS.SHARED.SEC_VW_enum_Mission_Essential_Functions_  on APP_CFACTS.SHARED.SEC_VW_enum_Mission_Essential_Functions_.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Mission_Essential_Functions_.Value
group by APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Mission_Essential_Functions_.ParentContentId
),
e_mefs as (
SELECT DISTINCT APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId, MEFs.text as MEFs
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package join MEFs on MEFs.ParentContentId = APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId
),
pol as (
select APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Operating_Location.ParentContentId, listagg(APP_CFACTS.SHARED.SEC_VW_enum_Operating_Location.Value,',') as Value
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Operating_Location  
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Operating_Location on (APP_CFACTS.SHARED.SEC_VW_enum_Operating_Location.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Operating_Location.Value)
group by APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Operating_Location.ParentContentId
),
SCAs as (
select r.ParentContentId, listagg(r.DisplayName,';') AS text
FROM (SELECT ParentContentId, DisplayName 
        FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Security_Control_Assessor_SCA
        order by ParentContentId, lower(DisplayName)) r -- 231012 added sort
group by r.ParentContentId
),
ap_sca as (
SELECT DISTINCT APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId, SCAs.text as SCAs
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package join SCAs on  SCAs.ParentContentId = APP_CFACTS.SHARED.SEC_VW_Authorization_Package.ContentId
),
aISA as (
select ParentContentId, listagg(DisplayName, ',') as DispLayName
from APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Administrator_ISA
group by ParentContentId
),
isso_count as (
SELECT ParentContentId,count(1) as ISSO_Count
FROM APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Security_Officer_ISSO			
GROUP BY ParentContentId
)
SELECT
APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Acronym as ACRONYM
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ACTUAL_DECOMMISION_DATE) as ACTUAL_DECOMMISION_DATE -- 231218
,APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Tracking_ID as ARCHER_TRACKING_ID
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.ATO_EXPIRATION_DATE) as ATO_EXPIRATION_DATE -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.COPY_OF_BO_REQUEST_REVIEW_DATE_1) as ATO_REVIEW_DATE -- 230801 function was in PUBLIC schema
,CORE.FN_CRM_CLEANSTRING(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Authorization_Comments) as AUTH_COMMENTS -- 231013 add FN_CRM_CLEANSTRING
,APP_CFACTS.SHARED.SEC_VW_enum_Authorization_Decision.Value as AUTH_DECISION
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.CIO_SUBMITTED_DATE) as AUTHORIZATION_MEMO_SIGNED_DATE -- 230801 function was in PUBLIC schema
,RTRIM(CORE.FN_CRM_CLEANSTRING(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Authorization_Package_Name)) as AUTHORIZATION_PACKAGE_NAME -- 231013 add FN_CRM_CLEANSTRING
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.COPY_OF_BO_REQUEST_REVIEW__DUE_DATE) as BO_RECOMMENDATION_REVIEW_DATE -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.BO_SUBMITTED_DATE) as BO_REVIEW_DATE -- 230801 function was in PUBLIC schema
,aControlOwner.text as BUSINESS_OWNER
,APP_CFACTS.SHARED.SEC_VW_Allocated_Controls_Control_Standards_Chief_Information_Officer_Inherited.DisplayName as CIO
,APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Chief_Information_Security_Officer_CISO.DisplayName as CISO
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.CISO_SUBMITTED_DATE) as CISO_REVIEW_DATE -- 230801 function was in PUBLIC schema
,e_csp.CloudServiceProviders as CLOUD_SERVICE_PROVIDER
,tdcg.COMPONENT_ACRONYM as COMPONENT_ACRONYM
,CORE.FN_CRM_CLEANSTRING(tdcg.COMPONENT_DESCRIPTION) as COMPONENT_DESCRIPTION -- 231013 add FN_CRM_CLEANSTRING
,tdcg.COMPONENT_NAME as COMPONENT_NAME
,ap_crro.CRROs as COMPONENT_RISK_REPORTS_OVERSIGHT
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Last_Contingency_Plan_Expiration_Date) as CONTINGENCYEXPIRATIONDATE -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Control_Set_Version_Number_System_Provid as CONTROL_SET_VERSION_NUMBER_SYSTEM_PROVID
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Contingency_Plan_Status_Date) as CP_TEST_DATE -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_enum_Contingency_Plan_Test_Results.Value as CP_TEST_RESULTS
,ap_cras.CRAs as CRA
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.CRA_SUBMITTED_DATE) as CRA_REVIEW_DATE -- 230801 function was in PUBLIC schema
,ap_cybervet.CyberVets as CYBERVET 
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ATO_IATO_Expiration_Date) as DATE_AUTH_MEMO_EXPIRES -- 230801 function was in PUBLIC schema 
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ATO_IATO_Date) as DATE_AUTH_MEMO_SIGNED -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Owner_ISO.DisplayName as DCISO
,tdcg.DIVISION_ACRONYM as DIVISION_ACRONYM
,CORE.FN_CRM_CLEANSTRING(tdcg.DIVISION_DESCRIPTION) as DIVISION_DESCRIPTION -- 231013 add FN_CRM_CLEANSTRING
,TRIM(tdcg.DIVISION_NAME) as DIVISION_NAME -- 231012 added TRIM
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.DSPC_SUBMITTED_DATE) as DSPC_REVIEW_DATE -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.DSPPO_SUBMITTED_DATE) as DSPPO_REVIEW_DATE -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.EAuthentication_Expiration_Date) as E_AUTH_EXP_DATE -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_enum_EAuthentication_Level.Value as E_AUTH_LEVEL
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.EAuthentication_Date)  as E_AUTH_RISK_ASSESSMENT_DATE -- 230801 function was in PUBLIC schema      
,APP_CFACTS.SHARED.SEC_VW_enum_Financial_System.Value as FINANCIAL_SYSTEM
,ap_FIPS_avail.Value as FIPS_199_AVAILABILITY_RATING
,ap_FIPS_Confident.Value as FIPS_199_CONFIDENTIALITY_RATING
,ap_FIPS_integ.Value as FIPS_199_INTEGRITY_RATING
,ap_FIPS_Overall.Value as FIPS_199_OVERALL_IMPACT_RATING 
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.First_Published_Date)  as FIRST_PUBLISHED_DATE -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_enum_FISMA_Reportable.Value as FISMA_SYSTEM
,tdcg.GROUP_ACRONYM as GROUP_ACRONYM
,CORE.FN_CRM_CLEANSTRING(tdcg.GROUP_DESCRIPTION) as GROUP_DESCRIPTION -- 231013 add FN_CRM_CLEANSTRING
,TRIM(tdcg.GROUP_NAME) as GROUP_NAME -- 231012 added TRIM
,APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.HVA_Score  as HVA_SCORE
,IFNULL(APP_CFACTS.SHARED.SEC_VW_enum_GVL_YesNo.Value,'No') as HVASTATUS 
,APP_CFACTS.SHARED.SEC_VW_enum_Information_System_Type.Value as INFORMATION_SYSTEM_TYPE
,case IFNULL(APP_CFACTS.SHARED.SEC_VW_enum_Marketplace_Systems.Value,'0') When 'Yes' then '1' Else '0' End as IS_MARKETPLACE
,case IFNULL(APP_CFACTS.SHARED.SEC_VW_enum_OA_Ready.Value,'0') When 'Yes' then '1' Else '0' End as IS_OA_READY
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ISRA_Review_Date)  as ISRA_REVIEW_DATE -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_enum_ISRA_Status.Value as ISRA_STATUS
,ap_isso.ISSOs as ISSO
,isso_count.ISSO_Count as ISSO_COUNT
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.ISSO_REVIEW_DUE_DATE) as ISSO_REVIEW_DATE -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.ISSO_SUBMITTED_DATE) as ISSO_SUBMISSION_DATE -- 230801 function was in PUBLIC schema
,ap_issocs.ISSOCS as ISSOCS         
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Last_ACT_Date) as LAST_ACT_DATE -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE) as LAST_ACT_SCA_CAAT_PROCESSED_FILE_DATE -- 230428; -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Last_ACT_SCA_Final_Report_Date) as LAST_ACT_SCA_FINAL_REPORT_DATE -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.LAST_PENTEST_CAAT_PROCESSED_FILE_DATE) as LAST_PENTEST_CAAT_PROCESSED_FILE_DATE -- 230428; -- 230801 function was in PUBLIC schema 
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Last_Pentest_Date) as LAST_PENTEST_DATE -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_enum_Is_this_HVA_necessary_to_perform_MEF.Value as MEF
,e_mefs.MEFs as MEF_CONTEXT 
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Next_Required_Contingency_Plan_Test_Date) as NEXT_REQUIRED_CP_TEST_DATE -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_enum_OA_Status2.value as OA_STATUS
,APP_CFACTS.SHARED.SEC_VW_ENUM_OPERATED_BY.value as OPERATED_BY -- 250103 Tersa needs this for FISMA Report
,APP_CFACTS.SHARED.SEC_VW_enum_Package_Type.Value as PACKAGE_TYPE
,PIA014.PIA_014 as PIA_014
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.PIA_Expiration_Date) as PIA_EXPIRATION_DATE -- 230801 function was in PUBLIC schema
,APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Primary_Information_System_Security_Offi.DisplayName as PRIMARY_ISSO -- PRIMARY INFORMATION SYSTEM SECURITY OFFICER (ISSO)
,TRIM(pol.Value) as PRIMARY_OPERATING_LOCATION -- 231012 added TRIM
,APP_CFACTS.SHARED.SEC_VW_ENUM_REASON_FOR_ATO_REQUEST.VALUE as REASON_FOR_ATO_REQUEST
,ap_sca.SCAs as SCA
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.SCA_Date) as SCA_DATE -- 230801 function was in PUBLIC schema
,aISA.DisplayName as SDM
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.SDM_REVIEW_DUE_DATE) as SOP_REVIEW_DATE -- 230801 function was in PUBLIC schema
,REF_LOOKUPS.SHARED.FN_PUB_ANY_TO_TIMESTAMP_LTZ(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.STE_Date) as STE_DATE -- 230801 function was in PUBLIC schema
,CORE.FN_CRM_CLEANSTRING(APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.SystemDescription_Truncated) as SYSTEM_DESCRIPTION -- 231013 add FN_CRM_CLEANSTRING
,APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.IDUID as SYSTEM_ID       
,APP_CFACTS.SHARED.SEC_VW_enum_XLC_Phase.Value as TLC_PHASE
FROM APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE 
LEFT OUTER JOIN (
SELECT
APP_CFACTS.SHARED.SEC_VW_DIVISION.DIVISION_ACRONYM as DIVISION_ACRONYM
,APP_CFACTS.SHARED.SEC_VW_DIVISION.DESCRIPTION as DIVISION_DESCRIPTION
,APP_CFACTS.SHARED.SEC_VW_DIVISION.DIVISION as DIVISION_NAME
,APP_CFACTS.SHARED.SEC_VW_GROUP.GROUP_ACRONYM as GROUP_ACRONYM
,APP_CFACTS.SHARED.SEC_VW_GROUP.DESCRIPTION as GROUP_DESCRIPTION
,APP_CFACTS.SHARED.SEC_VW_GROUP.GROUP_NAME as GROUP_NAME
,APP_CFACTS.SHARED.SEC_VW_COMPONENT.COMPONENT_ACRONYM as COMPONENT_ACRONYM
,APP_CFACTS.SHARED.SEC_VW_COMPONENT.DESCRIPTION as COMPONENT_DESCRIPTION
,APP_CFACTS.SHARED.SEC_VW_COMPONENT.COMPONENT_NAME as COMPONENT_NAME
,APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.IDUID as SYSTEM_ID
FROM APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE  
JOIN APP_CFACTS.SHARED.SEC_VW_DIVISION_AUTHORIZATION_PACKAGES_X_AUTHORIZATION_PACKAGE_OFFICE  
on APP_CFACTS.SHARED.SEC_VW_DIVISION_AUTHORIZATION_PACKAGES_X_AUTHORIZATION_PACKAGE_OFFICE.Authorization_Package_Office_ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
JOIN APP_CFACTS.SHARED.SEC_VW_DIVISION on APP_CFACTS.SHARED.SEC_VW_DIVISION.ContentId = APP_CFACTS.SHARED.SEC_VW_DIVISION_AUTHORIZATION_PACKAGES_X_AUTHORIZATION_PACKAGE_OFFICE.Division_Authorization_Packages_ContentId
JOIN APP_CFACTS.SHARED.SEC_VW_GROUP_DIVISION_X_DIVISION_GROUP on APP_CFACTS.SHARED.SEC_VW_GROUP_DIVISION_X_DIVISION_GROUP.Division_Group_ContentId = APP_CFACTS.SHARED.SEC_VW_DIVISION.ContentId
JOIN APP_CFACTS.SHARED.SEC_VW_GROUP on APP_CFACTS.SHARED.SEC_VW_GROUP.ContentId = APP_CFACTS.SHARED.SEC_VW_GROUP_DIVISION_X_DIVISION_GROUP.Group_Division_ContentId
JOIN APP_CFACTS.SHARED.SEC_VW_COMPONENT on APP_CFACTS.SHARED.SEC_VW_COMPONENT.Component_Acronym = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Component_Acronym
) tdcg 
on tdcg.SYSTEM_ID = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.IDUID

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_TLC_Phase 
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_TLC_Phase.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_XLC_Phase on APP_CFACTS.SHARED.SEC_VW_enum_XLC_Phase.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_TLC_Phase.Value  

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_FISMA_Reportable 
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_FISMA_Reportable.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_FISMA_Reportable 
on APP_CFACTS.SHARED.SEC_VW_enum_FISMA_Reportable.ID = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_FISMA_Reportable.Value

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Is_this_system_on_the_HVA_tracking_list 
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Is_this_system_on_the_HVA_tracking_list.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_GVL_YesNo  
on APP_CFACTS.SHARED.SEC_VW_enum_GVL_YesNo.ID = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Is_this_system_on_the_HVA_tracking_list.Value

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_EAuthentication_Level  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_EAuthentication_Level.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_EAuthentication_Level  
on APP_CFACTS.SHARED.SEC_VW_enum_EAuthentication_Level.ID = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_EAuthentication_Level.Value

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Primary_Information_System_Security_Offi
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Primary_Information_System_Security_Offi.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Operated_by  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Operated_by.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Operated_by 
on APP_CFACTS.SHARED.SEC_VW_enum_Operated_by.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Operated_by.Value

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Is_this_HVA_necessary_to_perform_MEF  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Is_this_HVA_necessary_to_perform_MEF.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Is_this_HVA_necessary_to_perform_MEF  
on APP_CFACTS.SHARED.SEC_VW_enum_Is_this_HVA_necessary_to_perform_MEF.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Is_this_HVA_necessary_to_perform_MEF.Value

LEFT OUTER JOIN e_mefs on e_mefs.ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Authorization_Decision  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Authorization_Decision.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Authorization_Decision 
on APP_CFACTS.SHARED.SEC_VW_enum_Authorization_Decision.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Authorization_Decision.Value

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Contingency_Plan_Test_Results  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Contingency_Plan_Test_Results.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Contingency_Plan_Test_Results  
on APP_CFACTS.SHARED.SEC_VW_enum_Contingency_Plan_Test_Results.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Contingency_Plan_Test_Results.Value

LEFT OUTER JOIN e_csp on e_csp.ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN ap_crro on ap_crro.ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Chief_Information_Security_Officer_CISO  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Chief_Information_Security_Officer_CISO.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Allocated_Controls_Control_Standards_Chief_Information_Officer_Inherited  
on APP_CFACTS.SHARED.SEC_VW_Allocated_Controls_Control_Standards_Chief_Information_Officer_Inherited.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN ap_cybervet on ap_cybervet.ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Owner_ISO  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Owner_ISO.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Package_Type  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Package_Type.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Package_Type  
ON APP_CFACTS.SHARED.SEC_VW_enum_Package_Type.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Package_Type.Value

LEFT OUTER JOIN ap_sca on ap_sca.ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN ap_isso on ap_isso.ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN isso_count on isso_count.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN ap_issocs on ap_issocs.ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Financial_System  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Financial_System.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Financial_System  
ON APP_CFACTS.SHARED.SEC_VW_enum_Financial_System.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Financial_System.Value

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_ISRA_Status  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_ISRA_Status.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_ISRA_Status  
ON APP_CFACTS.SHARED.SEC_VW_enum_ISRA_Status.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_ISRA_Status.Value

LEFT OUTER JOIN ap_cras on ap_cras.ContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN (
select APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Confidentiality_Control_Cate.ParentContentId,APP_CFACTS.SHARED.SEC_VW_enum_Security_Category.Value
from APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Confidentiality_Control_Cate 
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Security_Category  
on APP_CFACTS.SHARED.SEC_VW_enum_Security_Category.ID = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Confidentiality_Control_Cate.Value 
) ap_FIPS_Confident
on ap_FIPS_Confident.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN (
select APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Integirty_Control_Category.ParentContentId,APP_CFACTS.SHARED.SEC_VW_enum_Security_Category.Value
from APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Integirty_Control_Category 
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Security_Category  
on APP_CFACTS.SHARED.SEC_VW_enum_Security_Category.ID = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Integirty_Control_Category.Value 
) ap_FIPS_integ
on ap_FIPS_integ.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN (
select APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Availability_Control_Categor.ParentContentId,APP_CFACTS.SHARED.SEC_VW_enum_Security_Category.Value
from APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Availability_Control_Categor 
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Security_Category  
on APP_CFACTS.SHARED.SEC_VW_enum_Security_Category.ID = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Availability_Control_Categor.Value 
) ap_FIPS_avail
on ap_FIPS_avail.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN (
select APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Security_Category.ParentContentId,APP_CFACTS.SHARED.SEC_VW_enum_Security_Category.Value
from APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Security_Category 
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Security_Category  
on APP_CFACTS.SHARED.SEC_VW_enum_Security_Category.ID = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Recommended_Security_Category.Value 
) ap_FIPS_Overall
on ap_FIPS_Overall.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Type  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Type.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_Information_System_Type  
on APP_CFACTS.SHARED.SEC_VW_enum_Information_System_Type.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Information_System_Type.Value

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_OA_Ready  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_OA_Ready.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_OA_Ready  
on APP_CFACTS.SHARED.SEC_VW_enum_OA_Ready.Id = APP_CFACTS.SHARED.SEC_VW_Authorization_Package_OA_Ready.Value

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_OA_Status  
on APP_CFACTS.SHARED.SEC_VW_Authorization_Package_OA_Status.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_enum_OA_Status2  
ON APP_CFACTS.SHARED.SEC_VW_enum_OA_Status2.ID=APP_CFACTS.SHARED.SEC_VW_Authorization_Package_OA_Status.value -- 231102 0947 CFACTS used enum_OA_Status prior to 10/27

LEFT JOIN APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Marketplace_Systems  
ON APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Marketplace_Systems.ParentContentId=APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId
LEFT JOIN APP_CFACTS.SHARED.SEC_VW_enum_Marketplace_Systems  
ON APP_CFACTS.SHARED.SEC_VW_enum_Marketplace_Systems.ID=APP_CFACTS.SHARED.SEC_VW_Authorization_Package_Marketplace_Systems.Value

LEFT JOIN aControlOwner on ( APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId= aControlOwner.ParentContentId ) 		
LEFT JOIN pol on (pol.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId) 
LEFT JOIN aISA on (APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentId = aISA.ParentContentId)

LEFT JOIN (
select AUTHORIZATION_PACKAGE_ATO_RED_FOLDER_INFORMATION_SYSTEM_OR_PAC_CONTENTID as AP_CONTENTID
,max(ATO_RED_FOLDER_INFORMATION_SYSTEM_OR_PACKAGE_CONTENTID) as FOLDER_CONTENTID
FROM APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE_ATO_RED_FOLDER_INFORMATION_SYSTEM_OR_PAC_X_ATO_RED_FOLDER_INFORMATION_SYSTEM_OR_PACKAGE
GROUP BY AUTHORIZATION_PACKAGE_ATO_RED_FOLDER_INFORMATION_SYSTEM_OR_PAC_CONTENTID
) ato_x 
ON APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.CONTENTID=ato_x.AP_CONTENTID

LEFT JOIN APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER ON APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.CONTENTID=ato_x.FOLDER_CONTENTID

LEFT JOIN APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER_REASON_FOR_ATO_REQUEST  
ON APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER_REASON_FOR_ATO_REQUEST.PARENTCONTENTID=APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER.CONTENTID
LEFT JOIN APP_CFACTS.SHARED.SEC_VW_ENUM_REASON_FOR_ATO_REQUEST  
ON APP_CFACTS.SHARED.SEC_VW_ENUM_REASON_FOR_ATO_REQUEST.ID=APP_CFACTS.SHARED.SEC_VW_ATO_RED_FOLDER_REASON_FOR_ATO_REQUEST.VALUE

LEFT OUTER JOIN (
-- 230705 found more than one record in VW_AUTHORIZATION_PACKAGE_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHOR_X_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHORIZATION_PACKAGE but ultimately
-- VW_ENUM_HELPER_PIA014 always had one distinct PIA value per System
SELECT DISTINCT APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.contentid,APP_CFACTS.SHARED.SEC_VW_ENUM_HELPER_PIA014.VALUE as PIA_014
FROM APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE 
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHOR_X_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHORIZATION_PACKAGE on APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHOR_X_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHORIZATION_PACKAGE.AUTHORIZATION_PACKAGE_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHOR_CONTENTID = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.CONTENTID -- 230621
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_HELPER_PIA014  
on APP_CFACTS.SHARED.SEC_VW_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_HELPER_PIA014.PARENTCONTENTID = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHOR_X_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHORIZATION_PACKAGE.PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_AUTHORIZATION_PACKAGE_CONTENTID -- 230621
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_ENUM_HELPER_PIA014  on APP_CFACTS.SHARED.SEC_VW_ENUM_HELPER_PIA014.ID = APP_CFACTS.SHARED.SEC_VW_PRIVACY_IMPACT_ASSESSMENT_PIA_NEW_HELPER_PIA014.VALUE
) PIA014 
on PIA014.contentid = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.contentid

WHERE APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.IDUID IS NOT NULL
;