create or replace view VW_CFACTS_SYSTEMS_INFORMATION_TYPES_TEST(
	ACRONYM,
	AP_CONTENTID,
	VALUE,
	CONTENTID,
	TRACKING_ID,
	FIRST_PUBLISHED_DATE,
	FIRST_PUBLISHED_USERNAME,
	FIRST_PUBLISHED_DISPLAYNAME,
	LAST_UPDATED_DATE,
	LAST_UPDATED_USERNAME,
	LAST_UPDATED_DISPLAYNAME,
	INFORMATION_TYPE,
	DESCRIPTION,
	RECORD_STATUS,
	CLASSIFICATION_RATING_JUST,
	NEXT_ASSESSMENT_DATE,
	UCF_RECORD_ID,
	RETENTION_EVENT,
	HELPER__PUBLIC_INFORMATION
) as
SELECT
APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.Acronym as ACRONYM
,APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.CONTENTID as AP_CONTENTID
,APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE_INFORMATION_SYSTEM_TYPE.VALUE
,APP_CFACTS.SHARED.SEC_VW_INFORMATION_TYPES.*

FROM APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE 

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE_INFORMATION_SYSTEM_TYPE
on APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE_INFORMATION_SYSTEM_TYPE.ParentContentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.ContentID

LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_INFORMATION_TYPES 
ON APP_CFACTS.SHARED.SEC_VW_INFORMATION_TYPES.CONTENTID = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE_INFORMATION_SYSTEM_TYPE.value

/*
LEFT OUTER JOIN APP_CFACTS.SHARED.SEC_VW_INFORMATION_TYPES
on APP_CFACTS.SHARED.SEC_VW_INFORMATION_TYPES.contentId = APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.tracking_id
*/
WHERE APP_CFACTS.SHARED.SEC_VW_AUTHORIZATION_PACKAGE.IDUID IS NOT NULL
;