create or replace view VW_CFACTS_USERMAPPING(
	ACRONYM,
	COMPONENT_ACRONYM,
	GROUP_ACRONYM,
	ROLE,
	SYSTEM_ID,
	USER_ID
) COMMENT='Map CFACTS users to system, component, group and role'
 as
SELECT ule.ACRONYM
,CORE.VW_SYSTEMS.Component_Acronym 
,CORE.VW_SYSTEMS.Group_Acronym 
,ule.ROLE
,CORE.VW_SYSTEMS.SYSTEM_ID
,ule.USER_ID
FROM (SELECT 
CASE APP_CFACTS.SHARED.SEC_VW_USERLIST.ACRONYM
    when 'PS&amp;R' then 'PS&R' -- 240506 CR886 EBF - workaround
    else ACRONYM
END as ACRONYM
,APP_CFACTS.SHARED.SEC_VW_USERLIST.ROLE
,APP_CFACTS.SHARED.SEC_VW_USERLIST.userid as USER_ID
FROM APP_CFACTS.SHARED.SEC_VW_USERLIST) ule
LEFT OUTER JOIN CORE.VW_SYSTEMS on upper(CORE.VW_SYSTEMS.ACRONYM) = upper(ule.ACRONYM);