create or replace view VW_HWAM_AWS_V2(
	ACCOUNT_NUMBER,
	BIGFIX_ASSET_ID,
	BIOS_GUID,
	COMPUTER_TYPE,
	DATACENTER_ID,
	DEVICE_TYPE,
	ENVIRONMENT,
	FISMA_UUID,
	FQDN,
	HOSTNAME,
	INSTANCEID,
	INSTANCESTATUS,
	IPV4,
	IPV6,
	LAST_CONFIRMED_TIME,
	MAC,
	MOTHERBOARD_SN,
	NETBIOS_HN,
	OS,
	OS_CPE,
	OS_VERSION,
	SYSTEM_ID,
	REPORT_TIME,
	SOURCE_TOOL,
	SYSTEM_ACRONYM
) COMMENT='CRITICAL; Replacement for APP_CDM.SHARED.SEC_VW_HWAM_AWS for missing PRIMARY_FISMA_ID_DERIVED and invalid SYSTEM_ACRONYM\t'
 as
--
-- 240724 CR940
--
select
h.ACCOUNT_NUMBER
,h.BIGFIX_ASSET_ID
,h.BIOS_GUID
,h.COMPUTER_TYPE
,h.DATACENTER_ID_DERIVED as DATACENTER_ID
,h.DEVICE_TYPE
,h.ENVIRONMENT
,h.FISMA_UUID -- What is the purpose of this column? It doesn't match PRIMARY_FISMA_ID_DERIVED
,h.FQDN
,h.HOSTNAME
,h.INSTANCEID
,h.INSTANCESTATUS
,h.IPV4
,h.IPV6
,h.LAST_CONFIRMED_TIME
,h.MAC
,h.MOTHERBOARD_SN
,h.NETBIOS_HN
,h.OS
,h.OS_CPE
,h.OS_VERSION
-- 240528 added SYSTEM_ACRONYM for visibility of invalid acronyms like UNDECIDED
,coalesce(h.PRIMARY_FISMA_ID_DERIVED,s.SYSTEM_ID,com.SYSTEM_ID,h.SYSTEM_ACRONYM) as SYSTEM_ID
--,h.PRIMARY_FISMA_ID_TATTOO -- Is always NULL
,h.REPORT_TIME
,h.SOURCE_TOOL
,coalesce(s.ACRONYM,com.ACRONYM,h.SYSTEM_ACRONYM) as SYSTEM_ACRONYM
FROM APP_CDM.SHARED.SEC_VW_HWAM_AWS h
LEFT OUTER JOIN CORE.VW_SYSTEMS s on upper(s.ACRONYM) = upper(h.SYSTEM_ACRONYM)
LEFT OUTER JOIN CORE.VW_SYSTEMS com on upper(com.COMMONNAME) = upper(h.SYSTEM_ACRONYM)
;