create or replace view VW_IUSG_MAG_TATTOO_TEST(
	ASSET_ID_TATTOO,
	AVAILABLITY_ZONE,
	AWS_ACCOUNTID,
	AWS_INSTANCE_ID,
	COMPLIANCE_ACTUAL_VALUE,
	COMPLIANCE_RESULT,
	DNSNAME,
	HOSTUNIQUENESS,
	IP,
	IS_IN_CAMP_DB,
	MACADDRESS,
	NETBIOSNAME,
	PLUGINTEXT,
	PORT,
	REGION,
	S3_FILE_CREATE,
	REPOSITORY_DESCRIPTION,
	REPOSITORY_ID,
	SEVERITY_ID,
	SOURCE,
	SYSTEM_ID,
	UUID,
	VERIFIED_SYSTEM_ID
) COMMENT='CRITICAL; Workaround obtaining uniform tattoo plugin data for IUSG_MAG\t'
 as
SELECT
t.ASSET_ID_TATTOO
,t.AVAILABLITY_ZONE
,t.AWS_ACCOUNTID
,t.AWS_INSTANCE_ID
,t.COMPLIANCE_ACTUAL_VALUE
,t.COMPLIANCE_RESULT
,t.DNSNAME
,t.HOSTUNIQUENESS
,t.IP
,t.IS_IN_CAMP_DB
,t.MACADDRESS
,t.NETBIOSNAME
,t.PLUGIN_ID
--,t.PLUGINTEXT -- Uncomment for diagnostics
,t.PORT
,t.REGION
,t.S3_FILE_CREATE
,t.REPOSITORY_DESCRIPTION
,t.REPOSITORY_ID
,t.SEVERITY_ID
,t.SOURCE
,t.SYSTEM_ID_TAG as SYSTEM_ID
,t.UUID
,s.SYSTEM_ID as VERIFIED_SYSTEM_ID
FROM ( 
select DISTINCT
REPLACE(split_part(split_part(v.PLUGINTEXT,'availabilityZone: ',2),' ',1),CHR(10),'') AVAILABLITY_ZONE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'accountId: ',2),' ',1),CHR(10),'') AWS_ACCOUNTID
,REPLACE(split_part(split_part(v.PLUGINTEXT,'instanceId: ',2),' ',1),CHR(10),'') AWS_INSTANCE_ID
,NULL as COMPLIANCE_VALUE_POS1
,NULL as COMPLIANCE_VALUE_POS2
,NULL as COMPLIANCE_ACTUAL_VALUE
,NULL as COMPLIANCE_RESULT_POS1
,NULL as COMPLIANCE_RESULT_POS2
,NULL as COMPLIANCE_RESULT
,NULL as ASSET_ID_TATTOO
,v.DNSNAME
,v.HOSTUNIQUENESS
,v.IP
,case(coalesce(flu.SYSTEM_ID,'ITSNULL'))
    when 'ITSNULL' then 0
    Else 1
End as IS_IN_CAMP_DB
,v.MACADDRESS
,v.NETBIOSNAME
,v.PLUGIN_ID
,v.PLUGINTEXT
,v.PORT
,REPLACE(split_part(split_part(v.PLUGINTEXT,'region: ',2),' ',1),CHR(10),'') REGION
,v.S3_FILE_CREATE
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,v.SEVERITY_ID
,'SEC_VW_IUSG_MAG_CUMULATIVE_VULNS' as SOURCE
,flu.SYSTEM_ID as SYSTEM_ID_TAG
,v.UUID
FROM APP_TENABLE.SHARED.SEC_VW_IUSG_MAG_CUMULATIVE_VULNS v
LEFT OUTER JOIN CORE.VW_AWS_CAMPDB_LOOKUP flu on flu.account_number = AWS_ACCOUNTID
WHERE v.PLUGIN_ID IN
(
'90191' -- Amazon Web Services EC2 Instance Metadata Enumeration (Unix)
,'90427' -- Amazon Web Services EC2 Instance Metadata Enumeration (Windows)
)

UNION ALL

select DISTINCT
REPLACE(split_part(split_part(v.PLUGINTEXT,'availabilityZone: ',2),' ',1),CHR(10),'') AVAILABLITY_ZONE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'accountId: ',2),' ',1),CHR(10),'') AWS_ACCOUNTID
,REPLACE(split_part(split_part(v.PLUGINTEXT,'instanceId: ',2),' ',1),CHR(10),'') AWS_INSTANCE_ID
,NULL as COMPLIANCE_VALUE_POS1
,NULL as COMPLIANCE_VALUE_POS2
,NULL as COMPLIANCE_ACTUAL_VALUE
,NULL as COMPLIANCE_RESULT_POS1
,NULL as COMPLIANCE_RESULT_POS2
,NULL as COMPLIANCE_RESULT
,NULL as ASSET_ID_TATTOO
,v.DNSNAME
,v.HOSTUNIQUENESS
,v.IP
,case(coalesce(flu.SYSTEM_ID,'ITSNULL'))
    when 'ITSNULL' then 0
    Else 1
End as IS_IN_CAMP_DB
,v.MACADDRESS
,v.NETBIOSNAME
,v.PLUGIN_ID
,v.PLUGINTEXT
,v.PORT
,REPLACE(split_part(split_part(v.PLUGINTEXT,'region: ',2),' ',1),CHR(10),'') REGION
,v.S3_FILE_CREATE
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,v.SEVERITY_ID
,'SEC_VW_IUSG_MAG_MITIGATED_VULNS' as SOURCE
,flu.SYSTEM_ID as SYSTEM_ID_TAG
,v.UUID
FROM APP_TENABLE.SHARED.SEC_VW_IUSG_MAG_MITIGATED_VULNS v
LEFT OUTER JOIN CORE.VW_AWS_CAMPDB_LOOKUP flu on flu.account_number = AWS_ACCOUNTID
WHERE v.PLUGIN_ID IN
(
'90191' -- Amazon Web Services EC2 Instance Metadata Enumeration (Unix)
,'90427' -- Amazon Web Services EC2 Instance Metadata Enumeration (Windows)
)

UNION ALL

select DISTINCT
NULL as AVAILABLITY_ZONE
,NULL as AWS_ACCOUNTID
,NULL as AWS_INSTANCE_ID
,POSITION('<cm:compliance-actual-value>',v.PLUGINTEXT) as COMPLIANCE_VALUE_POS1
,POSITION('</cm:compliance-actual-value>',v.PLUGINTEXT) as COMPLIANCE_VALUE_POS2
,SUBSTRING(v.PLUGINTEXT,(COMPLIANCE_VALUE_POS1 + 28),COMPLIANCE_VALUE_POS2 - COMPLIANCE_VALUE_POS1 - 28) as COMPLIANCE_ACTUAL_VALUE
,POSITION('<cm:compliance-result>',v.PLUGINTEXT) as COMPLIANCE_RESULT_POS1
,POSITION('</cm:compliance-result>',v.PLUGINTEXT) as COMPLIANCE_RESULT_POS2
,SUBSTRING(v.PLUGINTEXT,(COMPLIANCE_RESULT_POS1 + 22),COMPLIANCE_RESULT_POS2 - COMPLIANCE_RESULT_POS1 - 22) as COMPLIANCE_RESULT
,coalesce(NULLIF(REPLACE(split_part(split_part(COMPLIANCE_ACTUAL_VALUE,'The Asset_ID is ',2),CHR(10),1),CHR(10),''),''),'No Asset_ID tag') as ASSET_ID_TATTOO
,v.DNSNAME
,v.HOSTUNIQUENESS
,v.IP
,case(coalesce(flu.SYSTEM_ID,'ITSNULL'))
    when 'ITSNULL' then 0
    Else 1
End as IS_IN_CAMP_DB
,v.MACADDRESS
,v.NETBIOSNAME
,v.PLUGIN_ID
,v.PLUGINTEXT
,v.PORT
,NULL as REGION
,v.S3_FILE_CREATE
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,v.SEVERITY_ID
,'SEC_VW_IUSG_MAG_CUMULATIVE_VULNS' as SOURCE
,coalesce(NULLIF(split_part(split_part(split_part(COMPLIANCE_ACTUAL_VALUE,'The Primary_FISMA_ID is ',2),'<',1),CHR(10),1),''),'No Primary_FISMA_ID tag') as SYSTEM_ID_TAG
,v.UUID
FROM APP_TENABLE.SHARED.SEC_VW_IUSG_MAG_CUMULATIVE_VULNS v
LEFT OUTER JOIN CORE.VW_AWS_CAMPDB_LOOKUP flu on flu.SYSTEM_ID = SYSTEM_ID_TAG
WHERE v.PLUGIN_ID = '1221295' -- Print out FISMA registry keys. (Windows)

UNION ALL

select DISTINCT
NULL as AVAILABLITY_ZONE
,NULL as AWS_ACCOUNTID
,NULL as AWS_INSTANCE_ID
,POSITION('<cm:compliance-actual-value>',v.PLUGINTEXT) as COMPLIANCE_VALUE_POS1
,POSITION('</cm:compliance-actual-value>',v.PLUGINTEXT) as COMPLIANCE_VALUE_POS2
,SUBSTRING(v.PLUGINTEXT,(COMPLIANCE_VALUE_POS1 + 28),COMPLIANCE_VALUE_POS2 - COMPLIANCE_VALUE_POS1 - 28) as COMPLIANCE_ACTUAL_VALUE
,POSITION('<cm:compliance-result>',v.PLUGINTEXT) as COMPLIANCE_RESULT_POS1
,POSITION('</cm:compliance-result>',v.PLUGINTEXT) as COMPLIANCE_RESULT_POS2
,SUBSTRING(v.PLUGINTEXT,(COMPLIANCE_RESULT_POS1 + 22),COMPLIANCE_RESULT_POS2 - COMPLIANCE_RESULT_POS1 - 22) as COMPLIANCE_RESULT
,coalesce(NULLIF(REPLACE(split_part(split_part(COMPLIANCE_ACTUAL_VALUE,'/var/CMS/FISMA/Asset_ID/',2),CHR(10),1),CHR(10),''),''),'No Asset_ID tag') as ASSET_ID_TATTOO
,v.DNSNAME
,v.HOSTUNIQUENESS
,v.IP
,case(coalesce(flu.SYSTEM_ID,'ITSNULL'))
    when 'ITSNULL' then 0
    Else 1
End as IS_IN_CAMP_DB
,v.MACADDRESS
,v.NETBIOSNAME
,v.PLUGIN_ID
,v.PLUGINTEXT
,v.PORT
,NULL as REGION
,v.S3_FILE_CREATE
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,v.SEVERITY_ID
,'SEC_VW_IUSG_MAG_CUMULATIVE_VULNS' as SOURCE
,coalesce(NULLIF(split_part(split_part(split_part(COMPLIANCE_ACTUAL_VALUE,'/var/CMS/FISMA/Primary_FISMA_ID/',2),'<',1),CHR(10),1),''),'No Primary_FISMA_ID tag') as SYSTEM_ID_TAG
,v.UUID
FROM APP_TENABLE.SHARED.SEC_VW_IUSG_MAG_CUMULATIVE_VULNS v
LEFT OUTER JOIN CORE.VW_AWS_CAMPDB_LOOKUP flu on flu.SYSTEM_ID = SYSTEM_ID_TAG
WHERE v.PLUGIN_ID = '1218405' -- Check for Empty FISMA Tattoo files. (Linux)
) t
LEFT OUTER JOIN CORE.SYSTEMS s on s.SYSTEM_ID = t.SYSTEM_ID_TAG
;