create or replace view VW_IUSG_MAG_LOOKUP_TEST(
	SUBSCRIPTION_ID,
	DATE,
	ACCOUNT_NUMBER,
	SYSTEM_ACRONYM,
	APP_PHASE_NAME,
	ACCOUNT_NAME,
	ACCOUN_TYPE,
	LONG_APP_NAME,
	SHORT_APP_NAME,
	APP_LIVE_STATUS,
	ADO_TECH_MANAGER_EMAIL,
	ENV_NAME,
	MARKETPLACE,
	MEDIC_OE_EFFECT,
	OE_EFFECT,
	PLATFORM_NAME,
	PROJ_PHASE,
	ID,
	FILE_NAME,
	FILE_LAST_MODIFIED
) as
SELECT DISTINCT
v.SUBSCRIPTION_ID
,flu.*

FROM APP_TENABLE.SHARED.SEC_VW_IUSG_MAG_CUMULATIVE_VULNS v
--LEFT OUTER JOIN REF_LOOKUPS.SHARED.SEC_VW_FISMA_LOOKUPS flu on upper(flu.account_number) = upper(v.SUBSCRIPTION_ID)
--LEFT OUTER JOIN REF_LOOKUPS.PUBLIC.SEC_VW_FISMA_LOOKUPS_ALL flu on upper(flu.account_number) = upper(v.SUBSCRIPTION_ID)
--LEFT OUTER JOIN REF_LOOKUPS.PUBLIC.SEC_VW_FISMA_CAMP flu on upper(flu.account_number) = upper(v.SUBSCRIPTION_ID)
LEFT OUTER JOIN REF_LOOKUPS.PUBLIC.SEC_VW_FISMA_CAMP flu on upper(flu.account_number) = upper(v.SUBSCRIPTION_ID)
WHERE S3_FILE_CREATE::date = current_date()
;