create or replace view VW_NESSUS_SCAN_INFORMATION(
	BACKPORTS,
	CREDENTIALED_CHECK_DETAIL,
	CREDENTIALED_CHECK,
	DNSNAME,
	HOSTUNIQUENESS,
	IP,
	MACADDRESS,
	NESSUS_BUILD,
	NESSUS_VERSION,
	NETBIOSNAME,
	PATCH_MANAGEMENT_CHECKS,
	PLUGIN_FEED_VERSION,
	PLUGIN_ID,
	PORT,
	REPORTDATE,
	REPOSITORY_DESCRIPTION,
	REPOSITORY_ID,
	SCAN_NAME,
	SCAN_POLICY_USED,
	SCAN_START_DATE,
	SCAN_TYPE,
	SCANNER_OS,
	SEVERITY_ID,
	SOURCE,
	UUID
) COMMENT='CRITICAL; Capture Nessus Scan Information using PLUGIN_ID = 19506\t'
 as
SELECT t.*
/*
t.CREDENTIALED_CHECK_DETAIL
,t.NESSUS_VERSION
,t.PATCH_MANAGEMENT_CHECKS
,t.PLUGIN_FEED_VERSION
,t.PLUGIN_ID
,t.SCANNER_OS
*/
FROM ( 
select DISTINCT
REPLACE(split_part(split_part(v.PLUGINTEXT,'Backports : ',2),CHR(10),1),CHR(10),'') BACKPORTS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Credentialed checks : ',2),CHR(10),1),CHR(10),'') CREDENTIALED_CHECK_DETAIL
,SUBSTRING(CREDENTIALED_CHECK_DETAIL,1,3) CREDENTIALED_CHECK
,v.DNSNAME
,v.HOSTUNIQUENESS
,v.IP
,v.MACADDRESS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Nessus build : ',2),CHR(10),1),CHR(10),'') NESSUS_BUILD
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Nessus version : ',2),CHR(10),1),CHR(10),'') NESSUS_VERSION
,v.NETBIOSNAME
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Patch management checks : ',2),CHR(10),1),CHR(10),'') PATCH_MANAGEMENT_CHECKS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Plugin feed version : ',2),CHR(10),1),CHR(10),'') PLUGIN_FEED_VERSION
,v.PLUGIN_ID
--,v.PLUGINTEXT
,v.PORT
,v.REPORTDATE
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan name : ',2),CHR(10),1),CHR(10),'') SCAN_NAME
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan policy used :',2),CHR(10),1),CHR(10),'') SCAN_POLICY_USED
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan Start Date : ',2),CHR(10),1),CHR(10),'') SCAN_START_DATE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan type : ',2),CHR(10),1),CHR(10),'') SCAN_TYPE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scanner OS : ',2),CHR(10),1),CHR(10),'') SCANNER_OS
,v.SEVERITY_ID
,'SEC_VW_CCIC_TENABLE_CUMULATIVE_INFO' as SOURCE
,v.UUID
FROM APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_CUMULATIVE_INFO v
WHERE v.PLUGIN_ID = '19506' -- Nessus Scan Information

UNION ALL

select DISTINCT
REPLACE(split_part(split_part(v.PLUGINTEXT,'Backports : ',2),CHR(10),1),CHR(10),'') BACKPORTS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Credentialed checks : ',2),CHR(10),1),CHR(10),'') CREDENTIALED_CHECK_DETAIL
,SUBSTRING(CREDENTIALED_CHECK_DETAIL,1,3) CREDENTIALED_CHECK
,v.DNSNAME
,v.HOSTUNIQUENESS
,v.IP
,v.MACADDRESS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Nessus build : ',2),CHR(10),1),CHR(10),'') NESSUS_BUILD
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Nessus version : ',2),CHR(10),1),CHR(10),'') NESSUS_VERSION
,v.NETBIOSNAME
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Patch management checks : ',2),CHR(10),1),CHR(10),'') PATCH_MANAGEMENT_CHECKS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Plugin feed version : ',2),CHR(10),1),CHR(10),'') PLUGIN_FEED_VERSION
,v.PLUGIN_ID
--,v.PLUGINTEXT
,v.PORT
,v.REPORTDATE
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan name : ',2),CHR(10),1),CHR(10),'') SCAN_NAME
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan policy used :',2),CHR(10),1),CHR(10),'') SCAN_POLICY_USED
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan Start Date : ',2),CHR(10),1),CHR(10),'') SCAN_START_DATE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan type : ',2),CHR(10),1),CHR(10),'') SCAN_TYPE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scanner OS : ',2),CHR(10),1),CHR(10),'') SCANNER_OS
,v.SEVERITY_ID
,'SEC_VW_CCIC_TENABLE_CUMULATIVE_VULNS' as SOURCE
,v.UUID
FROM APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_CUMULATIVE_VULNS v
WHERE v.PLUGIN_ID = '19506' -- Nessus Scan Information

UNION ALL

select DISTINCT
REPLACE(split_part(split_part(v.PLUGINTEXT,'Backports : ',2),CHR(10),1),CHR(10),'') BACKPORTS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Credentialed checks : ',2),CHR(10),1),CHR(10),'') CREDENTIALED_CHECK_DETAIL
,SUBSTRING(CREDENTIALED_CHECK_DETAIL,1,3) CREDENTIALED_CHECK
,v.DNSNAME
,v.HOSTUNIQUENESS
,v.IP
,v.MACADDRESS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Nessus build : ',2),CHR(10),1),CHR(10),'') NESSUS_BUILD
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Nessus version : ',2),CHR(10),1),CHR(10),'') NESSUS_VERSION
,v.NETBIOSNAME
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Patch management checks : ',2),CHR(10),1),CHR(10),'') PATCH_MANAGEMENT_CHECKS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Plugin feed version : ',2),CHR(10),1),CHR(10),'') PLUGIN_FEED_VERSION
,v.PLUGIN_ID
--,v.PLUGINTEXT
,v.PORT
,v.REPORTDATE
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan name : ',2),CHR(10),1),CHR(10),'') SCAN_NAME
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan policy used :',2),CHR(10),1),CHR(10),'') SCAN_POLICY_USED
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan Start Date : ',2),CHR(10),1),CHR(10),'') SCAN_START_DATE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan type : ',2),CHR(10),1),CHR(10),'') SCAN_TYPE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scanner OS : ',2),CHR(10),1),CHR(10),'') SCANNER_OS
,v.SEVERITY_ID
,'SEC_VW_CCIC_TENABLE_MITIGATED_INFO' as SOURCE
,v.UUID
FROM APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_MITIGATED_INFO v
WHERE v.PLUGIN_ID = '19506' -- Nessus Scan Information

UNION ALL

select DISTINCT
REPLACE(split_part(split_part(v.PLUGINTEXT,'Backports : ',2),CHR(10),1),CHR(10),'') BACKPORTS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Credentialed checks : ',2),CHR(10),1),CHR(10),'') CREDENTIALED_CHECK_DETAIL
,SUBSTRING(CREDENTIALED_CHECK_DETAIL,1,3) CREDENTIALED_CHECK
,v.DNSNAME
,v.HOSTUNIQUENESS
,v.IP
,v.MACADDRESS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Nessus build : ',2),CHR(10),1),CHR(10),'') NESSUS_BUILD
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Nessus version : ',2),CHR(10),1),CHR(10),'') NESSUS_VERSION
,v.NETBIOSNAME
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Patch management checks : ',2),CHR(10),1),CHR(10),'') PATCH_MANAGEMENT_CHECKS
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Plugin feed version : ',2),CHR(10),1),CHR(10),'') PLUGIN_FEED_VERSION
,v.PLUGIN_ID
--,v.PLUGINTEXT
,v.PORT
,v.REPORTDATE
,v.REPOSITORY_DESCRIPTION
,v.REPOSITORY_ID
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan name : ',2),CHR(10),1),CHR(10),'') SCAN_NAME
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan policy used :',2),CHR(10),1),CHR(10),'') SCAN_POLICY_USED
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan Start Date : ',2),CHR(10),1),CHR(10),'') SCAN_START_DATE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scan type : ',2),CHR(10),1),CHR(10),'') SCAN_TYPE
,REPLACE(split_part(split_part(v.PLUGINTEXT,'Scanner OS : ',2),CHR(10),1),CHR(10),'') SCANNER_OS
,v.SEVERITY_ID
,'SEC_VW_CCIC_TENABLE_MITIGATED_VULNS' as SOURCE
,v.UUID
FROM APP_TENABLE.SHARED.SEC_VW_CCIC_TENABLE_MITIGATED_VULNS v
WHERE v.PLUGIN_ID = '19506' -- Nessus Scan Information

) t
;