create or replace view VW_POAMHIST(
	ID,
	ACTUAL_COMPLETION_DATE,
	ACTUAL_LABOR_COST,
	ARCHER_TRACKING_ID,
	AUTHORIZATION_PACKAGE,
	CAAT,
	CAAT_ID,
	COST,
	CVE,
	DAYS_OPEN,
	ESTIMATED_COMPLETION_DATE,
	FUNDING_SOURCE,
	LABOR_ESTIMATE,
	OVERALL_STATUS,
	POAM_CLOSED_DATE,
	POAM_ID,
	POAM_OWNER,
	POAM_REVIEWER,
	REPORT_ID,
	REPORT_DATE,
	REVIEW_COMMENTS,
	REVIEW_DATE,
	REVIEW_STATUS,
	SCHEDULED_COMPLETION_DATE,
	SUBMISSION_STATUS,
	SYSTEM_ID,
	TARGET,
	WEAKNESS_CREATION_DATE,
	WEAKNESS_ID,
	WEAKNESS_POC,
	WEAKNESS_RISK_LEVEL,
	WEAKNESS_RISK_LEVEL_WEIGHT,
	WEAKNESS_SEVERITY
) COMMENT='Return POAM history ingested from CFACTS for every report_id. '
 as
SELECT
p.ID
,p.ACTUAL_COMPLETION_DATE
,p.ACTUAL_LABOR_COST
,s.ARCHER_TRACKING_ID
,s.AUTHORIZATION_PACKAGE
,p.CAAT
,p.CAAT_ID
,p.COST
,p.CVE
,p.DAYS_OPEN
,p.ESTIMATED_COMPLETION_DATE
,p.FUNDING_SOURCE
,p.LABOR_ESTIMATE
,p.OVERALL_STATUS
,p.POAM_CLOSED_DATE
,p.POAM_ID
,p.POAM_OWNER
,p.POAM_REVIEWER
,p.REPORT_ID
,r.REPORT_DATE
,p.REVIEW_COMMENTS
,p.REVIEW_DATE
,p.REVIEW_STATUS
,p.SCHEDULED_COMPLETION_DATE
,p.SUBMISSION_STATUS
,p.SYSTEM_ID
,p.TARGET
,p.WEAKNESS_CREATION_DATE
,p.WEAKNESS_ID
,p.WEAKNESS_POC
,p.WEAKNESS_RISK_LEVEL
,CASE p.WEAKNESS_RISK_LEVEL
    when 'Critical' then 45
    when 'High' then 30
    when 'Moderate' then 15
    when 'Low' then 10
    Else 0
END as WEAKNESS_RISK_LEVEL_WEIGHT
,p.WEAKNESS_SEVERITY
FROM CORE.POAMHist p
JOIN CORE.REPORT_IDS r on r.REPORT_ID = p.REPORT_ID
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = p.SYSTEM_ID;