create or replace view VW_REPORTSNAPSHOTS(
	REPORTSNAPSHOTID,
	DATACATEGORY,
	REPORT_ID,
	REPORT_DATE,
	IS_ENDOFMONTH,
	SNAPSHOT_ID,
	SNAPSHOT_DATE
) COMMENT='Show all report_id and snapshot_id relation with datetime and datacatagory. '
 as
SELECT t.REPORT_ID as ReportSnapshotID
,t.DATACATEGORY
,t.REPORT_ID
,t.REPORT_DATE
,t.IS_ENDOFMONTH
,t.REPORT_ID as SNAPSHOT_ID
,t.REPORT_DATE as SNAPSHOT_DATE
--,snap.MIN_DATE
--,snap.MAX_DATE
FROM 
(
select REPORT_ID,REPORT_DATE,Is_endOfMonth,'CFACTS' as DATACATEGORY from CORE.REPORT_IDS where IS_VIABLE = 1 -- 240607 EBF
UNION ALL
select REPORT_ID,REPORT_DATE,Is_endOfMonth,'HWAM' as DATACATEGORY from CORE.REPORT_IDS where IS_VIABLE = 1 -- 240607 EBF
UNION ALL
select REPORT_ID,REPORT_DATE,Is_endOfMonth,'VUL' as DATACATEGORY from CORE.REPORT_IDS where IS_VIABLE = 1 -- 240607 EBF
) t
order by t.REPORT_ID desc;