create or replace view VW_SYSTEMSUMMARY(
	ID,
	ACRONYM,
	ASSETRISKTOLERANCE,
	ASSETS,
	HWAMRAWAWS,
	HWAMRAWBIGFIX,
	HWAMRAWFORESCOUT,
	IS_ENDOFMONTH,
	KEV_FIXED_MONTHTODATE,
	KEV_FIXED_TODAY,
	KEV_OPEN,
	KEV_REOPENED,
	PREVASSETS,
	REPORT_DATE,
	REPORT_ID,
	RESIDUALRISK,
	RESILIENCYSCORE,
	SCANNABLEASSETS,
	SUM_ASSET_VULNRISKTOLERANCE,
	SYSTEM_ID,
	VUL_CRITICAL_FIXED_TODAY,
	VUL_CRITICAL_OPEN,
	VUL_CRITICAL_REOPENED,
	VUL_DELETED_TODAY,
	VUL_HIGH_FIXED_TODAY,
	VUL_HIGH_OPEN,
	VUL_HIGH_REOPENED,
	VUL_INACTIVE_ASSET_TODAY,
	VUL_LOW_FIXED_TODAY,
	VUL_LOW_OPEN,
	VUL_LOW_REOPENED,
	VUL_MEDIUM_FIXED_TODAY,
	VUL_MEDIUM_OPEN,
	VUL_MEDIUM_REOPENED,
	VULCRITICAL,
	VULCRITICAL_GT15_LTE60DAYS,
	VULCRITICAL_GT30_LTE60DAYS,
	VULCRITICAL_GT60DAYS,
	VULCRITICAL_GTE15DAYS,
	VULCRITICAL_LTE15DAYS,
	VULCRITICAL_LTE30DAYS,
	VULDELETED,
	VULHIGH,
	VULHIGH_GT30_LTE60DAYS,
	VULHIGH_GT60DAYS,
	VULHIGH_LTE30DAYS,
	VULLOW,
	VULMEDIUM,
	VULNRISKTOLERANCE,
	VULRAW,
	VULRAW_CRITICAL,
	VULRAW_HIGH,
	VULRAW_LOW,
	VULRAW_MEDIUM,
	VULUNIQUECRITICAL_GT15_LTE60DAYS,
	VULUNIQUECRITICAL_GT30_LTE60DAYS,
	VULUNIQUECRITICAL_GT60DAYS,
	VULUNIQUECRITICAL_GTE15DAYS,
	VULUNIQUEHIGH_GT30_LTE60DAYS,
	VULUNIQUEHIGH_GT60DAYS,
	VULUNIQUELOW,
	VULUNIQUEMEDIUM
) COMMENT='Return system level total for all report_id to show history of system summary changes.'
 as
SELECT
ss.ID
,s.ACRONYM
,ss.ASSETRISKTOLERANCE
,ss.ASSETS
,ss.HWAMRAWAWS
,ss.HWAMRAWBIGFIX
,ss.HWAMRAWFORESCOUT
,r.IS_ENDOFMONTH
,ss.KEV_FIXED_MONTHTODATE
,ss.KEV_FIXED_TODAY
,ss.KEV_OPEN
,ss.KEV_REOPENED
,ss.PREVASSETS
,r.REPORT_DATE
,ss.REPORT_ID
,ss.RESIDUALRISK
,ss.RESILIENCYSCORE
,ss.SCANNABLEASSETS
,ss.SUM_ASSET_VULNRISKTOLERANCE
,ss.SYSTEM_ID
,ss.VUL_CRITICAL_FIXED_TODAY -- 240222 CR840 
,ss.VUL_CRITICAL_OPEN -- 240222 CR840 
,ss.VUL_CRITICAL_REOPENED -- 240222 CR840 
,ss.VUL_DELETED_TODAY -- 240222 CR840 
,ss.VUL_HIGH_FIXED_TODAY -- 240222 CR840 
,ss.VUL_HIGH_OPEN -- 240222 CR840 
,ss.VUL_HIGH_REOPENED -- 240222 CR840 
,ss.VUL_INACTIVE_ASSET_TODAY -- 240222 CR840 
,ss.VUL_LOW_FIXED_TODAY -- 240222 CR840 
,ss.VUL_LOW_OPEN -- 240222 CR840 
,ss.VUL_LOW_REOPENED -- 240222 CR840 
,ss.VUL_MEDIUM_FIXED_TODAY -- 240222 CR840 
,ss.VUL_MEDIUM_OPEN -- 240222 CR840 
,ss.VUL_MEDIUM_REOPENED -- 240222 CR840 
-- 240222 CR840 ,ss.VULCRITICAL
,(ss.VUL_CRITICAL_OPEN + ss.VUL_CRITICAL_REOPENED) as VULCRITICAL -- 240222 CR840
,ss.VULCRITICAL_GT15_LTE60DAYS
,ss.VULCRITICAL_GT30_LTE60DAYS
,ss.VULCRITICAL_GT60DAYS
,ss.VULCRITICAL_GTE15DAYS
,ss.VULCRITICAL_LTE15DAYS
,ss.VULCRITICAL_LTE30DAYS
-- 240222 CR840 ,ss.VULCRITICALREMEDIATED -- was never set by SP_CRM_WRITE_SUMMARY_TABLES use VUL_CRITICAL_FIXED_TODAY
,ss.VULDELETED
-- 240222 CR840 ,ss.VULHIGH
,(ss.VUL_HIGH_OPEN + ss.VUL_HIGH_REOPENED) as VULHIGH -- 240222 CR840
,ss.VULHIGH_GT30_LTE60DAYS
,ss.VULHIGH_GT60DAYS
,ss.VULHIGH_LTE30DAYS
-- 240222 CR840 ,ss.VULHIGHREMEDIATED -- was never set by SP_CRM_WRITE_SUMMARY_TABLES use VUL_HIGH_FIXED_TODAY
-- 240222 CR840 ,ss.VULLOW
,(ss.VUL_LOW_OPEN + ss.VUL_LOW_REOPENED) as VULLOW -- 240222 CR840
-- 240222 CR840 ,ss.VULMEDIUM
,(ss.VUL_MEDIUM_OPEN + ss.VUL_MEDIUM_REOPENED) as VULMEDIUM -- 240222 CR840
,ss.VULNRISKTOLERANCE
,ss.VULRAW
,ss.VULRAW_CRITICAL
,ss.VULRAW_HIGH
,ss.VULRAW_LOW
,ss.VULRAW_MEDIUM
,ss.VULUNIQUECRITICAL_GT15_LTE60DAYS
,ss.VULUNIQUECRITICAL_GT30_LTE60DAYS
,ss.VULUNIQUECRITICAL_GT60DAYS
,ss.VULUNIQUECRITICAL_GTE15DAYS
,ss.VULUNIQUEHIGH_GT30_LTE60DAYS
,ss.VULUNIQUEHIGH_GT60DAYS
,ss.VULUNIQUELOW
,ss.VULUNIQUEMEDIUM
FROM CORE.SYSTEMSUMMARY ss
JOIN CORE.SYSTEMS s on s.SYSTEM_ID = ss.SYSTEM_ID
JOIN CORE.REPORT_IDS r on r.REPORT_ID = ss.REPORT_ID
;