create or replace view VW_TEST_RAW_TENABLE_VUL(
	RAW_TENABLE_VUL_ID,
	TEMP_DW_ASSET_ID,
	ASSET_ID_TATTOO,
	DATACENTER_ID,
	DNSNAME,
	HOSTNAME,
	IP,
	MACADDRESS,
	NETBIOSNAME,
	PRIMARY_FISMA_ID_TATTOO,
	REPOSITORY_NAME,
	SNAPSHOT_ID,
	SYSTEM_ID,
	TENABLEUUID,
	COMPLIANCE_CHECK_NAME,
	COMPLIANCE_ACTUAL_VALUE
) COMMENT='Temporary view to test tenable vuln.'
 as
SELECT 
r.RAW_TENABLE_VUL_ID
--,r.APPLICABILITYCODE
,r.TEMP_DW_ASSET_ID
,r.ASSET_ID_TATTOO
,r.DATACENTER_ID
--,r.DATACENTER_ID_DERIVED
,r.DNSNAME
,r.HOSTNAME
--,r.HOSTUNIQUENESS
--,r.HOSTUUID
,r.IP
,r.MACADDRESS
,r.NETBIOSNAME
--,r.PLUGIN_ID
--,r.PRIMARY_FISMA_ID_DERIVED
,r.PRIMARY_FISMA_ID_TATTOO
,r.REPOSITORY_NAME
,r.SNAPSHOT_ID
,r.SYSTEM_ID
--,r.UNIQUENESS
,r.TENABLEUUID
,r.COMPLIANCE_CHECK_NAME
,r.COMPLIANCE_ACTUAL_VALUE

FROM CORE.RAW_TENABLE_VUL r
Where r.SNAPSHOT_ID = 250 and r.APPLICABILITYCODE <> 'Excluding AWS VUL from CCIC VUL FEED';