create or replace view VW_VULPLUGINS_MASTER(
	DW_VUL_ID,
	DATACENTER_ACRONYM,
	SYSTEM_ACRONYM,
	DW_ASSET_ID,
	PLUGIN_ID,
	CVE,
	PLUGIN_MITIGATIONSTATUS,
	CVE_MITIGATIONSTATUS,
	EXTENDED_MITIGATIONSTATUS,
	PLUGIN_DELETIONREASON,
	TOTAL_PLUGIN_COUNT,
	OPEN_PLUGIN_COUNT,
	DELETED_PLUGIN_COUNT,
	FIXED_PLUGIN_COUNT,
	BODDUEDATE,
	CVSSV2BASESCORE,
	CVSSV3BASESCORE,
	DATACENTER_ID,
	DATEMITIGATED,
	DATEMODIFIED,
	DATEREOPENED,
	DAYSSINCEDISCOVERY,
	EXPLOITAVAILABLE,
	FIRSTSEEN,
	FISMASEVERITY,
	INSERT_DATE,
	IS_FROM_AWS_FEED,
	IS_KEV,
	IS_LEGACY,
	LASTFOUND,
	NUMERIC_SEVERITY,
	REPOSITORY_ID,
	REPOSITORY_LASTSEEN,
	REPOSITORY_NAME,
	SYSTEM_ID
) COMMENT='View reports Tenable vulnerabilities from VULPLUGINS_MASTER and VULMASTER table.\t'
 as
SELECT
vm.dw_vul_id
,a.datacenter_acronym
,a.system_acronym
,vm.DW_ASSET_ID
,vpm.PLUGIN_ID 
,vm.CVE
,vpm.mitigationstatus as Plugin_MitigationStatus
,vm.MITIGATIONSTATUS as CVE_Mitigationstatus
,vm.extended_mitigationstatus
,vpm.DELETIONREASON as Plugin_DELETIONREASON
,vm.total_plugin_count
,vm.open_plugin_count
,vm.deleted_plugin_count
,vm.fixed_plugin_count
,kev.BODDUEDATE
,vm.CVSSV2BASESCORE
,vm.CVSSV3BASESCORE
,a.DATACENTER_ID
,vm.DATEMITIGATED
,vm.DATEMODIFIED
,vm.DATEREOPENED
,vm.DAYSSINCEDISCOVERY
,vm.EXPLOITAVAILABLE
,vm.FIRSTSEEN
,vm.FISMASEVERITY
,vm.INSERT_DATE
,vm.IS_FROM_AWS_FEED -- 230719
,case coalesce(kev.ID,0)
    WHEN 0 THEN 0
    ELSE 1
end::boolean as IS_KEV
,vm.IS_LEGACY
,vm.LASTFOUND
,vm.NUMERIC_SEVERITY -- 230719
,vm.REPOSITORY_ID -- 230720
,trh.REPOSITORY_LASTSEEN -- 230720
,vm.REPOSITORY_NAME -- 230719
,a.SYSTEM_ID
FROM CORE.VULMASTER vm
JOIN CORE.VW_ASSETS a on a.DW_ASSET_ID = vm.DW_ASSET_ID
LEFT OUTER JOIN 
(SELECT f.value::string as Plugin_CVE,v.* exclude CVE
--v.dw_asset_id,v.plugin_id,f.value::string as CVE,v.mitigationstatus,v.DELETIONREASON
    FROM CORE.VULPLUGINS_MASTER v
    join table(flatten(cve,outer=>true)) as f) vpm on vpm.DW_ASSET_ID = vm.DW_ASSET_ID and Plugin_CVE = vm.CVE
LEFT OUTER JOIN CORE.KEV_CATALOG kev on kev.CVE = vm.CVE and kev.IS_DELETED = 0
LEFT OUTER JOIN (select DATACENTER_ID,REPOSITORY_ID,MAX(INSERT_DATE) as REPOSITORY_LASTSEEN
    FROM CORE.TENABLE_REPOSITORYHIST 
    GROUP BY DATACENTER_ID,REPOSITORY_ID) trh on trh.DATACENTER_ID = a.DATACENTER_ID and trh.REPOSITORY_ID = vm.REPOSITORY_ID
WHERE vm.DELETIONREASON IS NULL;