create or replace view VW_VULHIST_UNFILTERED(
	ASSET_ID_TATTOO,
	BODDUEDATE,
	COMPONENT_ACRONYM,
	COMPONENT_NAME,
	CVE,
	CVSSV2BASESCORE,
	CVSSV3BASESCORE,
	DATACENTER_ID,
	DATACENTERACRONYM,
	DATEMITIGATED,
	DAYSSINCEDISCOVERY,
	DESCRIPTION,
	DNSNAME,
	DW_ASSET_ID,
	DW_VUL_ID,
	EXPLOITAVAILABLE,
	FAMILYNAME,
	FIRSTSEEN,
	FISMASEVERITY,
	GROUP_ACRONYM,
	GROUP_NAME,
	ID,
	IP,
	IS_BOD,
	LASTFOUND,
	MACADDRESS,
	MITIGATIONSTATUS,
	NETBIOSNAME,
	OS,
	PLUGIN_ID,
	REPORT_DATE,
	REPORT_ID,
	SIGNATURE,
	SOLUTION,
	SOURCE_TOOL,
	SYSTEM_ID,
	SYSTEMACRONYM
) COMMENT='Unfiltered Vulnerability History. RESEARCH WHERE VW_VULHIST IS USED TO SEE IF IT CAN SERVE THE SAME PURPOSE\t'
 as
SELECT 
ah.ASSET_ID_TATTOO
,kev.BODDUEDATE
,s.COMPONENT_ACRONYM
,s.COMPONENT_NAME
,vm.CVE
,v.CVSSV2BASESCORE
,v.CVSSV3BASESCORE
,ah.DATACENTER_ID
,dc.Acronym as DATACENTERACRONYM
,vm.DATEMITIGATED
,DATEDIFF(day,vm.firstseen,v.lastFound) as DAYSSINCEDISCOVERY
,NULL as DESCRIPTION
,ah.FQDN as DNSNAME
,ah.DW_ASSET_ID
,vm.DW_VUL_ID
,v.EXPLOITAVAILABLE
,NULL as FAMILYNAME
,vm.FIRSTSEEN
,v.FISMASEVERITY
,s.GROUP_ACRONYM -- 230623
,s.GROUP_NAME
,v.ID
,ah.IPv4 as IP
,case coalesce(kev.ID,0)
    WHEN 0 THEN 0
    ELSE 1
end::boolean as IS_BOD
,v.LASTFOUND
,ah.MACADDRESS
,v.MITIGATIONSTATUS
,ah.NETBIOSNAME
,ah.OS
,plugs.PLUGIN_ID
,r.REPORT_DATE
,r.REPORT_ID
,NULL as SIGNATURE
,NULL as SOLUTION
,'Tenable' as SOURCE_TOOL -- 230623
,ah.SYSTEM_ID
,s.Acronym as SYSTEMACRONYM
FROM CORE.REPORT_IDS r
JOIN CORE.VULHIST v on v.REPORT_ID = r.REPORT_ID
JOIN CORE.VulMaster vm on vm.DW_VUL_ID = v.DW_VUL_ID
LEFT OUTER JOIN CORE.KEV_CATALOG kev on kev.CVE = vm.CVE -- Do not check IS_DELETED = 0. We want to know if it was a BOD at that point in time
JOIN CORE.VW_ASSETHIST ah on ah.REPORT_ID = r.REPORT_ID and ah.DW_ASSET_ID = vm.DW_ASSET_ID
JOIN CORE.VW_SYSTEMS dc on dc.SYSTEM_ID = ah.DATACENTER_ID
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = ah.SYSTEM_ID
LEFT OUTER JOIN CORE.VULPLUGINS_COALESCED plugs on plugs.DW_VUL_ID = v.DW_VUL_ID
;