create or replace view VW_VULHIST(
	ASSET_ID_TATTOO,
	BODDUEDATE,
	COMPONENT_ACRONYM,
	COMPONENT_NAME,
	CVE,
	CVSSV2BASESCORE,
	CVSSV3BASESCORE,
	DATACENTER_ID,
	DATACENTERACRONYM,
	DATEMITIGATED,
	DAYSSINCEDISCOVERY,
	DESCRIPTION,
	DNSNAME,
	DW_ASSET_ID,
	DW_VUL_ID,
	EXPLOITAVAILABLE,
	FAMILYNAME,
	FIRSTSEEN,
	FISMASEVERITY,
	GROUP_ACRONYM,
	GROUP_NAME,
	ID,
	IP,
	IS_BOD,
	LASTFOUND,
	MACADDRESS,
	MITIGATIONSTATUS,
	NETBIOSNAME,
	OS,
	PLUGIN_ID,
	REPORT_DATE,
	REPORT_ID,
	SIGNATURE,
	SOLUTION,
	SOURCE_TOOL,
	SYSTEM_ID,
	SYSTEMACRONYM
) COMMENT='Return open/reopened historical vulnerability for all report_id.'
 as
SELECT 
ah.ASSET_ID_TATTOO
,kev.BODDUEDATE
,s.COMPONENT_ACRONYM
,s.COMPONENT_NAME
,v.CVE -- 240625 CR916 was pulling from VulMaster
,v.CVSSV2BASESCORE
,v.CVSSV3BASESCORE
,ah.DATACENTER_ID
,dc.Acronym as DATACENTERACRONYM
,v.DATEMITIGATED -- 240625 CR916 was pulling from VulMaster
,DATEDIFF(day,v.firstseen,v.lastFound) as DAYSSINCEDISCOVERY -- 240625 CR916 was pulling from VulMaster
,NULL as DESCRIPTION
,ah.FQDN as DNSNAME
,ah.DW_ASSET_ID
,v.DW_VUL_ID -- 240625 CR916 was pulling from VulMaster
,v.EXPLOITAVAILABLE
,NULL as FAMILYNAME
,v.FIRSTSEEN -- 240625 CR916 was pulling from VulMaster
,v.FISMASEVERITY
,s.GROUP_ACRONYM -- 230623
,s.GROUP_NAME
,v.ID
,ah.IPv4 as IP
,case coalesce(kev.ID,0)
    WHEN 0 THEN 0
    ELSE 1
end::boolean as IS_BOD
,v.LASTFOUND
,ah.MACADDRESS
,v.MITIGATIONSTATUS
,ah.NETBIOSNAME
,ah.OS
,plugs.PLUGIN_ID
,r.REPORT_DATE
,r.REPORT_ID
,NULL as SIGNATURE
,NULL as SOLUTION
,'Tenable' as SOURCE_TOOL -- 230623
,ah.SYSTEM_ID
,s.Acronym as SYSTEMACRONYM
FROM CORE.REPORT_IDS r
JOIN CORE.VULHIST v on v.REPORT_ID = r.REPORT_ID
-- 240625 CR916 JOIN CORE.VulMaster vm on vm.DW_VUL_ID = v.DW_VUL_ID
LEFT OUTER JOIN CORE.KEV_CATALOG kev on kev.CVE = v.CVE -- Do not check IS_DELETED = 0. We want to know if it was a BOD at that point in time
JOIN CORE.VW_ASSETHIST ah on ah.REPORT_ID = r.REPORT_ID and ah.DW_ASSET_ID = v.DW_ASSET_ID
JOIN CORE.VW_SYSTEMS dc on dc.SYSTEM_ID = ah.DATACENTER_ID
JOIN CORE.VW_SYSTEMS s on s.SYSTEM_ID = ah.SYSTEM_ID
LEFT OUTER JOIN CORE.VULPLUGINS_COALESCED plugs on plugs.DW_VUL_ID = v.DW_VUL_ID
where v.MitigationStatus IN ('open','reopened');