create or replace view VW_VULMASTER(
	BODDUEDATE,
	CVE,
	CVSSV2BASESCORE,
	CVSSV3BASESCORE,
	DATACENTER_ID,
	DATEMITIGATED,
	DATEMODIFIED,
	DATEREOPENED,
	DAYSSINCEDISCOVERY,
	DW_ASSET_ID,
	DW_VUL_ID,
	EXPLOITAVAILABLE,
	EXTENDED_MITIGATIONSTATUS,
	FIRSTSEEN,
	FISMASEVERITY,
	INSERT_DATE,
	IS_FROM_AWS_FEED,
	IS_KEV,
	IS_LEGACY,
	LASTFOUND,
	MITIGATIONSTATUS,
	NUMERIC_SEVERITY,
	REPOSITORY_ID,
	REPOSITORY_LASTSEEN,
	REPOSITORY_NAME,
	SYSTEM_ID
) COMMENT='CRITICAL; View reports Tenable vulnerabilities from VULMASTER table. Related asset must be active (not logically deleted). It is used throughout CRM\t'
 as
SELECT
kev.BODDUEDATE
,vm.CVE
,vm.CVSSV2BASESCORE
,vm.CVSSV3BASESCORE
,a.DATACENTER_ID
,vm.DATEMITIGATED
,vm.DATEMODIFIED
,vm.DATEREOPENED
,vm.DAYSSINCEDISCOVERY
,vm.DW_ASSET_ID
,vm.DW_VUL_ID
,vm.EXPLOITAVAILABLE
,vm.EXTENDED_MITIGATIONSTATUS -- 240625 CR916
,vm.FIRSTSEEN
,vm.FISMASEVERITY
,vm.INSERT_DATE
,vm.IS_FROM_AWS_FEED -- 230719
,case coalesce(kev.ID,0)
    WHEN 0 THEN 0
    ELSE 1
end::boolean as IS_KEV
,vm.IS_LEGACY
,vm.LASTFOUND
,vm.MITIGATIONSTATUS
,vm.NUMERIC_SEVERITY -- 230719
,vm.REPOSITORY_ID -- 230720
,trh.REPOSITORY_LASTSEEN -- 230720
,vm.REPOSITORY_NAME -- 230719
,a.SYSTEM_ID
FROM CORE.VULMASTER vm
JOIN CORE.VW_ASSETS a on a.DW_ASSET_ID = vm.DW_ASSET_ID
LEFT OUTER JOIN CORE.KEV_CATALOG kev on kev.CVE = vm.CVE and kev.IS_DELETED = 0
LEFT OUTER JOIN (select DATACENTER_ID,REPOSITORY_ID,MAX(INSERT_DATE) as REPOSITORY_LASTSEEN
    FROM CORE.TENABLE_REPOSITORYHIST 
    GROUP BY DATACENTER_ID,REPOSITORY_ID) trh on trh.DATACENTER_ID = a.DATACENTER_ID and trh.REPOSITORY_ID = vm.REPOSITORY_ID
WHERE vm.DELETIONREASON IS NULL;